import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {build} from 'esbuild';
const sql=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+f,'utf8'));
let user='brand-owner';globalThis.__brandUser=()=>user?{userId:user}:null;
globalThis.__brandEnv={DB:{
 prepare(query){
  const stmt=sql.prepare(query);
  return {bind(...args){return {
   async first(){return stmt.get(...args)??null;},
   async all(){return {results:stmt.all(...args)};},
   async run(){return {meta:{changes:stmt.run(...args).changes}};}
  };}};
 }
}};

const bundle=await build({stdin:{contents:"export * from './lib/brand-standards';export * from './lib/material-products';export * from './lib/scene-model';export * from './lib/design-variants';export * from './app/api/brands/route';export * as projectAPI from './app/api/projects/route';",resolveDir:process.cwd()},bundle:true,platform:'node',format:'esm',write:false,plugins:[{name:'runtime',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'env',namespace:'stub'}));b.onResolve({filter:/chatgpt-auth$/},()=>({path:'auth',namespace:'stub'}));b.onLoad({filter:/.*/,namespace:'stub'},a=>({contents:a.path==='env'?'export const env=globalThis.__brandEnv':'export async function getChatGPTUser(){return globalThis.__brandUser()}'}));}}]});
const m=await import('data:text/javascript;base64,'+Buffer.from(bundle.outputFiles[0].text).toString('base64'));let count=0;async function test(name,fn){await fn();count++;console.log('PASS '+name)}
const source=m.initialScene(),brand=m.ofdBrand(),room={width:5000,depth:6600,height:2900},identity={id:'ofd-starter',revision:0},empty={...source,nodes:[]},uid=()=>crypto.randomUUID();
await test('OFD explicitly proposed with seven roles and four verified manufacturer codes',()=>{assert.equal(brand.status,'draft');assert.equal(Object.keys(brand.materials).length,7);assert.ok(brand.note.includes('공식 시공 표준'));assert.equal(brand.materials.floor.finish.catalogId,'lx-101748');assert.equal(brand.materials.accent.finish.catalogId,undefined);for(const slot of Object.values(brand.materials)){if(slot.finish.catalogId)assert.ok(m.materialProduct(slot.finish.catalogId));assert.equal(slot.finish.textureId??null,null)}});
await test('strict brand schema rejects unknown products private images unsafe links missing roles and invalid module sizes',()=>{for(const change of [{...brand,owner:'other'},{...brand,referenceUrl:'javascript:alert(1)'},{...brand,name:' '},{...brand,materials:{...brand.materials,floor:{...brand.materials.floor,finish:{catalogId:'fake'}}}},{...brand,materials:{...brand.materials,floor:{...brand.materials.floor,finish:{textureId:uid()}}}},{...brand,modules:{...brand.modules,counter:{...brand.modules.counter,width:NaN}}}])assert.throws(()=>m.validateBrand(change));assert.deepEqual(m.validateBrand(JSON.parse(JSON.stringify(brand))),brand)});
await test('surface-only application changes exactly five finishes preserving all furniture locks and geometry',()=>{const s=structuredClone(source);s.nodes[0].locked=true;const before=JSON.stringify(s),n=m.brandScene(s,brand,identity,'surfaces',room);assert.equal(JSON.stringify(s),before);assert.deepEqual(n.nodes,s.nodes);assert.equal(n.room.width,s.room.width);assert.equal(n.room.surfaces.floor.finish.catalogId,'lx-101748');assert.equal(n.room.surfaces.back.finish.color,'#1C304A');assert.equal(n.brandApplication.mode,'surfaces')});
await test('empty rooms with stored project content still require replacement consent',()=>{const s={...empty,photoId:'reference',palette:['#123456']};assert.deepEqual(m.brandReplacementItems(s),['참고 사진','팔레트']);assert.throws(()=>m.brandScene(s,brand,identity,'layout',room),/기존 배치/);const next=m.brandScene(s,brand,identity,'layout',room,true);assert.equal(next.photoId,undefined);assert.equal(next.palette,undefined)});
await test('layout replacement requires explicit consent before removing an existing scene',()=>{assert.throws(()=>m.brandScene(source,brand,identity,'layout',room),/기존 배치/);const n=m.brandScene(source,brand,identity,'layout',room,true);assert.equal(n.nodes.length,9);assert.ok(n.nodes.every(n=>!source.nodes.some(o=>o.id===n.id)));assert.deepEqual(source,m.initialScene())});
await test('10 15 and 20 pyeong presets fit with stable module sizes fresh IDs and independent groups',()=>{const ids=new Set();for(const [width,depth] of [[5000,6600],[6000,8300],[7200,9200]]){const n=m.brandScene(empty,brand,identity,'layout',{...room,width,depth});assert.equal(n.nodes.length,9);assert.equal(new Set(n.nodes.flatMap(n=>n.group?[n.group.id]:[])).size,3);assert.equal(n.nodes.find(n=>n.name==='주문·픽업 상판').width,2600);assert.equal(n.nodes.find(n=>n.name==='주문·픽업 상판').height,40);for(const node of n.nodes){assert.ok(!ids.has(node.id));ids.add(node.id)}assert.deepEqual(m.validateScene(JSON.parse(JSON.stringify(n))),n)}});
await test('ordinary module bounds do not overlap at preset sizes',()=>{const n=m.brandScene(empty,brand,identity,'layout',room),boxes=n.nodes.filter(n=>!n.host).map(n=>{const quarter=Math.abs(n.rotation)%180===90;return {...n,w:quarter?n.depth:n.width,d:quarter?n.width:n.depth}});for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++){const a=boxes[i],b=boxes[j],overlap=Math.abs(a.x-b.x)<(a.w+b.w)/2-.1&&Math.abs(a.z-b.z)<(a.d+b.d)/2-.1&&a.y<b.y+b.height-.1&&b.y<a.y+a.height-.1;assert.ok(!overlap,`${a.name} overlaps ${b.name}`)}});
await test('room constraints report insufficient depth width height and short seating without clipping or shrinking modules',()=>{assert.throws(()=>m.brandScene(empty,brand,identity,'layout',{...room,depth:3000}),/깊이/);assert.throws(()=>m.brandScene(empty,brand,identity,'layout',{...room,width:2600}));const tall=structuredClone(brand);tall.modules.backbar.height=2400;assert.throws(()=>m.brandScene(empty,tall,identity,'layout',{...room,height:2200}),/천장/);const short=structuredClone(brand);short.modules.seating.width=1500;assert.throws(()=>m.brandScene(empty,short,identity,'layout',room),/1,600/);const compact=structuredClone(brand);compact.modules.seating.enabled=false;const n=m.brandScene(empty,compact,identity,'layout',{...room,depth:4000});assert.equal(n.nodes.length,6)});
await test('layout clears previous photo floorplan facade budget cameras renders but retains project candidate list and variants',()=>{const s=m.saveVariant({...source,materialShortlist:['lx-101748'],photoId:'old-photo'},'기존 매장'),n=m.brandScene(s,brand,identity,'layout',room,true);assert.deepEqual(n.materialShortlist,s.materialShortlist);assert.deepEqual(n.variants,s.variants);assert.equal(n.photoId,undefined);assert.deepEqual(n.cameras,[]);const restored=m.restoreVariant(n,n.variants[0].id);assert.equal(restored.brandApplication,undefined);assert.deepEqual(restored.nodes,s.nodes)});
await test('brand provenance follows design variant and cannot reference unknown schema fields',()=>{const a=m.brandScene(empty,brand,{id:uid(),revision:2},'layout',room),b=m.saveVariant(a,'브랜드 안'),c=m.restoreVariant({...b,brandApplication:undefined},b.variants[0].id);assert.deepEqual(c.brandApplication,a.brandApplication);assert.throws(()=>m.validateScene({...a,brandApplication:{...a.brandApplication,revision:-1}}))});
await test('stale scene and identical scene in another project session reject preview acceptance',()=>{const base=JSON.stringify(source);m.assertBrandSnapshot(source,base,5,5);assert.throws(()=>m.assertBrandSnapshot(source,base,6,5));assert.throws(()=>m.assertBrandSnapshot({...source,name:'changed'},base,5,5))});
const request=(method,body,id='',revision='')=>new Request(`https://test.local/api/brands?id=${id}&revision=${revision}`,{method,headers:{origin:'https://test.local','Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
let key=uid(),saved;
await test('brand API stores exact standard and returns same revision for exact create retries',async()=>{const payload={id:key,revision:0,standard:brand};const response=await m.POST(request('POST',payload));assert.equal(response.status,200);assert.equal(response.headers.get('Cache-Control'),'no-store');saved=await response.json();assert.equal(saved.revision,1);assert.deepEqual(saved.standard,brand);assert.deepEqual(await (await m.POST(request('POST',payload))).json(),saved);assert.deepEqual(await (await m.GET(request('GET',null,key))).json(),saved)});
await test('updates are compare-and-swap and uncertain retries cannot overwrite subsequent edits',async()=>{const update={id:key,revision:1,standard:{...brand,name:'OFD 신규 기준'}};let r=await m.POST(request('POST',update));assert.equal(r.status,200);const changed=await r.json();assert.equal(changed.revision,2);assert.deepEqual(await (await m.POST(request('POST',update))).json(),changed);assert.equal((await m.POST(request('POST',{...update,standard:brand}))).status,409);assert.equal((await m.POST(request('POST',{...update,revision:2,standard:{...brand,name:'가장 최신'}}))).status,200);assert.equal((await m.POST(request('POST',update))).status,409)});
await test('owner scoping covers list get update delete and unowned identifier collisions',async()=>{user='another-owner';assert.deepEqual(await (await m.GET(request('GET'))).json(),{brands:[]});assert.equal((await m.GET(request('GET',null,key))).status,404);for(const revision of [0,3])assert.equal((await m.POST(request('POST',{id:key,revision,standard:brand}))).status,409);assert.equal((await m.DELETE(request('DELETE',null,key,3))).status,200);user='brand-owner';assert.equal((await m.GET(request('GET',null,key))).status,200)});
await test('delete rejects stale revisions and exact delete retries are safe',async()=>{assert.equal((await m.DELETE(request('DELETE',null,key,1))).status,409);assert.equal((await m.DELETE(request('DELETE',null,key,3))).status,200);assert.equal((await m.DELETE(request('DELETE',null,key,3))).status,200);assert.equal((await m.GET(request('GET',null,key))).status,404)});
await test('authentication origin schema and payload bounds enforced before mutation',async()=>{user=null;assert.equal((await m.GET(request('GET'))).status,401);assert.equal((await m.POST(request('POST',{id:uid(),revision:0,standard:brand}))).status,401);assert.equal((await m.DELETE(request('DELETE',null,uid(),1))).status,401);user='brand-owner';const evil=request('POST',{id:uid(),revision:0,standard:brand});evil.headers.set('origin','https://foreign.local');assert.equal((await m.POST(evil)).status,403);assert.equal((await m.POST(request('POST',{id:uid(),revision:0,standard:brand,owner:'fake'}))).status,400);assert.equal((await m.POST(new Request('https://test.local/api/brands',{method:'POST',body:'x'.repeat(20001)}))).status,413);assert.equal((await m.DELETE(request('DELETE',null,uid(),0))).status,400)});
await test('project API persists brand provenance and applied material module geometry',async()=>{const scene=m.brandScene(empty,brand,{id:uid(),revision:3},'layout',room),key='brand-project';const make=(method,body)=>new Request('https://test.local/api/projects?id='+key,{method,headers:{origin:'https://test.local','Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});assert.equal((await m.projectAPI.POST(make('POST',{id:key,revision:0,scene}))).status,200);const restored=await (await m.projectAPI.GET(make('GET'))).json();assert.deepEqual(restored.scene,scene);assert.equal(restored.revision,1)});
await test('atomic per-owner 50-brand cap and indexed reads',async()=>{const payloads=Array.from({length:52},()=>({id:uid(),revision:0,standard:brand})),responses=await Promise.all(payloads.map(p=>m.POST(request('POST',p))));assert.equal(responses.filter(r=>r.status===200).length,50);assert.equal((await (await m.GET(request('GET'))).json()).brands.length,50);const first=payloads[responses.findIndex(r=>r.status===200)];assert.equal((await m.POST(request('POST',first))).status,200);await m.DELETE(request('DELETE',null,first.id,1));assert.equal((await m.POST(request('POST',{id:uid(),revision:0,standard:brand}))).status,200);const plan=sql.prepare('EXPLAIN QUERY PLAN SELECT id,content,revision,updated_at FROM brands WHERE owner=? ORDER BY updated_at DESC,id DESC LIMIT 50').all(user);assert.ok(plan.some(r=>r.detail.includes('brands_owner_updated')))});
console.log(`${count} brand standards checks passed; real SQLite with substituted authentication/runtime.`);sql.close();delete globalThis.__brandUser;delete globalThis.__brandEnv;
