import assert from 'node:assert/strict';import {build} from 'esbuild';import {mkdtemp,writeFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {pathToFileURL} from 'node:url';
const dir=await mkdtemp(join(tmpdir(),'spatial-focus-')),file=join(dir,'bundle.mjs');
const bundle=await build({stdin:{contents:"export * as T from 'three';export * from './lib/scene-engine';export * from './lib/scene-model';export * from './lib/model-loader';",resolveDir:process.cwd()},bundle:true,platform:'node',format:'esm',write:false});
await writeFile(file,bundle.outputFiles[0].text);const m=await import(pathToFileURL(file));await rm(dir,{recursive:true,force:true});const{T}=m;
let checks=0;const failures=[];async function test(name,fn){try{await fn();checks++;console.log('PASS '+name);}catch(error){failures.push({name,error});console.error('FAIL '+name+' '+error.message);}}
const near=(a,b,e=1e-6)=>assert.ok(Math.abs(a-b)<e,`${a} != ${b}`),nearVec=(a,b)=>{for(const k of ['x','y','z'])near(a[k],b[k]);};
const node=(patch={})=>({...m.createNode('box','item'),width:1200,height:800,depth:600,...patch});
function fixture(nodes=[node()],camera=new T.PerspectiveCamera(38,1.6,.05,200)){
 const e=Object.create(m.SceneEngine.prototype),s={...m.initialScene(),nodes},root=new T.Group();camera.position.set(5,4,7);let updates=0,measurementUpdates=0;
 Object.assign(e,{data:s,root,camera,perspective:camera instanceof T.PerspectiveCamera?camera:new T.PerspectiveCamera(38,1.6,.05,200),planCamera:camera instanceof T.OrthographicCamera?camera:new T.OrthographicCamera(-6,6,5,-5,.01,200),view:camera instanceof T.OrthographicCamera?'top':'perspective',selection:null,mode:'select',pivot:new T.Group(),dragActive:false,transform:{dragging:false,axis:null},orbit:{target:new T.Vector3(.5,.4,-.5),minDistance:1,maxDistance:70,enabled:true,update(){updates++;camera.updateMatrixWorld(true);}},measurementOverlay:{update(){measurementUpdates++;}},material(id){return new T.MeshStandardMaterial({name:id,color:m.materials.find(v=>v.id===id).color});}});
 for(const n of nodes)e.buildNode(n);camera.lookAt(e.orbit.target);camera.updateMatrixWorld(true);return{e,root,get updates(){return updates},get measurementUpdates(){return measurementUpdates}};
}
function release(root){root.traverse(o=>{o.geometry?.dispose();for(const mat of o.material?(Array.isArray(o.material)?o.material:[o.material]):[])mat.dispose();});}
function corners(box){return[-1,1].flatMap(x=>[-1,1].flatMap(y=>[-1,1].map(z=>new T.Vector3(x<0?box.min.x:box.max.x,y<0?box.min.y:box.max.y,z<0?box.min.z:box.max.z))));}
function assertVisible(camera,box){camera.updateMatrixWorld(true);for(const p of corners(box)){const q=p.clone().project(camera);assert.ok(Math.abs(q.x)<=1.00001&&Math.abs(q.y)<=1.00001&&q.z>=-1.00001&&q.z<=1.00001,`outside frustum ${q.toArray()} for ${p.toArray()}`);}}
function glb(){const bin=new Float32Array([0,0,0,1,1,0,0,0,1]);const data={asset:{version:'2.0'},scene:0,scenes:[{nodes:[0]}],nodes:[{mesh:0,translation:[2,1,-3]}],meshes:[{primitives:[{attributes:{POSITION:0},material:0}]}],materials:[{pbrMetallicRoughness:{baseColorFactor:[.2,.4,.6,1]}}],buffers:[{byteLength:bin.byteLength}],bufferViews:[{buffer:0,byteOffset:0,byteLength:bin.byteLength}],accessors:[{bufferView:0,componentType:5126,count:3,type:'VEC3',min:[0,0,0],max:[1,1,1]}]};let json=Buffer.from(JSON.stringify(data));json=Buffer.concat([json,Buffer.alloc((4-json.length%4)%4,32)]);const bytes=new ArrayBuffer(28+json.length+bin.byteLength),view=new DataView(bytes),out=new Uint8Array(bytes);view.setUint32(0,0x46546c67,true);view.setUint32(4,2,true);view.setUint32(8,bytes.byteLength,true);view.setUint32(12,json.length,true);view.setUint32(16,0x4e4f534a,true);out.set(json,20);const at=20+json.length;view.setUint32(at,bin.byteLength,true);view.setUint32(at+4,0x004e4942,true);out.set(new Uint8Array(bin.buffer),at+8);return bytes;}
await test('perspective focus fits actual mesh bounds in landscape and portrait while preserving direction',()=>{for(const aspect of [2,.6,.18]){const camera=new T.PerspectiveCamera(38,aspect,.05,200),{e,root}=fixture([node({x:1300,z:-700,rotation:37,width:4000,height:3000,depth:6000})],camera),before=camera.position.clone().sub(e.orbit.target).normalize(),bounds=new T.Box3().setFromObject(root);assert.equal(e.focusNodes(['item']),true);nearVec(e.orbit.target,bounds.getCenter(new T.Vector3()));nearVec(camera.position.clone().sub(e.orbit.target).normalize(),before);assertVisible(camera,bounds);release(root);}});
await test('focus uses the effective perspective field of view when a saved camera has zoom',()=>{const camera=new T.PerspectiveCamera(38,.55,.05,200);camera.zoom=3;camera.updateProjectionMatrix();const{e,root}=fixture([node({width:4000,height:3000,depth:6000})],camera),bounds=new T.Box3().setFromObject(root);assert.equal(e.focusNodes(['item']),true);assertVisible(camera,bounds);release(root);});
await test('giant objects in a very narrow viewport fit within the camera far clipping plane',()=>{const camera=new T.PerspectiveCamera(38,.18,.05,200),{e,root}=fixture([node({width:20000,height:6000,depth:20000})],camera),bounds=new T.Box3().setFromObject(root);assert.equal(e.focusNodes(['item']),true);assertVisible(camera,bounds);assert.ok(e.orbit.maxDistance>camera.position.distanceTo(e.orbit.target));release(root);});
await test('small geometry respects the orbit minimum distance with finite camera coordinates',()=>{const{e,root}=fixture([node({width:20,height:20,depth:20})]);assert.equal(e.focusNodes(['item']),true);assert.ok(e.camera.position.toArray().every(Number.isFinite));assert.ok(e.camera.position.distanceTo(e.orbit.target)>=e.orbit.minDistance);assertVisible(e.camera,new T.Box3().setFromObject(root));release(root);});
await test('orthographic top focus centres actual X/Z extents and preserves overhead direction',()=>{for(const bounds of [[-8,8,5,-5],[-3,3,8,-8]]){const camera=new T.OrthographicCamera(...bounds,.01,200),{e,root}=fixture([node({x:2100,z:-1700,width:4000,height:1800,depth:2400,rotation:37})],camera);camera.up.set(0,0,-1);camera.position.set(.5,20,-.5);camera.lookAt(e.orbit.target);const direction=camera.position.clone().sub(e.orbit.target).normalize(),box=new T.Box3().setFromObject(root);assert.equal(e.focusNodes(['item']),true);nearVec(e.orbit.target,box.getCenter(new T.Vector3()));nearVec(camera.position.clone().sub(e.orbit.target).normalize(),direction);assert.ok(camera.zoom>0);assertVisible(camera,box);release(root);}});
await test('orthographic tiny objects remain finite within the supported zoom cap',()=>{const camera=new T.OrthographicCamera(-6,6,5,-5,.01,200),{e,root}=fixture([node({width:20,height:20,depth:20})],camera);camera.up.set(0,0,-1);camera.position.set(.5,20,-.5);assert.equal(e.focusNodes(['item']),true);assert.ok(camera.zoom<=100&&camera.zoom>0);assertVisible(camera,new T.Box3().setFromObject(root));release(root);});
await test('missing and hidden selected objects return false without moving the camera',()=>{const{e,root}=fixture([node({hidden:true})]),position=e.camera.position.clone(),target=e.orbit.target.clone();for(const ids of [[],['missing'],['item'],['missing','item']]){assert.equal(e.focusNodes(ids),false);nearVec(e.camera.position,position);nearVec(e.orbit.target,target);}release(root);});
await test('multiple selected IDs fit their combined real bounds and ignore unrelated or duplicate IDs',()=>{const{e,root}=fixture([node({id:'a',x:-2200,z:1400}),node({id:'b',x:3200,z:-2400,rotation:90}),node({id:'elsewhere',x:12000,z:10000})]),box=new T.Box3();for(const g of root.children.filter(g=>['a','b'].includes(g.userData.nodeId)))box.union(new T.Box3().setFromObject(g));assert.equal(e.focusNodes(['a','b','a','missing']),true);nearVec(e.orbit.target,box.getCenter(new T.Vector3()));assertVisible(e.camera,box);release(root);});
await test('focus follows actual open door leaf and handle bounds outside the nominal wall',()=>{const opening={id:crypto.randomUUID(),name:'문',kind:'door',x:0,bottom:0,width:900,height:2100,door:{hinge:'left',side:'positive',angle:90}},n=node({kind:'partition',width:2400,height:2900,depth:500,x:1000,z:-500,rotation:37,openings:[opening]}),{e,root}=fixture([n]),box=new T.Box3().setFromObject(root),declared=new T.Box3().setFromCenterAndSize(new T.Vector3(n.x/1000,n.height/2000,n.z/1000),new T.Vector3(n.width/1000,n.height/1000,n.depth/1000));assert.equal(e.focusNodes(['item']),true);nearVec(e.orbit.target,box.getCenter(new T.Vector3()));assert.ok(e.orbit.target.distanceTo(declared.getCenter(new T.Vector3()))>.1);assertVisible(e.camera,box);release(root);});
await test('focus uses loaded GLB nested mesh transforms instead of node dimension metadata',async()=>{const parsed=await m.parseModel(glb()),{e,root}=fixture([]),group=new T.Group();group.userData.nodeId='imported';group.position.set(2,1,-1);group.rotation.y=37*Math.PI/180;parsed.root.scale.multiply(new T.Vector3(3,1.5,2));group.add(parsed.root);root.add(group);e.data.nodes=[node({id:'imported',kind:'model',assetId:crypto.randomUUID(),width:100,height:100,depth:100})];const box=new T.Box3().setFromObject(group);assert.equal(e.focusNodes(['imported']),true);nearVec(e.orbit.target,box.getCenter(new T.Vector3()));assertVisible(e.camera,box);release(root);});
await test('selection, painted materials and persisted scene data remain unchanged after focus',()=>{const n=node({faces:{'body:4':'sage'},estimate:{unitPrice:12000},locked:true}),{e,root}=fixture([n]),selection={id:'item',face:'body:4'};e.selection=selection;e.measureStart={kind:'room',surface:'floor',u:.5,v:.5,offset:0};const before=JSON.stringify(e.data),positions=root.children.map(o=>o.position.clone()),materials=[];root.traverse(o=>{for(const a of o.material?(Array.isArray(o.material)?o.material:[o.material]):[])materials.push({ref:a,uuid:a.uuid,color:a.color.getHex()});});assert.equal(e.focusNodes(['item']),true);assert.equal(JSON.stringify(e.data),before);assert.equal(e.selection,selection);assert.equal(e.measureStart,null);root.children.forEach((o,i)=>nearVec(o.position,positions[i]));for(const a of materials){assert.equal(a.ref.uuid,a.uuid);assert.equal(a.ref.color.getHex(),a.color);}release(root);});
await test('pending transforms are cancelled before calculating the final focus position',()=>{const n=node({x:300,z:-600}),{e,root}=fixture([n]);e.selection={id:'item'};e.dragActive=true;e.transform.dragging=true;root.children[0].position.set(8,0,5);assert.equal(e.focusNodes(['item']),true);assert.equal(e.dragActive,false);near(root.children[0].position.x,.3);near(root.children[0].position.z,-.6);const expected=new T.Box3().setFromObject(root).getCenter(new T.Vector3());nearVec(e.orbit.target,expected);release(root);});
await test('a degenerate starting camera offset receives a usable finite viewing direction',()=>{const{e,root}=fixture();e.camera.position.copy(e.orbit.target);assert.equal(e.focusNodes(['item']),true);assert.ok(e.camera.position.toArray().every(Number.isFinite));assert.ok(e.camera.position.distanceTo(e.orbit.target)>0);assertVisible(e.camera,new T.Box3().setFromObject(root));release(root);});
function hostFixture(nodes,view='perspective',outside='front'){
 const camera=view==='top'?new T.OrthographicCamera(-6,6,5,-5,.01,200):new T.PerspectiveCamera(38,1.6,.05,200),f=fixture(nodes,camera),{e,root}=f;
 Object.assign(e,{cutaway:true,helpers:new T.Group(),multiOutlines:[],host:{clientWidth:900,clientHeight:600,style:{}},resize(){}});e.transform.detach=()=>{};
 e.orbit.target.set(0,view==='top'?0:1,0);
 if(view==='top'){camera.up.set(0,0,-1);camera.position.set(0,20,.00001);}else camera.position.set(outside==='left'?-9:outside==='right'?9:0,3,outside==='back'?-9:outside==='front'?9:0);
 camera.lookAt(e.orbit.target);camera.updateMatrixWorld(true);
 for(const host of ['front','back','left','right']){const wall=new T.Group();wall.userData.wall=host;root.add(wall);}
 e.updateCutaway();return f;
}
const hosted=(kind='door',host='front',hidden=false)=>({...m.createNode(kind,`${kind}-${host}`),host,hidden});
await test('automatic cutaway does not prevent focus on any hosted door or window in top and perspective views',()=>{
 for(const view of ['top','perspective'])for(const host of ['front','back','left','right'])for(const kind of ['door','window']){
  const n=hosted(kind,host),{e,root}=hostFixture([n],view,host),object=root.children.find(o=>o.userData.nodeId===n.id),wall=root.children.find(o=>o.userData.wall===host),before=JSON.stringify(e.data);
  assert.equal(object.visible,false);assert.equal(wall.visible,false);e.setSelection({id:n.id});assert.equal(e.focusNodes([n.id]),true);assert.equal(object.visible,true);assert.equal(wall.visible,false);assert.equal(e.data.nodes[0].hidden,false);assert.equal(JSON.stringify(e.data),before);assertVisible(e.camera,new T.Box3().setFromObject(object));release(root);release(e.helpers);
 }
});
await test('explicitly hidden hosted objects remain hidden and unfocusable despite cutaway overrides',()=>{
 for(const view of ['top','perspective'])for(const host of ['front','back','left','right']){
  const n=hosted('door',host,true),{e,root}=hostFixture([n],view,host),object=root.children.find(o=>o.userData.nodeId===n.id),position=e.camera.position.clone(),target=e.orbit.target.clone();assert.equal(e.focusNodes([n.id]),false);e.updateCutaway();assert.equal(object.visible,false);assert.ok(!e.focusedHostIds?.has(n.id));nearVec(e.camera.position,position);nearVec(e.orbit.target,target);release(root);release(e.helpers);
 }
});
await test('changing or clearing the selection restores automatic cutaway on the previously focused host',()=>{
 const a=hosted('door','front'),b=hosted('window','back'),{e,root}=hostFixture([a,b],'top'),first=root.children.find(o=>o.userData.nodeId===a.id),second=root.children.find(o=>o.userData.nodeId===b.id);
 e.setSelection({id:a.id});assert.equal(e.focusNodes([a.id]),true);assert.equal(first.visible,true);assert.equal(second.visible,false);
 e.setSelection({id:b.id});e.updateCutaway();assert.equal(first.visible,false);assert.equal(second.visible,false);assert.ok(!e.focusedHostIds.has(a.id));assert.equal(e.focusNodes([b.id]),true);assert.equal(second.visible,true);
 e.setSelection(null);e.updateCutaway();assert.equal(second.visible,false);assert.equal(e.focusedHostIds.size,0);release(root);release(e.helpers);
});
await test('same-selection refresh retains the host visibility override while a newly hidden node still wins',()=>{
 const n=hosted(),{e,root}=hostFixture([n],'top'),object=root.children.find(o=>o.userData.nodeId===n.id);e.setSelection({id:n.id});assert.equal(e.focusNodes([n.id]),true);e.setSelection({id:n.id});e.updateCutaway();assert.equal(object.visible,true);
 e.data={...e.data,nodes:[{...n,hidden:true}]};e.updateCutaway();assert.equal(object.visible,false);assert.equal(e.focusNodes([n.id]),false);release(root);release(e.helpers);
});
await test('resetting the current view clears focused-host overrides and restores wall cutaway',()=>{
 for(const view of ['top','perspective']){
  const n=hosted(),{e,root}=hostFixture([n],view),object=root.children.find(o=>o.userData.nodeId===n.id);e.setSelection({id:n.id});assert.equal(e.focusNodes([n.id]),true);assert.equal(object.visible,true);e.setView(view);assert.equal(e.focusedHostIds.size,0);e.updateCutaway();assert.equal(object.visible,false);release(root);release(e.helpers);
 }
});
console.log(`${checks} camera focus checks passed, ${failures.length} failed.`);if(failures.length)process.exitCode=1;
