import assert from 'node:assert/strict';
import {build} from 'esbuild';
const bundle=await build({stdin:{contents:"export * as T from 'three';export * from './lib/scene-model';export * from './lib/selection';export * from './lib/design-variants';export * from './lib/floor-plan';export * from './lib/scene-engine';",resolveDir:process.cwd()},bundle:true,platform:'node',format:'esm',write:false});
const m=await import('data:text/javascript;base64,'+Buffer.from(bundle.outputFiles[0].text).toString('base64')),{T}=m;
let checks=0;
function test(name,fn){try{fn();checks++;console.log('PASS '+name)}catch(e){console.error('FAIL '+name+': '+e.message);process.exitCode=1}}
const near=(a,b,tolerance=1e-8)=>assert.ok(Math.abs(a-b)<tolerance,`${a} != ${b}`);
function pair(){const s=m.initialScene();s.nodes=[m.createNode('chair','a',-650,0),m.createNode('chair','b',650,0)];return s}
const ids=['a','b'];
test('group no-op preserves negative yaw and fractional coordinates exactly',()=>{const s=pair();Object.assign(s.nodes[0],{x:-650.4,y:12.3,z:2.7,rotation:-90});s.nodes[1].rotation=12.4;const next=m.transformGroup(s,ids,{x:0,y:0,z:0,rotation:0});assert.deepEqual(next,s);const moved=m.transformGroup(s,ids,{x:100,y:0,z:0,rotation:0});assert.equal(moved.nodes[1].rotation,12.4);assert.equal(moved.nodes[0].y,12.3);assert.equal(moved.nodes[0].z,2.7)});
test('group rotation follows Three Y yaw and preserves relative spacing within mm precision',()=>{const s=pair();for(const yaw of [90,-90,45]){const next=m.transformGroup(s,ids,{x:100,y:50,z:200,rotation:yaw});near(Math.hypot(next.nodes[0].x-next.nodes[1].x,next.nodes[0].z-next.nodes[1].z),1300,1.5);near(next.nodes[0].y,50);const expected=new T.Vector3(-650,0,0).applyAxisAngle(new T.Vector3(0,1,0),yaw*Math.PI/180);near(next.nodes[0].x,Math.round(expected.x+100));near(next.nodes[0].z,Math.round(expected.z+200));}});
test('group boundary, floor, lock and hosted failures reject atomically',()=>{for(const mutate of [s=>{s.nodes[1].x=3300},s=>{s.nodes[0].locked=true},s=>{s.nodes[0].hidden=true},s=>{s.nodes[0]={...m.createNode('window','a'),host:'left'}}]){const s=pair();mutate(s);const before=JSON.stringify(s);assert.throws(()=>m.transformGroup(s,ids,{x:600,y:0,z:0,rotation:0}));assert.equal(JSON.stringify(s),before)}assert.throws(()=>m.transformGroup(pair(),ids,{x:0,y:-1,z:0,rotation:0}));assert.throws(()=>m.transformGroup(pair(),ids,{x:NaN,y:0,z:0,rotation:0}))});
test('multi-select toggles, prunes deleted nodes, and keeps surfaces single',()=>{const s=pair();let selection=m.chooseSelection(s,{id:'a'},{id:'b'},true);assert.deepEqual(m.selectionIds(selection),ids);selection=m.chooseSelection(s,selection,{id:'a'},true);assert.deepEqual(selection,{id:'b'});assert.deepEqual(m.chooseSelection(s,{id:'floor'},{id:'a'},true),{id:'a'});assert.deepEqual(m.chooseSelection(s,{id:'a'},{id:'floor'},true),{id:'floor'});assert.deepEqual(m.normalizeSelection(s,{id:'a',ids:['a','missing','a']}),{id:'a'});assert.equal(m.normalizeSelection(s,{id:'missing'}),null)});
test('bulk paint clears overrides for all, duplicate IDs differ, and locked deletion is atomic',()=>{const s=pair();s.nodes[0].faces={'seat:0':'oak'};s.nodes[0].faceFinishes={'seat:0':{color:'#ffffff'}};const painted=m.batchAction(s,ids,{type:'material',material:'steel'});for(const n of painted.nodes){assert.equal(n.material,'steel');assert.equal(n.uniformMaterial,true);assert.deepEqual(n.faces,{});assert.deepEqual(n.faceFinishes,{})}let count=0;const duplicated=m.batchAction(s,ids,{type:'duplicate',x:0,z:500},()=>`copy-${++count}`);assert.equal(new Set(duplicated.nodes.map(n=>n.id)).size,4);assert.equal(duplicated.nodes[3].z,500);s.nodes[1].locked=true;assert.throws(()=>m.batchAction(s,ids,{type:'delete'}));assert.equal(s.nodes.length,2)});
test('bulk alignment uses rotated footprint edges',()=>{const s=pair();s.nodes[0].rotation=45;s.nodes[1].rotation=90;const next=m.batchAction(s,ids,{type:'align',axis:'x',edge:'min'});const edges=next.nodes.map(n=>n.x-m.footprint(n).width/2);near(edges[0],edges[1])});
test('quick material command reaches all selected nodes; size command does not partially resize',()=>{const selected={id:'a',ids};const commands=m.quickCommands('소재를 오크로 바꿔줘',selected);assert.ok(commands?.length===2);assert.deepEqual(commands.map(c=>c.target),ids);assert.equal(m.quickCommands('폭 1000',selected),null)});
test('variants are independent nonrecursive snapshots, with provenance restored or cleared',()=>{let s=pair();s=m.saveVariant(s,'manual');const first=s.variants[0];assert.equal(first.design.variants,undefined);assert.equal(first.design.cameras,undefined);s.nodes[0].x=-300;s.photoId='photo-b';s.palette=['#ffffff'];s.draft={method:'photo-ai',summary:'B',notes:['추정 배치']};s=m.saveVariant(s,'AI');const ai=s.variants[1];assert.equal(ai.design.draft.summary,'B');s.name='current project';s.cameras=[{id:'view',name:'view',position:[1,2,3],target:[0,0,0]}];const restored=m.restoreVariant(s,first.id);assert.equal(restored.nodes[0].x,-650);assert.equal(restored.photoId,undefined);assert.equal(restored.palette,undefined);assert.equal(restored.draft,undefined);assert.equal(restored.name,s.name);assert.deepEqual(restored.cameras,s.cameras);assert.equal(restored.variants.length,2);assert.equal(m.restoreVariant(restored,ai.id).draft.summary,'B');restored.nodes[0].x=0;assert.equal(first.design.nodes[0].x,-650)});
test('snapshot limits, IDs and stored geometry are validated',()=>{let s=pair();for(let i=0;i<6;i++)s=m.saveVariant(s,`안 ${i}`);assert.throws(()=>m.saveVariant(s,'overflow'));const duplicate=structuredClone(s);duplicate.variants[1].id=duplicate.variants[0].id;assert.throws(()=>m.validateScene(duplicate));const invalid=structuredClone(s);invalid.variants[0].design.nodes[0].x=10000;assert.throws(()=>m.validateScene(invalid));assert.throws(()=>m.restoreVariant(s,'missing'));const heavy=pair();heavy.nodes=Array.from({length:300},(_,i)=>({...m.createNode('chair',String(i)),name:'가'.repeat(80),faceFinishes:Object.fromEntries(Array.from({length:12},(_,j)=>[`좌석${j}`,{color:'#ffffff',roughness:.5}]))}));heavy.variants=Array.from({length:6},()=>({id:crypto.randomUUID(),name:'안',note:'',createdAt:new Date().toISOString(),design:m.designSchema.parse(heavy)}));assert.throws(()=>m.validateScene(heavy),/프로젝트 크기/)});
test('change summary captures object, room-material and lighting differences',()=>{const a=pair(),b=structuredClone(a);b.nodes[0].material='steel';b.nodes.pop();b.nodes.push(m.createNode('chair','c'));b.room.surfaces.floor.material='charcoal';b.lighting.warmth=3000;assert.deepEqual(m.designChanges(a,b),{added:1,removed:1,changed:1,room:true,lighting:true,facade:false,budget:false,layers:false,measurements:false,underlay:false})});
test('plan yaw matches Three geometry and hosted spans use correct wall coordinates',()=>{const n={...m.createNode('box','box',100,200),rotation:37};const actual=m.planCorners(n);for(const [i,[u,v]]of [[-1,-1],[1,-1],[1,1],[-1,1]].entries()){const p=new T.Vector3(u*n.width/2,0,v*n.depth/2).applyAxisAngle(new T.Vector3(0,1,0),37*Math.PI/180);near(actual[i].x,100+p.x);near(actual[i].z,200+p.z)}const s=pair();for(const host of ['left','right','back','front']){const opening={...m.createNode('window','window',300,600),host};const span=m.openingSpan(opening,s.room);assert.equal(span.along,['left','right'].includes(host)?600:300);assert.equal(span.cross,host==='left'?-3600:host==='right'?3600:host==='back'?-3200:3200)}});
test('plan fits largest room and rejects paper overflow; hidden/upper filters preserve numbering',()=>{const s=pair();s.room.width=s.room.depth=20000;assert.equal(m.planScale(s),150);assert.throws(()=>m.planScale(s,25));s.nodes[0].hidden=true;s.nodes.push({...m.createNode('pendant','lamp'),y:1500});assert.equal(m.planRows(s).length,2);assert.equal(m.planRows(s,false).length,1);assert.equal(m.planRows(s,false)[0][0],'1')});
test('plan escapes text, neutralizes CSV formulas and reflects floor/wall materials',()=>{const s=pair();s.nodes[0].name='<script>alert(1)</script>';s.nodes[1].name=' =1+1';s.nodes[0].rotation=45;s.room.surfaces.floor={material:'oak',finish:{color:'#123456'}};const svg=m.floorPlanSvg(s,'<img onerror="alert(1)">');assert.ok(!svg.includes('<script>'));assert.ok(svg.includes('&lt;script&gt;'));assert.ok(svg.includes('rotate(-45)'));assert.ok(svg.includes('fill="#123456"'));assert.ok(m.floorPlanCsv(s).includes('"\' =1+1"'));const rows=m.surfaceRows(s);assert.equal(rows.length,5);assert.equal(rows[0][2],'#123456')});
test('printed schedule includes all 300 long names and surface specifications',()=>{const s=pair();s.nodes=Array.from({length:300},(_,i)=>({...m.createNode('chair',String(i)),name:`N${i}-`+'긴'.repeat(70)}));const html=m.floorPlanPrintHtml(s,'매장 <테스트>');for(const n of s.nodes)assert.ok(html.includes(`<td>${n.name}</td>`));assert.ok(html.includes('벽·바닥 소재'));assert.ok(html.includes('매장 &lt;테스트&gt;'));assert.ok(html.includes('@page{size:A3 landscape'));assert.ok((html.match(/class="page schedule"/g)||[]).length>=20)});
function engineFixture(){const data=pair(),engine=Object.create(m.SceneEngine.prototype);Object.assign(engine,{root:new T.Group(),helpers:new T.Group(),pivot:new T.Group(),data,geometryKey:'same',multiOutlines:[],selection:null,mode:'translate',dragActive:false,orbit:{enabled:true},transform:{object:null,dragging:false,detach(){this.object=null},attach(o){this.object=o},setMode(){}}});for(const n of data.nodes){const g=new T.Group();g.userData.nodeId=n.id;g.position.set(n.x/1000,n.y/1000,n.z/1000);g.add(new T.Mesh(new T.BoxGeometry(n.width/1000,n.height/1000,n.depth/1000),new T.MeshBasicMaterial()));engine.root.add(g)}engine.setSelection({id:'a',ids});return engine}
function gesture(engine,delta){const pivot=m.groupBounds(engine.data.nodes).center;engine.groupDrag={key:engine.geometryKey,nodes:structuredClone(engine.data.nodes),pivot};engine.dragActive=true;engine.transform.dragging=true;engine.pivot.position.set((pivot.x+delta.x)/1000,(pivot.y+delta.y)/1000,(pivot.z+delta.z)/1000);engine.pivot.rotation.set(0,delta.rotation*Math.PI/180,0);for(const p of m.groupPoses(engine.groupDrag.nodes,delta,pivot)){const o=engine.root.children.find(o=>o.userData.nodeId===p.id);o.position.set(p.x/1000,p.y/1000,p.z/1000);o.rotation.set(0,p.rotation*Math.PI/180,0)}}
test('actual engine keeps group selected during async refresh and cancels all members',()=>{const e=engineFixture();assert.equal(e.transform.object,e.pivot);assert.equal(e.multiOutlines.length,2);gesture(e,{x:500,y:50,z:0,rotation:90});const outlines=e.multiOutlines;e.setSelection({id:'a',ids});assert.equal(e.multiOutlines,outlines);e.cancelTransform();assert.equal(e.dragActive,false);assert.equal(e.transform.dragging,false);assert.equal(e.pivot.rotation.y,0);for(const n of e.data.nodes){const o=e.root.children.find(o=>o.userData.nodeId===n.id);near(o.position.x*1000,n.x);near(o.position.y*1000,n.y)}});
test('actual engine ends no-op gestures without history and resets pivot drift',()=>{const e=engineFixture();let commits=0;e.onTransformGroup=()=>commits++;gesture(e,{x:.1,y:0,z:0,rotation:0});e.finishGroupTransform();assert.equal(commits,0);near(e.pivot.position.x,0);near(e.pivot.rotation.y,0);assert.equal(e.dragActive,false);assert.equal(e.groupDrag,undefined)});
test('actual engine commits once and resets pivot from live transformed members before React updates',()=>{const e=engineFixture();let commits=0;e.onTransformGroup=(received,delta,pivot)=>{commits++;assert.deepEqual(received,ids);assert.equal(e.dragActive,false);assert.equal(e.transform.dragging,false);m.transformGroup(e.data,received,delta,pivot)};gesture(e,{x:500,y:50,z:200,rotation:90});e.finishGroupTransform();assert.equal(commits,1);near(e.pivot.position.x,.5);near(e.pivot.position.z,.2);near(e.pivot.rotation.y,0)});
test('actual engine discards stale transaction and restores rejected transforms',()=>{const e=engineFixture();let commits=0;e.onTransformGroup=()=>commits++;gesture(e,{x:500,y:0,z:0,rotation:45});e.geometryKey='new';e.finishGroupTransform();assert.equal(commits,0);near(e.root.children[0].position.x,-.65);e.onTransformGroup=()=>{throw new Error('rejected')};gesture(e,{x:500,y:0,z:0,rotation:45});assert.throws(()=>e.finishGroupTransform(),/rejected/);near(e.root.children[0].position.x,-.65);near(e.pivot.position.x,0);near(e.pivot.rotation.y,0)});
console.log(`${checks} design-tool checks passed.`);
