import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {mkdtemp,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
const dir=await mkdtemp(join(tmpdir(),'spatial-door-integration-')),file=join(dir,'bundle.mjs');
const bundle=await build({stdin:{contents:"export * as T from 'three';export * from './lib/scene-model';export * from './lib/partition-openings';export * from './lib/scene-engine';export * from './lib/door-geometry';export * from './lib/budget';export * from './lib/design-variants';export * from './lib/material-catalog';export * from './lib/measurement-picking';export * from './lib/glb';",resolveDir:process.cwd()},bundle:true,platform:'node',format:'esm',write:false});
await writeFile(file,bundle.outputFiles[0].text);const m=await import(pathToFileURL(file));await rm(dir,{recursive:true,force:true});const {T}=m;
let checks=0;async function test(name,fn){await fn();checks++;console.log('PASS '+name);}
const near=(a,b,tolerance=1e-6)=>assert.ok(Math.abs(a-b)<tolerance,`${a} != ${b}`),uuid=()=>crypto.randomUUID();
const opening=(extra={})=>({id:uuid(),name:'내부 문',kind:'door',x:0,bottom:0,width:900,height:2100,door:{hinge:'left',side:'positive',angle:90},...extra});
const node=(extra={})=>({...m.createNode('partition','wall'),width:2400,height:2900,depth:120,openings:[opening()],...extra});
const scene=(n=node())=>{const s=m.initialScene();return{...s,room:{...s.room,width:12000,depth:12000,height:3200},nodes:[n]};};
function engine(n){const e=Object.create(m.SceneEngine.prototype);Object.assign(e,{root:new T.Group(),data:scene(n),material(id){const a=m.materials.find(v=>v.id===id);return new T.MeshStandardMaterial({name:id,color:a.color});},modelsReady:async()=>{}});const g=e.buildNode(n);e.root.updateMatrixWorld(true);return{e,g};}
function dispose(g){g.traverse(o=>{o.geometry?.dispose();if(o.material)for(const a of Array.isArray(o.material)?o.material:[o.material])a.dispose();});}
function part(g,name){let found;g.traverse(o=>{if(o.userData.part===name)found=o;});assert.ok(found,`missing ${name}`);return found;}
function expectedBox(n,local){const b=m.toWorldDoorBox(n,local),r=b.rotation*Math.PI/180,hx=(Math.abs(Math.cos(r))*b.width+Math.abs(Math.sin(r))*b.depth)/2,hz=(Math.abs(Math.sin(r))*b.width+Math.abs(Math.cos(r))*b.depth)/2;return new T.Box3(new T.Vector3((b.x-hx)/1000,(b.y-b.height/2)/1000,(b.z-hz)/1000),new T.Vector3((b.x+hx)/1000,(b.y+b.height/2)/1000,(b.z+hz)/1000));}
function sameBox(a,b){for(const bound of ['min','max'])for(const axis of ['x','y','z'])near(a[bound][axis],b[bound][axis],1e-6);}
function obstacleAt(n,local,extra={}){const p=m.toWorldDoorBox(n,local);return{...m.createNode('box','obstacle',p.x,p.z),y:p.y-100,width:100,height:200,depth:100,rotation:p.rotation,...extra};}
await test('door configuration survives JSON and independent variant restoration',()=>{const n=node({openings:[opening({door:{hinge:'right',side:'negative',angle:67.125}})]}),s=m.saveVariant(scene(n),'열림'),changed=structuredClone(s);changed.nodes[0].openings[0].door.angle=0;const json=m.validateScene(JSON.parse(JSON.stringify(changed)));assert.equal(json.nodes[0].openings[0].door.angle,0);assert.equal(m.restoreVariant(json,json.variants[0].id).nodes[0].openings[0].door.angle,67.125);assert.deepEqual(s.nodes[0].openings,n.openings);});
await test('non-door configurations and invalid finite angle hinge or side values reject',()=>{for(const patch of [{kind:'passage'},{kind:'window',bottom:600,height:1200}])assert.throws(()=>m.validateScene(scene(node({openings:[opening(patch)]}))),/문에만/);for(const patch of [{angle:-.01},{angle:120.01},{angle:NaN},{angle:Infinity},{hinge:'middle'},{side:'outside'}])assert.throws(()=>m.validateScene(scene(node({openings:[opening({door:{hinge:'left',side:'positive',angle:0,...patch}})]}))));for(const angle of [0,120])assert.equal(m.validateScene(scene(node({openings:[opening({door:{hinge:'right',side:'negative',angle}})]}))).nodes[0].openings[0].door.angle,angle);});
await test('upgraded leaf and closed handle enforce the exact 60mm room inner boundary',()=>{for(const rotation of [0,90])for(const angle of [0,90]){const extent=angle===0?107:914.5,axis=rotation===0?'z':'x',n=node({rotation,[axis]:6000-60-extent,openings:[opening({door:{hinge:'left',side:'positive',angle}})]}),s=scene(n);m.validateScene(s);const before=JSON.stringify(s);assert.throws(()=>m.validateScene({...s,nodes:[{...n,[axis]:n[axis]+.01}]}),/손잡이.*안쪽/);assert.equal(JSON.stringify(s),before);}});
await test('hidden nodes and inactive variants cannot conceal an out-of-room leaf',()=>{const n=node({z:5100}),s=scene(n);assert.throws(()=>m.validateScene({...s,nodes:[{...n,hidden:true}]}),/실내 벽/);const saved=m.saveVariant(scene(),'이전');saved.variants[0].design.nodes=[{...n,hidden:true}];assert.throws(()=>m.validateScene(saved),/실내 벽/);});
await test('opening-angle-only edits preserve confirmed price basis and aggregation',()=>{const n=node(),s=m.editEstimates(scene(n),['wall'],{unitPrice:550000}),o=n.openings[0],p=m.planPartitionOpenings(s,'wall',[{...o,door:{...o.door,angle:12.5}}]);assert.equal(m.priceBasis(p.scene.nodes[0]),m.priceBasis(s.nodes[0]));assert.equal(m.priceNeedsReview(p.scene.nodes[0]),false);const both={...p.scene,nodes:[s.nodes[0],{...p.scene.nodes[0],id:'copy'}]};assert.equal(m.budgetRows(both).length,1);assert.equal(m.budgetRows(both)[0].amount,1100000);});
await test('hinge side and legacy-to-surface mounting changes require price review',()=>{const n=node(),s=m.editEstimates(scene(n),['wall'],{unitPrice:550000}),o=n.openings[0];for(const change of [{hinge:'right'},{side:'negative'}]){const p=m.planPartitionOpenings(s,'wall',[{...o,door:{...o.door,...change}}]);assert.equal(m.priceNeedsReview(p.scene.nodes[0]),true);}const legacy=node({openings:[opening({door:undefined})]}),priced=m.editEstimates(scene(legacy),['wall'],{unitPrice:550000}),mounted=m.planPartitionOpenings(priced,'wall',[{...legacy.openings[0],door:{hinge:'left',side:'positive',angle:0}}]);assert.equal(m.priceNeedsReview(mounted.scene.nodes[0]),true);});
await test('true partition collision leaves passage voids empty while retaining wall and header',()=>{const wall=node({openings:[opening({kind:'passage',door:undefined})]}),s=scene(wall),box={...m.createNode('box','box'),width:500,depth:50,height:1000};s.nodes.push(box);assert.equal(m.collisions(s).length,0);s.nodes[1]={...box,x:900};assert.equal(m.collisions(s).length,1);s.nodes[1]={...box,y:2200,height:200};assert.equal(m.collisions(s).length,1);});
await test('open leaves outside the partition footprint collide at arbitrary parent rotation',()=>{for(const rotation of [0,37,90,-143]){const wall=node({rotation,x:300,z:-400}),geometry=m.doorGeometry(wall,wall.openings[0]),s=scene(wall);s.nodes.push(obstacleAt(wall,geometry.leaf));const collisions=m.collisions(s);assert.equal(collisions.length,1);assert.deepEqual(new Set([collisions[0].a,collisions[0].b]),new Set(['wall','obstacle']));}});
await test('closed handles outside the wall are included in collision with exact height separation',()=>{const wall=node({openings:[opening({door:{hinge:'left',side:'positive',angle:0}})]}),geometry=m.doorGeometry(wall,wall.openings[0]),s=scene(wall),handle=obstacleAt(wall,geometry.handle,{width:20,depth:15,height:20,y:geometry.handle.y-10});s.nodes.push(handle);assert.equal(m.collisions(s).length,1);s.nodes[1]={...handle,y:geometry.handle.y+geometry.handle.height/2+2};assert.equal(m.collisions(s).length,0);});
await test('above-leaf furniture and hidden partitions are excluded from door collision',()=>{const wall=node(),geometry=m.doorGeometry(wall,wall.openings[0]),s=scene(wall);s.nodes.push(obstacleAt(wall,geometry.leaf,{y:2200,height:200}));assert.equal(m.collisions(s).length,0);s.nodes[1]=obstacleAt(wall,geometry.leaf);s.nodes[0]={...wall,hidden:true};assert.equal(m.collisions(s).length,0);});
await test('legacy array helper measures the full asymmetric width or depth without changing door data',()=>{for(const axis of ['x','z']){const wall=node({rotation:37,x:-1000,z:-1000}),s=scene(wall),p=m.arrayNode(s,'wall',2,225.25,axis);let previous=m.physicalNodeBounds(p.nodes[0]);for(const copy of p.nodes.slice(1)){const b=m.physicalNodeBounds(copy);near(b.min[axis]-previous.max[axis],225.25);assert.deepEqual(copy.openings,wall.openings);previous=b;}}});
await test('legacy wall placement helper uses true asymmetric extremes and physical center',()=>{const wall=node({rotation:37,x:500.125,z:-300.875}),s=scene(wall);for(const edge of ['left','right','back','front','center']){const p=m.placeAgainst(s,'wall',edge),b=m.physicalNodeBounds(p.nodes[0]);if(edge==='center'){near(b.center.x,0);near(b.center.z,0);}else{const axis=['left','right'].includes(edge)?'x':'z',negative=['left','back'].includes(edge);near(negative?b.min[axis]:b.max[axis],(negative?-1:1)*(6000-65));}assert.deepEqual(p.nodes[0].openings,wall.openings);}});
await test('actual engine panel and handle boxes match helper across yaw hinges sides thickness and angle',()=>{for(const rotation of [0,37,-143])for(const hinge of ['left','right'])for(const side of ['positive','negative'])for(const angle of [0,47.5,90,120])for(const depth of [20,500]){const o=opening({door:{hinge,side,angle}}),n=node({rotation,x:500.125,y:42.875,z:-600.25,depth,openings:[o]}),{g}=engine(n),geometry=m.doorGeometry(n,o);try{sameBox(new T.Box3().setFromObject(part(g,`op-${o.id}-panel`)),expectedBox(n,geometry.leaf));sameBox(new T.Box3().setFromObject(part(g,`op-${o.id}-handle`)),expectedBox(n,geometry.handle));}finally{dispose(g);}}});
await test('opening face keys remain material-selectable and keep face paint under pivot nesting',()=>{const o=opening(),face=`op-${o.id}-panel:4`,n=node({openings:[o],faces:{[face]:'walnut',[`op-${o.id}-handle:2`]:'sage'}}),{g}=engine(n);try{const slots=m.renderedMaterialSlots(g,[n]);assert.ok(slots.some(s=>s.face===face));assert.ok(slots.some(s=>s.face===`op-${o.id}-handle:2`));assert.equal(part(g,`op-${o.id}-panel`).material[4].name,'walnut');assert.equal(part(g,`op-${o.id}-handle`).material[2].name,'sage');assert.ok(slots.filter(s=>s.face.startsWith(`op-${o.id}-`)).every(s=>s.hasUv));}finally{dispose(g);}});
await test('temporary motion preview moves actual mesh without mutating data geometry materials or metadata',()=>{const o=opening({door:{hinge:'right',side:'negative',angle:90}}),n=node({rotation:37,openings:[o]}),{e,g}=engine(n),before=JSON.stringify(e.data),panel=part(g,`op-${o.id}-panel`),geometry=panel.geometry,material=panel.material,metadata=JSON.stringify(g.userData);try{assert.equal(e.previewDoorAngle('wall',o.id,15.75),true);sameBox(new T.Box3().setFromObject(panel),expectedBox(n,m.doorGeometry(n,{...o,door:{...o.door,angle:15.75}}).leaf));assert.equal(JSON.stringify(e.data),before);assert.equal(JSON.stringify(g.userData),metadata);assert.equal(panel.geometry,geometry);assert.equal(panel.material,material);assert.equal(e.previewDoorAngle('wall',o.id,90),true);sameBox(new T.Box3().setFromObject(panel),expectedBox(n,m.doorGeometry(n,o).leaf));for(const angle of [-1,121,NaN,Infinity])assert.equal(e.previewDoorAngle('wall',o.id,angle),false);assert.equal(e.previewDoorAngle('missing',o.id,0),false);assert.equal(e.previewDoorAngle('wall','missing',0),false);}finally{dispose(g);}});
await test('measurement picking blocks moving leaves and handles without clicking through to frame',()=>{const o=opening(),n=node({openings:[o]}),{e,g}=engine(n);try{const frame=part(g,`op-${o.id}-frameL`),framePoint=new T.Vector3();frame.getWorldPosition(framePoint);const frameHit={object:frame,point:framePoint,distance:2};for(const role of ['panel','handle']){const moving=part(g,`op-${o.id}-${role}`),point=new T.Vector3();moving.getWorldPosition(point);assert.throws(()=>m.pickMeasurementAnchor(e.data,[{object:moving,point,distance:1},frameHit]),/문틀이나 벽면/);}const anchor=m.pickMeasurementAnchor(e.data,[frameHit]);assert.equal(anchor.kind,'node');assert.equal(anchor.nodeId,'wall');}finally{dispose(g);}});
await test('actual GLB export contains nested door pivot pose and saved opening configuration',async()=>{const o=opening({door:{hinge:'right',side:'negative',angle:67.5}}),n=node({x:500,z:-700,rotation:37,openings:[o]}),{e,g}=engine(n),reader=globalThis.FileReader;globalThis.FileReader=class{readAsArrayBuffer(blob){blob.arrayBuffer().then(data=>{this.result=data;this.onloadend?.();});}};try{let triangles=0;g.traverse(v=>{if(v.geometry)triangles+=(v.geometry.index?.count??v.geometry.getAttribute('position').count)/3;});const bytes=await e.exportGlb(),view=new DataView(bytes),json=JSON.parse(new TextDecoder().decode(new Uint8Array(bytes,20,view.getUint32(12,true))));assert.equal(m.inspectGlb(bytes).triangles,triangles);const parent=json.nodes.find(v=>v.extras?.partitionOpenings?.[0]?.id===o.id),pivot=json.nodes.find(v=>v.extras?.doorOpeningId===o.id);assert.deepEqual(parent.extras.partitionOpenings[0].door,o.door);assert.equal(pivot.extras.doorParentId,'wall');assert.ok(pivot.matrix||pivot.rotation);assert.equal(pivot.children.length,2);}finally{globalThis.FileReader=reader;dispose(g);}});
console.log(`${checks} door-integration checks passed.`);
