import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {build} from 'esbuild';
const sql=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+f,'utf8'));
let user='owner',calls=[],runs=new Map(),lostAck=false,plainAccess=false,badCaps=false,redirect=false;
globalThis.__hermesEnv={
 SPATIAL_CONNECTION_KEY:Buffer.alloc(32,19).toString('base64'),
 DB:{prepare(query){const stmt=sql.prepare(query);return {bind(...args){return {
  async first(){return stmt.get(...args)||null},
  async all(){return {results:stmt.all(...args)}},
  async run(){return {meta:{changes:stmt.run(...args).changes}}}
 };}};}},
 BUCKET:{async get(){return {body:readFileSync('tests/fixtures/material.png')};}}
};
globalThis.__hermesUser=()=>user?{userId:user,email:'fixture@example.test'}:null;
const b=await build({stdin:{contents:"export * from './lib/hermes-server';export {POST as connect,GET as connection,DELETE as disconnect} from './app/api/hermes/route';export {POST as jobAction,GET as jobs} from './app/api/hermes/jobs/route';export {GET as config} from './app/api/config/route';export {POST as edit} from './app/api/ai/route';export {POST as photo} from './app/api/object-photo/route';export {initialScene} from './lib/scene-model';",resolveDir:process.cwd()},bundle:true,format:'esm',platform:'node',write:false,plugins:[{name:'boundaries',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'env',namespace:'stub'}));b.onResolve({filter:/chatgpt-auth$/},()=>({path:'auth',namespace:'stub'}));b.onLoad({filter:/.*/,namespace:'stub'},a=>({contents:a.path==='env'?'export const env=globalThis.__hermesEnv':'export async function getChatGPTUser(){return globalThis.__hermesUser()}'}))}}]});
const m=await import('data:text/javascript;base64,'+Buffer.from(b.outputFiles[0].text).toString('base64'));
const originalFetch=globalThis.fetch,origin='https://spatial.example',endpoint='https://gateway.example/p/design',token='fixture-only-hermes-connection-key';
globalThis.fetch=async(url,init={})=>{calls.push({url,init});assert.ok(url.startsWith(endpoint+'/'));assert.equal(init.redirect,'manual');
 if(redirect)return new Response(null,{status:302,headers:{location:'https://other.example'}});
 const auth=init.headers?.Authorization;
 if(url.endsWith('/capabilities'))return !auth?Response.json({}, {status:plainAccess?200:401}):Response.json({object:'hermes.api_server.capabilities',platform:'hermes-agent',features:{run_submission:true,run_status:true,run_stop:true,runs_idempotency:{durable:!badCaps,retention_seconds:86400}}});
 assert.equal(auth,'Bearer '+token);
 if(url.endsWith('/models'))return Response.json({data:[{id:'existing-hermes-profile'}]});
 if(url.endsWith('/runs')&&init.method==='POST'){const key=init.headers['Idempotency-Key'],body=JSON.parse(init.body);if(!runs.has(key))runs.set(key,{id:'run_'+runs.size,status:'running',body});else assert.deepEqual(runs.get(key).body,body);if(lostAck){lostAck=false;throw new TypeError('connection lost after acceptance');}return Response.json({run_id:runs.get(key).id,status:'started'},{status:202});}
 const id=String(url).split('/runs/')[1]?.split('/')[0],r=[...runs.values()].find(r=>r.id===id);assert.ok(r);
 if(url.endsWith('/stop')){r.status='cancelled';return Response.json({status:'stopping'});}
 return Response.json({object:'hermes.run',run_id:r.id,status:r.status,output:r.output});
};
const req=(path,body,id=crypto.randomUUID(),requestOrigin=origin)=>new Request(origin+path,{method:'POST',headers:{origin:requestOrigin,'Content-Type':'application/json','X-Spatial-Request-Id':id},body:JSON.stringify(body)});
const editBody=()=>({scene:m.initialScene(),prompt:'바닥 소재를 밝은 참나무로 바꾸세요.'});
let checks=0;async function test(name,fn){await fn();checks++;console.log('PASS '+name)}
try{
await test('unsafe endpoints reject and profile base paths normalize',async()=>{for(const url of ['http://gateway.example','https://127.0.0.1','https://[::1]','https://user:pass@gateway.example','https://gateway.example?x=1','https://gateway.internal','https://gateway.example/#x'])assert.throws(()=>m.hermesEndpoint(url));assert.equal(m.hermesEndpoint(endpoint+'/v1/'),endpoint)});
await test('connection and jobs require owner identity and same-origin writes',async()=>{user=null;assert.equal((await m.connect(req('/api/hermes',{endpoint,token}))).status,401);assert.equal((await m.jobs()).status,401);user='owner';assert.equal((await m.connect(req('/api/hermes',{endpoint,token},undefined,'https://foreign.example'))).status,403);assert.equal(calls.length,0)});
await test('credentials save only after authenticated capabilities and unprotected-access check',async()=>{const r=await m.connect(req('/api/hermes',{endpoint:endpoint+'/v1',token}));assert.equal(r.status,200);const text=await r.text();assert.ok(text.includes('existing-hermes-profile'));assert.ok(!text.includes(token));const stored=sql.prepare('SELECT secret FROM hermes_connections WHERE owner=?').get(user).secret;assert.ok(!stored.includes(token));assert.ok(!stored.includes(endpoint));assert.equal((await m.unseal(stored,user)).token,token);await assert.rejects(()=>m.unseal(stored,'other'))});
await test('unprotected, incompatible and redirecting gateways cannot replace working connection',async()=>{const previous=sql.prepare('SELECT secret FROM hermes_connections WHERE owner=?').get(user).secret;plainAccess=true;assert.equal((await m.connect(req('/api/hermes',{endpoint,token}))).status,422);plainAccess=false;badCaps=true;assert.equal((await m.connect(req('/api/hermes',{endpoint,token}))).status,422);badCaps=false;redirect=true;assert.equal((await m.connect(req('/api/hermes',{endpoint,token}))).status,502);redirect=false;assert.equal(sql.prepare('SELECT secret FROM hermes_connections WHERE owner=?').get(user).secret,previous)});
await test('Hermes enables design features while image generation stays separately unavailable',async()=>{const c=await (await m.config()).json();assert.equal(c.ai,true);assert.equal(c.provider,'hermes');assert.equal(c.aiKeyConfigured,false);assert.equal(c.imageReady,false);user='other';assert.equal((await (await m.config()).json()).ai,false);user='owner'});
let editId,body,run;
await test('lost submit acknowledgement retries exactly the same native run and session',async()=>{editId=crypto.randomUUID();body=editBody();lostAck=true;assert.equal((await m.edit(req('/api/ai',body,editId))).status,502);const pending=await m.edit(req('/api/ai',body,editId));assert.equal(pending.status,202);assert.equal((await pending.json()).pending,true);assert.equal(runs.size,1);run=[...runs.values()][0];assert.ok(run.body.session_id.startsWith('spatial-'));assert.deepEqual(run.body.conversation_history,[]);assert.ok(!('model' in run.body));assert.ok(!JSON.stringify(run.body).includes(token));assert.match(run.body.instructions,/Do not use native tools/)});
await test('a changed scene cannot replay an existing request ID',async()=>{const changed=editBody();changed.scene.name='another scene';assert.equal((await m.edit(req('/api/ai',changed,editId))).status,400);assert.equal(runs.size,1)});
await test('another owner cannot read, poll or stop this run',async()=>{user='other';assert.equal((await m.jobAction(req('/api/hermes/jobs',{id:editId,action:'stop'}))).status,404);assert.deepEqual((await (await m.jobs()).json()).jobs,[]);assert.equal((await (await m.connection()).json()).connected,false);user='owner'});
await test('disconnect blocks until in-flight runs are resolved',async()=>{assert.equal((await m.disconnect(new Request(origin+'/api/hermes',{method:'DELETE',headers:{origin}}))).status,409)});
await test('validated completed commands return once without invoking a new model run',async()=>{run.status='completed';run.output='```json\n'+JSON.stringify({summary:'바닥 참나무 제안',commands:[{type:'material',target:'floor',material:'oak'}]})+'\n```';let r=await m.edit(req('/api/ai',body,editId));if(r.status!==200)console.log(await r.clone().text());assert.equal(r.status,200);assert.equal((await r.json()).commands[0].material,'oak');assert.equal((await m.edit(req('/api/ai',body,editId))).status,200);assert.equal(runs.size,1)});
await test('photo bytes use the native multimodal input and preserve strict proxy validation',async()=>{const imageId=crypto.randomUUID(),id=crypto.randomUUID();sql.prepare('INSERT INTO assets VALUES(?,?,?,?,?,?,?,?)').run(imageId,user,'image','photo','image/png','photo','{}',new Date().toISOString());assert.equal((await m.photo(req('/api/object-photo',{imageId},id))).status,202);const r=[...runs.values()].at(-1);assert.equal(r.body.input[0].content[1].type,'image_url');assert.match(r.body.input[0].content[1].image_url.url,/^data:image\/png;base64,/);assert.match(r.body.instructions,/photo_object_proxy/);r.status='completed';r.output=JSON.stringify({kind:'table',name:'사진 책상',material:'oak',color:'#a08060',notes:['형태 추정'],parts:[]});const response=await m.photo(req('/api/object-photo',{imageId},id));assert.equal(response.status,200);assert.equal((await response.json()).analysis.kind,'table')});
await test('foreign photos never reach Hermes',async()=>{const before=calls.length;assert.equal((await m.photo(req('/api/object-photo',{imageId:crypto.randomUUID()}))).status,404);assert.equal(calls.length,before)});
await test('invalid commands are never applied',async()=>{const id=crypto.randomUUID();assert.equal((await m.edit(req('/api/ai',editBody(),id))).status,202);const r=[...runs.values()].at(-1);r.status='completed';r.output='{"commands":[{"type":"execute","shell":"bad"}]}';assert.equal((await m.edit(req('/api/ai',editBody(),id))).status,502)});
await test('stop confirms native cancellation and discards eventual output',async()=>{const id=crypto.randomUUID();assert.equal((await m.edit(req('/api/ai',editBody(),id))).status,202);const r=await m.jobAction(req('/api/hermes/jobs',{id,action:'stop'}));assert.equal(r.status,200);assert.equal((await r.json()).status,'cancelled');assert.equal((await m.edit(req('/api/ai',editBody(),id))).status,422)});
await test('expired ambiguous submissions are not resubmitted outside retention',async()=>{const id=crypto.randomUUID();lostAck=true;assert.equal((await m.edit(req('/api/ai',editBody(),id))).status,502);sql.prepare('UPDATE hermes_jobs SET deadline=0 WHERE id=?').run(id);const count=runs.size;assert.equal((await m.edit(req('/api/ai',editBody(),id))).status,409);assert.equal(runs.size,count)});
await test('same endpoint reconnection preserves execution identity without returning its token',async()=>{const old=await m.readHermes(user);assert.equal((await m.connect(req('/api/hermes',{endpoint,token}))).status,200);assert.equal((await m.readHermes(user)).id,old.id);assert.ok(!(await (await m.connection()).text()).includes(token))});
console.log(`${checks} Hermes integration checks passed with actual routes, AES-GCM and SQLite; mocked external gateway and identity.`);
}finally{globalThis.fetch=originalFetch;delete globalThis.__hermesEnv;delete globalThis.__hermesUser;sql.close()}
