import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {mkdtemp,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
const dir=await mkdtemp(join(tmpdir(),'spatial-transfer-')),file=join(dir,'bundle.mjs');
const bundle=await build({stdin:{contents:"export * as T from 'three';export * from './lib/scene-model';export * from './lib/material-transfer';export * from './lib/material-board';export * from './lib/scene-engine';export * from './lib/selection';export * from './lib/budget';export * from './lib/design-variants';",resolveDir:process.cwd()},bundle:true,platform:'node',format:'esm',write:false});
await writeFile(file,bundle.outputFiles[0].text);const m=await import(pathToFileURL(file));await rm(dir,{recursive:true,force:true});
let checks=0;function test(name,fn){fn();checks++;console.log('PASS '+name);}
const empty=()=>({...m.initialScene(),nodes:[]}),pair=()=>({...empty(),nodes:[m.createNode('chair','source',-700),m.createNode('box','target',700)]});
const sample=(material='steel',finish={})=>({material,finish,sourceName:'복사한 소재',sourceId:'former-source'});
function catalog(s){const e=Object.create(m.SceneEngine.prototype);Object.assign(e,{root:new m.T.Group(),data:s,material(){return new m.T.MeshStandardMaterial();}});for(const n of s.nodes)e.buildNode(n);const c=e.materialCatalog();e.root.traverse(o=>{o.geometry?.dispose();if(o.material)for(const a of Array.isArray(o.material)?o.material:[o.material])a.dispose();});return c;}
const paste=(s,selection,choice=sample(),scope='face',c=catalog(s))=>m.pasteMaterial(s,selection,choice,scope,c);
function modelScene(){const s=empty(),n={...m.createNode('box','model'),kind:'model',assetId:crypto.randomUUID()};s.nodes=[n];const c=[0,1].map(i=>({nodeId:n.id,face:`mesh${i}:0`,hasUv:true,nativeName:`원본 ${i}`,nativeColor:'#abcdef'}));return {s,n,c};}

test('real procedural part defaults sample the clicked region rather than the base material',()=>{const s=pair(),c=catalog(s),seat=m.sampleMaterial(s,{id:'source',face:'seat:0'},c),leg=m.sampleMaterial(s,{id:'source',face:'leg-1-1:0'},c);assert.equal(seat.material,'oak');assert.equal(leg.material,'charcoal');assert.equal(leg.sourceFace,'leg-1-1:0');assert.equal(leg.sourceId,'source');assert.equal(leg.sourceName,s.nodes[0].name);});
test('mixed objects require a face while truly uniform actual regions support object sampling',()=>{const s=pair(),c=catalog(s);assert.throws(()=>m.sampleMaterial(s,{id:'source'},c),/여러 소재/);assert.equal(m.sampleMaterial(s,{id:'target'},c).material,'oak');const painted=m.editAppearance(s,{id:'source'},{material:'linen',finish:{scale:475,rotation:35}},'object'),choice=m.sampleMaterial(painted,{id:'source'},c);assert.deepEqual(choice.finish,{scale:475,rotation:35});assert.equal(choice.material,'linen');assert.equal(choice.sourceFace,undefined);});
test('sampling resolves inherited color finish and explicit face boundaries into detached snapshots',()=>{const s=pair(),id=crypto.randomUUID();s.nodes[0].color='#123456';s.nodes[0].finish={textureId:id,scale:1175,rotation:30};s.nodes[0].faces['seat:0']='walnut';s.nodes[0].faceFinishes={'seat:0':{roughness:.2}};const c=catalog(s),a=m.sampleMaterial(s,{id:'source',face:'seat:1'},c),b=m.sampleMaterial(s,{id:'source',face:'seat:0'},c);assert.deepEqual(a.finish,{color:'#123456',textureId:id,scale:1175,rotation:30});assert.deepEqual(b.finish,{roughness:.2});a.finish.scale=500;b.finish.roughness=.8;assert.equal(s.nodes[0].finish.scale,1175);assert.equal(s.nodes[0].faceFinishes['seat:0'].roughness,.2);});
test('face paste exactly replaces tint image and overrides without leaking or repainting adjacent faces',()=>{const s=pair(),old=crypto.randomUUID(),next=crypto.randomUUID();s.nodes[1].color='#123456';s.nodes[1].finish={textureId:old,roughness:.1};s.nodes[1].faces['body:0']='clay';s.nodes[1].faceFinishes={'body:0':{color:'#ff0000',scale:999}};const before=JSON.stringify(s),choice=sample('linen',{textureId:next,scale:650,rotation:-45}),result=paste(s,{id:'target',face:'body:0'},choice),n=result.nodes[1];assert.deepEqual(m.nodeAppearance(n,'body:0'),{material:'linen',finish:choice.finish,original:false});assert.equal(m.nodeAppearance(n,'body:1').finish.textureId,old);assert.equal(JSON.stringify(s),before);choice.finish.scale=1000;assert.equal(n.faceFinishes['body:0'].scale,650);});
test('empty copied finish clears inherited image on one face through an explicit material boundary',()=>{const s=pair(),old=crypto.randomUUID();s.nodes[1].finish={textureId:old,color:'#aabbcc',roughness:.1};const r=paste(s,{id:'target',face:'body:0'},sample('oak'));assert.deepEqual(m.nodeAppearance(r.nodes[1],'body:0').finish,{});assert.equal(m.nodeAppearance(r.nodes[1],'body:1').finish.textureId,old);});
test('whole object paste replaces all parts and removes stale tint images and face overrides',()=>{const s=pair();s.nodes[0].color='#123456';s.nodes[0].finish={textureId:crypto.randomUUID()};s.nodes[0].faces={'seat:0':'clay'};s.nodes[0].faceFinishes={'seat:0':{textureId:crypto.randomUUID()},'unused:0':{textureId:crypto.randomUUID()}};const c=catalog(s),r=paste(s,{id:'source'},sample('steel',{roughness:.42}),'object',c),n=r.nodes[0];assert.equal(n.uniformMaterial,true);assert.equal(n.color,undefined);assert.deepEqual(n.faces,{});assert.deepEqual(n.faceFinishes,{});assert.deepEqual(n.finish,{roughness:.42});assert.deepEqual(m.imageReferences(r),[]);for(const slot of c.filter(x=>x.nodeId==='source'))assert.equal(m.nodeAppearance(n,slot.face).material,'steel');});
test('room surfaces copy and replace as one surface with no furniture catalog requirement',()=>{const s=empty();s.room.surfaces.floor={material:'oak',color:'#123456',finish:{textureId:crypto.randomUUID(),scale:425}};const choice=m.sampleMaterial(s,{id:'floor',face:'surface:2'},[]);assert.equal(choice.sourceName,'바닥');assert.equal(choice.sourceFace,undefined);const r=paste(s,{id:'back'},choice,'face',[]);assert.deepEqual(r.room.surfaces.back,{material:choice.material,finish:choice.finish});assert.deepEqual(r.room.surfaces.floor,s.room.surfaces.floor);const cleared=paste(r,{id:'floor'},sample('steel'),'object',[]);assert.deepEqual(cleared.room.surfaces.floor,{material:'steel',finish:{}});assert.throws(()=>paste(s,{id:'floor',face:'fake:1'},choice,'face',[]),/다시 선택/);});
test('locked source remains readable but hidden sources and missing selections reject',()=>{const s=pair(),c=catalog(s);s.nodes[0].locked=true;assert.equal(m.sampleMaterial(s,{id:'source',face:'seat:0'},c).material,'oak');s.nodes[0].hidden=true;assert.throws(()=>m.sampleMaterial(s,{id:'source',face:'seat:0'},c),/숨김/);for(const selection of [null,{id:'missing'},{id:'source',ids:['target']},{id:'source',ids:['source','target']}])assert.throws(()=>m.sampleMaterial(s,selection,c));});
test('all target locks hidden states and missing nodes are checked before atomic multi-apply',()=>{for(const patch of [{locked:true},{hidden:true}]){const s=pair();Object.assign(s.nodes[1],patch);const before=JSON.stringify(s);assert.throws(()=>paste(s,{id:'source',ids:['source','target']},sample(),'object'));assert.equal(JSON.stringify(s),before);}const s=pair(),before=JSON.stringify(s);assert.throws(()=>paste(s,{id:'source',ids:['source','missing']},sample(),'object'),/찾을 수/);assert.equal(JSON.stringify(s),before);});
test('normalized whole group selection applies atomically and member edit retains other members',()=>{const s=m.createGroup(pair(),['source','target'],'좌석'),selection=m.normalizeSelection(s,{id:'source'}),r=paste(s,selection,sample('sage'),'object');assert.ok(r.nodes.every(n=>n.material==='sage'));for(let i=0;i<s.nodes.length;i++)assert.deepEqual(r.nodes[i].group,s.nodes[i].group);assert.throws(()=>m.sampleMaterial(s,selection,catalog(s)),/하나/);const member=paste(s,{id:'source',face:'seat:0'},sample('walnut'));assert.deepEqual(member.nodes[1],s.nodes[1]);assert.deepEqual(member.nodes[0].group,s.nodes[0].group);});
test('wall-mounted doors and windows allow material operations while room mixing and multi-face edits reject',()=>{const s=empty();s.nodes=[m.createNode('door','door')];const c=catalog(s),choice=m.sampleMaterial(s,{id:'door',face:'handle:0'},c);assert.equal(choice.material,'steel');const r=paste(s,{id:'door'},sample('walnut'),'object',c);assert.equal(r.nodes[0].host,'back');assert.equal(r.nodes[0].material,'walnut');assert.throws(()=>paste(s,{id:'floor',ids:['floor','door']},sample(),'object',c),/하나씩/);assert.throws(()=>paste(pair(),{id:'source',ids:['source','target'],face:'seat:0'}),/면 하나/);});
test('native GLB material is never misrepresented as its fallback built-in ID',()=>{const {s,n,c}=modelScene();assert.throws(()=>m.sampleMaterial(s,{id:'model',face:'mesh0:0'},c),/원본 소재/);assert.throws(()=>m.sampleMaterial(s,{id:'model'},c),/원본 소재/);n.faceFinishes={'mesh0:0':{color:'#123456'}};assert.throws(()=>m.sampleMaterial(s,{id:'model',face:'mesh0:0'},c),/원본 소재/);const r=paste(s,{id:'model',face:'mesh0:0'},sample('oak'),'face',c);assert.equal(m.nodeAppearance(r.nodes[0],'mesh0:0').original,false);assert.equal(m.nodeAppearance(r.nodes[0],'mesh1:0').original,true);assert.equal(m.sampleMaterial(r,{id:'model',face:'mesh0:0'},c).material,'oak');});
test('GLB image overrides and explicit uniform materials can be copied with exact physical settings',()=>{const {s,n,c}=modelScene(),id=crypto.randomUUID();n.faceFinishes={'mesh0:0':{textureId:id,scale:833,rotation:67}};assert.deepEqual(m.sampleMaterial(s,{id:'model',face:'mesh0:0'},c).finish,n.faceFinishes['mesh0:0']);const r=paste(s,{id:'model'},sample('steel',{metalness:.4}),'object',c);assert.equal(m.sampleMaterial(r,{id:'model'},c).material,'steel');assert.ok(c.every(slot=>!m.nodeAppearance(r.nodes[0],slot.face).original));});
test('missing UV blocks the entire image batch but still allows selected UV face and plain material',()=>{const {s,c}=modelScene(),choice=sample('oak',{textureId:crypto.randomUUID()}),before=JSON.stringify(s);c[1].hasUv=false;assert.throws(()=>paste(s,{id:'model'},choice,'object',c),/UV/);assert.equal(JSON.stringify(s),before);assert.equal(paste(s,{id:'model',face:'mesh0:0'},choice,'face',c).nodes[0].faceFinishes['mesh0:0'].textureId,choice.finish.textureId);assert.equal(paste(s,{id:'model'},sample(),'object',c).nodes[0].material,'steel');assert.throws(()=>paste(s,{id:'model',face:'mesh0:0'},choice,'face',[...c,{...c[0],hasUv:false}]),/UV/);});
test('absent catalogs and stale fabricated region IDs never fall back to whole-object paint',()=>{const s=pair(),c=catalog(s),before=JSON.stringify(s);for(const selection of [{id:'target',face:'fake:0'},{id:'target'}])assert.throws(()=>paste(s,selection,sample(),'face',c));assert.throws(()=>paste(s,{id:'target'},sample(),'object',[]),/표시/);assert.throws(()=>m.sampleMaterial(s,{id:'source',face:'fake:0'},c),/존재/);assert.equal(JSON.stringify(s),before);});
test('effective default equality and image tint equality return the exact original scene',()=>{let s=m.editEstimates(pair(),['target'],{unitPrice:25000}),c=catalog(s);const defaults=sample('oak',{color:'#C7A477',roughness:.65,metalness:0,scale:900,rotation:0});assert.equal(paste(s,{id:'target'},defaults,'object',c),s);assert.equal(paste(s,{id:'target',face:'body:0'},defaults,'face',c),s);assert.equal(m.priceNeedsReview(s.nodes[1]),false);const id=crypto.randomUUID();s.nodes[1].finish={textureId:id,color:'#111111',scale:400};assert.equal(paste(s,{id:'target'},sample('oak',{textureId:id,color:'#FFFFFF',scale:400}),'object',c),s);});
test('mixed batches preserve rendering-equivalent target metadata and change only differing objects',()=>{const s=pair(),c=catalog(s),r=paste(s,{id:'source',ids:['source','target']},sample('oak'),'object',c);assert.equal(r.nodes[0].uniformMaterial,true);assert.deepEqual(r.nodes[1],s.nodes[1]);});
test('geometry groups layers measurements variants and verified estimate snapshots remain intact',()=>{let s=m.createGroup(pair(),['source','target'],'구성');const layer=crypto.randomUUID();s.layers=[{id:layer,name:'좌석',color:'#123456'}];for(const n of s.nodes)n.layerId=layer;s=m.editEstimates(s,['source','target'],{unitPrice:150000});s=m.saveVariant(s,'원안');s.measurements=[{id:crypto.randomUUID(),name:'테스트 치수',hidden:false,start:{kind:'room',surface:'floor',u:.2,v:.2,offset:0},end:{kind:'room',surface:'floor',u:.5,v:.2,offset:0}}];const before=JSON.stringify(s),r=paste(s,{id:'source',face:'seat:0'},sample());for(const key of ['x','y','z','width','height','depth','rotation','group','layerId','estimate'])assert.deepEqual(r.nodes[0][key],s.nodes[0][key]);for(const key of ['layers','measurements','variants','name','cameras'])assert.deepEqual(r[key],s[key]);assert.equal(m.priceNeedsReview(r.nodes[0]),true);assert.equal(m.priceNeedsReview(r.nodes[1]),false);assert.equal(JSON.stringify(s),before);assert.deepEqual(m.validateScene(JSON.parse(JSON.stringify(r))),r);});
test('snapshot paste still works after the source was removed and does not depend on its ID',()=>{const s=pair(),c=catalog(s),choice=m.sampleMaterial(s,{id:'source',face:'leg-1-1:0'},c);s.nodes.shift();const r=paste(s,{id:'target'},choice,'object',c);assert.equal(r.nodes[0].material,'charcoal');});
test('image cap validation rejects atomically and whole replacement releases old image references',()=>{const s=pair();s.nodes[0].faceFinishes=Object.fromEntries(Array.from({length:8},(_,i)=>[`unused:${i}`,{textureId:crypto.randomUUID()}]));const choice=sample('oak',{textureId:crypto.randomUUID()}),before=JSON.stringify(s),c=catalog(s);assert.throws(()=>paste(s,{id:'target',face:'body:0'},choice,'face',c),/이미지 8개/);assert.equal(JSON.stringify(s),before);const r=paste(s,{id:'source'},choice,'object',c);assert.deepEqual(m.imageReferences(r),[choice.finish.textureId]);});
test('runtime malformed samples and scope values cannot partially change a scene',()=>{const s=pair(),c=catalog(s),before=JSON.stringify(s);for(const choice of [null,{...sample(),material:'invented'},sample('oak',{scale:0}),sample('oak',{roughness:Infinity}),sample('oak',{textureId:'not-an-id'}),{...sample(),sourceId:''},{...sample(),sourceFace:'x'.repeat(61)}])assert.throws(()=>paste(s,{id:'target'},choice,'object',c));assert.throws(()=>paste(s,{id:'target'},sample(),'invalid',c),/범위/);assert.equal(JSON.stringify(s),before);});
console.log(`${checks} material-transfer checks passed.`);
