import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {mkdtemp,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';import {join} from 'node:path';import {pathToFileURL} from 'node:url';
const dir=await mkdtemp(join(tmpdir(),'spatial-material-tests-')),file=join(dir,'bundle.mjs');
const bundle=await build({stdin:{contents:"export * as T from 'three';export * from './lib/scene-model';export * from './lib/material-board';export * from './lib/material-catalog';export * from './lib/scene-engine';export * from './lib/selection';export * from './lib/budget';export * from './lib/design-variants';",resolveDir:process.cwd()},bundle:true,platform:'node',format:'esm',write:false});await writeFile(file,bundle.outputFiles[0].text);const m=await import(pathToFileURL(file));await rm(dir,{recursive:true,force:true});
let checks=0;function test(name,fn){fn();checks++;console.log('PASS '+name)}
const empty=()=>({...m.initialScene(),nodes:[]}),pair=()=>({...empty(),nodes:[m.createNode('chair','a',-600),m.createNode('chair','b',600)]}),choice=(material='walnut',finish={})=>({material,finish});
function catalog(s){const e=Object.create(m.SceneEngine.prototype);Object.assign(e,{root:new m.T.Group(),data:s,material(){return new m.T.MeshStandardMaterial();}});for(const n of s.nodes)e.buildNode(n);const c=e.materialCatalog();e.root.traverse(o=>{o.geometry?.dispose();if(o.material)for(const a of Array.isArray(o.material)?o.material:[o.material])a.dispose();});return c;}
const row=(s,c,id)=>m.materialRows(s,c).find(r=>r.material===id&&!r.original),plan=(s,c,r,replace=choice(),keys=r.uses.map(u=>u.key))=>m.planMaterialReplacement(s,c,r.key,keys,replace);
function modelScene(){const s=empty(),n={...m.createNode('box','model'),kind:'model',assetId:crypto.randomUUID()};s.nodes=[n];const c=[0,1].map(i=>({nodeId:n.id,face:`mesh${i}:0`,hasUv:true,nativeName:`원본 ${i}`,nativeColor:'#abcdef'}));return {s,c,n};}
test('catalog follows real built-in geometry for every kind and excludes fixed bulbs',()=>{for(const kind of m.kinds){const s=empty();s.nodes=[m.createNode(kind,'a')];const c=catalog(s);const counts={table:12,'round-table':9,chair:36,bench:18,counter:36,shelf:42,plant:16,pendant:6,box:6,cylinder:3,partition:6,door:30,window:36};assert.equal(c.length,counts[kind],kind);assert.ok(c.every(x=>x.nodeId==='a'&&x.hasUv));}});
test('catalog ignores unused material slots, unknown nodes, fixed meshes and placeholders',()=>{const root=new m.T.Group(),mesh=new m.T.Mesh(new m.T.BoxGeometry(),[new m.T.MeshStandardMaterial(),new m.T.MeshStandardMaterial()]);mesh.geometry.clearGroups();mesh.geometry.addGroup(0,3,1);mesh.userData={nodeId:'a',part:'body'};root.add(mesh);const fixed=mesh.clone();fixed.userData={nodeId:'a'};root.add(fixed);const placeholder=mesh.clone();placeholder.userData={nodeId:'a',part:'loading',unmeasurable:true};root.add(placeholder);const unknown=mesh.clone();unknown.userData={nodeId:'missing',part:'body'};root.add(unknown);assert.deepEqual(m.renderedMaterialSlots(root,[m.createNode('box','a')]).map(s=>s.face),['body:1']);});
test('hidden catalog regions remain available and UV absence is conservative for duplicate slots',()=>{const root=new m.T.Group(),mesh=new m.T.Mesh(new m.T.BoxGeometry(),new m.T.MeshStandardMaterial());mesh.userData={nodeId:'a',part:'body'};mesh.visible=false;root.add(mesh);const second=mesh.clone();second.geometry=mesh.geometry.clone();second.geometry.deleteAttribute('uv');root.add(second);const c=m.renderedMaterialSlots(root,[m.createNode('box','a')]);assert.equal(c.length,1);assert.equal(c[0].hasUv,false);});
test('usage finds actual chair legs and never invents stale face overrides',()=>{const s=pair();s.nodes[0].faces['unused:0']='glass';const c=catalog(s),rows=m.materialRows(s,c);assert.equal(rows.find(r=>r.material==='charcoal').uses.length,48);assert.equal(rows.find(r=>r.material==='oak').uses.length,24);assert.ok(!rows.some(r=>r.material==='glass'));});
test('room surfaces aggregate into the same finish rows as furniture',()=>{const s=pair();s.room.surfaces.floor={material:'oak'};const c=catalog(s),r=row(s,c,'oak');assert.equal(r.uses.filter(u=>!u.face).length,1);assert.equal(r.uses.length,25);assert.equal(m.materialRows(s,c).find(r=>r.material==='plaster').uses.length,4);});
test('base finishes inherit only until an explicit face material boundary',()=>{const s=pair();s.nodes[0].finish={color:'#123456',roughness:.2};s.nodes[0].faces['seat:0']='oak';const c=catalog(s),rows=m.materialRows(s,c),inherited=rows.find(r=>r.uses.some(u=>u.id==='a'&&u.face==='seat:1')),explicit=rows.find(r=>r.uses.some(u=>u.id==='a'&&u.face==='seat:0'));assert.equal(inherited.finish.color,'#123456');assert.equal(explicit.finish.color,undefined);assert.notEqual(inherited.key,explicit.key);});
test('face image removal masks inherited texture and resolved defaults aggregate',()=>{const s=pair(),id=crypto.randomUUID();s.nodes[0].finish={textureId:id};s.nodes[0].faceFinishes={'seat:0':{textureId:null}};s.nodes[1].finish={color:'#C7A477',roughness:.65,metalness:0,scale:900,rotation:0};const c=catalog(s),rows=m.materialRows(s,c),a=rows.find(r=>r.uses.some(u=>u.id==='a'&&u.face==='seat:0')),b=rows.find(r=>r.uses.some(u=>u.id==='b'&&u.face==='seat:0'));assert.equal(a.key,b.key);assert.notEqual(a.key,rows.find(r=>r.uses.some(u=>u.id==='a'&&u.face==='seat:1')).key);});
test('finish signatures separate physical settings while ignoring color behind an image',()=>{const base=m.finishKey(choice('oak'));for(const f of [{color:'#123456'},{roughness:.2},{metalness:.7},{scale:450},{rotation:30},{textureId:crypto.randomUUID()}])assert.notEqual(m.finishKey(choice('oak',f)),base);const id=crypto.randomUUID();assert.equal(m.finishKey(choice('oak',{textureId:id,color:'#123456'})),m.finishKey(choice('oak',{textureId:id,color:'#abcdef'})));});
test('original imported materials remain distinct by asset and actual region',()=>{const {s,c,n}=modelScene();s.nodes.push({...structuredClone(n),id:'b',assetId:crypto.randomUUID()});c.push({...c[0],nodeId:'b'});const rows=m.materialRows(s,c).filter(r=>r.original);assert.equal(rows.length,3);assert.ok(rows.every(r=>r.name.startsWith('원본')));assert.equal(m.materialRows(s,c).filter(r=>r.material==='oak'&&!r.original).length,0);});
test('imported explicit faces and texture overrides become ordinary replacement materials',()=>{const {s,c,n}=modelScene();n.faces['mesh0:0']='steel';n.faceFinishes={'mesh1:0':{textureId:crypto.randomUUID()}};const rows=m.materialRows(s,c);assert.ok(!rows.some(r=>r.original));assert.equal(rows.find(r=>r.material==='steel').uses[0].face,'mesh0:0');});
test('replacing one material preserves every unrelated appearance, geometry and group',()=>{let s=m.createGroup(pair(),['a','b'],'좌석');s=m.editEstimates(s,['a','b'],{unitPrice:50000});const before=JSON.stringify(s),c=catalog(s),r=row(s,c,'oak'),p=plan(s,c,r,choice(),r.uses.filter(u=>u.id==='a').map(u=>u.key));assert.equal(p.changedRegions,12);assert.equal(p.changedElements,1);assert.equal(p.reviewPrices,1);assert.equal(JSON.stringify(s),before);assert.deepEqual(p.scene.nodes[1],s.nodes[1]);assert.deepEqual(p.scene.nodes[0].group,s.nodes[0].group);for(const slot of c.filter(x=>x.nodeId==='a'))assert.equal(m.nodeAppearance(p.scene.nodes[0],slot.face).material,slot.face.startsWith('leg')?'charcoal':'walnut');assert.equal(p.scene.nodes[0].x,s.nodes[0].x);assert.equal(m.priceNeedsReview(p.scene.nodes[0]),true);assert.equal(m.priceNeedsReview(p.scene.nodes[1]),false);});
test('one exact face replacement freezes its own finish without tint or texture leaking in',()=>{const s=pair();s.nodes[0].finish={color:'#123456',textureId:crypto.randomUUID(),roughness:.1};const c=catalog(s),r=m.materialRows(s,c).find(r=>r.uses.some(u=>u.id==='a'&&u.face==='seat:0')),key=r.uses.find(u=>u.id==='a'&&u.face==='seat:0').key,p=plan(s,c,r,choice('steel'),[key]),n=p.scene.nodes[0];assert.deepEqual(m.nodeAppearance(n,'seat:0').finish,{});assert.equal(m.nodeAppearance(n,'seat:1').finish.textureId,s.nodes[0].finish.textureId);assert.equal(p.changedRegions,1);});
test('room replacement clears its old tint and finish and leaves other walls intact',()=>{const s=empty();s.room.surfaces.floor={material:'oak',color:'#123456',finish:{roughness:.2}};const r=row(s,[],'oak'),p=plan(s,[],r,choice('steel',{scale:500}));assert.deepEqual(p.scene.room.surfaces.floor,{material:'steel',finish:{scale:500}});assert.deepEqual(p.scene.room.surfaces.back,s.room.surfaces.back);});
test('hidden, selection, node, room and layer scopes keep exact matching regions',()=>{const s=pair(),layer=crypto.randomUUID();s.layers=[{id:layer,name:'좌석',color:'#123456'}];s.nodes[0].layerId=layer;s.nodes[1].hidden=true;s.room.surfaces.floor={material:'oak'};const c=catalog(s),r=row(s,c,'oak'),scope=(kind,extra={})=>m.scopedMaterialUses(r,{kind,includeHidden:false,...extra});assert.equal(scope('all').length,13);assert.equal(scope('all',{includeHidden:true}).length,25);assert.equal(scope('room').length,1);assert.equal(scope('nodes').length,12);assert.equal(scope('selection',{ids:['floor','a']}).length,13);assert.equal(scope('layer',{layerId:layer}).length,12);assert.equal(scope('layer',{layerId:null,includeHidden:true}).length,12);});
test('locked target batches fail atomically and a filtered batch succeeds',()=>{const s=pair();s.nodes[1].locked=true;const before=JSON.stringify(s),c=catalog(s),r=row(s,c,'oak');assert.throws(()=>plan(s,c,r),/잠긴/);assert.equal(JSON.stringify(s),before);assert.equal(plan(s,c,r,choice(),r.uses.filter(u=>!u.locked).map(u=>u.key)).changedElements,1);});
test('unknown region, empty selection and invalid finish values reject',()=>{const s=pair(),c=catalog(s),r=row(s,c,'oak');assert.throws(()=>plan(s,c,r,choice(),[]),/선택/);assert.throws(()=>plan(s,c,r,choice(),['missing']),/변경/);assert.throws(()=>plan(s,c,r,choice('walnut',{scale:0})));assert.throws(()=>m.planMaterialReplacement(s,c,'missing',[],choice()),/소재/);});
test('missing UV blocks image replacement before mutation but accepts a standard material',()=>{const {s,c}=modelScene();c[0].hasUv=false;const r=m.materialRows(s,c).find(r=>r.original),before=JSON.stringify(s);assert.throws(()=>plan(s,c,r,choice('oak',{textureId:crypto.randomUUID()})),/UV/);assert.equal(JSON.stringify(s),before);assert.equal(plan(s,c,r).changedRegions,1);});
test('only selected native model regions convert and unselected original slots remain native',()=>{const {s,c}=modelScene(),r=m.materialRows(s,c).find(r=>r.original),p=plan(s,c,r,choice('steel'));assert.equal(m.nodeAppearance(p.scene.nodes[0],'mesh0:0').original,false);assert.equal(m.nodeAppearance(p.scene.nodes[0],'mesh1:0').original,true);assert.equal(p.scene.nodes[0].uniformMaterial,undefined);});
test('equal effective settings produce a real no-op and keep verified unit prices',()=>{const s=m.editEstimates(pair(),['a'],{unitPrice:100}),c=catalog(s),r=row(s,c,'oak'),p=plan(s,c,r,choice('oak',{color:'#C7A477',roughness:.65,metalness:0,scale:900,rotation:0}));assert.equal(p.scene,s);assert.equal(p.changedElements,0);assert.equal(p.reviewPrices,0);assert.equal(m.priceNeedsReview(p.scene.nodes[0]),false);});
test('preview does not change variants, measurements, prices or project metadata',()=>{let s=pair();s=m.saveVariant(s,'기존');s.budget={target:100000,extras:[]};const c=catalog(s),p=plan(s,c,row(s,c,'oak'));assert.deepEqual(p.scene.variants,s.variants);assert.deepEqual(p.scene.budget,s.budget);assert.equal(p.scene.name,s.name);assert.deepEqual(m.validateScene(JSON.parse(JSON.stringify(p.scene))),p.scene);});
test('image reference limit is validated across the resulting scene before returning a plan',()=>{const s=pair();s.nodes[0].faceFinishes=Object.fromEntries(Array.from({length:8},(_,i)=>[`unused:${i}`,{textureId:crypto.randomUUID()}]));const c=catalog(s),r=row(s,c,'oak');assert.throws(()=>plan(s,c,r,choice('oak',{textureId:crypto.randomUUID()})),/이미지 8개/);});
test('preview application rejects changed scene and another project with identical content',()=>{const s=pair(),c=catalog(s),p=plan(s,c,row(s,c,'oak'));assert.deepEqual(m.acceptMaterialPlan(s,p,4,4),p.scene);assert.throws(()=>m.acceptMaterialPlan(s,p,5,4),/변경/);assert.throws(()=>m.acceptMaterialPlan({...s,name:'다른 이름'},p,4,4),/변경/);});
test('engine refuses a material catalog from a scene that has not yet reached the viewer',()=>{const s=empty(),e=Object.create(m.SceneEngine.prototype);Object.assign(e,{root:new m.T.Group(),data:s});assert.deepEqual(e.materialCatalog(s),[]);assert.throws(()=>e.materialCatalog({...s,name:'갱신 중'}),/갱신/);});
test('duplicate catalog entries do not inflate inventory or replacement quantities',()=>{const s=pair(),c=catalog(s),r=row(s,c,'oak'),duplicates=[...c,...c,...c];assert.equal(row(s,duplicates,'oak').uses.length,r.uses.length);assert.equal(plan(s,duplicates,r).changedRegions,r.uses.length);});
console.log(`${checks} material board checks passed.`);
