import assert from 'node:assert/strict';
import {build} from 'esbuild';
const bundle=await build({stdin:{contents:"export * as T from 'three';export * from './lib/scene-model';export * from './lib/measurements';export * from './lib/measurement-picking';export * from './lib/measurement-overlay';export * from './lib/selection';export * from './lib/design-variants';export * from './lib/scene-engine';",resolveDir:process.cwd()},bundle:true,platform:'node',format:'esm',write:false});
const m=await import('data:text/javascript;base64,'+Buffer.from(bundle.outputFiles[0].text).toString('base64')),{T}=m;
let checks=0;async function test(name,fn){await fn();checks++;console.log('PASS '+name)}
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-7,`${a} != ${b}`),pointNear=(a,b)=>{near(a.x,b.x);near(a.y,b.y);near(a.z,b.z)},uuid=()=>crypto.randomUUID();
const empty=()=>({...m.initialScene(),nodes:[]}),floor=(s,x,z)=>m.measurementAnchor(s,'floor',{x,y:0,z});
const measured=()=>{const s=empty();s.nodes=[{...m.createNode('box','box',-400,250),width:800,height:600,depth:400,rotation:37}];return m.addMeasurement(s,m.measurementAnchor(s,'box',{x:-400,y:600,z:250}),floor(s,900,250),'카운터 높이');};
const fakeLabel=()=>new T.Sprite(new T.SpriteMaterial({map:new T.Texture()}));
await test('rotated non-square node anchors match actual Three transforms with exact round-trip',()=>{const s=empty(),n={...m.createNode('box','n',311.57,-102.93),y:123.71,width:1250.5,height:732.3,depth:619.7,rotation:-137.4};s.nodes=[n];const parent=new T.Group();parent.position.set(n.x,n.y,n.z);parent.rotation.y=n.rotation*Math.PI/180;parent.updateMatrixWorld(true);for(const local of [new T.Vector3(-450,230,121),new T.Vector3(610,700,-299)]){const world=parent.localToWorld(local.clone()),a=m.measurementAnchor(s,'n',world);pointNear(m.resolveMeasurementAnchor(s,a),world);near(a.point[0]*n.width,local.x);near(a.point[1]*n.height,local.y);near(a.point[2]*n.depth,local.z)}});
await test('all hosted wall anchors use actual origins and both side walls positive 90-degree yaw',()=>{for(const host of ['back','front','left','right']){const s=empty(),n={...m.createNode('window','w'),host,x:['back','front'].includes(host)?217:0,z:['left','right'].includes(host)?317:0};s.nodes=[n];const parent=new T.Group();parent.position.set(host==='left'?-s.room.width/2:host==='right'?s.room.width/2:n.x,n.y,host==='back'?-s.room.depth/2:host==='front'?s.room.depth/2:n.z);parent.rotation.y=['left','right'].includes(host)?Math.PI/2:0;parent.updateMatrixWorld(true);const world=parent.localToWorld(new T.Vector3(370,430,31)),a=m.measurementAnchor(s,'w',world);pointNear(m.resolveMeasurementAnchor(s,a),world);const changed=structuredClone(s);changed.room.width+=1000;changed.room.depth+=1200;const p=m.resolveMeasurementAnchor(changed,a);near(p.x-world.x,host==='left'?-500:host==='right'?500:0);near(p.z-world.z,host==='back'?-600:host==='front'?600:0)}});
await test('wall inside-face measurements retain 120 mm wall thickness on room resize',()=>{let s=empty();const a=m.measurementAnchor(s,'left',{x:-s.room.width/2+60,y:1100,z:0}),b=m.measurementAnchor(s,'right',{x:s.room.width/2-60,y:1100,z:0});s=m.addMeasurement(s,a,b,'실내 폭');near(m.readMeasurement(s,s.measurements[0]).length,s.room.width-120);s.room.width=10000;near(m.readMeasurement(s,s.measurements[0]).length,9880);assert.equal(a.offset,60);assert.equal(b.offset,-60)});
await test('room face, floor underside and reveal offsets round-trip without projection error',()=>{const s=empty();for(const [id,p]of [['floor',{x:1300,y:-150,z:800}],['back',{x:-500,y:1200,z:-s.room.depth/2+17}],['front',{x:1200,y:700,z:s.room.depth/2-60}],['left',{x:-s.room.width/2-60,y:1234,z:311}],['right',{x:s.room.width/2+60,y:1900,z:-811}]])pointNear(m.resolveMeasurementAnchor(s,m.measurementAnchor(s,id,p)),p);assert.throws(()=>m.measurementAnchor(s,'facade-sign',{x:0,y:0,z:0}),/가구·벽·바닥/)});
await test('distance decomposes true 3D diagonal, horizontal run and height without rounding storage',()=>{const s=empty();s.nodes=[{...m.createNode('box','a'),width:5000,height:2500,depth:4000}];const a=m.measurementAnchor(s,'a',{x:0,y:0,z:0}),b=m.measurementAnchor(s,'a',{x:300,y:400,z:1200}),next=m.addMeasurement(s,a,b);const v=m.readMeasurement(next,next.measurements[0]);near(v.length,1300);near(v.horizontal,Math.hypot(300,1200));near(v.y,400);near(v.x,300);near(v.z,1200);assert.equal(next.measurements[0].length,undefined)});
await test('node movement, rotation and proportional resize update saved endpoints',()=>{const s=measured(),a=s.measurements[0].start,next=structuredClone(s);next.nodes[0].x+=321.25;next.nodes[0].height*=2;const before=m.resolveMeasurementAnchor(s,a),after=m.resolveMeasurementAnchor(next,a);near(after.x-before.x,321.25);near(after.y,1200);const corner=m.measurementAnchor(s,'box',{x:-300,y:200,z:350});next.nodes[0].rotation+=90;const o=m.nodeMeasurementPose(next,next.nodes[0]);const matrix=new T.Matrix4().compose(new T.Vector3(o.x,o.y,o.z),new T.Quaternion().setFromAxisAngle(new T.Vector3(0,1,0),o.yaw),new T.Vector3(next.nodes[0].width,next.nodes[0].height,next.nodes[0].depth));const expected=new T.Vector3(...corner.point).applyMatrix4(matrix);pointNear(m.resolveMeasurementAnchor(next,corner),expected)});
await test('protruding parts preserve ratios outside nominal bounds rather than silently clamping',()=>{const s=empty();s.nodes=[{...m.createNode('box','b'),height:20,depth:20}];const p={x:550,y:20.5,z:35},a=m.measurementAnchor(s,'b',p);assert.ok(a.point[0]>.5&&a.point[1]>1&&a.point[2]>.5);pointNear(m.resolveMeasurementAnchor(s,a),p)});
await test('orphan measurements remain editable and recover on undo without stale distance',()=>{const s=measured(),deleted=m.batchAction(s,['box'],{type:'delete'});assert.equal(deleted.measurements.length,1);assert.equal(m.readMeasurement(deleted,deleted.measurements[0]),null);assert.ok(m.readMeasurement(s,s.measurements[0]));const renamed=m.editMeasurement(deleted,deleted.measurements[0].id,{type:'rename',name:'복원 대기'});assert.equal(renamed.measurements[0].name,'복원 대기');assert.equal(m.editMeasurement(renamed,renamed.measurements[0].id,{type:'delete'}).measurements.length,0)});
await test('creation limits, duplicate IDs, invalid offsets and zero-length input fail atomically',()=>{const s=empty(),a=floor(s,0,0),b=floor(s,1000,0);assert.throws(()=>m.addMeasurement(s,a,a),/1mm/);let full=s;for(let i=0;i<30;i++)full=m.addMeasurement(full,a,b);const before=JSON.stringify(full);assert.throws(()=>m.addMeasurement(full,a,b),/30개/);assert.equal(JSON.stringify(full),before);const one=m.addMeasurement(s,a,b);assert.throws(()=>m.addMeasurement(one,a,b,'중복',()=>one.measurements[0].id),/치수 ID/);const invalid=structuredClone(one);invalid.measurements[0].start.offset=20;assert.throws(()=>m.validateScene(invalid),/표면/);assert.throws(()=>m.addMeasurement(s,{kind:'node',nodeId:'missing',point:[0,0,0]},b),/찾을/)});
await test('later zero distance is valid and hidden nodes suppress only the overlay',()=>{const s=measured();s.measurements[0].end=structuredClone(s.measurements[0].start);m.validateScene(s);assert.equal(m.readMeasurement(s,s.measurements[0]).length,0);s.nodes[0].hidden=true;assert.equal(m.measurementVisible(s,s.measurements[0]),false);assert.equal(m.readMeasurement(s,s.measurements[0]).length,0)});
await test('legacy JSON and variant restore preserve or clear measurements independently',()=>{const old=m.saveVariant(empty(),'이전'),s=measured();s.variants=old.variants;const saved=m.saveVariant(s,'치수 있음'),json=m.validateScene(JSON.parse(JSON.stringify(saved)));assert.deepEqual(json.measurements,s.measurements);assert.equal(m.restoreVariant(json,json.variants[0].id).measurements,undefined);assert.deepEqual(m.restoreVariant(json,json.variants[1].id).measurements,s.measurements);assert.equal(m.designChanges(empty(),s).measurements,true);const corrupt=structuredClone(json);corrupt.variants[1].design.measurements.push(corrupt.variants[1].design.measurements[0]);assert.throws(()=>m.validateScene(corrupt),/치수 ID/)});
await test('CSV escapes names and formulas, preserves negative numeric coordinates and unavailable state',()=>{const s=measured();s.measurements[0].name=' =SUM(1,2)';const csv=m.measurementsCsv(s);assert.ok(csv.startsWith('\ufeff'));assert.ok(csv.includes('"\' =SUM(1,2)"'));assert.ok(csv.includes('"-400"'));assert.ok(!csv.includes('"\'-400"'));s.nodes=[];assert.ok(m.measurementsCsv(s).includes('연결 대상 없음'));const before=empty();assert.deepEqual(m.validateScene(before),before)});
function hit(id,point=new T.Vector3()){const mesh=new T.Mesh(new T.BoxGeometry(),new T.MeshBasicMaterial());mesh.userData.nodeId=id;return{object:mesh,point,distance:1};}
await test('picking honors ancestor visibility and blocks placeholders or unsupported foreground geometry',()=>{const s=measured(),hidden=hit('box'),parent=new T.Group();parent.visible=false;parent.add(hidden.object);const valid=hit('floor',new T.Vector3(.5,0,.3));assert.equal(m.pickMeasurementAnchor(s,[hidden,valid]).surface,'floor');const pending=hit('box');pending.object.userData.unmeasurable=true;assert.throws(()=>m.pickMeasurementAnchor(s,[pending,valid]),/다 불러온/);assert.throws(()=>m.pickMeasurementAnchor(s,[hit('facade-sign'),valid]),/가구·벽·바닥/);assert.throws(()=>m.pickMeasurementAnchor(s,[]),/클릭/)});
await test('annotation overlay updates distances without churn and disposes lines, sprites and textures',()=>{const s=measured(),overlay=new m.MeasurementOverlay(fakeLabel);overlay.update(s);const original=[...overlay.group.children],line=original.find(o=>o instanceof T.Line),sprite=original.find(o=>o instanceof T.Sprite);assert.ok(line&&sprite);let lineDisposed=0,textureDisposed=0;line.geometry.addEventListener('dispose',()=>lineDisposed++);sprite.material.map.addEventListener('dispose',()=>textureDisposed++);overlay.update(structuredClone(s));assert.equal(overlay.group.children[0],original[0]);const changed=structuredClone(s);changed.nodes[0].x+=100;overlay.update(changed);assert.equal(lineDisposed,1);assert.equal(textureDisposed,1);changed.nodes[0].hidden=true;overlay.update(changed);assert.equal(overlay.group.children.length,0);overlay.dispose();});
function engineFixture(s){const e=Object.create(m.SceneEngine.prototype);Object.assign(e,{data:s,root:new T.Group(),modelCache:new Map(),imageCache:new Map(),geometryKey:JSON.stringify({room:s.room,nodes:s.nodes,facade:s.facade}),measurementOverlay:new m.MeasurementOverlay(fakeLabel),measureStart:null,setLighting(){},setSelection(){},updateCutaway(){},transform:{detach(){}},buildNode(){},box(parent,w,h,d,x,y,z,id){const o=new T.Mesh(new T.BoxGeometry(w,h,d),new T.MeshBasicMaterial());o.position.set(x,y,z);o.userData.nodeId=id;parent.add(o);return o;},surfaceMaterial(){return new T.MeshBasicMaterial()}});return e;}
await test('actual engine refreshes measurement-only updates and cancels pending points on geometry changes',()=>{const s=empty(),e=engineFixture(s),next=m.addMeasurement(s,floor(s,0,0),floor(s,1000,0));e.setScene(next);assert.ok(e.measurementOverlay.group.children.some(o=>o instanceof T.Line));e.measureStart=floor(next,100,0);let cancelled=0;e.onMeasureStatus=started=>{if(!started)cancelled++};const changed={...next,nodes:[m.createNode('box','box')]};e.setScene(changed);assert.equal(e.measureStart,null);assert.equal(cancelled,1);e.measurementOverlay.dispose()});
await test('actual two-click tape records one complete measurement and retains start after rejection',()=>{const s=empty(),e=engineFixture(s);const ray=p=>({intersectObjects:()=>[hit('floor',new T.Vector3(...p))]});let calls=0;e.onMeasure=(a,b)=>{calls++;m.addMeasurement(s,a,b);return true};e.measureAt(ray([0,0,0]));assert.ok(e.measureStart);e.measureAt(ray([1,0,0]));assert.equal(calls,1);assert.equal(e.measureStart,null);e.measureAt(ray([0,0,0]));let error='';e.onMeasureStatus=(_,msg)=>error=msg??'';e.measureAt(ray([0,0,0]));assert.ok(e.measureStart);assert.match(error,/1mm/);e.cancelMeasurement();e.measurementOverlay.dispose()});
await test('actual screenshot excludes annotations by default, includes only explicitly and restores on error',async()=>{const e=Object.create(m.SceneEngine.prototype),overlay=new m.MeasurementOverlay(fakeLabel),visibility=[];let fail=false;Object.assign(e,{measurementOverlay:overlay,modelsReady:async()=>{},camera:new T.PerspectiveCamera(38,1.5,.05,200),helpers:new T.Group(),transform:{getHelper:()=>gizmo},renderer:{getSize:v=>v.set(900,600),getPixelRatio:()=>1,setPixelRatio(){},setSize(){},render(){visibility.push(overlay.group.visible);if(fail)throw new Error('render failed')},domElement:{toDataURL:()=> 'data:image/png;base64,test'}}});const gizmo=new T.Group();await e.screenshot();assert.deepEqual(visibility,[false]);assert.equal(overlay.group.visible,true);await e.screenshot(2048,undefined,true);assert.equal(visibility[1],true);overlay.group.visible=false;fail=true;await assert.rejects(e.screenshot(2048,undefined,true),/render failed/);assert.equal(overlay.group.visible,false);assert.equal(e.helpers.visible,true);assert.equal(gizmo.visible,true)});
await test('real Float32 floor and wall ray hits produce saveable anchors at exact physical faces',()=>{const s=empty(),floorMesh=new T.Mesh(new T.BoxGeometry(7.2,.15,6.4),new T.MeshBasicMaterial());floorMesh.position.y=-.075;floorMesh.userData.nodeId='floor';floorMesh.updateMatrixWorld(true);for(const [origin,direction,offset]of [[new T.Vector3(0,1,0),new T.Vector3(0,-1,0),0],[new T.Vector3(0,-1,0),new T.Vector3(0,1,0),-150]]){const hits=new T.Raycaster(origin,direction).intersectObject(floorMesh),a=m.pickMeasurementAnchor(s,hits);assert.equal(a.offset,offset);m.addMeasurement(s,a,{...a,u:a.u+.1});}const wall=new T.Mesh(new T.BoxGeometry(7.2,2.9,.12),new T.MeshBasicMaterial());wall.position.set(0,1.45,-3.2);wall.userData.nodeId='back';wall.updateMatrixWorld(true);const a=m.pickMeasurementAnchor(s,new T.Raycaster(new T.Vector3(0,1,0),new T.Vector3(0,0,-1)).intersectObject(wall));assert.equal(a.offset,60);m.addMeasurement(s,a,floor(s,0,0));});
console.log(`${checks} measurement checks passed.`);
