import assert from 'node:assert/strict';
import {build} from 'esbuild';
const r=await build({stdin:{contents:"export * as T from 'three'; export * from './lib/glb'; export * from './lib/model-loader'; export * from './lib/scene-model'; export * from './lib/scene-engine';",resolveDir:process.cwd()},bundle:true,platform:'node',format:'esm',write:false});
const m=await import('data:text/javascript;base64,'+Buffer.from(r.outputFiles[0].text).toString('base64'));const {T}=m;
function glb(change=d=>d){const bin=new Float32Array([0,0,0,1,1,0,0,0,1]);const d=change({asset:{version:'2.0'},scene:0,scenes:[{nodes:[0]}],nodes:[{mesh:0}],meshes:[{primitives:[{attributes:{POSITION:0},material:0}]}],materials:[{pbrMetallicRoughness:{baseColorFactor:[.2,.4,.6,1],metallicFactor:.3,roughnessFactor:.7}}],buffers:[{byteLength:bin.byteLength}],bufferViews:[{buffer:0,byteOffset:0,byteLength:bin.byteLength}],accessors:[{bufferView:0,componentType:5126,count:3,type:'VEC3',min:[0,0,0],max:[1,1,1]}]});let json=Buffer.from(JSON.stringify(d));json=Buffer.concat([json,Buffer.alloc((4-json.length%4)%4,32)]);const out=new ArrayBuffer(12+8+json.length+8+bin.byteLength),v=new DataView(out),a=new Uint8Array(out);v.setUint32(0,0x46546c67,true);v.setUint32(4,2,true);v.setUint32(8,out.byteLength,true);v.setUint32(12,json.length,true);v.setUint32(16,0x4e4f534a,true);a.set(json,20);const at=20+json.length;v.setUint32(at,bin.byteLength,true);v.setUint32(at+4,0x004e4942,true);a.set(new Uint8Array(bin.buffer),at+8);return out}
let checks=0;async function test(name,fn){await fn();checks++;console.log('PASS '+name)}
await test('valid static GLB normalizes floor center and reports real dimensions',async()=>{const parsed=await m.parseModel(glb());assert.equal(parsed.width,1000);assert.equal(parsed.height,1000);assert.equal(parsed.metadata.triangles,1);const box=new T.Box3().setFromObject(parsed.root);assert.equal(box.min.y,0);assert.equal(box.min.x,-.5);assert.equal(box.max.z,.5);m.disposeModel(parsed.root)});
await test('malformed, external and oversized model contracts fail before loading',()=>{assert.throws(()=>m.inspectGlb(new ArrayBuffer(30)));for(const mutate of [d=>{d.buffers[0].uri='https://elsewhere/model.bin';return d},d=>{d.images=[{uri:'http://external/texture.png'}];return d},d=>{d.nodes[0].children=[0];return d},d=>{d.extensionsUsed=['KHR_draco_mesh_compression'];return d},d=>{d.scenes[0].nodes=[0,0];return d},d=>{d.accessors[0].count=200001;d.nodes=[{mesh:0},{mesh:0}];d.scenes[0].nodes=[0,1];return d}])assert.throws(()=>m.inspectGlb(glb(mutate)))});
await test('instances own separate geometry, materials and textures',async()=>{const parsed=await m.parseModel(glb());let original;parsed.root.traverse(o=>{if(o.isMesh)original=o});original.material.map=new T.Texture();const a=m.cloneModel(parsed.root),b=m.cloneModel(parsed.root);let ma,mb;a.traverse(o=>{if(o.isMesh)ma=o});b.traverse(o=>{if(o.isMesh)mb=o});assert.notEqual(ma.geometry,mb.geometry);assert.notEqual(ma.material,mb.material);assert.notEqual(ma.material.map,mb.material.map);ma.material.color.set('#ff0000');assert.notEqual(ma.material.color.getHex(),mb.material.color.getHex());m.disposeModel(a);assert.equal(mb.material.color.getHex(),original.material.color.getHex());m.disposeModel(b);m.disposeModel(parsed.root)});
await test('model IDs survive JSON, remain out of AI creation catalog, and paint resolves by slot',()=>{const s=m.initialScene(),n={...m.createNode('box','model-1'),kind:'model',assetId:'a3071cec-5507-4b6e-9cf6-8a7e1ac9b749'};s.nodes=[n];assert.equal(m.validateScene(JSON.parse(JSON.stringify(s))).nodes[0].assetId,n.assetId);assert.equal(m.kinds.includes('model'),false);assert.throws(()=>m.applyCommands(s,[{type:'add',kind:'model',count:1}]));assert.equal(m.nodeAppearance(n,'mesh0:0').original,true);const next=m.editAppearance(s,{id:n.id,face:'mesh0:0'},{material:'steel'});assert.equal(m.nodeAppearance(next.nodes[0],'mesh0:0').original,false);assert.equal(m.nodeAppearance(next.nodes[0],'mesh1:0').original,true)});
await test('engine import keeps scalar material visible and ignores detached late targets',async()=>{const parsed=await m.parseModel(glb()),engine=Object.create(m.SceneEngine.prototype);engine.root=new T.Group();engine.disposed=false;engine.setSelection=()=>{};engine.modelAsset=async()=>parsed.root;engine.selection=null;const group=new T.Group();engine.root.add(group);const n={...m.createNode('box','id'),kind:'model',assetId:crypto.randomUUID(),width:1500,height:750,depth:600};engine.buildModel(group,n);await new Promise(r=>setTimeout(r,0));let mesh;group.traverse(o=>{if(o.isMesh)mesh=o});assert.ok(mesh);assert.equal(Array.isArray(mesh.material),false);assert.equal(mesh.userData.part,'mesh0');assert.equal(mesh.userData.nodeId,n.id);const size=new T.Box3().setFromObject(group).getSize(new T.Vector3());assert.equal(size.x,1.5);assert.equal(size.y,.75);assert.equal(size.z,.6);const stale=new T.Group();engine.root.add(stale);engine.buildModel(stale,n);engine.root.remove(stale);await new Promise(r=>setTimeout(r,0));assert.equal(stale.children.length,1);assert.equal(stale.children[0].material.wireframe,true);engine.modelCache=new Map();engine.geometryKey='stable';engine.data={nodes:[]};const OriginalReader=globalThis.FileReader;globalThis.FileReader=class{readAsArrayBuffer(blob){blob.arrayBuffer().then(data=>{this.result=data;this.onloadend?.()})}readAsDataURL(blob){blob.arrayBuffer().then(data=>{this.result='data:'+blob.type+';base64,'+Buffer.from(data).toString('base64');this.onloadend?.()})}};try{const output=await engine.exportGlb();assert.equal(m.inspectGlb(output).triangles,1);const roundtrip=await m.parseModel(output);assert.equal(roundtrip.width,1500);assert.equal(roundtrip.height,750);m.disposeModel(roundtrip.root)}finally{globalThis.FileReader=OriginalReader}engine.clearGroup(group);engine.clearGroup(stale);m.disposeModel(parsed.root)});
await test('export readiness rejects scene changes during model loading',async()=>{const e=Object.create(m.SceneEngine.prototype);e.geometryKey='old';e.disposed=false;let finish;e.modelCache=new Map([['id',{promise:new Promise(r=>finish=r)}]]);const ready=e.modelsReady();e.geometryKey='new';finish(new T.Group());await assert.rejects(ready,/변경/)});
console.log(`${checks} model import checks passed.`);
