import assert from 'node:assert/strict';
import {build} from 'esbuild';
const bundle=await build({stdin:{contents:"export * as T from 'three';export {SceneEngine} from './lib/scene-engine';export * from './lib/object-photo';export * from './lib/scene-model';export * from './lib/selection';export * from './lib/assemblies';export * from './lib/design-variants';export {planRows} from './lib/floor-plan';export {sceneForDesignAi} from './lib/ai-context';",resolveDir:process.cwd()},bundle:true,platform:'node',format:'esm',write:false});
const m=await import('data:text/javascript;base64,'+Buffer.from(bundle.outputFiles[0].text).toString('base64'));let checks=0;
function test(name,fn){fn();checks++;console.log('PASS '+name)}
const scene={...m.initialScene(),nodes:[]},photo={imageId:crypto.randomUUID(),representation:'parametric',analysis:'manual',dimensions:'measured',brand:'사용자 입력 제조사',productCode:'TEST-01',notes:[]},input={kind:'table',name:'사진 테이블',width:1200,depth:700,height:750,material:'oak',color:'#a08060',photo};
const part=(name,x,y,z,width,height,depth,shape='box')=>({shape,name,x,y,z,width,height,depth,material:'oak',color:'#a08060'});
const parts=[part('상판',0,.9,0,1,.1,1),...[-.4,.4].flatMap(x=>[-.4,.4].map(z=>part('다리',x,0,z,.1,.9,.1,'cylinder')))];
let made;
test('manual photo proxy preserves exact entered dimensions and reference without replacing the room',()=>{made=m.createPhotoObject(scene,input);assert.equal(made.scene.nodes.length,1);assert.deepEqual([made.node.width,made.node.depth,made.node.height],[1200,700,750]);assert.equal(made.node.objectPhoto.productCode,'TEST-01');assert.deepEqual(made.scene.room,scene.room);assert.equal(scene.nodes.length,0);assert.equal(made.node.estimated,true)});
test('AI parts union fits authoritative width, height and depth exactly with one editable group',()=>{const result=m.createPhotoObject(scene,{...input,parts,photo:{...photo,analysis:'ai'}});const b=m.groupBounds(result.nodes);for(const key of ['width','height','depth'])assert.ok(Math.abs(b[key]-input[key])<1e-6);assert.equal(result.nodes.length,5);assert.equal(new Set(result.nodes.map(n=>n.group.id)).size,1);assert.equal(new Set(result.ids).size,5);assert.equal(new Set(result.nodes.map(n=>n.objectPhoto.objectId)).size,1);assert.deepEqual(m.imageReferences(result.scene),[photo.imageId]);assert.ok(result.nodes.every((n,i)=>n.objectPhoto.partIndex===i&&n.objectPhoto.partCount===5));assert.deepEqual(result.nodes[0].objectPhoto.sourceSize,{width:1200,height:750,depth:700});made=result});
test('normalization supports offset part coordinates without changing total input bounds',()=>{const normalized=m.photoPartLayout(parts.map(p=>({...p,x:p.x+.2,z:p.z-.3,y:p.y+.1})),input);const result=m.createPhotoObject(scene,{...input,parts:normalized.map(p=>({...p,x:p.x/1200,y:p.y/750,z:p.z/700,width:p.width/1200,height:p.height/750,depth:p.depth/700}))});assert.ok(Math.abs(m.groupBounds(result.nodes).width-1200)<1e-6)});
test('empty AI parts use an explicitly labeled standard proxy',()=>{const result=m.createPhotoObject(scene,{...input,parts:[],photo:{...photo,analysis:'ai'}});assert.equal(result.nodes.length,1);assert.equal(result.node.kind,'table');assert.equal(result.node.objectPhoto.representation,'parametric')});
test('too-thin inferred parts are rejected instead of silently changing dimensions',()=>{assert.throws(()=>m.createPhotoObject(scene,{...input,parts:[part('상판',0,.9,0,1,.1,1),part('얇은 다리',0,0,0,.01,.9,.01)]}),/20mm/)});
test('unknown parts, excess parts, zero dimensions and oversized room objects fail atomically',()=>{for(const value of [{...input,width:0},{...input,parts:Array(17).fill(parts[0])},{...input,parts:[{...parts[0],shape:'mesh'}]},{...input,width:10000,depth:10000},{...input,height:9000}])assert.throws(()=>m.createPhotoObject(scene,value));assert.equal(scene.nodes.length,0)});
test('adding parts respects the total 300-element scene capacity',()=>{const full={...scene,nodes:Array.from({length:298},(_,i)=>({...m.createNode('box','existing-'+i),hidden:true}))};assert.throws(()=>m.createPhotoObject(full,{...input,parts}),/300/);assert.equal(full.nodes.length,298)});
test('stored variants and reusable sets retain photo metadata and independently place parts',()=>{const restored=m.validateScene(JSON.parse(JSON.stringify(m.saveVariant(made.scene,'사진 시안'))));assert.equal(restored.variants[0].design.nodes[0].objectPhoto.imageId,photo.imageId);const a=m.captureAssembly(made.scene,made.ids,'사진 세트'),placed=m.insertAssembly(scene,a,{x:0,y:0,z:0,rotation:90});assert.equal(placed.ids.length,5);assert.ok(placed.scene.nodes.every(n=>n.objectPhoto.imageId===photo.imageId));assert.notEqual(placed.scene.nodes[0].group.id,made.nodes[0].group.id)});
test('private image quota counts distinct object photographs, including hidden parts',()=>{const s={...scene,nodes:Array.from({length:8},(_,i)=>({...m.createNode('box','photo-'+i),hidden:true,objectPhoto:{...photo,imageId:crypto.randomUUID()}}))};assert.equal(m.imageReferences(m.validateScene(s)).length,8);assert.throws(()=>m.createPhotoObject(s,input),/8개/)});
test('plan schedule distinguishes estimated part dimensions from user measured outer dimensions',()=>{assert.ok(m.planRows(made.scene).every(row=>row[8]==='사진 추정부품'));assert.equal(m.planRows(m.createPhotoObject(scene,input).scene)[0][8],'사용자 실측')});
test('strict AI contract rejects invented real-world dimensions or unsupported geometry',()=>{const result={kind:'table',name:'테이블',material:'oak',color:'#a08060',notes:['사진 비례를 단순화했습니다.'],parts};assert.ok(m.objectPhotoAnalysisSchema.safeParse(result).success);assert.equal(m.objectPhotoAnalysisSchema.safeParse({...result,width:1200}).success,false);assert.equal(m.objectPhotoAnalysisSchema.safeParse({...result,parts:[{...parts[0],rotation:45}]}).success,false)});
test('resizing a measured standard proxy removes the measured label without altering the source snapshot',()=>{const result=m.createPhotoObject(scene,input);result.scene.nodes[0].width+=100;assert.equal(m.planRows(result.scene)[0][8],'입력');assert.equal(result.scene.nodes[0].objectPhoto.sourceSize.width,1200)});
test('object photograph metadata is excluded from generic design AI context',()=>{assert.equal(m.sceneForDesignAi(made.scene).nodes[0].objectPhoto,undefined)});
// Actual Three geometry and GLTF export, with only procedural bitmap creation bypassed.
{
 const {T}=m,e=Object.assign(Object.create(m.SceneEngine.prototype),{data:made.scene,root:new T.Group(),modelsReady:async()=>{},material(id,color){return new T.MeshStandardMaterial({color:color??'#a08060'})}});
 for(const n of made.nodes)e.buildNode(n);e.root.updateMatrixWorld(true);const box=new T.Box3().setFromObject(e.root),extent=box.getSize(new T.Vector3());
 for(const [axis,mm]of [['x',1200],['y',750],['z',700]])assert.ok(Math.abs(extent[axis]*1000-mm)<.01);
 const originalReader=globalThis.FileReader;globalThis.FileReader=class{readAsArrayBuffer(blob){blob.arrayBuffer().then(data=>{this.result=data;this.onloadend?.()})}};
 try{const bytes=await e.exportGlb(),view=new DataView(bytes),json=JSON.parse(new TextDecoder().decode(new Uint8Array(bytes,20,view.getUint32(12,true))));assert.equal(view.getUint32(0,true),0x46546c67);assert.ok(json.nodes.some(n=>n.extras?.furnitureGroupId&&n.children.length===5));assert.equal(json.nodes.filter(n=>n.extras?.nodeId&&made.ids.includes(n.extras.nodeId)&&n.children).length,5);checks++;console.log('PASS photo parts generate exact physical Three bounds and grouped GLB output');}finally{globalThis.FileReader=originalReader;e.clearGroup(e.root)}
}
console.log(`${checks} photo object checks passed. AI geometry fixtures are synthetic, not provider output.`);
