import assert from 'node:assert/strict';import {build} from 'esbuild';import {mkdtemp,writeFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {pathToFileURL} from 'node:url';
const dir=await mkdtemp(join(tmpdir(),'spatial-openings-')),file=join(dir,'bundle.mjs');
const bundle=await build({stdin:{contents:"export * as T from 'three';export * from './lib/scene-model';export * from './lib/partition-openings-schema';export * from './lib/partition-openings';export * from './lib/partition-geometry';export * from './lib/scene-engine';export * from './lib/material-catalog';export * from './lib/walk-world';export * from './lib/budget';export * from './lib/floor-plan';export * from './lib/selection';export * from './lib/assemblies';export * from './lib/placement';export * from './lib/design-variants';export * from './lib/measurements';export * from './lib/ai-context';export * from './lib/glb';",resolveDir:process.cwd()},bundle:true,platform:'node',format:'esm',write:false});
await writeFile(file,bundle.outputFiles[0].text);const m=await import(pathToFileURL(file));await rm(dir,{recursive:true,force:true});const {T}=m;
let checks=0;async function test(name,fn){await fn();checks++;console.log('PASS '+name);}
const near=(a,b,tolerance=1e-6)=>assert.ok(Math.abs(a-b)<tolerance,`${a} != ${b}`),uuid=()=>crypto.randomUUID();
const opening=(extra={})=>({id:uuid(),name:'통로',kind:'passage',x:0,bottom:0,width:900,height:2100,...extra});
const node=(extra={})=>({...m.createNode('partition','wall'),width:5000,height:2900,depth:120,...extra});
const scene=(n=node())=>{const s=m.initialScene();return{...s,room:{...s.room,width:20000,depth:20000,height:6000},nodes:[n]};};
function engine(n){const s=scene(n),e=Object.create(m.SceneEngine.prototype);Object.assign(e,{root:new T.Group(),data:s,material(id){const a=m.materials.find(v=>v.id===id);return new T.MeshStandardMaterial({name:id,color:a.color});},modelsReady:async()=>{}});const g=e.buildNode(n);e.root.updateMatrixWorld(true);return{e,g};}
function world(n,x,y,z){const r=n.rotation*Math.PI/180;return new T.Vector3((n.x+Math.cos(r)*x+Math.sin(r)*z)/1000,(n.y+y)/1000,(n.z-Math.sin(r)*x+Math.cos(r)*z)/1000);}
function cast(g,n,x,y,side=1){const a=world(n,x,y,2000*side),b=world(n,x,y,-2000*side);return new T.Raycaster(a,b.sub(a).normalize()).intersectObject(g,true);}
function dispose(g){g.traverse(o=>{o.geometry?.dispose();if(o.material)for(const a of Array.isArray(o.material)?o.material:[o.material])a.dispose();});}
await test('legacy scenes retain their exact schema and solid six-face partition mesh',()=>{const s=scene(),before=JSON.stringify(s);assert.equal(JSON.stringify(m.validateScene(s)),before);const {g}=engine(s.nodes[0]);assert.equal(g.children.length,1);assert.ok(g.children[0].geometry instanceof T.BoxGeometry);assert.equal(m.renderedMaterialSlots(g,s.nodes).length,6);dispose(g);});
await test('schema accepts fractional apertures at exact 100mm side and header boundaries',()=>{const o=opening({x:-1949.875,width:900.25,height:2800}),s=scene(node({openings:[o]}));m.validateScene(s);assert.equal(s.nodes[0].openings[0].width,900.25);for(const patch of [{x:o.x-.01},{height:2800.01}])assert.throws(()=>m.validateScene(scene(node({openings:[{...o,...patch}]}))),/100mm/);});
await test('only partitions allow openings and runtime invalid values reject',()=>{for(const kind of ['chair','box','door','model'])assert.throws(()=>m.validateScene(scene({...node({openings:[opening()]}),kind})),/파티션/);for(const patch of [{id:'bad'},{name:''},{x:NaN},{width:199},{height:199},{bottom:-1},{kind:'arch'}])assert.throws(()=>m.validateScene(scene(node({openings:[opening(patch)]}))));});
await test('doors and passages start at parent floor while windows require a 100mm sill',()=>{for(const kind of ['door','passage'])for(const patch of [{bottom:1},{width:299},{height:799}])assert.throws(()=>m.validateScene(scene(node({openings:[opening({kind,...patch})]}))),/바닥/);m.validateScene(scene(node({openings:[opening({kind:'window',bottom:100,width:200,height:200})]})));assert.throws(()=>m.validateScene(scene(node({openings:[opening({kind:'window',bottom:99})]}))),/창문/);});
await test('opening pairs need 100mm separation horizontally or vertically including hidden walls',()=>{const a=opening({kind:'window',x:-500,bottom:100,width:400,height:300}),b=opening({kind:'window',x:0,bottom:100,width:400,height:300});m.validateScene(scene(node({openings:[a,b]})));assert.throws(()=>m.validateScene(scene(node({hidden:true,openings:[a,{...b,x:-.01}]}))),/간격/);m.validateScene(scene(node({openings:[a,{...b,x:-500,bottom:500}]})));assert.throws(()=>m.validateScene(scene(node({openings:[a,{...b,x:-500,bottom:499.99}]}))),/간격/);});
await test('opening IDs are unique within each parent but may be retained by independent clones',()=>{const o=opening(),n=node({openings:[o]});assert.throws(()=>m.validateScene(scene({...n,openings:[o,{...o,x:1500}]})),/ID가 중복/);const s=scene(n);s.nodes.push({...n,id:'copy',z:2000});assert.equal(m.validateScene(s).nodes.length,2);});
await test('eight per parent and one hundred per design limits also apply to inactive variants',()=>{const make=()=>node({width:16000,openings:Array.from({length:8},(_,i)=>opening({x:-6000+i*1500,width:300,height:900}))});const s=scene(make());s.nodes=Array.from({length:13},(_,i)=>({...make(),id:`wall-${i}`}));s.nodes[12].openings=s.nodes[12].openings.slice(0,4);assert.equal(m.validateScene(s).nodes.length,13);const saved=m.saveVariant(s,'100개');s.nodes[12].openings.push(opening({x:6000,width:300,height:900}));assert.throws(()=>m.validateScene(s),/100개/);saved.variants[0].design.nodes=s.nodes;assert.throws(()=>m.validateScene(saved),/100개/);assert.throws(()=>m.validateScene(scene({...make(),openings:[...make().openings,opening()]})));});
await test('wall cells preserve exact removed area and deterministic geometry after reordering',()=>{const n=node({openings:[opening({x:-1200,width:900.125}),opening({kind:'window',x:1100,bottom:700.25,width:1100.5,height:1300.75})]}),cells=m.partitionCells(n);near(cells.reduce((a,c)=>a+c.width*c.height,0),n.width*n.height-n.openings.reduce((a,o)=>a+o.width*o.height,0),1e-5);for(const c of cells){assert.ok(c.width>0&&c.height>0);assert.ok(!n.openings.some(o=>Math.abs(c.x-o.x)<o.width/2&&c.y>o.bottom&&c.y<o.bottom+o.height));}assert.deepEqual(cells,m.partitionCells({...n,openings:[...n.openings].reverse()}));});
await test('exposed mesh area matches perimeter and void area with no internal cell faces',()=>{const n=node({openings:[opening()]}),g=m.partitionWallGeometry(n),p=g.getAttribute('position'),index=g.index;let area=0;for(let i=0;i<index.count;i+=3){const a=new T.Vector3().fromBufferAttribute(p,index.getX(i)),b=new T.Vector3().fromBufferAttribute(p,index.getX(i+1)),c=new T.Vector3().fromBufferAttribute(p,index.getX(i+2));area+=new T.Vector3().crossVectors(b.sub(a),c.sub(a)).length()/2;}const W=5,H=2.9,D=.12,ow=.9,oh=2.1;near(area,2*(W*H-ow*oh)+D*(2*W+2*H+2*oh),1e-5);assert.equal(g.groups.length,6);g.dispose();});
await test('front and back rays pass through empty apertures but hit jambs and header at every yaw',()=>{for(const rotation of [0,37,90,-143]){const n=node({x:400.125,z:-250.875,rotation,openings:[opening()]}),{g}=engine(n);for(const side of [-1,1]){assert.equal(cast(g,n,0,1000,side).length,0);assert.ok(cast(g,n,800,1000,side).length>0);assert.ok(cast(g,n,0,2500,side).length>0);}dispose(g);}});
await test('front-face winding lets light-facing rays hit all external faces and reveals',()=>{const n=node({openings:[opening()]}),g=new T.Mesh(m.partitionWallGeometry(n),new T.MeshBasicMaterial());g.updateMatrixWorld(true);for(const [origin,direction] of [[[3,1,0],[-1,0,0]],[[-3,1,0],[1,0,0]],[[0,3.5,0],[0,-1,0]],[[-2,-1,0],[0,1,0]],[[0,1,0],[1,0,0]],[[0,1,0],[0,1,0]]])assert.ok(new T.Raycaster(new T.Vector3(...origin),new T.Vector3(...direction)).intersectObject(g).length>0);dispose(g);});
await test('body material slots and continuous front UVs remain stable across changes in tessellation',()=>{const n=node({openings:[opening({x:-900}),opening({kind:'window',x:1200,bottom:800,width:900,height:1200})],faces:{'body:4':'sage'}}),{g}=engine(n),slots=m.renderedMaterialSlots(g,[n]);assert.deepEqual(slots.filter(s=>s.face.startsWith('body:')).map(s=>s.face).sort(),Array.from({length:6},(_,i)=>`body:${i}`));assert.ok(slots.every(s=>s.hasUv));const body=g.children.find(c=>c.userData.part==='body'),geo=body.geometry,pos=geo.getAttribute('position'),uv=geo.getAttribute('uv'),part=geo.groups.find(p=>p.materialIndex===4);for(let i=part.start;i<part.start+part.count;i++){const at=geo.index.getX(i);near(uv.getX(at),pos.getX(at)/5+.5,1e-6);near(uv.getY(at),pos.getY(at)/2.9,1e-6);}assert.equal(body.material[4].name,'sage');dispose(g);});
await test('door and window real meshes block aperture rays and resolve independent pane/frame defaults',()=>{for(const kind of ['door','window']){const o=opening({kind,bottom:kind==='window'?500:0,height:kind==='window'?1500:2100}),n=node({openings:[o]}),{g}=engine(n);const hits=cast(g,n,0,o.bottom+o.height/2);assert.ok(hits.some(hit=>hit.object.userData.part===`op-${o.id}-panel`));assert.equal(m.nodeAppearance(n,`op-${o.id}-panel:0`).material,kind==='window'?'glass':'oak');assert.equal(m.nodeAppearance(n,`op-${o.id}-frameL:0`).material,'charcoal');dispose(g);}});
await test('walkthrough traverses sufficiently wide and tall empty passages in rotated parent walls',()=>{for(const rotation of [0,37,90,-143]){const n=node({x:500,z:-300,rotation,openings:[opening()]}),r=rotation*Math.PI/180,a=world(n,0,0,1000),b=world(n,0,0,-1000),worldMap=m.walkWorld(scene(n),1650),p={x:a.x*1000,z:a.z*1000},q={x:b.x*1000,z:b.z*1000};assert.equal(m.walkBlocker(worldMap,{x:n.x,z:n.z}),null);const move=m.moveWalk(worldMap,p,{x:q.x-p.x,z:q.z-p.z});near(move.point.x,q.x);near(move.point.z,q.z);assert.equal(move.blocked,null);}});
await test('narrow passages, low headers, sills, closed doors and windows still block walking',()=>{for(const o of [opening({width:400}),opening({height:1700}),opening({kind:'window',bottom:100,height:2200}),opening({kind:'door'})]){const n=node({openings:[o]}),w=m.walkWorld(scene(n),1650);assert.ok(m.walkBlocker(w,{x:0,z:0}));const move=m.moveWalk(w,{x:0,z:1000},{x:0,z:-2000});assert.ok(move.point.z>0);assert.ok(move.blocked);}const n=node({hidden:true,openings:[opening({kind:'door'})]});assert.equal(m.walkWorld(scene(n),1650).obstacles.length,0);});
await test('preview editing is atomic and rejects missing, nonpartition, locked and hidden targets',()=>{for(const patch of [{locked:true},{hidden:true},{kind:'box'}]){const s=scene(node(patch)),before=JSON.stringify(s);assert.throws(()=>m.planPartitionOpenings(s,'wall',[opening()]));assert.equal(JSON.stringify(s),before);}const s=scene(),before=JSON.stringify(s);assert.throws(()=>m.planPartitionOpenings(s,'missing',[opening()]));assert.throws(()=>m.planPartitionOpenings(s,'wall',[opening({width:4999})]));assert.equal(JSON.stringify(s),before);});
await test('preview accept rejects stale sessions or source changes and keeps exact opening IDs',()=>{const s=scene(),o=opening(),p=m.planPartitionOpenings(s,'wall',[o]);assert.equal(s.nodes[0].openings,undefined);assert.deepEqual(m.acceptPartitionOpenings(s,p,3,3),p.scene);assert.equal(p.scene.nodes[0].openings[0].id,o.id);assert.throws(()=>m.acceptPartitionOpenings(s,p,4,3),/프로젝트/);assert.throws(()=>m.acceptPartitionOpenings({...s,name:'changed'},p,3,3),/바뀌/);});
await test('default opening placement finds the nearest free span without overwriting an existing cut',()=>{let n=node();const a=m.newPartitionOpening(n,'door');n={...n,openings:[a]};const b=m.newPartitionOpening(n,'door');assert.notEqual(a.x,b.x);m.validatePartitionOpenings({...n,openings:[a,b]});assert.equal(a.x,0);const small=node({width:1000,height:900,openings:[opening({width:800,height:800})]});assert.throws(()=>m.newPartitionOpening(small,'door'),/여유/);});
await test('removing an opening cleans only its material roles and frees image references',()=>{const a=opening({kind:'window',x:-1200,bottom:600,height:1200}),b=opening({kind:'door',x:1200}),key=o=>`op-${o.id}-panel:4`,imageA=uuid(),imageB=uuid(),n=node({openings:[a,b],faces:{[key(a)]:'steel',[key(b)]:'walnut','body:4':'sage'},faceFinishes:{[key(a)]:{textureId:imageA},[key(b)]:{textureId:imageB}}});const p=m.planPartitionOpenings(scene(n),'wall',[b]);assert.deepEqual(m.imageReferences(p.scene),[imageB]);assert.equal(p.scene.nodes[0].faces[key(a)],undefined);assert.equal(p.scene.nodes[0].faces[key(b)],'walnut');assert.equal(p.scene.nodes[0].faces['body:4'],'sage');assert.equal(n.faceFinishes[key(a)].textureId,imageA);});
await test('type changes remove absent frame roles and preserve common painted parts with stable IDs',()=>{const o=opening({kind:'window',bottom:500,height:1500}),panel=`op-${o.id}-panel:0`,bottom=`op-${o.id}-frameBottom:0`,s=scene(node({openings:[o],faces:{[panel]:'glass',[bottom]:'steel'},faceFinishes:{[bottom]:{textureId:uuid()}}}));const door=m.planPartitionOpenings(s,'wall',[{...o,kind:'door',bottom:0}]).scene;assert.equal(door.nodes[0].faces[bottom],undefined);assert.equal(door.nodes[0].faces[panel],'glass');assert.equal(m.imageReferences(door).length,0);const passage=m.planPartitionOpenings(door,'wall',[{...o,kind:'passage',bottom:0}]).scene;assert.deepEqual(passage.nodes[0].faces,{});assert.equal(passage.nodes[0].faceFinishes,undefined);});
await test('opening physical changes trigger price review but rename, reorder and IDs do not',()=>{const a=opening({x:-1200}),b=opening({kind:'window',x:1200,bottom:700,height:1200}),s=m.editEstimates(scene(node({openings:[a,b]})),['wall'],{unitPrice:100000}),n=s.nodes[0];assert.equal(m.priceNeedsReview(n),false);assert.equal(m.priceBasis({...n,openings:[{...b,name:'renamed'},{...a,id:uuid()}]}),m.priceBasis(n));for(const change of [{width:a.width+10},{x:a.x+10},{height:a.height-10},{kind:'door'}]){const p=m.planPartitionOpenings(s,'wall',[{...a,...change},b]);assert.equal(m.priceNeedsReview(p.scene.nodes[0]),true);}assert.equal(m.budgetSummary(s).items,1);assert.ok(m.budgetMaterialDetails(n).includes('통로 900×2100'));});
await test('renumbered equivalent opening face keys aggregate the same physical price specification',()=>{const a=opening({kind:'door'}),b={...a,id:uuid(),name:'다른 이름'},na=node({openings:[a],faces:{[`op-${a.id}-panel:4`]:'walnut'},faceFinishes:{[`op-${a.id}-frameL:1`]:{color:'#abcdef'}}}),nb={...na,id:'copy',openings:[b],faces:{[`op-${b.id}-panel:4`]:'walnut'},faceFinishes:{[`op-${b.id}-frameL:1`]:{color:'#abcdef'}}};assert.equal(m.priceBasis(na),m.priceBasis(nb));const s=scene(na);s.nodes.push(nb);assert.equal(m.budgetRows(s).length,1);});
await test('parent resizing cannot strand apertures and ordinary group transforms retain local dimensions',()=>{const n=node({openings:[opening({x:1500})]}),s=scene(n),before=JSON.stringify(s);assert.throws(()=>m.validateScene({...s,nodes:[{...n,width:3000}]}),/100mm/);const moved=m.transformGroup(s,['wall'],{x:300,z:-200,rotation:45});assert.deepEqual(moved.nodes[0].openings,n.openings);assert.equal(JSON.stringify(s),before);});
await test('clone, array, assembly capture and insertion preserve parent-scoped IDs and painted faces',()=>{const o=opening({kind:'door'}),n=node({openings:[o],faces:{[`op-${o.id}-panel:4`]:'walnut'}}),s=scene(n),copy=m.cloneUngroupedNode(n);assert.deepEqual(copy.openings,n.openings);const p=m.planPlacement(s,['wall'],{type:'array',axis:'z',direction:1,count:1,gap:600});assert.deepEqual(p.scene.nodes[1].openings,n.openings);const a=m.captureAssembly(s,['wall'],'문 있는 벽'),insert=m.insertAssembly({...s,nodes:[]},a,{x:1000,y:0,z:2000,rotation:37});assert.deepEqual(insert.scene.nodes[0].openings,n.openings);assert.deepEqual(insert.scene.nodes[0].faces,n.faces);});
await test('JSON and design snapshots keep independent aperture sets and reject corrupted inactive cuts',()=>{let s=m.saveVariant(scene(),'이전');s=m.planPartitionOpenings(s,'wall',[opening()]).scene;s=m.saveVariant(s,'이후');const json=m.validateScene(JSON.parse(JSON.stringify(s)));assert.equal(m.restoreVariant(json,json.variants[0].id).nodes[0].openings,undefined);assert.deepEqual(m.restoreVariant(json,json.variants[1].id).nodes[0].openings,s.nodes[0].openings);json.variants[1].design.nodes[0].openings[0].width=9000;assert.throws(()=>m.validateScene(json),/100mm/);});
await test('floor plan and schedule show all three types with escaped names and parent-local coordinates',()=>{const n=node({width:7000,rotation:37,openings:[opening({x:-2000,name:'<door>'}),opening({kind:'door',x:0,name:'=SUM(A1)'}),opening({kind:'window',x:2000,bottom:600,height:1400})]}),s=scene(n),rows=m.planRows(s),svg=m.floorPlanSvg(s,'입면 <test>',{scale:150});assert.equal(rows.length,4);assert.equal(rows[1][0],'1.1');assert.equal(rows[1][2],'파티션 빈 통로');assert.ok(rows[3][9].includes('중심 2000mm'));assert.ok(svg.includes('rotate(-37)'));assert.ok(svg.includes('O 900')&&svg.includes('D 900')&&svg.includes('W 900'));assert.ok(svg.includes('입면 &lt;test&gt;'));assert.ok(m.floorPlanCsv(s).includes("'=SUM(A1)"));assert.ok(m.floorPlanPrintHtml(s,'안').includes('&lt;door&gt;'));});
await test('measurement points round trip on rotated cut reveals and AI context retains openings without costs',()=>{const n=node({rotation:37,x:450,z:-250,openings:[opening()]}),s=m.editEstimates(scene(n),['wall'],{unitPrice:1000}),p=world(n,450,1000,30),mm={x:p.x*1000,y:p.y*1000,z:p.z*1000},a=m.measurementAnchor(s,'wall',mm),resolved=m.resolveMeasurementAnchor(s,a);near(resolved.x,mm.x);near(resolved.y,mm.y);near(resolved.z,mm.z);const ai=m.sceneForDesignAi(s);assert.deepEqual(ai.nodes[0].openings,n.openings);assert.equal(ai.nodes[0].estimate,undefined);});
await test('actual GLB export preserves the cut mesh and opening metadata with the parent group',async()=>{const n=node({openings:[opening()]}),{e,g}=engine(n),expected=g.children[0].geometry.index.count/3,reader=globalThis.FileReader;globalThis.FileReader=class{readAsArrayBuffer(blob){blob.arrayBuffer().then(data=>{this.result=data;this.onloadend?.();});}};try{const bytes=await e.exportGlb(),view=new DataView(bytes),jsonLength=view.getUint32(12,true),json=JSON.parse(new TextDecoder().decode(new Uint8Array(bytes,20,jsonLength)));assert.equal(m.inspectGlb(bytes).triangles,expected);assert.ok(json.nodes.some(v=>v.extras?.partitionOpenings?.[0]?.id===n.openings[0].id));}finally{globalThis.FileReader=reader;dispose(g);}});
await test('untouched empty finish containers remain a true no-op and preserve confirmed prices',()=>{for(const openings of [undefined,[opening()]]){const s=m.editEstimates(scene(node({...(openings?{openings}:{}),faceFinishes:{}})),['wall'],{unitPrice:120000}),p=m.planPartitionOpenings(s,'wall',openings??[]);assert.equal(p.unchanged,true);assert.deepEqual(p.scene,s);assert.equal(m.priceNeedsReview(p.scene.nodes[0]),false);}});
await test('add can shrink a default door or window into a smaller valid remaining span',()=>{for(const kind of ['door','window']){const width=kind==='door'?300:200,bottom=kind==='window'?900:0,height=kind==='window'?1200:2100,n=node({width:1200,height:2400,openings:[opening({kind,width,bottom,height,x:-500+width/2})]}),o=m.newPartitionOpening(n,kind);assert.ok(o.width>=width&&o.width<900);m.validatePartitionOpenings({...n,openings:[...n.openings,o]});assert.ok(o.x>0);}});
await test('door handles touch their panel face and remain inside even 20mm or 500mm partitions',()=>{for(const depth of [20,120,500]){const o=opening({kind:'door'}),n=node({depth,openings:[o]}),{g}=engine(n),panel=g.children.find(c=>c.userData.part===`op-${o.id}-panel`),handle=g.children.find(c=>c.userData.part===`op-${o.id}-handle`),pb=new T.Box3().setFromObject(panel),hb=new T.Box3().setFromObject(handle);near(hb.min.z,pb.max.z);assert.ok(hb.max.z<=depth/2000+1e-6);dispose(g);}});
await test('plan aperture symbols leave overlapping furniture visible without opaque white erasing',()=>{const n=node({openings:[opening()]}),s=scene(n);s.nodes.unshift({...m.createNode('box','obstacle'),color:'#123456'});const svg=m.floorPlanSvg(s,'gap',{labels:false,dimensions:false});assert.equal((svg.match(/<rect[^>]*fill="white"/g)??[]).length,1);assert.ok(svg.includes('fill="#123456"'));});
console.log(`${checks} partition-opening checks passed.`);
