import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {build} from 'esbuild';

// Exercise the complete application route chain. Only user identity, R2 I/O and
// external AI transport are fixtures; all migrations, SQL and app logic are real.
const sql=new DatabaseSync(':memory:');
for(const file of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+file,'utf8'));
const objects=new Map();let user='workflow-owner',providerCalls=0;
globalThis.__photoWorkflowUser=()=>user?{userId:user}:null;
globalThis.__photoWorkflowEnv={
 DB:{prepare(query){
  const statement=sql.prepare(query);
  return {bind(...args){return {
   async first(){return statement.get(...args)??null},
   async all(){return {results:statement.all(...args)}},
   async run(){return {meta:{changes:statement.run(...args).changes}}}
  }}};
 }},
 BUCKET:{async put(key,bytes,options){objects.set(key,{bytes,options})},async get(key){const o=objects.get(key);return o?{body:o.bytes}:null},async delete(key){objects.delete(key)}}
};
const bundle=await build({stdin:{contents:"export {POST as upload} from './app/api/images/route';export {GET as readAsset} from './app/api/assets/route';export {POST as analyze} from './app/api/object-photo/route';export {POST as save,GET as load} from './app/api/projects/route';export {POST as saveSet,GET as loadSet} from './app/api/assemblies/route';export * from './lib/object-photo';export * from './lib/scene-model';export * from './lib/material-products';export * from './lib/design-variants';export * from './lib/assemblies';export {planRows,surfaceRows} from './lib/floor-plan';",resolveDir:process.cwd()},bundle:true,platform:'node',format:'esm',write:false,plugins:[{name:'workflow-boundaries',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'env',namespace:'stub'}));b.onResolve({filter:/chatgpt-auth$/},()=>({path:'auth',namespace:'stub'}));b.onLoad({filter:/.*/,namespace:'stub'},a=>({contents:a.path==='env'?'export const env=globalThis.__photoWorkflowEnv':'export async function getChatGPTUser(){return globalThis.__photoWorkflowUser()}'}))}}]});
const m=await import('data:text/javascript;base64,'+Buffer.from(bundle.outputFiles[0].text).toString('base64'));
const origin='https://workflow.test',request=(path,body)=>new Request(origin+path,body===undefined?{}:{method:'POST',headers:{origin,'Content-Type':'application/json'},body:JSON.stringify(body)});
const part=(name,x,y,z,width,height,depth)=>({shape:'box',name,x,y,z,width,height,depth,material:'oak',color:'#a08060'});
const analysis={kind:'table',name:'사진 부품 테이블',material:'oak',color:'#a08060',notes:['시험용 응답 · 정밀 스캔 아님'],parts:[part('상판',0,.9,0,1,.1,1),...[-.4,.4].flatMap(x=>[-.4,.4].map(z=>part('다리',x,0,z,.1,.9,.1)))]};
const originalFetch=globalThis.fetch;
globalThis.fetch=async(url,init)=>{assert.equal(url,'https://api.openai.com/v1/responses');providerCalls++;const sent=JSON.parse(init.body);assert.match(sent.input[0].content[1].image_url,/^data:image\/png;base64,/);return Response.json({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify(analysis)}]}]})};
let checks=0,imageId,scene,created,project,setId;
async function test(name,fn){await fn();checks++;console.log('PASS '+name)}
try{
await test('upload persists image bytes and metadata with an owner-scoped object key',async()=>{const png=readFileSync('tests/fixtures/material.png'),res=await m.upload(new Request(origin+'/api/images?name=workflow-reference.png',{method:'POST',headers:{origin,'Content-Type':'image/png'},body:png}));assert.equal(res.status,200);imageId=(await res.json()).id;const row=sql.prepare('SELECT * FROM assets WHERE id=?').get(imageId);assert.equal(row.owner,user);assert.equal(row.kind,'image');assert.deepEqual(Buffer.from(objects.get(row.object_key).bytes),png);assert.equal((await m.readAsset(request('/api/assets?id='+imageId))).status,200)});
await test('missing AI key preserves the uploaded reference and supports manual furniture',async()=>{assert.equal((await m.analyze(request('/api/object-photo',{imageId}))).status,503);assert.equal(providerCalls,0);const base={...m.initialScene(),nodes:[]};created=m.createPhotoObject(base,{kind:'table',name:'수동 참고 가구',width:1200,depth:700,height:750,material:'oak',color:'#a08060',photo:{imageId,representation:'parametric',analysis:'manual',dimensions:'entered'}});assert.equal(created.nodes.length,1);assert.equal(objects.size,1)});
await test('owned photo analysis becomes five editable parts using unchanged entered dimensions',async()=>{const res=await m.analyze(request('/api/object-photo',{imageId,apiKey:'test-only-key'}));assert.equal(res.status,200);const result=(await res.json()).analysis;created=m.createPhotoObject({...m.initialScene(),nodes:[]},{...result,width:1200,depth:700,height:750,photo:{imageId,representation:'parts',analysis:'ai',dimensions:'measured'}});assert.equal(created.nodes.length,5);assert.equal(new Set(created.nodes.map(n=>n.group.id)).size,1);assert.deepEqual(created.nodes[0].objectPhoto.sourceSize,{width:1200,height:750,depth:700});assert.equal(providerCalls,1);scene=created.scene});
await test('manufacturer finish and photo parts survive project save and actual SQL reload',async()=>{const p=m.materialProduct('lx-benif-pw132');scene=m.editAppearance(scene,{id:'floor'},{material:p.base,finish:m.productFinish(p)},'face');scene=m.editAppearance(scene,{id:created.ids[0],face:'body:0'},{material:p.base,finish:m.productFinish(p)},'face');scene=m.saveVariant(scene,'사진 시안');const res=await m.save(request('/api/projects',{scene,revision:0}));assert.equal(res.status,200);project=await res.json();const loaded=await m.load(request('/api/projects?id='+project.id));assert.equal(loaded.status,200);const saved=await loaded.json();assert.deepEqual(saved.scene,scene);assert.ok(m.planRows(saved.scene)[0][7].includes('PW132'));assert.ok(m.surfaceRows(saved.scene).some(row=>row[1].includes('PW132')));assert.equal(saved.scene.variants[0].design.nodes[0].objectPhoto.imageId,imageId)});
await test('saved furniture set retains the photograph and creates an independent group',async()=>{setId=crypto.randomUUID();const assembly=m.captureAssembly(scene,created.ids,'사진 테이블 세트');assert.equal((await m.saveSet(request('/api/assemblies',{id:setId,assembly}))).status,200);const loaded=await (await m.loadSet(request('/api/assemblies?id='+setId))).json();const inserted=m.insertAssembly({...scene,nodes:[]},loaded.assembly,{x:0,y:0,z:0,rotation:90});assert.equal(inserted.ids.length,5);assert.notEqual(inserted.scene.nodes[0].group.id,created.nodes[0].group.id);assert.deepEqual(m.imageReferences(inserted.scene),[imageId])});
await test('stale project revisions cannot overwrite the stored photo furniture',async()=>{const changed={...scene,name:'검증 수정'};assert.equal((await m.save(request('/api/projects',{id:project.id,revision:1,scene:changed}))).status,200);assert.equal((await m.save(request('/api/projects',{id:project.id,revision:1,scene}))).status,409);const current=await (await m.load(request('/api/projects?id='+project.id))).json();assert.equal(current.revision,2);assert.equal(current.scene.name,'검증 수정')});
await test('another account cannot read, analyze, save or reuse the private photograph',async()=>{user='other-owner';const calls=providerCalls;assert.equal((await m.readAsset(request('/api/assets?id='+imageId))).status,404);assert.equal((await m.load(request('/api/projects?id='+project.id))).status,404);assert.equal((await m.loadSet(request('/api/assemblies?id='+setId))).status,404);assert.equal((await m.analyze(request('/api/object-photo',{imageId,apiKey:'test-only-key'}))).status,404);assert.equal((await m.save(request('/api/projects',{scene,revision:0}))).status,400);assert.equal(providerCalls,calls);assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM projects').get().n,1);user='workflow-owner'});
await test('reference ownership remains enforced when the photograph exists only in an inactive design',async()=>{const archived={...scene,nodes:[]};sql.prepare('UPDATE assets SET owner=? WHERE id=?').run('other-owner',imageId);assert.equal((await m.save(request('/api/projects',{scene:archived,revision:0}))).status,400);sql.prepare('UPDATE assets SET owner=? WHERE id=?').run(user,imageId);assert.equal((await m.save(request('/api/projects',{scene:archived,revision:0}))).status,200)});
console.log(`${checks} photo workflow integration checks passed. Real migrations/SQLite/app routes; mocked identity, bucket and AI transport. No production user data was changed.`);
}finally{globalThis.fetch=originalFetch;delete globalThis.__photoWorkflowEnv;delete globalThis.__photoWorkflowUser;sql.close()}
