import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {build} from 'esbuild';
let database,puts=0,fetches=0,denyClaim=false,denyAssetInsert=false,commitThenThrow=false,denyRead=false,denyPut=false,lastRequest;
const objects=new Map();let initialReadBarrier=null,claimConflicts=0;
globalThis.__user={userId:'owner-a'};
globalThis.__env={BUCKET:{put:async(k,v)=>{if(denyPut)throw new Error('bucket failure');objects.set(k,v);puts++},delete:async keys=>{for(const k of Array.isArray(keys)?keys:[keys])objects.delete(k)}},DB:{prepare(sql){return{bind(...args){return{async first(){if(denyRead&&sql.includes('FROM assets'))throw new Error('read failure');const row=database.prepare(sql).get(...args)??null;if(initialReadBarrier&&sql.includes('FROM render_requests'))await initialReadBarrier();return row},async run(){if(denyClaim&&sql.startsWith('INSERT INTO render_requests'))throw new Error('claim failure');if(denyAssetInsert&&sql.startsWith('INSERT INTO assets'))throw new Error('insert failure');const result=database.prepare(sql).run(...args);if(sql.startsWith('INSERT INTO render_requests')&&!result.changes)claimConflicts++;if(commitThenThrow&&sql.startsWith('INSERT INTO assets'))throw new Error('insert response lost');return{meta:{changes:Number(result.changes)}}},async all(){return{results:database.prepare(sql).all(...args)}}}}}}}};
const r=await build({entryPoints:['app/api/render/route.ts'],bundle:true,platform:'node',format:'esm',write:false,plugins:[{name:'runtime',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'env',namespace:'stub'}));b.onResolve({filter:/chatgpt-auth$/},()=>({path:'auth',namespace:'stub'}));b.onLoad({filter:/.*/,namespace:'stub'},a=>({contents:a.path==='env'?'export const env=globalThis.__env':'export async function getChatGPTUser(){return globalThis.__user}'}))}}]});
const {POST}=await import('data:text/javascript;base64,'+Buffer.from(r.outputFiles[0].text).toString('base64'));
const image='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jWZkAAAAASUVORK5CYII=';
const jpeg=Buffer.from([255,216,255,224,0,2,255,217]).toString('base64');
const base={requestId:'c872092a-5cb3-40b4-bc20-712ed1c54c61',name:'test scene',prompt:'따뜻한 우드',quality:'medium',image,reference:image,apiKey:'test-only-key'};
const req=(b=base,origin='https://test.local')=>new Request('https://test.local/api/render',{method:'POST',headers:{origin,'Content-Type':'application/json'},body:JSON.stringify(b)});
const oldFetch=globalThis.fetch,oldError=console.error;let checks=0;
const output=()=>Response.json({data:[{b64_json:jpeg}]});
function provider(data={data:[{b64_json:jpeg}]},status=200){globalThis.fetch=async(url,init)=>{fetches++;assert.equal(url,'https://api.openai.com/v1/images/edits');lastRequest=JSON.parse(init.body);return Response.json(data,{status})}}
async function test(name,fn){database?.close();database=new DatabaseSync(':memory:');for(const file of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())database.exec(readFileSync('drizzle/'+file,'utf8'));objects.clear();puts=fetches=claimConflicts=0;initialReadBarrier=null;denyClaim=denyAssetInsert=commitThenThrow=denyRead=denyPut=false;globalThis.__user={userId:'owner-a'};provider();await fn();checks++;console.log('PASS '+name)}
const asset=()=>database.prepare('SELECT * FROM assets WHERE id=?').get(base.requestId);
try{
console.error=()=>{};
await test('render saves output and source with explicit layout/reference roles',async()=>{const res=await POST(req());assert.equal(res.status,200);const {result}=await res.json();assert.equal(result.id,base.requestId);assert.equal(puts,2);assert.equal(lastRequest.images.length,2);assert.ok(lastRequest.prompt.includes('authoritative 3D layout'));assert.equal(lastRequest.output_format,'jpeg');assert.equal(lastRequest.size,'1536x1024');assert.equal(lastRequest.quality,'medium');assert.equal(asset().owner,'owner-a');assert.ok(objects.has(JSON.parse(asset().metadata).sourceKey))});
await test('exterior retains facade and literal sign instructions',async()=>{assert.equal((await POST(req({...base,view:'exterior',signText:'OFD & CO.'}))).status,200);assert.ok(lastRequest.prompt.includes('exterior storefront facade'));assert.ok(lastRequest.prompt.includes('"OFD & CO."'))});
await test('saved result is reused after response loss or key removal',async()=>{const input={...base,reference:undefined};assert.equal((await POST(req(input))).status,200);assert.equal(lastRequest.images.length,1);assert.equal((await POST(req({...input,apiKey:undefined,view:'interior'}))).status,200);assert.equal(fetches,1)});
await test('changed payload with same request ID is rejected',async()=>{assert.equal((await POST(req())).status,200);for(const change of [{prompt:'new'},{reference:undefined},{quality:'high'},{name:'changed'},{view:'exterior'}])assert.equal((await POST(req({...base,...change}))).status,409);assert.equal(fetches,1)});
await test('claim permits only one concurrent provider call',async()=>{let release,entered;const started=new Promise(r=>entered=r);globalThis.fetch=async()=>{fetches++;entered();return new Promise(r=>release=()=>r(output()))};const first=POST(req());await started;assert.equal((await POST(req())).status,409);assert.equal(fetches,1);release();assert.equal((await first).status,200);assert.equal((await POST(req())).status,200);assert.equal(fetches,1)});
await test('simultaneous empty reads still admit only one atomic claim',async()=>{let releaseRead,reads=0,releaseProvider,entered;const readGate=new Promise(r=>releaseRead=r),started=new Promise(r=>entered=r);initialReadBarrier=async()=>{if(++reads===2){initialReadBarrier=null;releaseRead()}await readGate};globalThis.fetch=async()=>{fetches++;entered();return new Promise(r=>releaseProvider=()=>r(output()))};const first=POST(req()),second=POST(req());await started;assert.equal((await Promise.race([first,second])).status,409);assert.equal(claimConflicts,1);assert.equal(fetches,1);releaseProvider();assert.deepEqual((await Promise.all([first,second])).map(r=>r.status).sort(),[200,409])});
await test('auth, origin, key and input validation occur before generation',async()=>{globalThis.__user=null;assert.equal((await POST(req())).status,401);globalThis.__user={userId:'owner-a'};assert.equal((await POST(req(base,'https://other.local'))).status,403);assert.equal((await POST(req({...base,apiKey:undefined}))).status,503);assert.equal((await POST(req({...base,image:'data:image/png;base64,AAAA'}))).status,400);assert.equal((await POST(req({...base,image:'x'.repeat(2800001)}))).status,400);assert.equal(fetches,0);assert.equal(database.prepare('SELECT count(*) AS n FROM render_requests').get().n,0)});
await test('another owner cannot recover or reuse a request ID',async()=>{assert.equal((await POST(req())).status,200);globalThis.__user={userId:'owner-b'};const response=await POST(req());assert.equal(response.status,409);assert.equal((await response.json()).result,undefined);assert.equal(fetches,1)});
await test('provider access/quota/moderation/output errors retain claims',async()=>{for(const [status,expected,body] of [[401,401,{}],[403,403,{}],[404,403,{}],[429,429,{}],[400,422,{error:{code:'moderation_blocked'}}],[500,502,{}],[200,502,{data:[]}],[200,502,{data:[{b64_json:'AAAA'}]}]]){const input={...base,requestId:crypto.randomUUID()};provider(body,status);const before=fetches;assert.equal((await POST(req(input))).status,expected);assert.equal((await POST(req(input))).status,409);assert.equal(fetches,before+1)}assert.equal(puts,0)});
await test('claim write failure prevents provider call',async()=>{denyClaim=true;assert.equal((await POST(req())).status,500);assert.equal(fetches,0)});
await test('asset write failure cleans its files and never regenerates on retry',async()=>{denyAssetInsert=true;objects.set('existing-render',new Uint8Array([1]));assert.equal((await POST(req())).status,500);denyAssetInsert=false;assert.equal((await POST(req())).status,409);assert.equal(fetches,1);assert.equal(objects.size,1);assert.ok(objects.has('existing-render'))});
await test('R2 failure never regenerates on retry',async()=>{denyPut=true;assert.equal((await POST(req())).status,500);denyPut=false;assert.equal((await POST(req())).status,409);assert.equal(fetches,1)});
await test('committed asset with lost INSERT response recovers without deleting output',async()=>{commitThenThrow=true;assert.equal((await POST(req())).status,200);assert.equal(objects.size,2);assert.equal((await POST(req())).status,200);assert.equal(fetches,1)});
await test('unavailable database after generation preserves output until outcome is known',async()=>{globalThis.fetch=async()=>{fetches++;denyAssetInsert=true;denyRead=true;return output()};assert.equal((await POST(req())).status,500);assert.equal(objects.size,2);denyRead=denyAssetInsert=false;assert.equal((await POST(req())).status,409);assert.equal(fetches,1)});
await test('timeout retains claim and never performs paid retry',async()=>{globalThis.fetch=async()=>{fetches++;throw new DOMException('timeout','TimeoutError')};const res=await POST(req());assert.equal(res.status,504);assert.equal((await res.json()).requestState,'uncertain');assert.equal((await POST(req())).status,409);assert.equal(fetches,1);assert.equal(puts,0)});
await test('deleted generated asset is not silently generated again',async()=>{assert.equal((await POST(req())).status,200);database.prepare('DELETE FROM assets WHERE id=?').run(base.requestId);assert.equal((await POST(req())).status,409);assert.equal(fetches,1)});
console.log(`${checks} render API checks passed using migrated SQLite and a mocked AI provider. No paid AI call was made.`);
}finally{database?.close();console.error=oldError;globalThis.fetch=oldFetch;delete globalThis.__env;delete globalThis.__user}
