import assert from 'node:assert/strict';
import {build} from 'esbuild';
const records=new Map(),objects=new Map();let puts=0,fetches=0,denyInsert=false,lastRequest,priorId=null;
globalThis.__user={userId:'owner-a'};
globalThis.__env={BUCKET:{put:async(k,v)=>{objects.set(k,v);puts++},delete:async keys=>{for(const k of Array.isArray(keys)?keys:[keys])objects.delete(k)},get:async k=>objects.has(k)?{body:objects.get(k)}:null},DB:{prepare(sql){return{bind(...args){return{async first(){if(sql.includes('FROM assets'))return priorId&&args[0]===priorId&&args[1]==='owner-a'?records.get(priorId):null;return null},async run(){if(denyInsert)throw new Error('database failure');if(sql.startsWith('INSERT INTO assets'))records.set(args[0],{id:args[0],owner:args[1],kind:args[2],object_key:args[3],mime:args[4],name:args[5],metadata:args[6],created_at:args[7]});return{meta:{changes:1}}},async all(){return{results:[]}}}}}}}};
const r=await build({entryPoints:['app/api/render/route.ts'],bundle:true,platform:'node',format:'esm',write:false,plugins:[{name:'runtime',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'env',namespace:'stub'}));b.onResolve({filter:/chatgpt-auth$/},()=>({path:'auth',namespace:'stub'}));b.onLoad({filter:/.*/,namespace:'stub'},a=>({contents:a.path==='env'?'export const env=globalThis.__env':'export async function getChatGPTUser(){return globalThis.__user}'}))}}]});const {POST}=await import('data:text/javascript;base64,'+Buffer.from(r.outputFiles[0].text).toString('base64'));
const image='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jWZkAAAAASUVORK5CYII=';
const jpeg=Buffer.from([255,216,255,224,0,2,255,217]).toString('base64');
const base={requestId:'c872092a-5cb3-40b4-bc20-712ed1c54c61',name:'test scene',prompt:'따뜻한 우드',quality:'medium',image,reference:image,apiKey:'test-only-key'};
const req=(b=base,origin='https://test.local')=>new Request('https://test.local/api/render',{method:'POST',headers:{origin,'Content-Type':'application/json'},body:JSON.stringify(b)});
const oldFetch=globalThis.fetch;let checks=0;
function provider(data={data:[{b64_json:jpeg}]},status=200){globalThis.fetch=async(url,init)=>{fetches++;assert.equal(url,'https://api.openai.com/v1/images/edits');lastRequest=JSON.parse(init.body);return Response.json(data,{status})}}
async function test(name,fn){records.clear();objects.clear();puts=0;fetches=0;priorId=null;denyInsert=false;provider();await fn();checks++;console.log('PASS '+name)}
try{
await test('render sends explicit layout and reference roles and saves output plus source',async()=>{const res=await POST(req());assert.equal(res.status,200);const {result}=await res.json();assert.equal(result.id,base.requestId);assert.equal(puts,2);assert.equal(lastRequest.images.length,2);assert.equal(lastRequest.images[0].image_url,image);assert.ok(lastRequest.prompt.includes('authoritative 3D layout'));assert.equal(lastRequest.output_format,'jpeg');assert.equal(lastRequest.size,'1536x1024');assert.equal(lastRequest.quality,'medium');assert.equal(lastRequest.store,undefined);const row=records.get(result.id);assert.equal(row.owner,'owner-a');assert.equal(row.kind,'render');assert.ok(objects.has(JSON.parse(row.metadata).sourceKey))});
await test('no-reference variant sends one image and saved request reuse is free',async()=>{let res=await POST(req({...base,reference:undefined}));assert.equal(res.status,200);assert.equal(lastRequest.images.length,1);priorId=base.requestId;res=await POST(req());assert.equal(res.status,200);assert.equal(fetches,1)});
await test('auth, origin, missing key, malformed and oversize inputs fail before AI',async()=>{globalThis.__user=null;assert.equal((await POST(req())).status,401);globalThis.__user={userId:'owner-a'};assert.equal((await POST(req(base,'https://other.local'))).status,403);assert.equal((await POST(req({...base,apiKey:undefined}))).status,503);assert.equal((await POST(req({...base,image:'data:image/png;base64,AAAA'}))).status,400);assert.equal((await POST(req({...base,image:'x'.repeat(2800001)}))).status,400);assert.equal(fetches,0)});
await test('API access, quota, moderation and missing output have explicit failures',async()=>{for(const [status,expected,body] of [[401,401,{}],[403,403,{}],[404,403,{}],[429,429,{}],[400,422,{error:{code:'moderation_blocked'}}],[500,502,{}],[200,502,{data:[]}]]){provider(body,status);assert.equal((await POST(req())).status,expected)}assert.equal(puts,0)});
await test('storage failure cleans only this attempt and retains existing objects',async()=>{denyInsert=true;objects.set('existing-render',new Uint8Array([1]));const oldError=console.error;console.error=()=>{};try{assert.equal((await POST(req())).status,500)}finally{console.error=oldError}assert.equal(objects.size,1);assert.ok(objects.has('existing-render'))});
await test('timeout neither retries nor pretends to have saved output',async()=>{globalThis.fetch=async()=>{fetches++;throw new DOMException('timeout','TimeoutError')};const res=await POST(req());assert.equal(res.status,504);assert.equal(fetches,1);assert.equal(puts,0)});
console.log(`${checks} mocked render API checks passed. No paid AI call was made.`);
}finally{globalThis.fetch=oldFetch;delete globalThis.__env;delete globalThis.__user}
