import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {mkdtemp,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
const dir=await mkdtemp(join(tmpdir(),'spatial-scene-search-')),file=join(dir,'bundle.mjs');
const bundle=await build({stdin:{contents:"export * from './lib/scene-model';export * from './lib/scene-search';export * from './lib/selection';",resolveDir:process.cwd()},bundle:true,platform:'node',format:'esm',write:false});
await writeFile(file,bundle.outputFiles[0].text);const m=await import(pathToFileURL(file));await rm(dir,{recursive:true,force:true});
let checks=0;function test(name,fn){fn();checks++;console.log('PASS '+name);}
const uuid=()=>crypto.randomUUID();
function fixture(){let s=m.initialScene();const kitchen=uuid(),seats=uuid();s={...s,layers:[{id:kitchen,name:'주방 설비',color:'#123456'},{id:seats,name:'고객 좌석',color:'#abcdef'}],nodes:[{...m.createNode('counter','counter'),name:'OFD 카운터 01',layerId:kitchen},{...m.createNode('chair','chair'),name:'창가 의자',layerId:seats},{...m.createNode('table','table'),name:'창가 테이블',layerId:seats},{...m.createNode('shelf','shelf'),name:'Hidden Shelf',hidden:true},{...m.createNode('box','locked'),name:'LOCKED BOX',locked:true}]};return m.createGroup(s,['chair','table'],'창가 2인 세트');}
const ids=(result)=>result.rows.flatMap(row=>row.ids);
test('Korean whitespace full-width Latin and English case normalize consistently',()=>{assert.equal(m.normalizeSceneQuery(' ＯＦＤ  카 운 터\t０１ '),'ofd카운터01');const s=fixture();for(const query of ['ofd 카운터01','ＯＦＤ　카운터 ０１','ＯＦＤ카운터０１','카 운 터'])assert.deepEqual(ids(m.searchScene(s,{query})),['counter']);});
test('decomposed Hangul is normalized to searchable composed names',()=>{const s=fixture();assert.deepEqual(ids(m.searchScene(s,{query:'창가'.normalize('NFD')})),['chair','table']);});
test('multiple search words match across name layer and Korean or English kind fields',()=>{const s=fixture();for(const query of ['주방 카운터','설비 OFD','COUNTER 01'])assert.deepEqual(ids(m.searchScene(s,{query})),['counter']);assert.deepEqual(ids(m.searchScene(s,{query:'좌석 다이닝 체어'})),['chair']);assert.deepEqual(ids(m.searchScene(s,{query:'주방 의자'})),[]);});
test('group names match their individual members and group results appear only once',()=>{const s=fixture(),elements=m.searchScene(s,{query:'2인세트'}),groups=m.searchScene(s,{query:'2인 세트',mode:'groups'});assert.deepEqual(ids(elements),['chair','table']);assert.equal(groups.rows.length,1);assert.deepEqual(groups.rows[0].ids,['chair','table']);assert.equal(groups.rows[0].name,'창가 2인 세트');assert.equal(groups.total,1);assert.ok(elements.rows.every(row=>row.groupName==='창가 2인 세트'));});
test('group search matches member names and multiple member kinds without duplicate rows',()=>{const s=fixture();for(const query of ['테이블','의자 테이블','고객좌석','TABLE CHAIR']){const found=m.searchScene(s,{query,mode:'groups'});assert.equal(found.total,1);assert.deepEqual(found.rows[0].ids,['chair','table']);}});
test('unassigned layer is searchable and returned as a visible badge value',()=>{const s=fixture(),result=m.searchScene(s,{query:'미 분 류'});assert.deepEqual(ids(result),['shelf','locked']);assert.ok(result.rows.every(row=>row.layers[0]==='미분류'));});
test('status filters distinguish hidden results while allowing locked visible selections',()=>{const s=fixture();assert.deepEqual(ids(m.searchScene(s,{filter:'visible'})),['counter','chair','table','locked']);const hidden=m.searchScene(s,{filter:'hidden'});assert.deepEqual(ids(hidden),['shelf']);assert.equal(hidden.rows[0].disabled,true);const locked=m.searchScene(s,{filter:'locked'});assert.deepEqual(ids(locked),['locked']);assert.equal(locked.rows[0].locked,1);assert.equal(locked.rows[0].disabled,false);});
test('partially hidden groups are disabled and hidden while their visible individual remains selectable',()=>{const s=fixture();s.nodes.find(n=>n.id==='table').hidden=true;s.nodes.find(n=>n.id==='chair').locked=true;const group=m.searchScene(s,{mode:'groups'}).rows[0];assert.equal(group.hidden,1);assert.equal(group.locked,1);assert.equal(group.disabled,true);assert.deepEqual(group.ids,['chair','table']);assert.equal(m.searchScene(s,{mode:'groups',filter:'visible'}).rows.length,0);assert.equal(m.searchScene(s,{mode:'groups',filter:'hidden'}).rows.length,1);assert.equal(m.searchScene(s,{mode:'groups',filter:'locked'}).rows.length,1);const individual=m.searchScene(s,{query:'창가 의자'}).rows[0];assert.deepEqual(individual.ids,['chair']);assert.equal(individual.disabled,false);});
test('fully visible locked groups can be selected without unlocking any members',()=>{const s=fixture();for(const n of s.nodes.filter(n=>n.group))n.locked=true;const before=JSON.stringify(s),row=m.searchScene(s,{mode:'groups',filter:'locked'}).rows[0];assert.equal(row.disabled,false);assert.equal(row.locked,2);assert.equal(JSON.stringify(s),before);});
test('exact and prefix names rank before metadata matches with stable scene order',()=>{const s=fixture();s.nodes.unshift({...m.createNode('box','prefix'),name:'Counter Front'},{...m.createNode('box','exact'),name:'ＣＯＵＮＴＥＲ'});assert.deepEqual(ids(m.searchScene(s,{query:'counter'})),['exact','prefix','counter']);assert.deepEqual(ids(m.searchScene(s,{query:'   '})),s.nodes.map(n=>n.id));});
test('results have unique keys even if group and node identifiers or display names overlap',()=>{const s=fixture(),groupId=s.nodes.find(n=>n.group).group.id;s.nodes.push({...m.createNode('box',groupId),name:'창가 2인 세트'});const elements=m.searchScene(s),groups=m.searchScene(s,{mode:'groups'});assert.equal(new Set(elements.rows.map(row=>row.key)).size,elements.rows.length);assert.notEqual(elements.rows.find(row=>row.ids[0]===groupId).key,groups.rows[0].key);});
test('empty names and empty scenes give useful labels without inventing groups',()=>{const s=fixture();s.nodes=[{...m.createNode('box','unnamed'),name:''}];assert.equal(m.searchScene(s).rows[0].name,'이름 없는 요소');assert.equal(m.searchScene(s,{mode:'groups'}).total,0);s.nodes=[];assert.deepEqual(m.searchScene(s),{rows:[],total:0,truncated:false});});
test('maximum 300 rows keeps totals and applies limits only after matching',()=>{const s=fixture();s.nodes=Array.from({length:305},(_,i)=>({...m.createNode('box',String(i)),name:`요소 ${i}`}));const full=m.searchScene(s,{limit:1000});assert.equal(full.rows.length,300);assert.equal(full.total,305);assert.equal(full.truncated,true);assert.deepEqual(ids(m.searchScene(s,{query:'요소304'})),['304']);const limited=m.searchScene(s,{limit:12.9});assert.equal(limited.rows.length,12);assert.equal(limited.total,305);assert.equal(m.searchScene(s,{limit:NaN}).rows.length,300);});
test('searching never mutates source or returns mutable references to source IDs and names',()=>{const s=fixture(),before=JSON.stringify(s),result=m.searchScene(s,{mode:'groups'});result.rows[0].ids.push('different');result.rows[0].layers[0]='changed';result.rows[0].name='changed';assert.equal(JSON.stringify(s),before);});
test('combined hidden and locked states remain filterable without treating lock as invisibility',()=>{const s=fixture();s.nodes.find(n=>n.id==='shelf').locked=true;const locked=m.searchScene(s,{filter:'locked'});assert.equal(locked.total,2);assert.equal(locked.rows.find(row=>row.ids[0]==='shelf').disabled,true);assert.equal(locked.rows.find(row=>row.ids[0]==='locked').disabled,false);assert.deepEqual(ids(m.searchScene(s,{filter:'visible',query:'shelf'})),[]);});
console.log(`${checks} scene-search checks passed.`);
