import assert from 'node:assert/strict';
import { build } from 'esbuild';
import { readFile,rm } from 'node:fs/promises';
import * as THREE from 'three';
const result=await build({entryPoints:['lib/scene-model.ts'],bundle:true,platform:'node',format:'esm',write:false});
const model=await import('data:text/javascript;base64,'+Buffer.from(result.outputFiles[0].text).toString('base64'));
const {initialScene,validateScene,createNode,applyCommands,quickCommands}=model;
let tests=0;const check=(name,fn)=>{fn();tests++;console.log('PASS '+name)};
check('default store scene fits declared dimensions',()=>validateScene(initialScene()));
check('dimensions and logical face materials survive save/load',()=>{const s=initialScene();s.nodes[0].width=2400;s.nodes[0].faces['top:2']='walnut';const loaded=validateScene(JSON.parse(JSON.stringify(s)));assert.equal(loaded.nodes[0].width,2400);assert.equal(loaded.nodes[0].faces['top:2'],'walnut')});
check('wall material changes are shared across views without changing geometry',()=>{const s=initialScene(),n=applyCommands(s,[{type:'material',target:'walls',material:'oak'}]);assert.equal(n.room.surfaces.back.material,'oak');assert.equal(n.room.surfaces.right.material,'oak');assert.deepEqual(n.nodes,s.nodes);assert.equal(s.room.surfaces.back.material,'plaster')});
check('locked object rejects entire AI transaction',()=>{const s=initialScene();s.nodes[0].locked=true;const before=JSON.stringify(s);assert.throws(()=>applyCommands(s,[{type:'material',target:'walls',material:'oak'},{type:'resize',target:'counter',axis:'width',value:1000}]),/잠겨/);assert.equal(JSON.stringify(s),before)});
check('openings cannot extend outside host wall',()=>{const s=initialScene();s.nodes.find(n=>n.kind==='door').width=20000;assert.throws(()=>validateScene(s),/벽 범위/)});
check('overlapping openings are rejected',()=>{const s=initialScene();const door={...s.nodes.find(n=>n.kind==='door'),id:'other-door'};s.nodes.push(door);assert.throws(()=>validateScene(s),/겹칩니다/)});
check('hosted rotation and off-wall moves cannot silently succeed',()=>{const s=initialScene();assert.throws(()=>applyCommands(s,[{type:'rotate',target:'door-front',value:45}]),/회전/);assert.throws(()=>applyCommands(s,[{type:'move',target:'door-front',axis:'z',value:250}]),/문·창문/)});
check('rotated footprint must remain within room',()=>{const s=initialScene();const n=createNode('box','edge',3400,0);n.width=300;n.depth=2000;n.rotation=90;s.nodes.push(n);assert.throws(()=>validateScene(s),/바닥 경계/)});
check('invalid sizes, IDs and unsupported commands are rejected',()=>{const s=initialScene();s.nodes.push({...s.nodes[0]});assert.throws(()=>validateScene(s),/중복/);assert.throws(()=>applyCommands(initialScene(),[{type:'execute',code:'alert(1)'}]));assert.throws(()=>applyCommands(initialScene(),[{type:'resize',target:'chair-0',axis:'height',value:20}]),/최소/)});
check('basic Korean command maps to bounded edit',()=>{assert.deepEqual(quickCommands('테이블 3개 추가',null),[{type:'add',kind:'table',count:3}]);assert.deepEqual(quickCommands('높이를 50cm로',{id:'counter'}),[{type:'resize',target:'counter',axis:'height',value:500}]);assert.equal(quickCommands('복잡한 천장 만들어줘',null),null)});
check('yaw survives rotations beyond 90 degrees',()=>{for(const angle of [-170,-120,45,120,179]){const q=new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0,1,0),angle*Math.PI/180);const yaw=Math.round(Math.atan2(2*(q.w*q.y+q.x*q.z),1-2*(q.y*q.y+q.z*q.z))*180/Math.PI);assert.equal(yaw,angle)}});
check('new empty store remains editable',()=>{const s=initialScene();s.nodes=[];const box=createNode('box','sketch',0,0);box.width=2400;box.depth=1200;box.height=100;s.nodes=[box];validateScene(s);const extruded=applyCommands(s,[{type:'resize',target:'sketch',axis:'height',value:1200}]);assert.equal(extruded.nodes[0].height,1200)});
console.log(`${tests} core checks passed.`);
