import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {mkdtemp,writeFile,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';import {join} from 'node:path';import {pathToFileURL} from 'node:url';
const dir=await mkdtemp(join(tmpdir(),'spatial-selection-export-')),file=join(dir,'bundle.mjs');
const bundle=await build({stdin:{contents:"export * as T from 'three';export {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';export {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';export * from './lib/selection-export';export * from './lib/scene-model';export * from './lib/scene-engine';export * from './lib/selection';export * from './lib/image-textures';",resolveDir:process.cwd()},bundle:true,platform:'node',format:'esm',write:false});await writeFile(file,bundle.outputFiles[0].text);const m=await import(pathToFileURL(file));await rm(dir,{recursive:true,force:true});
const {T}=m;let checks=0;async function test(name,fn){await fn();checks++;console.log('PASS '+name);}
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`),nearArray=(a,b)=>a.forEach((v,i)=>near(v,b[i]));
const empty=()=>({...m.initialScene(),nodes:[]}),pair=()=>({...empty(),nodes:[{...m.createNode('chair','a',-1700,900),rotation:37,y:100},{...m.createNode('box','b',1600,-1000),rotation:-22,y:200},m.createNode('box','unselected',2600,1600)]});
function engine(s){const e=Object.create(m.SceneEngine.prototype);Object.assign(e,{root:new T.Group(),data:s,material(){return new T.MeshStandardMaterial();}});for(const n of s.nodes)e.buildNode(n);return e;}
function dispose(root){m.SceneEngine.prototype.clearGroup.call({disposeMaterial:m.SceneEngine.prototype.disposeMaterial},root);}
function find(root,id){let found;root.traverse(o=>{if(!found&&o.userData.nodeId===id)found=o;});return found;}
function box(root){root.updateMatrixWorld(true);return new T.Box3().setFromObject(root);}
function fingerprint(root){const rows=[];root.traverse(o=>rows.push({uuid:o.uuid,parent:o.parent?.uuid,visible:o.visible,position:o.position.toArray(),quaternion:o.quaternion.toArray(),scale:o.scale.toArray(),matrix:o.matrix.elements.slice(),world:o.matrixWorld.elements.slice(),userData:structuredClone(o.userData)}));return rows;}
async function binary(root){const old=globalThis.FileReader;globalThis.FileReader=class{readAsArrayBuffer(blob){blob.arrayBuffer().then(data=>{this.result=data;this.onloadend?.();});}readAsDataURL(blob){blob.arrayBuffer().then(data=>{this.result='data:'+blob.type+';base64,'+Buffer.from(data).toString('base64');this.onloadend?.();});}};try{return await new m.GLTFExporter().parseAsync(root,{binary:true,onlyVisible:true});}finally{globalThis.FileReader=old;}}
function json(buffer){const length=new DataView(buffer).getUint32(12,true);return JSON.parse(new TextDecoder().decode(new Uint8Array(buffer,20,length)));}

await test('selection clone excludes room surfaces facade helper nodes and all unselected furniture',()=>{const s=pair(),e=engine(s);for(const id of ['floor','back','facade-sign','guide']){const extra=new T.Mesh(new T.BoxGeometry(10,10,10),new T.MeshStandardMaterial());extra.userData={nodeId:id,wall:id==='back',facade:id==='facade-sign'};e.root.add(extra);}const output=m.prepareSelectionExport(e.root,s,['a']);assert.equal(output.children.length,1);assert.equal(output.children[0].userData.nodeId,'a');assert.equal(find(output,'b'),undefined);assert.equal(find(output,'floor'),undefined);assert.equal(find(output,'facade-sign'),undefined);assert.ok(box(output).getSize(new T.Vector3()).x<1);dispose(output);dispose(e.root);});
await test('default center uses actual rotated meshes at horizontal center and their lowest elevation',()=>{const s=pair(),e=engine(s),world=m.prepareSelectionExport(e.root,s,['a','b'],'world'),expected=box(world),out=m.prepareSelectionExport(e.root,s,['a','b']),bounds=box(out),offset=out.userData.originOffset;near((bounds.min.x+bounds.max.x)/2,0);near((bounds.min.z+bounds.max.z)/2,0);near(bounds.min.y,0);near(offset.x,(expected.min.x+expected.max.x)/2);near(offset.y,expected.min.y);near(offset.z,(expected.min.z+expected.max.z)/2);assert.equal(offset.unit,'metre');assert.equal(out.userData.exportOrigin,'center');assert.equal(out.userData.sourceSceneName,s.name);nearArray(bounds.getSize(new T.Vector3()).toArray(),expected.getSize(new T.Vector3()).toArray());dispose(world);dispose(out);dispose(e.root);});
await test('world origin includes live ancestor transforms without updating any source matrix caches',()=>{const s=pair(),e=engine(s),parent=new T.Group();parent.position.set(2,3,-4);parent.rotation.set(.2,.4,-.1);parent.scale.set(1.2,.9,1.1);e.root.position.set(.4,-.2,.7);e.root.rotation.y=.3;parent.add(e.root);const before=fingerprint(parent),out=m.prepareSelectionExport(e.root,s,['a'],'world'),original=e.root.children[0],expected=new T.Matrix4().compose(parent.position,parent.quaternion,parent.scale).multiply(new T.Matrix4().compose(e.root.position,e.root.quaternion,e.root.scale)).multiply(new T.Matrix4().compose(original.position,original.quaternion,original.scale));nearArray(out.children[0].matrixWorld.elements,expected.elements);assert.deepEqual(out.userData.originOffset,{x:0,y:0,z:0,unit:'metre'});assert.deepEqual(fingerprint(parent),before);dispose(out);dispose(e.root);});
await test('matrix-controlled imported roots retain shear and nested transforms exactly',()=>{const s=empty();s.nodes=[{...m.createNode('box','model'),kind:'model',assetId:crypto.randomUUID()}];const root=new T.Group(),asset=new T.Group(),part=new T.Mesh(new T.BoxGeometry(.8,1.4,.6),new T.MeshStandardMaterial());asset.userData.nodeId='model';asset.matrixAutoUpdate=false;asset.matrix.set(1,.2,0,2,0,1,.3,.4,0,0,1,-1,0,0,0,1);part.position.set(.2,.6,-.3);part.rotation.set(.1,.7,.2);asset.add(part);root.add(asset);const before=fingerprint(root),out=m.prepareSelectionExport(root,s,['model'],'world'),expected=asset.matrix.clone().multiply(new T.Matrix4().compose(part.position,part.quaternion,part.scale));nearArray(out.children[0].children[0].matrixWorld.elements,expected.elements);assert.deepEqual(fingerprint(root),before);dispose(out);dispose(root);});
await test('locked visible selections export while hidden missing room and empty selections reject atomically',()=>{const s=pair(),e=engine(s);s.nodes[0].locked=true;const out=m.prepareSelectionExport(e.root,s,['a'],'world');assert.equal(out.children.length,1);dispose(out);const before=fingerprint(e.root);s.nodes[1].hidden=true;for(const ids of [[],['missing'],['floor'],['a','b'],['']])assert.throws(()=>m.prepareSelectionExport(e.root,s,ids));assert.throws(()=>m.prepareSelectionExport(e.root,s,['a'],'invalid'),/원점/);assert.deepEqual(fingerprint(e.root),before);dispose(e.root);});
await test('duplicate requested IDs deduplicate while missing or ambiguous rendered nodes reject',()=>{const s=pair(),e=engine(s),out=m.prepareSelectionExport(e.root,s,['a','a']);assert.equal(out.children.length,1);dispose(out);const absent=e.root.children.pop();assert.throws(()=>m.prepareSelectionExport(e.root,s,['unselected']),/갱신/);e.root.add(absent);const duplicate=e.root.children[0].clone();e.root.add(duplicate);assert.throws(()=>m.prepareSelectionExport(e.root,s,['a']),/갱신/);duplicate.removeFromParent();dispose(e.root);});
await test('whole groups preserve hierarchy and only used layer metadata while leaving world matrices intact',()=>{let s=m.createGroup(pair(),['a','b'],'카페 좌석');const used=crypto.randomUUID(),unused=crypto.randomUUID();s.layers=[{id:used,name:'좌석',color:'#123456'},{id:unused,name:'수납',color:'#aabbcc'}];s.nodes[0].layerId=s.nodes[1].layerId=used;s.nodes[2].layerId=unused;const e=engine(s),out=m.prepareSelectionExport(e.root,s,['b','a'],'world'),group=out.children[0];assert.equal(out.children.length,1);assert.equal(group.userData.furnitureGroupId,s.nodes[0].group.id);assert.equal(group.name,'카페 좌석');assert.equal(group.children.length,2);assert.deepEqual(out.userData.designLayers,[s.layers[0]]);for(const id of ['a','b']){const child=find(out,id);assert.equal(child.userData.designLayerId,used);near(child.matrixWorld.elements[12],s.nodes.find(n=>n.id===id).x/1000);}dispose(out);dispose(e.root);});
await test('partial group selection exports only the selected member without stale group identity',()=>{const s=m.createGroup(pair(),['a','b'],'카페 좌석'),e=engine(s);e.root.children[0].userData.furnitureGroupId=s.nodes[0].group.id;const out=m.prepareSelectionExport(e.root,s,['a']);assert.equal(out.children.length,1);assert.equal(out.children[0].userData.nodeId,'a');out.traverse(o=>assert.equal(o.userData.furnitureGroupId,undefined));assert.equal(s.nodes[0].group.id,s.nodes[1].group.id);assert.equal(find(out,'b'),undefined);dispose(out);dispose(e.root);});
await test('hosted door autocut visibility is restored in clone and retains its actual wall position',()=>{const s=empty();s.nodes=[{...m.createNode('door','door'),host:'right',x:0,z:850,locked:true}];const e=engine(s),source=e.root.children[0];source.visible=false;const before=fingerprint(e.root),out=m.prepareSelectionExport(e.root,s,['door'],'world');assert.equal(out.children[0].visible,true);assert.equal(source.visible,false);near(out.children[0].position.x,s.room.width/2000);near(out.children[0].position.z,.85);near(out.children[0].rotation.y,Math.PI/2);assert.equal(out.children[0].userData.host,'right');assert.deepEqual(fingerprint(e.root),before);dispose(out);dispose(e.root);});
await test('configured door leaf hinge handle and opening metadata survive at the selected static angle',()=>{const s=empty(),opening={id:crypto.randomUUID(),name:'여닫이문',kind:'door',x:150,bottom:0,width:900,height:2100,door:{hinge:'right',side:'negative',angle:92}};s.nodes=[{...m.createNode('partition','wall',350,-500),width:2200,height:2600,rotation:37,openings:[opening]}];const e=engine(s),out=m.prepareSelectionExport(e.root,s,['wall'],'world');let sourcePivot,copyPivot;e.root.traverse(o=>{if(o.userData.doorOpeningId===opening.id)sourcePivot=o;});out.traverse(o=>{if(o.userData.doorOpeningId===opening.id)copyPivot=o;});assert.ok(copyPivot);nearArray(copyPivot.quaternion.toArray(),sourcePivot.quaternion.toArray());assert.equal(copyPivot.children.length,2);assert.ok(copyPivot.children.some(o=>o.userData.part.endsWith('-handle')));assert.deepEqual(out.children[0].userData.partitionOpenings,[opening]);nearArray(box(out).getSize(new T.Vector3()).toArray(),box(e.root).getSize(new T.Vector3()).toArray());dispose(out);dispose(e.root);});
await test('cloned geometry materials textures and clipping state are independently owned',()=>{const s=pair(),e=engine(s),source=e.root.children[0].children[0],image={width:4,height:2},map=new T.Texture(image),plane=new T.Plane(new T.Vector3(1,0,0),.4);source.material[0].map=map;source.material[0].clippingPlanes=[plane];source.material[0].clipShadows=true;source.material[0].clipIntersection=true;const out=m.prepareSelectionExport(e.root,s,['a']),copy=out.children[0].children[0];assert.notEqual(copy.geometry,source.geometry);assert.notEqual(copy.material[0],source.material[0]);assert.notEqual(copy.material[0].map,map);assert.equal(copy.material[0].map.image,image);assert.equal(copy.material[0].clippingPlanes,null);assert.equal(copy.material[0].clipShadows,false);assert.equal(copy.material[0].clipIntersection,false);assert.deepEqual(source.material[0].clippingPlanes,[plane]);assert.equal(source.material[0].clipShadows,true);let disposed=0;source.geometry.addEventListener('dispose',()=>disposed++);map.addEventListener('dispose',()=>disposed++);source.material[0].addEventListener('dispose',()=>disposed++);dispose(out);assert.equal(disposed,0);dispose(e.root);});
await test('only visible descendant geometry contributes to center origin while its visibility remains untouched',()=>{const s=empty();s.nodes=[m.createNode('box','a')];const e=engine(s),hidden=new T.Mesh(new T.BoxGeometry(4,4,4),new T.MeshStandardMaterial());hidden.visible=false;hidden.position.set(100,100,100);e.root.children[0].add(hidden);const out=m.prepareSelectionExport(e.root,s,['a']);near(out.userData.originOffset.x,0);near(out.userData.originOffset.z,0);near(out.userData.originOffset.y,0);assert.equal(out.children[0].children.at(-1).visible,false);assert.equal(hidden.visible,false);dispose(out);dispose(e.root);});
await test('loading placeholders and zero-mesh selections never produce a silently incomplete asset',()=>{const s=pair(),e=engine(s);e.root.children[0].children[0].userData.unmeasurable=true;assert.throws(()=>m.prepareSelectionExport(e.root,s,['a']),/다 불러온/);delete e.root.children[0].children[0].userData.unmeasurable;const child=e.root.children[1];dispose(child);assert.throws(()=>m.prepareSelectionExport(e.root,s,['a','b']),/형상/);assert.ok(e.root.children[0].children.length);dispose(e.root);});
await test('failed export clone cleanup does not close shared decoded image bitmaps or dispose source resources',()=>{const old=globalThis.ImageBitmap;let closes=0;globalThis.ImageBitmap=class{width=4;height=2;close(){closes++;}};const s=pair(),e=engine(s),map=new T.Texture(new ImageBitmap());e.root.children[0].children[0].material[0].map=map;dispose(e.root.children[1]);let disposals=0;map.addEventListener('dispose',()=>disposals++);try{assert.throws(()=>m.prepareSelectionExport(e.root,s,['a','b']),/형상/);assert.equal(closes,0);assert.equal(disposals,0);}finally{dispose(e.root);globalThis.ImageBitmap=old;}});
await test('export user data excludes estimates API-like fields and arbitrary imported extras',async()=>{const s=pair(),e=engine(s),source=e.root.children[0],mesh=source.children[0],secret='must-not-export';s.nodes[0].estimate={unitPrice:23000,priceBasis:'private'};e.root.userData={apiKey:secret,estimate:s.nodes[0].estimate};source.userData={...source.userData,apiKey:secret,estimate:s.nodes[0].estimate};mesh.userData.apiKey=secret;mesh.geometry.userData={private:secret};mesh.material[0].userData={apiKey:secret};const before=fingerprint(e.root),out=m.prepareSelectionExport(e.root,s,['a']),buffer=await binary(out),doc=json(buffer);assert.equal(JSON.stringify(doc).includes(secret),false);assert.equal(JSON.stringify(doc).includes('unitPrice'),false);assert.equal(JSON.stringify(doc).includes('priceBasis'),false);assert.equal(JSON.stringify(doc).includes('sourceSceneName'),true);assert.deepEqual(fingerprint(e.root),before);dispose(out);dispose(e.root);});
await test('actual GLB contains just selected grouped assets and preserves exported physical dimensions',async()=>{const s=m.createGroup(pair(),['a','b'],'창가 세트'),e=engine(s),out=m.prepareSelectionExport(e.root,s,['a','b']),expected=box(out),buffer=await binary(out),doc=json(buffer);assert.ok(doc.nodes.some(n=>n.extras?.furnitureGroupId===s.nodes[0].group.id));assert.ok(!doc.nodes.some(n=>n.extras?.nodeId==='unselected'));assert.ok(!doc.nodes.some(n=>['floor','back','left','right','front','facade-sign'].includes(n.extras?.nodeId)));const parsed=await new m.GLTFLoader().parseAsync(buffer,''),actual=box(parsed.scene);nearArray(actual.min.toArray(),expected.min.toArray());nearArray(actual.max.toArray(),expected.max.toArray());dispose(parsed.scene);dispose(out);dispose(e.root);});
await test('actual GLB embeds selected physical image bytes and baked UVs without changing original maps',async()=>{const png=await readFile('tests/fixtures/material.png'),saved={document:globalThis.document,ImageData:globalThis.ImageData};globalThis.document={createElement(){return {width:0,height:0,getContext(){return {translate(){},scale(){},putImageData(){}}},toBlob(fn){fn(new Blob([png],{type:'image/png'}));}};}};globalThis.ImageData=class{constructor(data,width,height){Object.assign(this,{data,width,height});}};const s=empty();s.nodes=[m.createNode('box','a')];const e=engine(s),mesh=e.root.children[0].children[0],source=new T.DataTexture(new Uint8Array(32).fill(255),4,2),map=m.materialImage(source,[1,.5],650,33);source.colorSpace=T.SRGBColorSpace;mesh.material[0].map=map;mesh.material[0].transparent=true;const uv=mesh.geometry.getAttribute('uv').array.slice(),matrix=map.matrix.elements.slice(),out=m.prepareSelectionExport(e.root,s,['a']);try{m.bakeImageTransforms(out);const buffer=await binary(out),doc=json(buffer),length=new DataView(buffer).getUint32(12,true),start=20+length+8,imageView=doc.bufferViews[doc.images[0].bufferView];assert.equal(doc.images[0].mimeType,'image/png');assert.deepEqual(Buffer.from(new Uint8Array(buffer,start+(imageView.byteOffset??0),png.length)),png);assert.ok(doc.materials.some(material=>material.alphaMode==='BLEND'));assert.deepEqual(mesh.geometry.getAttribute('uv').array,uv);assert.deepEqual(map.matrix.elements,matrix);assert.equal(map.matrixAutoUpdate,false);assert.equal(map.userData.physicalImage,true);}finally{dispose(out);dispose(e.root);source.dispose();globalThis.document=saved.document;globalThis.ImageData=saved.ImageData;}});
console.log(`${checks} selection-export checks passed.`);
