import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {mkdtemp,writeFile,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';import {join} from 'node:path';import {pathToFileURL} from 'node:url';
const dir=await mkdtemp(join(tmpdir(),'spatial-export-ready-')),file=join(dir,'bundle.mjs');
const bundle=await build({stdin:{contents:"export * as T from 'three';export * from './lib/scene-model';export * from './lib/scene-engine';",resolveDir:process.cwd()},bundle:true,platform:'node',format:'esm',write:false});await writeFile(file,bundle.outputFiles[0].text);const m=await import(pathToFileURL(file));await rm(dir,{recursive:true,force:true});
const {T}=m,png=await readFile('tests/fixtures/material.png'),saved={FileReader:globalThis.FileReader,document:globalThis.document,ImageData:globalThis.ImageData};let beforeRead;
globalThis.FileReader=class{readAsArrayBuffer(blob){blob.arrayBuffer().then(data=>{this.result=data;beforeRead?.();this.onloadend?.();});}readAsDataURL(blob){blob.arrayBuffer().then(data=>{this.result='data:'+blob.type+';base64,'+Buffer.from(data).toString('base64');beforeRead?.();this.onloadend?.();});}};
globalThis.document={createElement(){return {width:0,height:0,getContext(){return {translate(){},scale(){},putImageData(){}};},toBlob(fn){fn(new Blob([png],{type:'image/png'}));}};}};globalThis.ImageData=class{constructor(data,width,height){Object.assign(this,{data,width,height});}};
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};},tick=()=>new Promise(resolve=>setTimeout(resolve,0));
const fixture=(nodes=[m.createNode('box','a'),m.createNode('box','b',1500)])=>{const s={...m.initialScene(),nodes},e=Object.create(m.SceneEngine.prototype);Object.assign(e,{data:s,root:new T.Group(),modelCache:new Map(),imageCache:new Map(),pendingAssets:new Map(),assetErrors:[],geometryKey:'scene',assetEpoch:1,disposed:false,cancelTransform(){},cancelMeasurement(){},setSelection(){},material(){return new T.MeshStandardMaterial();}});return {s,e};};
const image=()=>new T.DataTexture(new Uint8Array(32).fill(255),4,2),doc=buffer=>JSON.parse(new TextDecoder().decode(new Uint8Array(buffer,20,new DataView(buffer).getUint32(12,true))));
let checks=0;async function test(name,fn){try{await fn();checks++;console.log('PASS '+name);}finally{beforeRead=undefined;}}
try{
await test('selected normal GLB exports despite unrelated failed assets and never-ending jobs',async()=>{const {s,e}=fixture();s.nodes.forEach(n=>e.buildNode(n));e.assetErrors=['unrelated model error'];e.modelCache.set('other',{promise:Promise.resolve(new T.Group()),error:'unrelated GLB error'});e.pendingAssets.set(new Promise(()=>{}),1);const wait=deferred();e.imageAsset=()=>wait.promise;e.bindImage('other',e.root.children[1].children[0].material[0],()=>{});const result=doc(await e.exportSelectionGlb(['a']));assert.ok(result.nodes.some(n=>n.extras?.nodeId==='a'));assert.ok(!result.nodes.some(n=>n.extras?.nodeId==='b'));e.clearGroup(e.root);});
await test('selected image binding delays export until pixels are applied and embedded in GLB',async()=>{const {s,e}=fixture();s.nodes.forEach(n=>e.buildNode(n));const wait=deferred(),mat=e.root.children[0].children[0].material[0];e.imageAsset=()=>wait.promise;e.bindImage('selected',mat,source=>{mat.map=source.clone();});let complete=false;const done=e.exportSelectionGlb(['a']).then(value=>{complete=true;return value;});await tick();assert.equal(complete,false);const source=image();wait.resolve(source);const result=doc(await done);assert.equal(result.images.length,1);assert.equal(result.images[0].mimeType,'image/png');assert.ok(mat.map);e.clearGroup(e.root);source.dispose();});
await test('selected image application failure blocks export even after its pending job settled',async()=>{const {s,e}=fixture();s.nodes.forEach(n=>e.buildNode(n));const wait=deferred();e.imageAsset=()=>wait.promise;e.bindImage('selected',e.root.children[0].children[0].material[0],()=>{throw new Error('selected image application failed');});wait.resolve(image());await tick();assert.equal(e.pendingAssets.size,0);await assert.rejects(e.exportSelectionGlb(['a']),/selected image application failed/);assert.ok(doc(await e.exportSelectionGlb(['b'])).nodes.some(n=>n.extras?.nodeId==='b'));e.clearGroup(e.root);});
await test('image jobs spawned by a delayed selected model are included before export starts',async()=>{const n={...m.createNode('box','model'),kind:'model',assetId:crypto.randomUUID(),uniformMaterial:true,finish:{textureId:crypto.randomUUID()}},{e}=fixture([n]),modelWait=deferred(),imageWait=deferred(),model=new T.Group(),mesh=new T.Mesh(new T.BoxGeometry(),new T.MeshStandardMaterial());mesh.userData.part='mesh0';model.add(mesh);e.modelAsset=()=>modelWait.promise;e.imageAsset=()=>imageWait.promise;e.nodeMaterial=()=>{const mat=new T.MeshStandardMaterial();e.bindImage(n.finish.textureId,mat,source=>{mat.map=source.clone();});return mat;};e.buildNode(n);let done=false;const pending=e.exportSelectionGlb(['model']).then(result=>{done=true;return result;});modelWait.resolve(model);await tick();assert.equal(done,false);const source=image();imageWait.resolve(source);assert.equal(doc(await pending).images.length,1);e.clearGroup(e.root);e.clearGroup(model);source.dispose();});
await test('selected scene epoch object and material changes while waiting reject stale exports',async()=>{for(const change of [e=>{e.assetEpoch++;},e=>{e.geometryKey='next';},e=>{e.data={...e.data,name:'다른 장면'};},e=>{e.disposed=true;},e=>{e.root.remove(e.root.children[0]);},e=>{e.root.children[0].children[0].material[0]=new T.MeshStandardMaterial();}]){const {s,e}=fixture();s.nodes.forEach(n=>e.buildNode(n));const wait=deferred(),mat=e.root.children[0].children[0].material[0];e.imageAsset=()=>wait.promise;e.bindImage('selected',mat,()=>{});const pending=e.exportSelectionGlb(['a']);await tick();change(e);const source=image();wait.resolve(source);await assert.rejects(pending,/변경|닫혔/);e.clearGroup(e.root);source.dispose();}});
await test('state changes during actual GLTF serialization reject and always dispose the export clone',async()=>{const {s,e}=fixture();s.nodes.forEach(n=>e.buildNode(n));let cleanups=0,originalDisposals=0;const clear=e.clearGroup;e.clearGroup=function(group){cleanups++;return clear.call(this,group);};e.root.children[0].children[0].geometry.addEventListener('dispose',()=>originalDisposals++);beforeRead=()=>{e.data={...e.data,name:'변경'};};await assert.rejects(e.exportSelectionGlb(['a']),/변경/);assert.equal(cleanups,1);assert.equal(originalDisposals,0);clear.call(e,e.root);});
await test('hidden unused descendant material jobs do not block visible selected geometry',async()=>{const {s,e}=fixture();s.nodes.forEach(n=>e.buildNode(n));const hidden=new T.Mesh(new T.BoxGeometry(),new T.MeshStandardMaterial());hidden.visible=false;e.root.children[0].add(hidden);e.imageAsset=()=>new Promise(()=>{});e.bindImage('hidden',hidden.material,()=>{});assert.ok(doc(await e.exportSelectionGlb(['a'])).nodes.some(n=>n.extras?.nodeId==='a'));e.clearGroup(e.root);});
console.log(`${checks} selection-export asset-readiness checks passed.`);
}finally{globalThis.FileReader=saved.FileReader;globalThis.document=saved.document;globalThis.ImageData=saved.ImageData;}
