import assert from 'node:assert/strict';import {build} from 'esbuild';import {mkdtemp,writeFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {pathToFileURL} from 'node:url';
const dir=await mkdtemp(join(tmpdir(),'spatial-snapping-')),file=join(dir,'bundle.mjs');
const bundle=await build({stdin:{contents:"export * as T from 'three';export * from './lib/snap-settings';export * from './lib/scene-engine';export * from './lib/scene-model';export * from './lib/measurements';",resolveDir:process.cwd()},bundle:true,platform:'node',format:'esm',write:false});
await writeFile(file,bundle.outputFiles[0].text);const m=await import(pathToFileURL(file));await rm(dir,{recursive:true,force:true});const{T}=m;
let checks=0;const test=(name,fn)=>{fn();checks++;console.log('PASS '+name);},near=(a,b,e=1e-9)=>assert.ok(Math.abs(a-b)<e,`${a} != ${b}`);
test('default settings retain 50 mm movement and 15 degree rotation',()=>{assert.deepEqual(m.defaultSnapSettings,{translation:50,rotation:15});assert.deepEqual(m.normalizeSnapping(undefined),m.defaultSnapSettings);assert.ok(Object.isFrozen(m.defaultSnapSettings));});
test('valid boundary, fractional and preset settings are preserved independently',()=>{for(const translation of [1,1.5,5,10,25,50,100,1000])for(const rotation of [1,1.5,5,15,30,45,90])assert.deepEqual(m.normalizeSnapping({translation,rotation}),{translation,rotation});});
test('unknown or nonfinite settings use defaults without coercion or shared mutation',()=>{for(const input of [undefined,null,[],true,123,'50',{}, {translation:NaN,rotation:Infinity},{translation:0,rotation:-1},{translation:1000.1,rotation:90.1},{translation:'25',rotation:'30'}])assert.deepEqual(m.normalizeSnapping(input),{translation:50,rotation:15});const a=m.normalizeSnapping({translation:25,rotation:NaN});assert.deepEqual(a,{translation:25,rotation:15});a.translation=200;assert.equal(m.defaultSnapSettings.translation,50);assert.deepEqual(m.normalizeSnapping({translation:NaN,rotation:30}),{translation:50,rotation:30});});
test('enabled drawing snaps metre coordinates using the chosen millimetre grid',()=>{const p={x:.063,z:-.088};for(const [step,x,z]of [[5,.065,-.09],[10,.06,-.09],[25,.075,-.1],[50,.05,-.1],[100,.1,-.1],[1000,0,0]]){const result=m.snapFloorPoint(p,true,step);near(result.x,x);near(result.z,z);}assert.deepEqual(p,{x:.063,z:-.088});});
test('disabled drawing keeps exact off-grid positions and returns a fresh point',()=>{const p={x:.0123456789,z:-.0987654321},result=m.snapFloorPoint(p,false,1000);assert.deepEqual(result,p);assert.notEqual(result,p);result.x=1;assert.equal(p.x,.0123456789);});
test('fractional settings and negative half-step ties follow the transform control rounding rule',()=>{const result=m.snapFloorPoint({x:.0037,z:-.0037},true,1.5);near(result.x,.003);near(result.z,-.003);const ties=m.snapFloorPoint({x:.0625,z:-.0625},true,25);near(ties.x,.075);near(ties.z,-.05);assert.equal(Object.is(m.snapFloorPoint({x:-.001,z:-.001},true,50).x,-0),false);});
test('invalid drawing steps fall back safely and invalid coordinates are rejected',()=>{for(const step of [0,-1,NaN,Infinity,1001,'25'])assert.deepEqual(m.snapFloorPoint({x:.063,z:-.088},true,step),m.snapFloorPoint({x:.063,z:-.088},true,50));for(const point of [{x:NaN,z:0},{x:0,z:Infinity},{x:-Infinity,z:0}])for(const enabled of [true,false])assert.throws(()=>m.snapFloorPoint(point,enabled,25),/좌표/);});
function engine(){const calls=[],e=Object.create(m.SceneEngine.prototype);e.transform={setTranslationSnap:value=>calls.push(['translation',value]),setRotationSnap:value=>calls.push(['rotation',value])};return{e,calls};}
test('actual engine setSnap remains backward compatible and converts mm and degrees for controls',()=>{const{e,calls}=engine();e.setSnap(true);assert.deepEqual(calls[0],['translation',.05]);near(calls[1][1],Math.PI/12);calls.length=0;e.setSnap(true,25,30);assert.deepEqual(calls[0],['translation',.025]);near(calls[1][1],Math.PI/6);assert.deepEqual(e.snapping,{translation:25,rotation:30});assert.equal(e.snapEnabled,true);});
test('disabling snapping disables both controls while retaining the chosen drawing settings',()=>{const{e,calls}=engine();e.setSnap(false,10,45);assert.deepEqual(calls,[['translation',null],['rotation',null]]);assert.equal(e.snapEnabled,false);assert.deepEqual(e.snapping,{translation:10,rotation:45});near(m.snapFloorPoint({x:.013,z:.017},e.snapEnabled,e.snapping.translation).x,.013);});
test('actual engine falls back on invalid settings without modifying scene or tape state',()=>{const{e,calls}=engine(),data=m.initialScene(),anchor={kind:'room',surface:'floor',u:.513,v:.517,offset:0};e.data=data;e.measureStart=anchor;const before=JSON.stringify(data);e.setSnap(true,NaN,999);assert.deepEqual(calls[0],['translation',.05]);near(calls[1][1],Math.PI/12);assert.equal(JSON.stringify(e.data),before);assert.equal(e.data,data);assert.equal(e.measureStart,anchor);});
test('actual measurement picking preserves off-grid points with snapping enabled or disabled',()=>{for(const enabled of [true,false]){const{e}=engine(),n={...m.createNode('box','item'),width:1000,height:1000,depth:1000},data={...m.initialScene(),nodes:[n]},root=new T.Group(),mesh=new T.Mesh(new T.BoxGeometry(1,1,1),new T.MeshBasicMaterial());mesh.position.y=.5;mesh.userData={nodeId:'item',part:'body'};root.add(mesh);Object.assign(e,{root,data,measureStart:null,measurementOverlay:{update(){}}});e.setSnap(enabled,1000,90);e.measureAt(new T.Raycaster(new T.Vector3(.013,.417,2),new T.Vector3(0,0,-1)));assert.ok(e.measureStart);const p=m.resolveMeasurementAnchor(data,e.measureStart);near(p.x,13);near(p.y,417);near(p.z,500);mesh.geometry.dispose();mesh.material.dispose();}});
console.log(`${checks} snap settings checks passed.`);
