import assert from 'node:assert/strict';
import {build} from 'esbuild';
const bundle=await build({stdin:{contents:"export * as T from 'three';export {OrbitControls} from 'three/addons/controls/OrbitControls.js';export * from './lib/scene-model';export * from './lib/walk-world';export * from './lib/walkthrough-controller';export * from './lib/scene-engine';",resolveDir:process.cwd()},bundle:true,platform:'node',format:'esm',write:false});
const m=await import('data:text/javascript;base64,'+Buffer.from(bundle.outputFiles[0].text).toString('base64')),{T}=m;
let checks=0;function test(name,fn){fn();checks++;console.log('PASS '+name)}
const empty=()=>({...m.initialScene(),nodes:[]}),near=(a,b,epsilon=1e-6)=>assert.ok(Math.abs(a-b)<epsilon,`${a} != ${b}`);
test('inside wall faces include body clearance and reject invalid points',()=>{const s=empty(),w=m.walkWorld(s,1650);near(w.limitX,s.room.width/2-310);assert.equal(m.walkBlocker(w,{x:w.limitX,z:0}),null);assert.equal(m.walkBlocker(w,{x:w.limitX+.01,z:0}),'벽');assert.ok(m.walkBlocker(w,{x:NaN,z:0}));assert.throws(()=>m.walkWorld(s,Infinity));});
test('thin rotated partition sweep cannot tunnel across the room',()=>{for(const yaw of [0,17,45,90,137,-75]){const s=empty();s.nodes=[{...m.createNode('partition','p'),width:2000,depth:20,rotation:yaw}];const w=m.walkWorld(s,1650),a=yaw*Math.PI/180,normal={x:Math.sin(a),z:Math.cos(a)},start={x:normal.x*1800,z:normal.z*1800},delta={x:-normal.x*3600,z:-normal.z*3600},r=m.moveWalk(w,start,delta);assert.equal(r.blocked,'파티션');assert.equal(m.walkBlocker(w,r.point),null);near(r.point.x*normal.x+r.point.z*normal.z,260.01,.001);}});
test('movement slides along a wall without losing tangential distance',()=>{const s=empty(),w=m.walkWorld(s,1650),r=m.moveWalk(w,{x:w.limitX-100,z:0},{x:900,z:700});assert.equal(r.blocked,'벽');near(r.point.z,700,.001);assert.ok(r.point.x<=w.limitX&&r.point.x>w.limitX-.1);});
test('rotated furniture slide preserves a safe final position',()=>{const s=empty();s.nodes=[{...m.createNode('box','b'),width:1600,depth:600,rotation:37}];const w=m.walkWorld(s,1650),o=w.obstacles[0],c=Math.cos(o.yaw),sin=Math.sin(o.yaw),world=(x,z)=>({x:c*x+sin*z,z:-sin*x+c*z}),r=m.moveWalk(w,world(-1500,1100),world(1900,-1200));assert.ok(r.blocked);assert.equal(m.walkBlocker(w,r.point),null);assert.ok(Math.hypot(r.point.x,r.point.z)>0);});
test('two-wall corner and blocked starting position never escape bounds',()=>{const w=m.walkWorld(empty(),1650),r=m.moveWalk(w,{x:0,z:0},{x:20000,z:20000});assert.equal(m.walkBlocker(w,r.point),null);assert.ok(r.point.x<=w.limitX&&r.point.z<=w.limitZ);assert.deepEqual(m.moveWalk(w,{x:50000,z:0},{x:-50000,z:0}).point,{x:50000,z:0});});
test('hidden and overhead objects do not block, but low furniture and head obstructions do',()=>{const s=empty();s.nodes=[{...m.createNode('box','hidden'),hidden:true},{...m.createNode('box','high'),x:1000,y:1900,height:200},{...m.createNode('box','low'),x:-1000,height:20}];const a=m.walkWorld(s,1650),b=m.walkWorld(s,1900);assert.deepEqual(a.obstacles.map(o=>o.id),['low']);assert.deepEqual(b.obstacles.map(o=>o.id),['high','low']);});
test('plant and anisotropic pendant protrusions stay inside conservative envelopes',()=>{const s=empty();s.nodes=[{...m.createNode('plant','p'),width:100,depth:3000},{...m.createNode('pendant','l'),x:1800,width:1500,depth:100,height:1000,y:1000}];const w=m.walkWorld(s,1650),p=w.obstacles[0],l=w.obstacles[1];assert.ok(p.halfX-250>=975);assert.ok(l.halfZ-250>=120);});
test('deep hosted frames use actual side-wall origins and yaw',()=>{const s=empty();s.nodes=[{...m.createNode('window','win'),host:'left',x:0,z:250,y:0,width:800,depth:2000}];const w=m.walkWorld(s,1650);assert.equal(m.walkBlocker(w,{x:-s.room.width/2+900,z:250}),'창문');assert.equal(m.walkBlocker(w,{x:0,z:0}),null);});
test('start search finds nearest free space and reports a completely blocked room',()=>{const s=m.initialScene(),w=m.walkWorld(s,1650),p=m.findWalkStart(w,{x:-1600,z:w.limitZ-120});assert.ok(p);assert.equal(m.walkBlocker(w,p),null);const blocked=empty();blocked.nodes=[{...m.createNode('box','all'),width:blocked.room.width,depth:blocked.room.depth}];assert.equal(m.findWalkStart(m.walkWorld(blocked,1650)),null);});
test('movement is normalized diagonally and elapsed time is bounded',()=>{const straight=m.walkDirection(0,1,0,1000,.05),diagonal=m.walkDirection(0,1,1,1000,.05);near(Math.hypot(straight.x,straight.z),50);near(Math.hypot(diagonal.x,diagonal.z),50);assert.deepEqual(m.walkDirection(0,1,0,1000,99),straight);near(m.walkDirection(Math.PI/2,1,0,1000,.05).x,-50);});
test('camera FOV survives validation and JSON while legacy cameras remain valid',()=>{const s=empty();s.cameras=[{id:'walk',name:'실내',position:[0,1.65,1],target:[0,1.65,-1],view:'interior',fov:65}];assert.equal(m.validateScene(JSON.parse(JSON.stringify(s))).cameras[0].fov,65);delete s.cameras[0].fov;assert.equal(m.validateScene(s).cameras[0].fov,undefined);s.cameras[0].fov=NaN;assert.throws(()=>m.validateScene(s));});

class FakeCanvas extends EventTarget{style={};captures=new Set();setAttribute(){}focus(){}setPointerCapture(id){this.captures.add(id)}hasPointerCapture(id){return this.captures.has(id)}releasePointerCapture(id){this.captures.delete(id)}}
const previous={window:globalThis.window,document:globalThis.document};globalThis.window=new EventTarget();globalThis.document=new EventTarget();document.hidden=false;
function event(type,props={}){const e=new Event(type,{cancelable:true});Object.assign(e,props);return e;}
function fixture(s=empty()){
 const camera=new T.PerspectiveCamera(38,1,.05,200),canvas=new FakeCanvas(),engine={camera,perspective:camera,view:'interior',scene:new T.Scene(),data:s,renderer:{domElement:canvas},orbit:{enabled:true,target:new T.Vector3()},helpers:new T.Group(),measurementOverlay:{group:new T.Group()},setMode(){},setSelection(){},setView(){},captureCamera:m.SceneEngine.prototype.captureCamera};let latest;
 const controller=new m.WalkthroughController(engine,s,state=>latest=state);return{engine,controller,canvas,state:()=>latest};
}
test('controller owns view and fixed eye height, then disposes idempotently',()=>{const f=fixture();assert.equal(f.engine.navigationActive,true);assert.equal(f.engine.orbit.enabled,false);assert.equal(f.engine.perspective.fov,65);near(f.engine.camera.position.y,1.65);f.controller.setEyeHeight(1200);near(f.engine.camera.position.y,1.2);const pose=f.engine.captureCamera();assert.equal(pose.fov,65);assert.equal(pose.view,'interior');near(new T.Vector3(...pose.position).distanceTo(new T.Vector3(...pose.target)),2);f.controller.dispose();f.controller.dispose();assert.equal(f.engine.navigationUpdate,undefined);assert.equal(f.engine.scene.children.length,0);});
test('keyboard movement stops on blur, ignores modifiers, and callbacks detach after close',()=>{const f=fixture();f.controller.teleport({x:0,z:0});f.canvas.dispatchEvent(event('keydown',{code:'KeyW'}));f.engine.navigationUpdate(100);f.engine.navigationUpdate(150);assert.ok(f.engine.camera.position.z<0);window.dispatchEvent(new Event('blur'));const stopped=f.engine.camera.position.z;f.engine.navigationUpdate(300);f.engine.navigationUpdate(350);near(f.engine.camera.position.z,stopped);f.canvas.dispatchEvent(event('keydown',{code:'KeyW',ctrlKey:true}));f.engine.navigationUpdate(500);near(f.engine.camera.position.z,stopped);const tick=f.engine.navigationUpdate;f.controller.dispose();f.canvas.dispatchEvent(event('keydown',{code:'KeyW'}));tick(1000);near(f.engine.camera.position.z,stopped);});
test('held buttons clear on tab hide and capture freeze does not move camera',()=>{const f=fixture();f.controller.teleport({x:0,z:0});f.controller.hold('forward',42);f.engine.navigationUpdate(100);f.engine.navigationUpdate(150);const z=f.engine.camera.position.z;f.controller.frozen=true;f.engine.navigationUpdate(200);near(f.engine.camera.position.z,z);f.controller.frozen=false;document.hidden=true;document.dispatchEvent(new Event('visibilitychange'));document.hidden=false;f.engine.navigationUpdate(300);f.engine.navigationUpdate(350);near(f.engine.camera.position.z,z);f.controller.dispose();});
test('drag direction, non-primary pointers and cancellation are deterministic',()=>{const f=fixture();f.canvas.dispatchEvent(event('pointerdown',{button:0,isPrimary:false,pointerId:2,clientX:0,clientY:0}));assert.equal(f.canvas.captures.size,0);f.canvas.dispatchEvent(event('pointerdown',{button:0,isPrimary:true,pointerId:1,clientX:0,clientY:0}));f.canvas.dispatchEvent(event('pointermove',{pointerId:1,clientX:100,clientY:50}));assert.ok(f.state().yaw<0&&f.state().pitch<0);f.canvas.dispatchEvent(event('pointercancel',{pointerId:1}));assert.equal(f.canvas.captures.size,0);const yaw=f.state().yaw;f.canvas.dispatchEvent(event('pointermove',{pointerId:1,clientX:200,clientY:50}));near(f.state().yaw,yaw);f.controller.dispose();});
test('teleport and eye-height rejection are atomic',()=>{const s=empty();s.nodes=[{...m.createNode('box','overhead'),y:1900,height:200}];const f=fixture(s);f.controller.teleport({x:0,z:0});assert.throws(()=>f.controller.setEyeHeight(1900),/아래/);assert.equal(f.state().eyeHeight,1650);assert.throws(()=>f.controller.teleport({x:50000,z:0}),/벽/);near(f.state().x,0);f.controller.dispose();});
test('actual camera restore keeps upward pose, field of view, zoom and interior ceiling',()=>{const s=empty(),e=Object.create(m.SceneEngine.prototype),camera=new T.PerspectiveCamera(38,1.6,.05,200),orbit=new m.OrbitControls(camera,null);Object.assign(e,{data:s,scene:new T.Scene(),root:new T.Group(),camera,perspective:camera,planCamera:new T.OrthographicCamera(),orbit,transform:{},host:{clientWidth:1000,clientHeight:625},cancelTransform(){},setSelection(){},resize(){}});const pose={view:'interior',fov:65,zoom:1,position:[.3,1.65,1],target:[.3,1.65+2*Math.sin(1),1-2*Math.cos(1)]};e.restoreCamera(pose);near(camera.fov,65);near(camera.position.y,1.65);near(camera.position.z,1);const direction=camera.getWorldDirection(new T.Vector3());near(direction.y,Math.sin(1));assert.equal(e.scene.children[0].name,'INTERIOR_CEILING');assert.equal(e.scene.children[0].visible,true);const saved=m.validateScene({...s,cameras:[{id:'camera',name:'위 보기',...e.captureCamera()}]}).cameras[0];e.setView('perspective');near(camera.fov,38);assert.equal(e.scene.children[0].visible,false);e.restoreCamera(saved);near(camera.fov,65);near(camera.getWorldDirection(new T.Vector3()).y,Math.sin(1));assert.equal(e.scene.children[0].visible,true);const first=e.scene.children[0];let disposed=0;first.geometry.addEventListener('dispose',()=>disposed++);e.updateInteriorCeiling();assert.equal(e.scene.children[0],first);e.data={...s,room:{...s.room,height:3500}};e.updateInteriorCeiling();assert.equal(disposed,1);near(e.scene.children[0].position.y,3.5);assert.equal(e.root.children.length,0);});
globalThis.window=previous.window;globalThis.document=previous.document;
console.log(`${checks} walkthrough checks passed.`);
