'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Layers,Save,Eye,Search,Trash2,RotateCw,LoaderCircle,ArrowLeft,Plus,RefreshCw} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {assemblyCategories,builtinAssemblies,captureAssembly,assemblySummary,insertAssembly,assemblyAnchor,type Assembly,type AssemblySummary,type AssemblyPlacement} from '@/lib/assemblies';
import {materials,type SceneData,type SceneNode} from '@/lib/scene-model';
import {groupBounds} from '@/lib/selection';
import {toast} from 'sonner';

function AssemblyPlan({nodes,room,added}:{nodes:SceneNode[];room?:SceneData['room'];added?:string[]}) {
    const b=groupBounds(nodes),w=room?.width??b.width,d=room?.depth??b.depth,pad=Math.max(w,d)*.07;
    return <svg viewBox={`${-w/2-pad} ${-d/2-pad} ${w+pad*2} ${d+pad*2}`} role="img" aria-label={room?'기존 공간 위의 세트 배치 평면':'세트 구성 평면'}>
        <rect x={-w/2} y={-d/2} width={w} height={d} fill="#fafbfe" stroke="#bdc4d2" strokeWidth={Math.max(w,d)*.004}/>
        {nodes.filter(n=>!n.hidden&&!n.host).map(n=>{const active=!added||added.includes(n.id),color=materials.find(m=>m.id===n.material)?.color??'#9a92b4';return <g key={n.id} transform={`translate(${n.x},${n.z}) rotate(${-n.rotation})`}><title>{n.name} · {Math.round(n.width)} × {Math.round(n.depth)}mm</title><rect x={-n.width/2} y={-n.depth/2} width={n.width} height={n.depth} fill={active?color:'#e0e4ec'} fillOpacity={active?.85:.6} stroke={active?'#6653dd':'#c4ccd9'} strokeWidth={Math.max(w,d)*(active?.006:.003)}/></g>})}
    </svg>;
}
const defaults=builtinAssemblies();
async function request<T>(url:string,options?:RequestInit):Promise<T>{const response=await fetch(url,options),data=await response.json() as T&{error?:string};if(!response.ok)throw new Error(data.error||'세트를 불러오지 못했습니다.');return data;}
const sizeText=(a:{width:number;depth:number;height:number})=>`${Math.round(a.width).toLocaleString()} × ${Math.round(a.depth).toLocaleString()} × ${Math.round(a.height).toLocaleString()}mm`;

export default function AssembliesDialog({scene,ids,initialSave=false,onClose,onPreview}:{scene:SceneData;ids:string[];initialSave?:boolean;onClose:()=>void;onPreview:(candidate:SceneData,ids:string[],name:string,details:string,base:string)=>void}) {
    const [base]=useState(()=>structuredClone(scene)),[mode,setMode]=useState<'browse'|'save'>(initialSave?'save':'browse');
    const [items,setItems]=useState<AssemblySummary[]>([]),[tab,setTab]=useState('saved'),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[fetching,setFetching]=useState(''),[error,setError]=useState('');
    const [selected,setSelected]=useState<{id:string;assembly:Assembly}|null>(null),[placement,setPlacement]=useState<AssemblyPlacement>({x:0,y:0,z:0,rotation:0});
    const [name,setName]=useState(''),[note,setNote]=useState(''),[category,setCategory]=useState<Assembly['category']>('custom'),[remove,setRemove]=useState<AssemblySummary|null>(null);
    const alive=useRef(true),listSequence=useRef(0),sequence=useRef(0),flight=useRef(false),controller=useRef<AbortController|null>(null),saveAttempt=useRef<{data:string;id:string}|null>(null);
    useEffect(()=>{alive.current=true;void load();return()=>{alive.current=false;sequence.current++;controller.current?.abort();}},[]);
    async function load(){const seq=++listSequence.current;setLoading(true);try{const data=await request<{assemblies:AssemblySummary[]}>('/api/assemblies');if(alive.current&&seq===listSequence.current)setItems(data.assemblies);}catch(e){if(alive.current&&seq===listSequence.current)setError((e as Error).message);}finally{if(alive.current&&seq===listSequence.current)setLoading(false)}}
    const captured=useMemo(()=>{try{return {assembly:captureAssembly(base,ids,name.trim()||'새 가구 세트',note,category),error:''}}catch(e){return {assembly:null,error:e instanceof Error&&e.name!=='ZodError'?e.message:'선택한 가구와 입력값을 확인하세요.'}}},[base,ids,name,note,category]);
    const candidate=useMemo(()=>{if(!selected)return null;try{return {...insertAssembly(base,selected.assembly,placement),error:''}}catch(e){return {scene:null,ids:[],overlaps:[],error:e instanceof Error&&e.name!=='ZodError'?e.message:'배치 위치와 회전 값을 확인하세요.'}}},[base,selected,placement]);
    async function choose(item:AssemblySummary){const seq=++sequence.current;setFetching(item.id);setSelected(null);setError('');try{let assembly=defaults.find(a=>a.id===item.id);if(!assembly){const data=await request<{assembly:Assembly}>(`/api/assemblies?id=${item.id}`);assembly={id:item.id,...data.assembly};}if(alive.current&&seq===sequence.current){setSelected({id:item.id,assembly});setPlacement({x:0,y:assembly.elevation,z:0,rotation:0});}}catch(e){if(alive.current&&seq===sequence.current)setError((e as Error).message);}finally{if(alive.current&&seq===sequence.current)setFetching('')}}
    async function save(){if(flight.current||!captured.assembly)return;const assembly={...captured.assembly,name:name.trim()||`선택 가구 ${ids.length}개`},data=JSON.stringify(assembly);if(saveAttempt.current?.data!==data)saveAttempt.current={data,id:crypto.randomUUID()};flight.current=true;setBusy(true);setError('');controller.current=new AbortController();try{const result=await request<{summary:AssemblySummary}>('/api/assemblies',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:saveAttempt.current.id,assembly}),signal:controller.current.signal});if(!alive.current)return;listSequence.current++;setLoading(false);setItems(old=>[result.summary,...old.filter(x=>x.id!==result.summary.id)]);setSelected({id:result.summary.id,assembly});setPlacement({x:0,y:assembly.elevation,z:0,rotation:0});setMode('browse');setTab('saved');setQuery('');saveAttempt.current=null;setName('');toast.success('가구 세트를 보관했습니다. 다른 프로젝트에서도 사용할 수 있습니다.');}catch(e){if(alive.current)setError((e as Error).message);}finally{flight.current=false;if(alive.current)setBusy(false)}}
    async function deleteSet(item:AssemblySummary){if(flight.current)return;flight.current=true;setBusy(true);setError('');try{await request(`/api/assemblies?id=${item.id}`,{method:'DELETE'});if(alive.current){listSequence.current++;setLoading(false);setItems(old=>old.filter(x=>x.id!==item.id));if(selected?.id===item.id)setSelected(null);setRemove(null);toast.success('보관함에서 세트를 삭제했습니다. 배치한 가구는 유지됩니다.');}}catch(e){if(alive.current)setError((e as Error).message);}finally{flight.current=false;if(alive.current)setBusy(false)}}
    function anchor(edge:'center'|'back'|'left'|'right'|'front'){if(!selected)return;try{const next=assemblyAnchor(base,selected.assembly,placement.rotation,edge);setPlacement(p=>({...p,...next}));setError('')}catch(e){setError((e as Error).message)}}
    const list=(tab==='saved'?items:defaults.map(a=>assemblySummary(a.id,a))).filter(a=>`${a.name} ${a.note} ${assemblyCategories[a.category]}`.toLowerCase().includes(query.toLowerCase()));
    const summary=selected?assemblySummary(selected.id,selected.assembly):null;
    return <><Dialog open onOpenChange={o=>!o&&onClose()}><DialogContent className="assemblies-dialog"><DialogHeader><DialogTitle><Layers size={22}/>{mode==='save'?'선택한 가구를 세트로 저장':'가구·설비 세트'}</DialogTitle><DialogDescription>{mode==='save'?'반복해서 쓰는 구성을 다른 매장에서도 불러오세요.':'세트를 고르고 위치를 정한 뒤, 실제 3D 공간에서 비교해 적용하세요.'}</DialogDescription></DialogHeader>
        {mode==='save'?<div className="assembly-save-layout"><div className="assembly-save-visual">{captured.assembly?<><AssemblyPlan nodes={captured.assembly.nodes}/><b>{captured.assembly.nodes.length}개 요소</b><p>{sizeText(assemblySummary('',captured.assembly))}</p></>:<div className="assembly-empty"><Layers size={32}/><p>{captured.error}</p></div>}</div><div className="assembly-save-fields"><label className="field-label">세트 이름<input className="text-input" value={name} disabled={busy} maxLength={80} onChange={e=>setName(e.target.value)} placeholder="예: OFD 소형점 카운터 세트"/></label><label className="field-label">분류<Select value={category} disabled={busy} onValueChange={v=>setCategory(v as Assembly['category'])}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{Object.entries(assemblyCategories).map(([key,label])=><SelectItem key={key} value={key}>{label}</SelectItem>)}</SelectContent></Select></label><label className="field-label">메모<textarea className="text-input" value={note} disabled={busy} maxLength={400} rows={3} onChange={e=>setNote(e.target.value)} placeholder="사용할 매장 타입이나 소재 메모"/></label><p className="fineprint">1~30개 요소 · 크기·상대 간격·면별 소재를 보관합니다. 원본은 그대로 두고, 잠금은 해제된 사본으로 저장합니다. 문·창문·숨긴 가구는 제외해서 선택하세요.</p><div className="assembly-save-actions"><button className="outline-button" disabled={busy} onClick={()=>setMode('browse')}><ArrowLeft size={15}/>보관함</button><button className="primary-button" disabled={busy||!captured.assembly} onClick={()=>void save()}>{busy?<LoaderCircle className="spin" size={16}/>:<Save size={16}/>}세트 저장</button></div></div></div>:<>
        <div className="assembly-browse-toolbar"><Tabs value={tab} onValueChange={setTab}><TabsList><TabsTrigger value="saved">내 세트 {items.length}</TabsTrigger><TabsTrigger value="basic">기본 구성 3</TabsTrigger></TabsList></Tabs><button className="outline-button" onClick={()=>{sequence.current++;setFetching('');setMode('save');setError('')}} disabled={!ids.length||busy}><Plus size={16}/>선택 가구 저장</button></div>
        <div className="assembly-browser"><section className="assembly-list-panel"><div className="search-field"><Search size={16}/><input aria-label="가구 세트 검색" value={query} onChange={e=>setQuery(e.target.value)} placeholder="이름·분류로 찾기"/><button className="assembly-refresh" disabled={loading||busy} aria-label="보관함 새로고침" onClick={()=>{setError('');void load()}}><RefreshCw size={15}/></button></div><div className="assembly-list">{loading&&tab==='saved'?<div className="assembly-empty"><LoaderCircle className="spin"/><p>세트 불러오는 중</p></div>:!list.length?<div className="assembly-empty"><Layers size={28}/><b>{query?'검색 결과가 없습니다':'아직 저장한 세트가 없습니다'}</b><p>{query?'다른 이름이나 분류로 찾아보세요.':'여러 가구를 선택해 저장하거나 기본 구성을 사용해 보세요.'}</p>{!query&&<button className="text-button" onClick={()=>setTab('basic')}>기본 구성 보기</button>}</div>:list.map(item=><article className={`assembly-card ${selected?.id===item.id?'selected':''}`} key={item.id}><button className="assembly-card-main" disabled={busy} onClick={()=>void choose(item)}><span className="assembly-card-symbol">{fetching===item.id?<LoaderCircle className="spin" size={20}/>:<Layers size={21}/>}</span><span><small>{assemblyCategories[item.category]} · {item.count}개 요소</small><b>{item.name}</b><span>{sizeText(item)}</span>{item.note&&<p>{item.note}</p>}</span></button>{tab==='saved'&&<button className="assembly-delete" disabled={busy||!!fetching} aria-label={`${item.name} 세트 삭제`} onClick={()=>setRemove(item)}><Trash2 size={16}/></button>}</article>)}</div><p className="fineprint">보관함 100개까지 · 내 세트는 계정에 저장됩니다.</p></section>
        <section className="assembly-placement">{selected&&summary?<><div className="assembly-placement-heading"><div><small>배치할 세트</small><h3>{summary.name}</h3></div><button className="outline-button" onClick={()=>setPlacement(p=>({...p,rotation:((Number.isFinite(p.rotation)?p.rotation:0)+90)%360}))}><RotateCw size={15}/>90°</button></div><div className="assembly-plan">{candidate?.scene?<AssemblyPlan nodes={candidate.scene.nodes} room={base.room} added={candidate.ids}/>:<AssemblyPlan nodes={selected.assembly.nodes}/>}</div><p className="assembly-plan-key"><span/>{candidate?.scene?'보라색 테두리: 추가할 세트 · 회색: 기존 가구':'세트 구성 · 현재 입력값으로는 배치할 수 없습니다'}</p><div className="assembly-anchor-buttons">{(['center','back','left','right','front'] as const).map((edge,i)=><button key={edge} onClick={()=>anchor(edge)}>{['중앙','안쪽 벽','왼쪽 벽','오른쪽 벽','입구 벽'][i]}</button>)}</div><div className="assembly-placement-fields">{(['x','z','y','rotation'] as const).map((axis,i)=><label className="field-label" key={axis}>{['좌우 위치 · X','앞뒤 위치 · Z','바닥~세트 하단','회전'][i]}<div><input aria-label={['세트 좌우 위치','세트 앞뒤 위치','세트 설치 높이','세트 회전'][i]} type="number" value={Number.isFinite(placement[axis])?placement[axis]:''} min={axis==='y'?0:axis==='rotation'?-360:-20000} max={axis==='rotation'?360:axis==='y'?6000:20000} step={axis==='rotation'?15:50} onChange={e=>setPlacement(p=>({...p,[axis]:e.target.value===''?NaN:Number(e.target.value)}))}/><span>{axis==='rotation'?'°':'mm'}</span></div></label>)}</div><p className="fineprint">방 중앙이 X/Z 0입니다. +X는 오른쪽, +Z는 입구 쪽입니다. 세트 크기 {sizeText(summary)}</p>{candidate?.error&&<p className="form-error" role="alert">{candidate.error}</p>}{candidate?.scene&&candidate.overlaps.length>0&&<div className="assembly-overlap"><b>추가 요소가 포함된 겹침 {candidate.overlaps.length}곳</b><p>{candidate.overlaps.slice(0,3).map(o=>o.names.join(' ↔ ')).join(' · ')}</p><small>외곽 치수 기준입니다. 의도한 겹침인지 3D에서 확인하세요.</small></div>}<button className="primary-button full" disabled={!candidate?.scene||busy||!!fetching} onClick={()=>{if(candidate?.scene)onPreview(candidate.scene,candidate.ids,summary.name,`${summary.count}개 요소 추가 · ${candidate.overlaps.length?`겹침 ${candidate.overlaps.length}곳 확인 필요`:'기존 가구 배치 유지'}`,JSON.stringify(base))}}><Eye size={17}/>3D 배치 미리보기</button></>:<div className="assembly-empty assembly-select-empty"><Layers size={38}/><b>배치할 세트를 선택하세요</b><p>가구 크기와 소재를 유지한 채<br/>위치·방향을 조절할 수 있습니다.</p></div>}</section></div></>}
        {error&&<p className="form-error" role="alert">{error}</p>}
    </DialogContent></Dialog><AlertDialog open={!!remove} onOpenChange={open=>!open&&!busy&&setRemove(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>보관한 세트를 삭제할까요?</AlertDialogTitle><AlertDialogDescription>‘{remove?.name}’을 보관함에서 삭제합니다. 이미 프로젝트에 배치한 가구와 원본 모델·소재 이미지는 유지됩니다.</AlertDialogDescription></AlertDialogHeader>{error&&<p className="form-error" role="alert">{error}</p>}<AlertDialogFooter><AlertDialogCancel disabled={busy}>취소</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();if(remove)void deleteSet(remove)}}>{busy?'삭제 중…':'세트 삭제'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>;
}
