'use client';
import {memo,useMemo,useState} from 'react';
import {Copy,Eye,Trash2,Plus,GitCompareArrows} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {saveVariant,removeVariant,designChanges} from '@/lib/design-variants';
import {floorPlanSvg} from '@/lib/floor-plan';
import type {SceneData,DesignVariant} from '@/lib/scene-model';
const VariantThumbnail=memo(function VariantThumbnail({design}:{design:DesignVariant['design']}){const svg=useMemo(()=>floorPlanSvg(design,'',{labels:false,dimensions:false}).replace('viewBox="0 0 420 297"','viewBox="25 45 260 211"'),[design]);return <div className="variant-thumb" dangerouslySetInnerHTML={{__html:svg}}/>});
export default function DesignVariantsDialog({open,onClose,scene,onCommit,onPreview}:{open:boolean;onClose:()=>void;scene:SceneData;onCommit:(s:SceneData,label?:string)=>boolean;onPreview:(id:string)=>void}){
 const [name,setName]=useState(''),[note,setNote]=useState(''),[compare,setCompare]=useState(''),[error,setError]=useState('');const variants=scene.variants??[],variant=variants.find(v=>v.id===compare),changes=variant?designChanges(scene,variant.design):null;
 function save(){try{const next=saveVariant(scene,name||`디자인 안 ${variants.length+1}`,note);if(onCommit(next,'현재 배치를 디자인 안으로 보관했습니다. 프로젝트 저장으로 함께 보관하세요.')){setName('');setNote('');setError('')}}catch(e){setError((e as Error).message)}}
 if(!open)return null;
 return <Dialog open={open} onOpenChange={o=>!o&&onClose()}><DialogContent className="variants-dialog"><DialogHeader><DialogTitle>디자인 안 비교</DialogTitle><DialogDescription>마음에 드는 배치와 소재를 보관하고, 다른 안을 만들어 비교하세요.</DialogDescription></DialogHeader><div className="variant-save"><div><label className="field-label">안 이름<input className="text-input" maxLength={60} value={name} onChange={e=>setName(e.target.value)} placeholder={`예: 우드 중심안 / 테이블 3개안`}/></label><label className="field-label">메모<input className="text-input" maxLength={400} value={note} onChange={e=>setNote(e.target.value)} placeholder="이 안에서 확인할 내용"/></label></div><button className="primary-button" onClick={save} disabled={variants.length>=6}><Plus size={16}/>현재 장면 보관</button></div><p className="fineprint">{variants.length}/6개 · 배치·소재·외관·조명·참고 사진을 보관합니다. 프로젝트를 저장하면 다른 기기에서도 이어 볼 수 있습니다.</p>{error&&<p className="form-error" role="alert">{error}</p>}{!variants.length?<div className="empty-state"><Copy/><b>첫 디자인 안을 남겨 보세요</b><p>이후 소재나 배치를 바꿔도 이 안을 다시 불러올 수 있습니다.</p></div>:<div className="variant-list">{variants.map(v=><article className="variant-card" key={v.id}><VariantThumbnail design={v.design}/><div className="variant-info"><b>{v.name}</b><p>{v.note||'메모 없음'}</p><small>{v.design.nodes.length}개 요소 · {new Date(v.createdAt).toLocaleDateString('ko-KR')}</small><div><button className="outline-button" onClick={()=>{onPreview(v.id);onClose()}}><Eye size={14}/>3D 비교·불러오기</button><button className="text-button" onClick={()=>setCompare(v.id)}><GitCompareArrows size={14}/>변경 요약</button><button className="variant-delete" aria-label={`${v.name} 삭제`} onClick={()=>{onCommit(removeVariant(scene,v.id),'디자인 안을 제거했습니다. 실행 취소로 복원할 수 있습니다.');if(compare===v.id)setCompare('')}}><Trash2 size={15}/></button></div></div></article>)}</div>}{variants.length>0&&<div className="variant-comparison"><label className="field-label">현재 장면과 비교<Select value={variant?.id??''} onValueChange={setCompare}><SelectTrigger><SelectValue placeholder="비교할 안 선택"/></SelectTrigger><SelectContent>{variants.map(v=><SelectItem key={v.id} value={v.id}>{v.name}</SelectItem>)}</SelectContent></Select></label>{changes&&<div className="variant-diff"><span>추가 <b>{changes.added}</b></span><span>제거 <b>{changes.removed}</b></span><span>변경 <b>{changes.changed}</b></span><span>공간·소재 <b>{changes.room?'다름':'같음'}</b></span><span>외관 <b>{changes.facade?'다름':'같음'}</b></span><span>조명 <b>{changes.lighting?'다름':'같음'}</b></span><p>현재 장면에서 선택한 안으로 바뀌는 내용입니다. 3D 비교에서 적용 전·후를 확인하세요.</p></div>}</div>}</DialogContent></Dialog>
}
