'use client';
import {useState} from 'react';
import {Store,Eye,Info} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Switch} from '@/components/ui/switch';
import {materials,type FacadeData,type SceneData} from '@/lib/scene-model';
import {awningDimensions,defaultFacade,facadeCandidate,type StorefrontOptions} from '@/lib/facade';

function Dimension({label,value,onChange,min,max,step=10}:{label:string;value:number;onChange:(v:number)=>void;min?:number;max?:number;step?:number}) {
    return <label className="field-label">{label}<div className="facade-dimension"><input type="number" value={Number.isFinite(value)?value:''} onChange={e=>onChange(e.target.value===''?NaN:Number(e.target.value))} min={min} max={max} step={step} required/><span>mm</span></div></label>;
}
function Color({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}) {
    return <label className="field-label">{label}<div className="facade-color"><input type="color" value={value} onChange={e=>onChange(e.target.value)}/><span>{value.toUpperCase()}</span></div></label>;
}
export default function FacadeDialog({scene,initialTab='sign',onClose,onPreview}:{scene:SceneData;initialTab?:'sign'|'awning'|'front';onClose:()=>void;onPreview:(scene:SceneData,summary:string)=>void}) {
    const [facade,setFacade]=useState<FacadeData>(()=>structuredClone(scene.facade??defaultFacade(scene)));
    const [replaceFront,setReplaceFront]=useState(false),[options,setOptions]=useState<StorefrontOptions>({doorPosition:'left',doorWidth:950,frameMaterial:'charcoal'}),[error,setError]=useState(''),[tab,setTab]=useState(initialTab);
    const sign=facade.sign,awning=facade.awning,dimensions=awningDimensions(awning),frontCount=scene.nodes.filter(n=>n.host==='front').length;
    function patch<K extends keyof FacadeData>(key:K,value:Partial<FacadeData[K]>) {setFacade(f=>({...f,[key]:{...f[key],...value}}));setError('')}
    function preview(){try{const candidate=facadeCandidate(scene,facade,replaceFront?options:undefined);onPreview(candidate,`${sign.enabled?'간판 적용':'간판 숨김'} · ${awning.enabled?'어닝 적용':'어닝 숨김'}${replaceFront?` · 기존 전면 문·창문 ${frontCount}개를 유리 전면 구성으로 교체`:''}`)}catch(e){setError(e instanceof Error&&e.name!=='ZodError'?e.message:'문구·색상·치수 범위를 확인하세요.')}}
    return <Dialog open onOpenChange={o=>!o&&onClose()}><DialogContent className="facade-dialog"><DialogHeader><DialogTitle><Store size={21}/>매장 외관 편집</DialogTitle><DialogDescription>간판과 어닝을 꾸미고, 외부 시점에서 적용 전·후를 비교하세요.</DialogDescription></DialogHeader>
        <div className="facade-room-summary"><span>전면 폭 <b>{scene.room.width.toLocaleString()}mm</b></span><span>매장 높이 <b>{scene.room.height.toLocaleString()}mm</b></span></div>
        <Tabs value={tab} onValueChange={v=>setTab(v as typeof tab)}><TabsList className="facade-tabs"><TabsTrigger value="sign">간판</TabsTrigger><TabsTrigger value="awning">어닝</TabsTrigger><TabsTrigger value="front">유리 전면</TabsTrigger></TabsList>
            <TabsContent value="sign"><div className="facade-section-heading"><b>문구와 소재</b><label className="switch-row"><span>간판 표시</span><Switch checked={sign.enabled} onCheckedChange={enabled=>patch('sign',{enabled})}/></label></div>
                <fieldset disabled={!sign.enabled}><label className="field-label">간판 문구<input className="text-input" value={sign.text} maxLength={60} onChange={e=>patch('sign',{text:e.target.value})} placeholder="매장 이름을 입력하세요"/></label><div className="facade-fields"><label className="field-label">글자 스타일<Select value={sign.font} onValueChange={font=>patch('sign',{font:font as typeof sign.font})} disabled={!sign.enabled}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="sans">볼드 산세리프</SelectItem><SelectItem value="serif">클래식 세리프</SelectItem><SelectItem value="condensed">좁고 굵은 글자</SelectItem></SelectContent></Select></label><label className="field-label">간판 소재<Select value={sign.material} disabled={!sign.enabled} onValueChange={id=>{const m=materials.find(m=>m.id===id)!;patch('sign',{material:m.id,color:m.color})}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{materials.filter(m=>m.id!=='glass').map(m=><SelectItem key={m.id} value={m.id}>{m.name}</SelectItem>)}</SelectContent></Select></label><Color label="간판 색상" value={sign.color} onChange={color=>patch('sign',{color})}/><Color label="글자 색상" value={sign.textColor} onChange={textColor=>patch('sign',{textColor})}/></div><label className="switch-row"><span>발광 문자 표현</span><Switch disabled={!sign.enabled} checked={sign.illuminated} onCheckedChange={illuminated=>patch('sign',{illuminated})}/></label>
                <div className="facade-section-heading"><b>간판 크기와 위치</b><button className="text-button" type="button" onClick={()=>patch('sign',{width:scene.room.width-200,x:0})}>전면 폭에 맞춤</button></div><div className="facade-fields three"><Dimension label="가로" value={sign.width} min={600} max={scene.room.width-200} onChange={width=>patch('sign',{width})}/><Dimension label="높이" value={sign.height} min={100} max={1400} onChange={height=>patch('sign',{height})}/><Dimension label="두께" value={sign.depth} min={40} max={400} onChange={depth=>patch('sign',{depth})}/><Dimension label="좌우 위치 · 중앙 0" value={sign.x} onChange={x=>patch('sign',{x})}/><Dimension label="바닥~간판 하단" value={sign.bottom} min={0} max={scene.room.height-sign.height} onChange={bottom=>patch('sign',{bottom})}/></div></fieldset><p className="fineprint">간판은 입력한 문구를 표시합니다. 전용 로고 파일이나 입체 채널 문자는 포함하지 않습니다.</p>
            </TabsContent>
            <TabsContent value="awning"><div className="facade-section-heading"><b>천과 색상</b><label className="switch-row"><span>어닝 표시</span><Switch checked={awning.enabled} onCheckedChange={enabled=>patch('awning',{enabled})}/></label></div><fieldset disabled={!awning.enabled}><label className="switch-row"><span>스트라이프 무늬</span><Switch disabled={!awning.enabled} checked={awning.striped} onCheckedChange={striped=>patch('awning',{striped})}/></label><div className="facade-fields"><Color label="기본 색상" value={awning.color} onChange={color=>patch('awning',{color})}/>{awning.striped&&<Color label="줄무늬 색상" value={awning.stripeColor} onChange={stripeColor=>patch('awning',{stripeColor})}/>}</div><div className="facade-section-heading"><b>어닝 크기와 높이</b><button className="text-button" type="button" onClick={()=>patch('awning',{width:scene.room.width-200,x:0})}>전면 폭에 맞춤</button></div><div className="facade-fields three"><Dimension label="가로" value={awning.width} min={600} max={scene.room.width-200} onChange={width=>patch('awning',{width})}/><Dimension label="앞으로 돌출" value={awning.projection} min={200} max={2400} onChange={projection=>patch('awning',{projection})}/><Dimension label="좌우 위치 · 중앙 0" value={awning.x} onChange={x=>patch('awning',{x})}/><Dimension label="벽 설치 높이" value={awning.mount} min={1000} max={scene.room.height} onChange={mount=>patch('awning',{mount})}/><Dimension label="경사로 내려가는 높이" value={awning.drop} min={0} max={1200} onChange={drop=>patch('awning',{drop})}/><Dimension label="앞단 천 길이" value={awning.valance} min={0} max={400} onChange={valance=>patch('awning',{valance})}/>{awning.striped&&<Dimension label="줄무늬 한 칸" value={awning.stripeWidth} min={80} max={500} onChange={stripeWidth=>patch('awning',{stripeWidth})}/>}</div><div className="facade-clearance"><Info size={17}/><div><b>어닝 하단 높이 {Number.isFinite(dimensions.clearance)?Math.round(dimensions.clearance).toLocaleString():'—'}mm</b><span>벽 설치 높이에서 경사와 앞단 천 길이를 뺀 값입니다.</span></div></div></fieldset></TabsContent>
            <TabsContent value="front"><div className="facade-section-heading"><b>유리 전면 구성</b><label className="switch-row"><span>이번 안에 포함</span><Switch checked={replaceFront} onCheckedChange={setReplaceFront}/></label></div><p className="section-description">전면에 유리 출입문과 창문을 배치합니다. 적용하면 기존 전면 문·창문 {frontCount}개가 새 구성으로 바뀝니다.</p><fieldset disabled={!replaceFront}><div className="facade-fields"><label className="field-label">출입문 위치<Select disabled={!replaceFront} value={options.doorPosition} onValueChange={doorPosition=>setOptions(o=>({...o,doorPosition:doorPosition as typeof o.doorPosition}))}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="left">외부에서 왼쪽</SelectItem><SelectItem value="center">중앙</SelectItem><SelectItem value="right">외부에서 오른쪽</SelectItem></SelectContent></Select></label><Dimension label="출입문 너비" value={options.doorWidth} min={700} max={1800} onChange={doorWidth=>setOptions(o=>({...o,doorWidth}))}/><label className="field-label">창문·문 프레임<Select disabled={!replaceFront} value={options.frameMaterial} onValueChange={frameMaterial=>setOptions(o=>({...o,frameMaterial:frameMaterial as typeof o.frameMaterial}))}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="charcoal">매트 차콜</SelectItem><SelectItem value="oak">내추럴 오크</SelectItem><SelectItem value="steel">브러시드 스틸</SelectItem></SelectContent></Select></label></div></fieldset><p className="fineprint">사진 인식 결과가 아닌 표준 배치 제안입니다. 적용 후 개별 창문과 문을 선택해 치수·소재를 바꿀 수 있습니다.</p></TabsContent>
        </Tabs>
        {error&&<p className="form-error" role="alert">{error}</p>}
        <div className="facade-dialog-footer"><p>입력값은 외관 미리보기에서 적용한 뒤 저장됩니다.</p><button className="outline-button" onClick={onClose}>닫기</button><button className="primary-button" onClick={preview}><Eye size={17}/>외관 미리보기</button></div>
    </DialogContent></Dialog>;
}
