'use client';
import {useMemo,useState} from 'react';
import {Download,Printer,ZoomIn,ZoomOut} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Switch} from '@/components/ui/switch';
import {floorPlanSvg,floorPlanCsv,floorPlanPrintHtml,planScale} from '@/lib/floor-plan';
import type {SceneData} from '@/lib/scene-model';
function saveFile(content:string,type:string,name:string){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000)}
export default function FloorPlanDialog({open,onClose,scene}:{open:boolean;onClose:()=>void;scene:SceneData}){
 const [scale,setScale]=useState('auto'),[labels,setLabels]=useState(true),[dimensions,setDimensions]=useState(true),[upper,setUpper]=useState(true),[zoom,setZoom]=useState(1),[error,setError]=useState('');const options={scale:scale==='auto'?undefined:Number(scale),labels,dimensions,upper};
 const computed=useMemo(()=>{if(!open)return{svg:'',scale:0,error:''};try{return{svg:floorPlanSvg(scene,scene.name,options),scale:planScale(scene,options.scale),error:''}}catch(e){return{svg:'',scale:0,error:(e as Error).message}}},[open,scene,scale,labels,dimensions,upper]);
 function print(){setError('');const popup=window.open('','_blank');if(!popup){setError('인쇄 창이 차단되었습니다. 이 사이트의 팝업을 허용한 뒤 다시 시도하세요.');return}popup.opener=null;popup.document.write(floorPlanPrintHtml(scene,scene.name,options));popup.document.close();popup.document.fonts.ready.then(()=>{popup.focus();popup.print()})}
 return <Dialog open={open} onOpenChange={o=>!o&&onClose()}><DialogContent className="plan-dialog"><DialogHeader><DialogTitle>치수 평면도</DialogTitle><DialogDescription>배치와 개구부를 확인하고, 가구 치수 목록과 함께 내려받으세요.</DialogDescription></DialogHeader><div className="plan-controls"><label className="field-label">출력 축척<Select value={scale} onValueChange={setScale}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="auto">A3에 자동 맞춤</SelectItem>{[25,50,75,100,150,200].map(s=><SelectItem key={s} value={String(s)}>1:{s}</SelectItem>)}</SelectContent></Select></label><label className="switch-row"><span>요소 번호</span><Switch checked={labels} onCheckedChange={setLabels}/></label><label className="switch-row"><span>치수 표시</span><Switch checked={dimensions} onCheckedChange={setDimensions}/></label><label className="switch-row"><span>상부 요소</span><Switch checked={upper} onCheckedChange={setUpper}/></label><div className="plan-zoom"><button aria-label="도면 축소" onClick={()=>setZoom(Math.max(.75,zoom-.25))}><ZoomOut size={17}/></button><span>{Math.round(zoom*100)}%</span><button aria-label="도면 확대" onClick={()=>setZoom(Math.min(2.5,zoom+.25))}><ZoomIn size={17}/></button></div></div>{computed.error?<p className="form-error" role="alert">{computed.error}</p>:<div className="plan-scroll"><div className="plan-paper" style={{width:`${1100*zoom}px`}} dangerouslySetInnerHTML={{__html:computed.svg}}/></div>}<div className="plan-footer"><p>A3 · 1:{computed.scale||'—'} · 벽 중심선 기준<br/><span>시공 도면이 아닙니다. 외부 모델은 외곽으로 표시하며 전체 치수 목록은 인쇄·CSV에 포함됩니다.</span></p><div><button className="outline-button" disabled={!computed.svg} onClick={()=>saveFile(floorPlanCsv(scene,upper),'text/csv;charset=utf-8',`${scene.name}-가구목록.csv`)}><Download size={15}/>목록 CSV</button><button className="outline-button" disabled={!computed.svg} onClick={()=>saveFile(computed.svg,'image/svg+xml',`${scene.name}-평면도.svg`)}><Download size={15}/>도면 SVG</button><button className="primary-button" disabled={!computed.svg} onClick={print}><Printer size={16}/>인쇄 / PDF 저장</button></div></div>{error&&<p className="form-error" role="alert">{error}</p>}</DialogContent></Dialog>
}
