'use client';
import {useState} from 'react';
import {Box,Layers,ChevronRight,ChevronDown,Eye,EyeOff,Lock,Unlock,Pencil} from 'lucide-react';
import {sceneGroups,selectionIds} from '@/lib/selection';
import type {SceneData,SceneNode,Selection} from '@/lib/scene-model';

export default function FurnitureTree({scene,selection,editingGroupId,onSelect,onSelectGroup,onEdit,onState}:{scene:SceneData;selection:Selection;editingGroupId:string|null;onSelect:(s:Selection,additive?:boolean)=>void;onSelectGroup:(id:string,additive:boolean)=>void;onEdit:(id:string,nodeId?:string)=>void;onState:(ids:string[],key:'hidden'|'locked',value:boolean)=>void}){
 const [expanded,setExpanded]=useState<string[]>([]),ids=selectionIds(selection),groups=sceneGroups(scene);
 function row(n:SceneNode,inside=false){return <div className={`tree-object ${ids.includes(n.id)?'selected':''}`} key={n.id}><button className="tree-label" onClick={e=>inside&&n.group&&editingGroupId!==n.group.id?onEdit(n.group.id,n.id):onSelect({id:n.id},e.shiftKey)} title={inside?'그룹 안에서 가구 편집':n.name}><Box size={14}/><span>{n.name}</span>{n.locked&&<Lock size={12}/>}</button>{(!inside||editingGroupId===n.group?.id)&&<button aria-label={`${n.name} ${n.hidden?'표시':'숨기기'}`} onClick={()=>onState([n.id],'hidden',!n.hidden)}>{n.hidden?<EyeOff size={14}/>:<Eye size={14}/>}</button>}</div>}
 return <>{groups.map(g=>{const open=expanded.includes(g.id)||editingGroupId===g.id,allSelected=g.nodes.every(n=>ids.includes(n.id)),someSelected=g.nodes.some(n=>ids.includes(n.id)),allHidden=g.nodes.every(n=>n.hidden),allLocked=g.nodes.every(n=>n.locked);return <div className={`tree-group ${editingGroupId===g.id?'editing':''}`} key={g.id}><div className={`tree-group-header ${allSelected?'selected':someSelected?'partial':''}`}><button className="tree-expand" aria-label={`${g.name} 구성 ${open?'접기':'보기'}`} aria-expanded={open} onClick={()=>setExpanded(a=>a.includes(g.id)?a.filter(id=>id!==g.id):[...a,g.id])} disabled={editingGroupId===g.id}>{open?<ChevronDown size={14}/>:<ChevronRight size={14}/>}</button><button className="tree-group-name" onClick={e=>onSelectGroup(g.id,e.shiftKey)} title={g.name}><Layers size={14}/><span>{g.name}</span><small>{g.nodes.length}</small></button><button aria-label={`${g.name} 안 편집`} onClick={()=>onEdit(g.id)}><Pencil size={13}/></button><button aria-label={`${g.name} 전체 ${allLocked?'잠금 해제':'잠금'}`} onClick={()=>onState(g.nodes.map(n=>n.id),'locked',!allLocked)}>{allLocked?<Lock size={13}/>:<Unlock size={13}/>}</button><button aria-label={`${g.name} 전체 ${allHidden?'표시':'숨기기'}`} onClick={()=>onState(g.nodes.map(n=>n.id),'hidden',!allHidden)}>{allHidden?<EyeOff size={13}/>:<Eye size={13}/>}</button></div>{open&&<div className="tree-group-children">{g.nodes.map(n=>row(n,true))}</div>}</div>})}{scene.nodes.filter(n=>!n.group).map(n=>row(n))}</>;
}
