'use client';
import {useEffect,useRef,useState} from 'react';
import {Link2,LoaderCircle} from 'lucide-react';
type Status={connected:boolean;endpoint?:string;model?:string;verifiedAt?:string;storageReady?:boolean};
type Job={id:string;status:string;purpose:string;created_at:number;cancel_requested:number};
const done=(s:string)=>['completed','failed','cancelled'].includes(s);
const labels:Record<string,string>={pending:'접수 확인 중',started:'시작됨',queued:'대기 중',running:'분석 중',waiting:'대기 중',waiting_approval:'승인 대기',waiting_for_approval:'승인 대기',stopping:'중지 확인 중',completed:'완료',failed:'실패',cancelled:'취소됨'};
async function api(url:string,options?:RequestInit){const r=await fetch(url,options),d=await r.json() as any;if(!r.ok)throw new Error(d.error||'Hermes 연결을 확인하지 못했습니다.');return d;}
export default function HermesConnection({onChanged}:{onChanged:()=>Promise<void>}){
 const [status,setStatus]=useState<Status>({connected:false}),[endpoint,setEndpoint]=useState(''),[token,setToken]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[message,setMessage]=useState(''),[error,setError]=useState(''),[jobs,setJobs]=useState<Job[]>([]);const flight=useRef(false),alive=useRef(true);
 async function refresh(){const s=await api('/api/hermes'),j=await api('/api/hermes/jobs');if(alive.current){setStatus(s);setEndpoint(s.endpoint||'');setJobs(j.jobs);}}
 useEffect(()=>{alive.current=true;refresh().catch(e=>{if(alive.current)setError(e.message)}).finally(()=>{if(alive.current)setLoading(false)});return()=>{alive.current=false;};},[]);
 async function act(fn:()=>Promise<void>){if(flight.current)return;flight.current=true;setBusy(true);setError('');setMessage('');try{await fn();}catch(e){if(alive.current)setError((e as Error).message);}finally{flight.current=false;if(alive.current)setBusy(false);}}
 return <section className="hermes-connection"><div className="connection-status"><Link2 size={20}/><div><b>{loading?'Hermes 연결 확인 중':status.connected?'Hermes 연결 확인됨':'Hermes 에이전트'}</b><p>{status.connected?`${status.model} · ${status.endpoint}`:'Orbit에서 사용하는 HTTPS 주소와 연결 암호를 입력하세요.'}</p></div></div><p className="fineprint">문장으로 공간 편집 · 매장 사진 초안 · 물체 사진 분석에 사용합니다. Hermes에 설정된 모델과 인증을 그대로 사용합니다. 사진 분석에는 해당 모델의 이미지 이해 기능이 필요합니다.</p><label className="field-label">Hermes 연결 주소<input className="text-input" type="url" autoComplete="off" placeholder="https://…/p/프로필명" value={endpoint} disabled={busy} onChange={e=>setEndpoint(e.target.value)}/></label><label className="field-label">Hermes 연결 암호<input className="text-input" type="password" autoComplete="off" placeholder={status.connected?'기존 암호를 다시 입력해 확인':'API_SERVER_KEY'} value={token} disabled={busy} onChange={e=>setToken(e.target.value)}/></label><p className="fineprint">암호는 계정별로 암호화해 보관합니다. 장면과 선택한 사진은 입력한 Hermes와 해당 모델 제공자에게 전송됩니다. 연결 확인은 실행 기능과 암호 보호를 검사하며, 실제 분석 성공은 첫 요청에서 확인합니다.</p>{error&&<p className="inline-error" role="alert">{error}</p>}{message&&<p className="fineprint" role="status">{message}</p>}<button className="primary-button full" disabled={loading||busy||!endpoint.trim()||token.trim().length<20} onClick={()=>act(async()=>{await api('/api/hermes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({endpoint,token})});setToken('');await refresh();await onChanged();setMessage('Hermes 연결을 확인해 저장했습니다. 이전 작업으로 돌아가 분석을 시작하세요.');})}>{busy?<LoaderCircle className="spin" size={16}/>:<Link2 size={16}/>}Hermes 연결 확인·저장</button>{status.connected&&<button className="text-button full" disabled={busy} onClick={()=>act(async()=>{await api('/api/hermes',{method:'DELETE'});await refresh();await onChanged();setMessage('Hermes 연결을 해제했습니다.');})}>Hermes 연결 해제</button>}{jobs.length>0&&<details><summary>최근 Hermes 요청 ({jobs.length})</summary><p className="fineprint">창을 닫아도 접수된 요청은 계속될 수 있습니다. 완료된 분석은 원래 기능에서 같은 내용으로 다시 요청해 가져옵니다. 중지는 완료 상태를 확인한 뒤 확정됩니다.</p>{jobs.map(j=><div key={j.id} className="hermes-job"><div><b>{j.purpose.endsWith('object-photo')?'물체 사진':j.purpose.endsWith('photo-draft')?'공간 초안':'문장 편집'}</b> · {labels[j.status]||j.status}{j.cancel_requested&&!done(j.status)?' · 중지 요청됨':''}<small>{new Date(j.created_at).toLocaleString('ko-KR')}</small></div><button className="outline-button" disabled={busy} onClick={()=>act(async()=>{await api('/api/hermes/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:j.id,action:'poll'})});await refresh();})}>상태 확인</button>{!done(j.status)&&<button className="outline-button" disabled={busy} onClick={()=>act(async()=>{await api('/api/hermes/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:j.id,action:'stop'})});await refresh();})}>중지</button>}</div>)}</details>}</section>;
}
