'use client';
import {useEffect,useRef,useState} from 'react';
import {Upload,ImagePlus,LoaderCircle,RefreshCw,Check} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {prepareImage,type ImageAsset} from '@/lib/image-assets';

export default function ImagePicker({title,currentId,onClose,onSelect}:{title:string;currentId?:string|null;onClose:()=>void;onSelect:(image:ImageAsset)=>void}) {
    const [items,setItems]=useState<ImageAsset[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');
    const input=useRef<HTMLInputElement>(null),alive=useRef(true),flight=useRef(false),controller=useRef<AbortController|null>(null);
    useEffect(()=>{alive.current=true;void load();return()=>{alive.current=false;controller.current?.abort();}},[]);
    async function load(){setLoading(true);setError('');try{const response=await fetch('/api/images');const data=await response.json() as {images:ImageAsset[];error?:string};if(!response.ok)throw new Error(data.error||'이미지를 불러오지 못했습니다.');if(alive.current)setItems(data.images);}catch(e){if(alive.current)setError((e as Error).message);}finally{if(alive.current)setLoading(false);}}
    async function upload(file?:File){if(!file||flight.current)return;flight.current=true;setBusy(true);setError('');try{const blob=await prepareImage(file);if(!alive.current)return;controller.current=new AbortController();const response=await fetch(`/api/images?name=${encodeURIComponent(file.name.slice(0,100))}`,{method:'POST',headers:{'Content-Type':blob.type},body:blob,signal:controller.current.signal});const data=await response.json() as ImageAsset & {error?:string};if(!response.ok)throw new Error(data.error||'이미지를 올리지 못했습니다.');if(alive.current)onSelect(data);}catch(e){if(alive.current)setError((e as Error).message);}finally{flight.current=false;if(alive.current)setBusy(false);if(input.current)input.current.value='';}}
    return <Dialog open onOpenChange={open=>!open&&onClose()}><DialogContent className="image-picker-dialog" onDragOver={e=>{if(e.dataTransfer.types.includes('Files'))e.preventDefault()}} onDrop={e=>{e.preventDefault();e.stopPropagation();void upload(e.dataTransfer.files?.[0])}}><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>PNG·JPG를 이 창에 끌어 놓거나 내 이미지 보관함에서 선택하세요.</DialogDescription></DialogHeader><input type="file" ref={input} accept="image/png,image/jpeg" hidden onChange={e=>void upload(e.target.files?.[0])}/><div className="image-picker-actions"><button className="primary-button" disabled={busy} onClick={()=>input.current?.click()}>{busy?<LoaderCircle className="spin" size={17}/>:<Upload size={17}/>} {busy?'이미지 준비·저장 중…':'이미지 업로드하고 사용'}</button><button className="text-button" disabled={loading||busy} onClick={()=>void load()}><RefreshCw size={15}/>새로고침</button></div><p className="fineprint">원본 8MB 이하 · 최대 2,048px로 조정하여 보관 · 투명 PNG 지원 · 소재·로고·도면·물체 사진 합계 8개</p>{error&&<p role="alert" className="form-error">{error}</p>}{loading?<div className="image-picker-empty"><LoaderCircle className="spin"/><p>이미지 불러오는 중</p></div>:!items.length?<div className="image-picker-empty"><ImagePlus size={30}/><b>로고·소재·물체 사진을 올려 보세요</b><p>보관한 이미지는 다른 프로젝트에서도 사용할 수 있습니다.</p></div>:<div className="image-picker-grid">{items.map(item=><button disabled={busy} key={item.id} className={currentId===item.id?'selected':''} onClick={()=>onSelect(item)}><span className="image-checker"><img src={`/api/assets?id=${item.id}`} alt={item.name} loading="lazy"/>{currentId===item.id&&<i><Check size={15}/></i>}</span><b>{item.name}</b><small>{item.metadata.width} × {item.metadata.height}px</small></button>)}</div>}<p className="fineprint">이미지 선택 후 프로젝트를 저장하면 적용 위치와 반복 크기도 함께 보관됩니다.</p></DialogContent></Dialog>;
}
