'use client';
import {useEffect,useState} from 'react';
import {Layers,Plus,Check,Eye,EyeOff,Lock,Unlock,Trash2,MousePointer2,Focus,Undo2,Redo2,X} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {layerRows,layerColors,availableLayerPresets,type LayerRow,type LayerAction} from '@/lib/layers';
import {expandGroupIds,selectionIds} from '@/lib/selection';
import type {SceneData,Selection} from '@/lib/scene-model';

function LayerCard({row,selection,canAssign,onAssign,onEdit,onSelect}:{row:LayerRow;selection:string[];canAssign:boolean;onAssign:(id:string|null)=>boolean;onEdit:(id:string|null,action:LayerAction)=>boolean;onSelect:(id:string|null)=>void}){
 const [name,setName]=useState(row.name),[color,setColor]=useState(row.color),[deleting,setDeleting]=useState(false);
 useEffect(()=>{setName(row.name);setColor(row.color)},[row.name,row.color]);
 const count=row.nodes.length,allHidden=count>0&&row.shown===0,allLocked=count>0&&row.locked===count,selected=row.nodes.filter(n=>selection.includes(n.id)).length;
 return <article className={`layer-card ${selected?'has-selection':''}`}><div className="layer-card-head">{row.id?<form onSubmit={e=>{e.preventDefault();onEdit(row.id,{type:'rename',name,color})}}><input aria-label={`${row.name} 레이어 색상`} type="color" value={color} onChange={e=>setColor(e.target.value)}/><input aria-label={`${row.name} 레이어 이름`} className="text-input" maxLength={50} value={name} onChange={e=>setName(e.target.value)}/><button className="outline-button" aria-label={`${row.name} 이름·색상 저장`} disabled={!name.trim()||name.trim()===row.name&&color===row.color}><Check size={15}/></button></form>:<div className="unassigned-name"><i style={{background:row.color}}/><b>미분류</b><small>아직 레이어를 지정하지 않은 요소</small></div>}<strong>{count}<small>개</small></strong></div><div className="layer-card-meta"><span>표시 {row.shown}/{count}</span><span>잠금 {row.locked}/{count}</span>{selected>0&&<b>선택 {selected}개 포함</b>}{count>0&&(row.shown>0&&row.shown<count||row.locked>0&&row.locked<count)&&<em>상태가 섞여 있음</em>}</div><div className="layer-card-actions"><button className="outline-button" disabled={!canAssign} onClick={()=>onAssign(row.id)}><Plus size={14}/>선택 요소 배정</button><button className="outline-button" disabled={!count} onClick={()=>onSelect(row.id)}><MousePointer2 size={14}/>가구 선택</button><button className="outline-button" disabled={!count} onClick={()=>onEdit(row.id,{type:'hidden',value:!allHidden})}>{allHidden?<Eye size={14}/>:<EyeOff size={14}/>}전체 {allHidden?'표시':'숨김'}</button><button className="outline-button" disabled={!count} onClick={()=>onEdit(row.id,{type:'locked',value:!allLocked})}>{allLocked?<Unlock size={14}/>:<Lock size={14}/>}전체 {allLocked?'해제':'잠금'}</button><button className="outline-button" disabled={!count} onClick={()=>onEdit(row.id,{type:'isolate'})}><Focus size={14}/>이 레이어만 보기</button>{row.id&&<button className="layer-delete" aria-label={`${row.name} 레이어 삭제`} onClick={()=>setDeleting(!deleting)}><Trash2 size={16}/></button>}</div>{deleting&&<div className="layer-delete-confirm"><p>레이어만 삭제합니다. 가구 {count}개는 배치를 유지한 채 미분류로 이동합니다.</p><div><button className="outline-button" onClick={()=>setDeleting(false)}>취소</button><button className="outline-button" onClick={()=>onEdit(row.id,{type:'delete'})}>레이어 삭제</button></div></div>}</article>;
}
export default function LayersDialog({scene,selection,onClose,onCreate,onAssign,onEdit,onSelect,onUndo,onRedo,canUndo,canRedo}:{scene:SceneData;selection:Selection;onClose:()=>void;onCreate:(name:string,color:string,includeSelection:boolean)=>boolean;onAssign:(id:string|null)=>boolean;onEdit:(id:string|null,action:LayerAction)=>boolean;onSelect:(id:string|null)=>void;onUndo:()=>void;onRedo:()=>void;canUndo:boolean;canRedo:boolean}){
 const ids=selectionIds(selection).filter(id=>scene.nodes.some(n=>n.id===id)),members=expandGroupIds(scene,ids),locked=scene.nodes.some(n=>members.includes(n.id)&&n.locked),rows=layerRows(scene);
 const [name,setName]=useState(''),[color,setColor]=useState(layerColors[(scene.layers?.length??0)%layerColors.length]),[include,setInclude]=useState(ids.length>0&&!locked),[query,setQuery]=useState('');
 const presets=availableLayerPresets(scene),matches=rows.filter(row=>row.name.toLowerCase().includes(query.trim().toLowerCase())),canAssign=members.length>0&&!locked;
 return <Dialog open onOpenChange={o=>!o&&onClose()}><DialogContent className="layers-dialog" showCloseButton={false}><DialogHeader><div className="layers-title"><DialogTitle><Layers size={22}/>레이어 관리</DialogTitle><div><button aria-label="이전 작업 실행 취소" className="outline-button" disabled={!canUndo} onClick={onUndo}><Undo2 size={16}/></button><button aria-label="이전 작업 다시 실행" className="outline-button" disabled={!canRedo} onClick={onRedo}><Redo2 size={16}/></button><button aria-label="레이어 관리 닫기" className="outline-button" onClick={onClose}><X size={16}/></button></div></div><DialogDescription>가구·문·창문을 용도별로 분류하고 함께 표시하거나 잠그세요.</DialogDescription></DialogHeader><div className="layer-selection-summary"><b>{ids.length?`${ids.length}개 선택`:'선택한 가구 없음'}</b><span>{members.length>ids.length?`그룹을 포함해 ${members.length}개를 함께 배정합니다.`:'가구를 선택한 뒤 이 창을 열면 원하는 레이어에 배정할 수 있습니다.'}</span>{locked&&<strong>잠긴 가구가 포함되어 있어 배정을 바꿀 수 없습니다.</strong>}</div><form className="layer-create" onSubmit={e=>{e.preventDefault();if(onCreate(name,color,include&&canAssign)){setName('');setColor(layerColors[((scene.layers?.length??0)+1)%layerColors.length]);setQuery('');}}}><div><input type="color" aria-label="새 레이어 색상" value={color} onChange={e=>setColor(e.target.value)}/><input className="text-input" aria-label="새 레이어 이름" maxLength={50} placeholder="예: 고객 좌석 · 주방 설비 · 조명" value={name} onChange={e=>setName(e.target.value)}/><button className="primary-button" disabled={!name.trim()||(scene.layers?.length??0)>=20}><Plus size={16}/>레이어 만들기</button></div><div className="layer-create-options"><label><Checkbox checked={include&&canAssign} disabled={!canAssign} onCheckedChange={v=>setInclude(v===true)}/>선택 요소 {members.length}개 포함</label><span>{scene.layers?.length??0}/20개</span></div>{presets.length>0&&<div className="layer-presets"><span>빠른 이름</span>{presets.map(p=><button type="button" key={p.name} onClick={()=>{setName(p.name);setColor(p.color)}}><i style={{background:p.color}}/>{p.name}</button>)}</div>}</form><div className="layer-list-heading"><b>레이어 목록</b><input className="text-input" aria-label="레이어 검색" placeholder="레이어 이름 검색" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="layer-list">{matches.map(row=><LayerCard key={row.id??'unassigned'} row={row} selection={members} canAssign={canAssign} onAssign={onAssign} onEdit={onEdit} onSelect={onSelect}/>)}{!matches.length&&<p className="empty-copy">검색한 레이어가 없습니다.</p>}</div><div className="layer-guide"><p>그룹은 레이어를 함께 옮깁니다. 새로 배정하는 가구의 표시·잠금 상태는 유지됩니다. ‘전체 표시·숨김·잠금’은 현재 레이어의 요소에 적용됩니다.</p><p>‘이 레이어만 보기’는 해당 요소를 표시하고 나머지 가구·문·창문을 숨깁니다. 벽·바닥·간판·어닝은 유지됩니다. 표시·잠금·분류 변경은 실행 취소로 복원할 수 있습니다.</p></div><button className="primary-button layer-done" onClick={onClose}>3D 공간으로 돌아가기</button></DialogContent></Dialog>;
}
