'use client';
import {useMemo,useState} from 'react';
import {ArrowRight,Check,Eye,Lock,Palette,Search} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import MaterialDetail from './material-detail';
import {finishImageUrl,finishTextureKey} from '@/lib/material-products';
import {materials,type SceneData,type Selection} from '@/lib/scene-model';
import {selectionIds} from '@/lib/selection';
import {materialRows,scopedMaterialUses,planMaterialReplacement,type FinishChoice,type MaterialPlan,type MaterialRow,type MaterialScope} from '@/lib/material-board';
import type {MaterialSlot} from '@/lib/material-catalog';
function Swatch({row}:{row:MaterialRow|FinishChoice}){
    const base=materials.find(m=>m.id===row.material)!;
    return <span className={`board-swatch pattern-${base.pattern}`} style={{backgroundColor:'color' in row?row.color:row.finish.color??base.color}}>{finishImageUrl(row.finish)?<img src={finishImageUrl(row.finish)!} alt="소재 이미지"/>:'original' in row&&row.original?<Palette size={19}/>:null}</span>;
}
function finishLabel(row:MaterialRow){const f=row.finish;if(row.original)return ['모델 원본',f.color,f.roughness!==undefined?`광택 ${Math.round((1-f.roughness)*100)}%`:null,f.metalness!==undefined?`금속 ${Math.round(f.metalness*100)}%`:null].filter(Boolean).join(' · ');const b=materials.find(m=>m.id===row.material)!;return `${finishTextureKey(f)?'소재 사진':f.color??b.color} · 광택 ${Math.round((1-(f.roughness??b.roughness))*100)}% · 금속 ${Math.round((f.metalness??b.metalness)*100)}% · ${f.scale??900}mm · ${f.rotation??0}°`;}
export default function MaterialBoardDialog({scene,catalog,selection,onClose,onPreview}:{scene:SceneData;catalog:MaterialSlot[];selection:Selection;onClose:()=>void;onPreview:(plan:MaterialPlan,name:string)=>void}){
    const rows=useMemo(()=>materialRows(scene,catalog),[scene,catalog]);
    const initial=rows.find(r=>r.uses.some(u=>u.id===selection?.id&&(!selection?.face||u.face===selection.face)))??rows[0];
    const [source,setSource]=useState(initial?.key??''),[query,setQuery]=useState(''),[scope,setScope]=useState<MaterialScope>({kind:'all',includeHidden:false}),[omitted,setOmitted]=useState<string[]>([]),[error,setError]=useState('');
    const [replacement,setReplacement]=useState<FinishChoice>({material:initial?.material??'oak',finish:structuredClone(initial?.finish??{})});
    const row=rows.find(r=>r.key===source)??rows[0],uses=row?scopedMaterialUses(row,{...scope,ids:selectionIds(selection)}):[];
    const entries=useMemo(()=>{const map=new Map<string,{id:string;name:string;layer?:string;hidden:boolean;locked:boolean;keys:string[];hasUv:boolean}>();for(const u of uses){let e=map.get(u.id);if(!e){e={id:u.id,name:u.name,layer:u.face?(scene.layers?.find(l=>l.id===u.layerId)?.name??'미분류'):undefined,hidden:u.hidden,locked:u.locked,keys:[],hasUv:true};map.set(u.id,e);}e.keys.push(u.key);e.hasUv=e.hasUv&&u.hasUv;}return [...map.values()];},[uses,scene.layers]);
    const selected=entries.filter(e=>!e.locked&&!omitted.includes(e.id)),keys=selected.flatMap(e=>e.keys),locked=entries.filter(e=>e.locked).length;
    const resetScope=(next:MaterialScope)=>{setScope(next);setOmitted([]);setError('');};
    const chooseSource=(next:MaterialRow)=>{setSource(next.key);setOmitted([]);setError('');setReplacement({material:next.material,finish:structuredClone(next.finish)});};
    const filtered=rows.filter(r=>[r.name,finishLabel(r),...r.uses.map(u=>u.name)].join(' ').toLowerCase().includes(query.toLowerCase()));
    return <Dialog open onOpenChange={open=>!open&&onClose()}><DialogContent className="material-board-dialog"><DialogHeader><DialogTitle>소재 모아보기 · 한 번에 교체</DialogTitle><DialogDescription>같은 소재의 적용 위치를 확인하고, 바꿀 요소를 골라 3D에서 비교하세요.</DialogDescription></DialogHeader>
        <div className="material-board-layout"><aside className="material-board-sources"><div className="small-heading"><b>1. 현재 사용 중인 소재</b><span>{rows.length}종</span></div><div className="search-field"><Search size={15}/><input aria-label="사용 중인 소재 검색" value={query} onChange={e=>setQuery(e.target.value)} placeholder="소재명 또는 가구명"/></div><div className="material-source-list">{filtered.map(r=><button key={r.key} className={`material-source ${r.key===row?.key?'selected':''}`} onClick={()=>chooseSource(r)} aria-pressed={r.key===row?.key}><Swatch row={r}/><span><b>{r.name}</b><small>{finishLabel(r)}</small><small>{new Set(r.uses.map(u=>u.id)).size}개 요소 · {r.uses.length}개 소재 영역</small></span>{r.key===row?.key&&<Check size={14}/>}</button>)}{!filtered.length&&<p className="empty-copy">검색한 소재가 없습니다.</p>}</div><p className="fineprint">전체 장면의 소재입니다. 색상·광택·이미지·결 설정이 다르면 따로 표시합니다.</p></aside>
        <section className="material-board-targets"><div className="small-heading"><b>2. 교체할 범위</b><span>{selected.length}개 선택</span></div><div className="material-scope"><label className="field-label">대상 범위<select className="text-input" value={scope.kind} onChange={e=>resetScope({...scope,kind:e.target.value as MaterialScope['kind']})}><option value="all">벽·바닥·가구 전체</option><option value="nodes">가구·설비만</option><option value="room">벽·바닥만</option><option value="selection" disabled={!selection}>편집 화면에서 선택한 요소</option><option value="layer">특정 레이어</option></select></label>{scope.kind==='layer'&&<label className="field-label">레이어<select className="text-input" value={scope.layerId??''} onChange={e=>resetScope({...scope,layerId:e.target.value||null})}><option value="">미분류</option>{scene.layers?.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label>}<label className="material-check"><input type="checkbox" checked={scope.includeHidden} onChange={e=>resetScope({...scope,includeHidden:e.target.checked})}/>숨긴 요소도 포함</label></div>
        <div className="small-heading"><span>동일 소재가 있는 요소 {entries.length}개</span><button className="text-button" onClick={()=>{setOmitted(selected.length?entries.filter(e=>!e.locked).map(e=>e.id):[]);setError('');}}>{selected.length?'선택 해제':'가능한 요소 모두 선택'}</button></div>
        <div className="material-use-list">{entries.map(e=><label key={e.id} className={`material-use ${e.locked?'locked':''}`}><input type="checkbox" aria-label={`${e.name} 소재 교체 대상`} disabled={e.locked} checked={!e.locked&&!omitted.includes(e.id)} onChange={event=>{setOmitted(event.target.checked?omitted.filter(id=>id!==e.id):[...omitted,e.id]);setError('');}}/><span><b>{e.name}</b><small>{e.layer??'공간 표면'} · {e.keys.length}개 영역{!e.hasUv?' · 이미지 적용 불가':''}</small></span>{e.hidden&&<Eye size={14} aria-label="숨긴 요소"/>}{e.locked&&<Lock size={14} aria-label="잠긴 요소"/>}</label>)}{!entries.length&&<p className="empty-copy">이 범위에는 해당 소재가 없습니다.<br/>범위를 바꾸거나 다른 소재를 선택하세요.</p>}</div>
        <p className="fineprint">잠긴 요소 {locked}개는 제외합니다. 선택한 요소 안에서 위 소재와 일치하는 부위만 바뀝니다. 그룹의 다른 가구는 자동으로 추가하지 않습니다.</p></section>
        <section className="material-board-replacement"><div className="small-heading"><b>3. 바꿔볼 소재</b><Palette size={15}/></div><div className="material-board-presets">{materials.map(m=><button key={m.id} aria-label={`${m.name}으로 교체`} aria-pressed={replacement.material===m.id} className={replacement.material===m.id?'selected':''} onClick={()=>{setReplacement({material:m.id,finish:{}});setError('');}}><span className={`swatch pattern-${m.pattern}`} style={{backgroundColor:m.color}}/><small>{m.name}</small></button>)}</div><details className="material-finish-details"><summary>사진·색상·광택·결 설정</summary><MaterialDetail material={replacement.material} finish={replacement.finish} model={selected.some(e=>scene.nodes.find(n=>n.id===e.id)?.kind==='model')} onChange={finish=>{setReplacement({...replacement,finish:{...replacement.finish,...finish}});setError('');}}/></details><div className="material-swap"><Swatch row={row}/><ArrowRight size={16}/><Swatch row={replacement}/><span>{materials.find(m=>m.id===replacement.material)?.name}</span></div><p className="fineprint">새 소재의 설정으로 교체합니다. 3D 미리보기에서 변경 전·후를 비교한 뒤 적용하세요.</p></section></div>
        <div className="material-board-footer"><div><b>{selected.length}개 요소 · {keys.length}개 소재 영역 선택</b><p>벽·바닥은 한 표면을 한 영역으로 셉니다. 면적 산출은 포함하지 않습니다. 간판·어닝은 외관 편집에서 바꾸며, 전구는 교체 대상에서 제외됩니다.</p></div><button className="primary-button" disabled={!keys.length} onClick={()=>{try{const plan=planMaterialReplacement(scene,catalog,row.key,keys,replacement);if(!plan.changedRegions){setError('선택한 부위와 같은 소재 설정입니다. 다른 소재나 설정을 선택하세요.');return;}onPreview(plan,materials.find(m=>m.id===replacement.material)!.name);}catch(e){setError(e instanceof Error&&e.name!=='ZodError'?e.message:'소재 설정 값을 확인하세요.');}}}><Eye size={16}/>3D에서 비교</button></div>{error&&<p className="material-board-error" role="alert">{error}</p>}
    </DialogContent></Dialog>;
}
