'use client';
import {useEffect,useState} from 'react';
import {Ruler,Plus,Eye,EyeOff,Trash2,Check,LocateFixed,Download,Camera} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Switch} from '@/components/ui/switch';
import {anchorName,readMeasurement,distanceLabel,type Measurement} from '@/lib/measurements';
import type {SceneData} from '@/lib/scene-model';

function MeasurementRow({scene,m,onEdit,onFocus}:{scene:SceneData;m:Measurement;onEdit:(id:string,action:{type:'rename';name:string}|{type:'hidden';value:boolean}|{type:'delete'})=>boolean;onFocus:(id:string)=>void}){
 const [name,setName]=useState(m.name);useEffect(()=>setName(m.name),[m.name]);const value=readMeasurement(scene,m),anchors=[m.start,m.end],hiddenSource=anchors.some(a=>a.kind==='node'&&scene.nodes.find(n=>n.id===a.nodeId)?.hidden);
 return <article className={`measurement-card ${!value?'unavailable':''}`}><div className="measurement-card-main"><form className="measurement-name-form" onSubmit={e=>{e.preventDefault();if(!onEdit(m.id,{type:'rename',name}))setName(m.name)}}><input className="text-input" aria-label={`${m.name} 이름`} value={name} maxLength={80} onChange={e=>setName(e.target.value)}/><button className="outline-button" aria-label={`${m.name} 이름 저장`} disabled={!name.trim()||name.trim()===m.name}><Check size={15}/></button></form><strong>{value?distanceLabel(value.length):'연결 대상 없음'}</strong><p>{anchorName(scene,m.start)} <span>→</span> {anchorName(scene,m.end)}</p>{value?<div className="measurement-breakdown"><span>수평 {distanceLabel(value.horizontal)}</span><span>높이 차 {distanceLabel(value.y)}</span><span>X {distanceLabel(value.x)} · Z {distanceLabel(value.z)}</span></div>:<p className="measurement-missing">삭제한 가구를 실행 취소로 복원하면 치수도 다시 연결됩니다.</p>}</div><div className="measurement-row-actions"><button className="outline-button" disabled={!value||hiddenSource} onClick={()=>onFocus(m.id)}><LocateFixed size={15}/>위치 보기</button><button className="outline-button" disabled={!value} onClick={()=>onEdit(m.id,{type:'hidden',value:!m.hidden})}>{m.hidden?<EyeOff size={15}/>:<Eye size={15}/>} {m.hidden?'표시하기':'숨기기'}</button><button className="measurement-delete" aria-label={`${m.name} 삭제`} onClick={()=>onEdit(m.id,{type:'delete'})}><Trash2 size={16}/></button>{hiddenSource&&<small>연결 가구가 숨겨져 있습니다.</small>}</div></article>;
}
export default function MeasurementsDialog({scene,onClose,onAdd,onEdit,onFocus,visible,onVisible,onCsv,onPng,exporting}:{scene:SceneData;onClose:()=>void;onAdd:()=>void;onEdit:(id:string,action:{type:'rename';name:string}|{type:'hidden';value:boolean}|{type:'delete'})=>boolean;onFocus:(id:string)=>void;visible:boolean;onVisible:(v:boolean)=>void;onCsv:()=>void;onPng:()=>void;exporting:boolean}){
 const measurements=scene.measurements??[],valid=measurements.filter(m=>readMeasurement(scene,m)),shown=valid.filter(m=>!m.hidden&&[m.start,m.end].every(a=>a.kind==='room'||!scene.nodes.find(n=>n.id===a.nodeId)?.hidden));
 return <Dialog open onOpenChange={o=>!o&&onClose()}><DialogContent className="measurements-dialog"><DialogHeader><DialogTitle><Ruler size={22}/>줄자 · 치수 메모</DialogTitle><DialogDescription>3D 공간에서 두 점 사이의 직선 거리를 확인하고 저장하세요.</DialogDescription></DialogHeader><div className="measurements-toolbar"><button className="primary-button" disabled={measurements.length>=30} onClick={onAdd}><Plus size={16}/>두 점 찍어 측정</button><label className="measurement-visibility"><Switch checked={visible} onCheckedChange={onVisible} aria-label="3D 화면에 치수 표시"/>3D에 치수 표시</label><span>{measurements.length} / 30개</span></div><div className="measurement-guide">가구의 이동·회전을 따라 갱신됩니다. 크기 변경 시 측정점은 가구 안의 비례 위치를 따라갑니다. 표시값은 입력한 3D 치수 기준이며 현장 실측값이 아닙니다.</div><div className="measurements-list">{measurements.length?measurements.map(m=><MeasurementRow key={m.id} scene={scene} m={m} onEdit={onEdit} onFocus={onFocus}/>):<div className="measurements-empty"><Ruler size={36}/><b>확인하고 싶은 두 지점을 찍어보세요.</b><p>가구 사이 거리, 벽에서의 거리, 높이 차를 저장할 수 있습니다.</p></div>}</div><div className="measurements-footer"><p>치수 포함 PNG는 현재 시점에서 표시 가능한 치수 {shown.length}개를 담습니다.<br/>일반 PNG·GLB·AI 시안 캡처에는 치수가 들어가지 않습니다.</p><div><button className="outline-button" disabled={!measurements.length} onClick={onCsv}><Download size={15}/>치수 목록 CSV</button><button className="primary-button" disabled={!shown.length||exporting} onClick={onPng}><Camera size={15}/>{exporting?'이미지 준비 중…':'치수 포함 PNG'}</button></div></div></DialogContent></Dialog>;
}
