'use client';
import {useMemo,useRef,useState,type PointerEvent} from 'react';
import {DoorOpen,Eye,Plus,RotateCcw,Square,Trash2} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {materials,type SceneData} from '@/lib/scene-model';
import {partitionCells,openingKindNames,type PartitionOpening} from '@/lib/partition-openings-schema';
import {newPartitionOpening,planPartitionOpenings,type PartitionOpeningPlan} from '@/lib/partition-openings';

const explain=(e:unknown)=>e instanceof Error&&e.name!=='ZodError'?e.message:'개구부 이름과 치수의 입력 범위를 확인하세요.';
function Numeric({label,value,onChange,min,max}:{label:string;value:number;onChange:(v:number)=>void;min?:number;max?:number}){return <label className="field-label">{label}<input className="text-input" type="number" step="any" min={min} max={max} value={Number.isFinite(value)?value:''} onChange={e=>onChange(e.target.valueAsNumber)}/></label>;}
export default function PartitionOpeningsDialog({scene,nodeId,initial,onClose,onPreview}:{scene:SceneData;nodeId:string;initial?:PartitionOpening[];onClose:()=>void;onPreview:(plan:PartitionOpeningPlan)=>void}){
 const [base]=useState(()=>structuredClone(scene)),[targetId,setTargetId]=useState(nodeId);
 const target=base.nodes.find(n=>n.id===targetId)!,[openings,setOpenings]=useState<PartitionOpening[]>(()=>structuredClone(initial??target.openings??[])),[activeId,setActiveId]=useState(initial?.[0]?.id??target.openings?.[0]?.id??'');
 const [message,setMessage]=useState(''),pointer=useRef<{x:number;y:number;id:number}|null>(null);
 const active=openings.find(o=>o.id===activeId),dirty=JSON.stringify(openings)!==JSON.stringify(target.openings??[]),readonly=target.locked||target.hidden,stale=JSON.stringify(scene)!==JSON.stringify(base);
 const result=useMemo(()=>{try{return{plan:planPartitionOpenings(base,targetId,openings),error:''};}catch(e){return{plan:null,error:explain(e)};}},[base,targetId,openings]);
 const validTarget=result.plan?.scene.nodes.find(n=>n.id===targetId),display=validTarget??target,cells=partitionCells(display),w=target.width,h=target.height,pad=Math.max(w,h)*.075,font=Math.max(w,h)/55;
 const finite=(o:PartitionOpening)=>[o.x,o.bottom,o.width,o.height].every(Number.isFinite)&&o.width>0&&o.height>0;
 function patch(p:Partial<PartitionOpening>){if(!active||readonly)return;setOpenings(a=>a.map(o=>o.id===active.id?{...o,...p}:o));setMessage('');}
 function add(kind:PartitionOpening['kind']){try{const o=newPartitionOpening({...target,openings},kind);setOpenings(a=>[...a,o]);setActiveId(o.id);setMessage('');}catch(e){setMessage(explain(e));}}
 function selectTarget(id:string){const n=base.nodes.find(n=>n.id===id)!;setTargetId(id);setOpenings(structuredClone(n.openings??[]));setActiveId(n.openings?.[0]?.id??'');setMessage('');}
 function place(e:PointerEvent<SVGSVGElement>){
  const start=pointer.current;pointer.current=null;if(readonly||!start||start.id!==e.pointerId||e.button!==0||Math.hypot(e.clientX-start.x,e.clientY-start.y)>6)return;
  const matrix=e.currentTarget.getScreenCTM();if(!matrix)return;const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(matrix.inverse()),y=h-p.y;
  if(Math.abs(p.x)>w/2||y<0||y>h)return;
  const hit=openings.find(o=>finite(o)&&Math.abs(o.x-p.x)<=o.width/2&&y>=o.bottom&&y<=o.bottom+o.height);if(hit){setActiveId(hit.id);return;}
  if(active&&finite(active)){const extent=w/2-100-active.width/2;if(extent<0)return;patch({x:Math.max(-extent,Math.min(extent,Math.round(p.x/50)*50)),...(active.kind==='window'?{bottom:Math.max(100,Math.min(h-active.height-100,Math.round((y-active.height/2)/50)*50))}:{})});}
 }
 return <Dialog open onOpenChange={o=>!o&&onClose()}><DialogContent className="partition-opening-workbench"><DialogHeader><DialogTitle>파티션에 통로·문·창문 만들기</DialogTitle><DialogDescription>벽을 정면에서 보며 개구부를 배치하세요. 파티션을 움직이면 문과 창문도 함께 이동합니다.</DialogDescription></DialogHeader>
 <div className="partition-opening-target"><label className="field-label">편집할 파티션<select className="text-input" value={targetId} disabled={dirty} onChange={e=>selectTarget(e.target.value)}>{base.nodes.filter(n=>n.kind==='partition').map(n=><option key={n.id} value={n.id}>{n.name}{n.locked?' · 잠김':n.hidden?' · 숨김':''}</option>)}</select></label><span>{w.toLocaleString()} × {h.toLocaleString()} mm · 두께 {target.depth} mm</span>{dirty&&<button className="text-button" onClick={()=>selectTarget(targetId)}><RotateCcw size={14}/>이 벽 변경 취소</button>}</div>
 <div className="partition-opening-layout"><section className="partition-opening-preview"><div className="small-heading"><b>입면에서 위치 확인</b><span>중심선 X · 단위 mm</span></div>
 <svg className="partition-opening-elevation" viewBox={`${-w/2-pad} ${-pad} ${w+pad*2} ${h+pad*2}`} role="img" aria-label="파티션 정면과 개구부 위치. 아래 목록과 치수 입력으로도 편집할 수 있습니다." onPointerDown={e=>{pointer.current=e.button===0?{x:e.clientX,y:e.clientY,id:e.pointerId}:null;}} onPointerCancel={()=>{pointer.current=null;}} onPointerLeave={()=>{pointer.current=null;}} onPointerUp={place}>
  <rect x={-w/2} y={0} width={w} height={h} fill="#f9fbfb" stroke="#b9adc4" strokeDasharray="5 4" strokeWidth={1} vectorEffect="non-scaling-stroke"/>
  <g fill={target.finish?.color??target.color??materials.find(m=>m.id===target.material)!.color}>{cells.map((c,i)=><rect key={i} x={c.x-c.width/2} y={h-c.y-c.height/2} width={c.width} height={c.height}/>)}</g>
  {openings.filter(finite).map((o,i)=>{const left=o.x-o.width/2,top=h-o.bottom-o.height,selected=o.id===activeId,color=o.kind==='window'?'#609da9':o.kind==='door'?'#a68258':'#4b9587';return <g key={o.id}><rect x={left} y={top} width={o.width} height={o.height} fill={o.kind==='passage'?'#fbfefe':o.kind==='window'?'#cce5e9':'#d6ba99'} fillOpacity={result.plan?1:.45} stroke={selected?'#8058ac':color} strokeWidth={selected?3:1.5} strokeDasharray={result.plan?undefined:'5 4'} vectorEffect="non-scaling-stroke"/>{o.kind==='window'&&<path d={`M${left+o.width*.2} ${top+o.height*.7}l${o.width*.25} ${-o.height*.4}m${o.width*.1} ${o.height*.3}l${o.width*.2} ${-o.height*.35}`} fill="none" stroke="white" strokeWidth={2} vectorEffect="non-scaling-stroke"/>}{o.kind==='door'&&<circle cx={left+o.width*.85} cy={top+o.height*.55} r={font*.18} fill="#796044"/>}<text x={o.x} y={top+o.height/2} textAnchor="middle" fontSize={font} fill="#56465f" stroke="white" strokeWidth={font*.1} paintOrder="stroke">{i+1} · {openingKindNames[o.kind]}</text><text x={o.x} y={top+o.height/2+font*1.4} textAnchor="middle" fontSize={font*.78} fill="#75677b">{o.width} × {o.height}</text></g>;})}
  <line x1={-w/2-pad/3} y1={h} x2={w/2+pad/3} y2={h} stroke="#95829f" strokeWidth={2} vectorEffect="non-scaling-stroke"/><text x={0} y={h+pad*.75} textAnchor="middle" fontSize={font*.85} fill="#907c9e">파티션 바닥 · 공간 바닥에서 {target.y} mm</text>
 </svg><p className="fineprint">개구부를 클릭해 선택하세요. 빈 벽을 클릭하면 선택한 개구부의 중심을 50mm 단위로 옮깁니다. 정확한 값은 오른쪽에 입력하세요.</p>
 <div className="partition-opening-add">{(['passage','door','window'] as const).map(kind=><button className="outline-button" key={kind} disabled={readonly||openings.length>=8||!!result.error} onClick={()=>add(kind)}>{kind==='window'?<Square size={16}/>:<DoorOpen size={16}/>}<span>{openingKindNames[kind]}</span><Plus size={13}/></button>)}</div>
 <div className="partition-opening-list">{openings.length?openings.map((o,i)=><button key={o.id} className={o.id===activeId?'selected':''} aria-pressed={o.id===activeId} onClick={()=>setActiveId(o.id)}><b>{i+1}</b><span>{o.name}<small>{openingKindNames[o.kind]} · {Number.isFinite(o.width)?o.width:'—'} × {Number.isFinite(o.height)?o.height:'—'} mm</small></span></button>):<div className="partition-opening-empty"><DoorOpen size={28}/><p>통로·문·창문을 추가하세요.<br/>벽의 양끝과 위에 100mm를 남깁니다.</p></div>}</div>
 </section><aside className="partition-opening-settings"><div className="small-heading"><b>{active?'선택한 개구부':'개구부 속성'}</b><span>{openings.length}/8개</span></div>{active?<><label className="field-label">이름<input className="text-input" value={active.name} maxLength={60} disabled={readonly} onChange={e=>patch({name:e.target.value})}/></label><label className="field-label">종류<select className="text-input" value={active.kind} disabled={readonly} onChange={e=>{const kind=e.target.value as PartitionOpening['kind'];patch({kind,bottom:kind==='window'?Math.max(100,active.bottom):0});}}>{Object.entries(openingKindNames).map(([value,name])=><option key={value} value={value}>{name}</option>)}</select></label><fieldset disabled={readonly}><div className="partition-opening-fields"><Numeric label="개구부 폭 (mm)" min={active.kind==='window'?200:300} max={w-200} value={active.width} onChange={width=>patch({width})}/><Numeric label="개구부 높이 (mm)" min={active.kind==='window'?200:800} max={h-active.bottom-100} value={active.height} onChange={height=>patch({height})}/><Numeric label="벽 중앙에서 X (mm)" value={active.x} onChange={x=>patch({x})}/>{active.kind==='window'?<Numeric label="파티션 바닥에서 높이" min={100} max={h-active.height-100} value={active.bottom} onChange={bottom=>patch({bottom})}/>:<div className="partition-opening-floor">하부 높이<strong>0 mm</strong><small>파티션 바닥에서 시작</small></div>}</div><div className="partition-opening-align"><button className="outline-button" onClick={()=>patch({x:-w/2+100+active.width/2})}>왼쪽 100</button><button className="outline-button" onClick={()=>patch({x:0})}>중앙</button><button className="outline-button" onClick={()=>patch({x:w/2-100-active.width/2})}>오른쪽 100</button></div></fieldset><button className="text-button partition-opening-remove" disabled={readonly} onClick={()=>{setOpenings(a=>a.filter(o=>o.id!==active.id));setActiveId(openings.find(o=>o.id!==active.id)?.id??'');setMessage('');}}><Trash2 size={15}/>선택 개구부 제거</button></>:<p className="fineprint">먼저 왼쪽에서 종류를 선택해 추가하세요.</p>}
 <div className="partition-opening-help"><b>벽과 함께 편집됩니다</b><p>그룹 이동·복제·레이어·저장에 함께 반영됩니다. 문짝과 프레임 소재는 적용 후 그룹 안 편집에서 면을 클릭해 바꾸세요.</p><p>문은 닫힌 상태입니다. 통행 가능한 빈 공간이 필요하면 ‘빈 통로’를 선택하세요. 프레임은 개구부 치수 안쪽에 포함됩니다.</p><p>단가는 파티션 구성 전체 기준입니다. 개구부 규격을 바꾸면 기존 단가를 재검토하도록 표시합니다.</p></div>
 </aside></div>
 {(message||result.error||stale)&&<p className="form-error" role="alert">{stale?'장면이 바뀌었습니다. 편집 창을 다시 여세요.':[...new Set([message,result.error].filter(Boolean))].join(' ')}</p>}
 <div className="partition-opening-footer"><p>치수 메모는 파티션 기준점에 연결됩니다. 개구부 위치를 바꾼 뒤 측정점을 확인하세요.</p><div><button className="outline-button" onClick={onClose}>취소</button><button className="primary-button" disabled={!result.plan||result.plan.unchanged||stale} onClick={()=>result.plan&&onPreview(result.plan)}><Eye size={16}/>3D에서 확인</button></div></div>
 </DialogContent></Dialog>;
}
