'use client';
import {useMemo,useState} from 'react';
import {Check,Copy,Move,ScanLine,Eye,ArrowLeft,Layers,MoveHorizontal,RotateCcw} from 'lucide-react';
import './relative-placement.css';
import PartitionPlanShape from './partition-plan-shape';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {selectionIds,groupBounds,sceneGroups} from '@/lib/selection';
import {samePhotoAssembly} from '@/lib/object-photo-schema';
import {collisions,type SceneData,type Selection,type SceneNode} from '@/lib/scene-model';
import {openingSpan} from '@/lib/floor-plan';
import {arrayCapacity,planPlacement,placementEdges,placementReferenceOptions,relativeEdges,type PlacementPlan,type PlacementRequest} from '@/lib/placement';

function RelativeGap({plan,font}:{plan:PlacementPlan;font:number}){
 if(plan.request.type!=='relative')return null;
 const request=plan.request,s=groupBounds(plan.scene.nodes.filter(n=>plan.sourceIds.includes(n.id))),r=groupBounds(plan.scene.nodes.filter(n=>request.referenceIds.includes(n.id))),horizontal=request.edge==='left'||request.edge==='right',positive=request.edge==='right'||request.edge==='front',axis=horizontal?'x':'z',other=horizontal?'z':'x';
 const a=positive?r.max[axis]:r.min[axis],b=positive?s.min[axis]:s.max[axis],cross=(s.center[other]+r.center[other])/2,point=(along:number,across:number)=>horizontal?{x:along,y:across}:{x:across,y:along};
 const from=point(a,cross),to=point(b,cross),ref=point(a,r.center[other]),target=point(b,s.center[other]),tick=font*.24,label=point((a+b)/2,cross-font*.55);
 return <g className="relative-gap-dimension" fill="none" stroke="#3b719d" strokeWidth={1.5}>
  <path d={`M${ref.x} ${ref.y}L${from.x} ${from.y}M${target.x} ${target.y}L${to.x} ${to.y}`} strokeDasharray="4 4" vectorEffect="non-scaling-stroke"/>
  <path d={`M${from.x} ${from.y}L${to.x} ${to.y}`} vectorEffect="non-scaling-stroke"/>
  {[from,to].map((p,i)=><path key={i} d={horizontal?`M${p.x} ${p.y-tick}v${tick*2}`:`M${p.x-tick} ${p.y}h${tick*2}`} vectorEffect="non-scaling-stroke"/>)}
  <text x={label.x} y={label.y} textAnchor="middle" fontSize={font*.8} fill="#305f88" stroke="white" strokeWidth={font*.12} paintOrder="stroke">{request.gap.toLocaleString()} mm</text>
  <rect x={s.min.x} y={s.min.z} width={s.width} height={s.depth} stroke="#248575" strokeDasharray="4 4" vectorEffect="non-scaling-stroke"/>
 </g>;
}
type RadialGuideInput={center:{x:number;z:number};angle:number};
function RadialGuide({base,sourceIds,input,font}:{base:SceneData;sourceIds:string[];input:RadialGuideInput;font:number}){
 const nodes=base.nodes.filter(n=>sourceIds.includes(n.id));if(!nodes.length||![input.center.x,input.center.z,input.angle].every(Number.isFinite))return null;
 const {center}=input,source=groupBounds(nodes).center,dx=source.x-center.x,dz=source.z-center.z,radius=Math.hypot(dx,dz),tick=font*.45;
 const angle=Math.max(0,Math.min(360,input.angle)),points=Array.from({length:Math.max(2,Math.ceil(angle/5)+1)},(_,i)=>{const t=angle*i/Math.max(1,Math.ceil(angle/5))*Math.PI/180;return `${center.x+Math.cos(t)*dx+Math.sin(t)*dz},${center.z-Math.sin(t)*dx+Math.cos(t)*dz}`;}).join(' ');
 return <g className="radial-placement-guide" fill="none" stroke="#9c6eae" strokeWidth={1.4}><polyline points={points} strokeDasharray="5 5" opacity={.65} vectorEffect="non-scaling-stroke"/><line x1={center.x} y1={center.z} x2={source.x} y2={source.z} strokeDasharray="4 4" vectorEffect="non-scaling-stroke"/><circle cx={center.x} cy={center.z} r={tick*.75} fill="#fff" vectorEffect="non-scaling-stroke"/><path d={`M${center.x-tick} ${center.z}h${tick*2}M${center.x} ${center.z-tick}v${tick*2}`} vectorEffect="non-scaling-stroke"/><text x={center.x} y={center.z-tick*1.6} textAnchor="middle" fontSize={font*.75} fill="#825591" stroke="white" strokeWidth={font*.12} paintOrder="stroke">원형 중심</text>{radius>50&&<circle cx={source.x} cy={source.z} r={tick*.45} fill="#9c6eae" stroke="white" vectorEffect="non-scaling-stroke"/>}</g>;
}
function PlacementMap({base,plan,before,sourceIds,referenceIds=[],radial}:{base:SceneData;plan:PlacementPlan|null;before:boolean;sourceIds:string[];referenceIds?:string[];radial?:RadialGuideInput}){
 const room=base.room,scene=before||!plan?base:plan.scene,pad=Math.max(room.width,room.depth)*.085,font=pad*.28;
 const reference=new Set(referenceIds),referenceNodes=base.nodes.filter(n=>reference.has(n.id)),referenceBounds=referenceNodes.length?groupBounds(referenceNodes):null;
 const selected=new Set(sourceIds),result=new Set(before?[]:plan?.resultIds??[]),newConflicts=new Set(before?[]:plan?.overlaps.flatMap(c=>[c.a,c.b])??[]);
 function shape(n:SceneNode,ghost=false){
  const color=ghost?'#8267ae':newConflicts.has(n.id)?'#c37035':result.has(n.id)?'#248575':selected.has(n.id)?'#8267ae':reference.has(n.id)?'#3b719d':'#a4abb3';
  if(n.host){const p=openingSpan(n,room);return <rect key={n.id} x={(p.horizontal?p.along:p.cross)-(p.horizontal?p.width:120)/2} y={(p.horizontal?p.cross:p.along)-(p.horizontal?120:p.width)/2} width={p.horizontal?p.width:120} height={p.horizontal?120:p.width} fill={color} opacity={.8}><title>{n.name}</title></rect>}
  return <g key={ghost?`ghost-${n.id}`:n.id} transform={`translate(${n.x} ${n.z}) rotate(${-n.rotation})`} fill={ghost?'none':color} fillOpacity={result.has(n.id)?.55:.28} stroke={color} strokeWidth={Math.max(room.width,room.depth)/300} strokeDasharray={ghost?'55 40':undefined}><title>{n.name}{ghost?' · 변경 전 위치':''}</title>{n.kind==='partition'?<PartitionPlanShape node={n} ghost={ghost}/>:['round-table','plant','cylinder','pendant'].includes(n.kind)?<ellipse rx={n.width/2} ry={n.depth/2}/>:<rect x={-n.width/2} y={-n.depth/2} width={n.width} height={n.depth}/>}</g>;
 }
 return <svg className="placement-map" viewBox={`${-room.width/2-pad} ${-room.depth/2-pad} ${room.width+pad*2} ${room.depth+pad*2}`} role="img" aria-label={before?'변경 전 가구 배치 평면':'배열·정렬 미리보기 평면'}><rect x={-room.width/2} y={-room.depth/2} width={room.width} height={room.depth} fill="#fbfafc" stroke="#d2ced7" strokeWidth={120}/><text x={0} y={-room.depth/2-pad*.4} textAnchor="middle" fontSize={font} fill="#81798b">{room.width.toLocaleString()} mm</text>{!before&&plan&&plan.request.type!=='array'&&plan.request.type!=='radial'&&base.nodes.filter(n=>selected.has(n.id)&&!n.hidden).map(n=>shape(n,true))}{scene.nodes.filter(n=>!n.hidden).map(n=>shape(n))}{referenceBounds&&<rect x={referenceBounds.min.x} y={referenceBounds.min.z} width={referenceBounds.width} height={referenceBounds.depth} fill="none" stroke="#3b719d" strokeWidth={1.5} strokeDasharray="5 4" vectorEffect="non-scaling-stroke"/>}{!before&&plan&&<RelativeGap plan={plan} font={font}/>} {radial&&<RadialGuide base={base} sourceIds={sourceIds} input={radial} font={font}/>}<text x={0} y={room.depth/2+pad*.65} textAnchor="middle" fontSize={font} fill="#81798b">입구 방향 · +Z</text></svg>;
}
export default function PlacementDialog({onClose,scene,selection,editingGroupId,onPreview,onSelect}:{onClose:()=>void;scene:SceneData;selection:Selection;editingGroupId:string|null;onPreview:(plan:PlacementPlan)=>void;onSelect:(s:Selection)=>void}){
 const [base]=useState(()=>structuredClone(scene)),[ids]=useState(()=>selectionIds(selection).filter(id=>base.nodes.some(n=>n.id===id))),[editGroup]=useState(editingGroupId);
 const nodes=useMemo(()=>base.nodes.filter(n=>ids.includes(n.id)),[base,ids]),host=nodes.length===1?nodes[0].host:undefined;
 const references=useMemo(()=>placementReferenceOptions(base,ids),[base,ids]);
 const [referenceKey,setReferenceKey]=useState(()=>references[0]?.key??''),[relativeEdge,setRelativeEdge]=useState<Extract<PlacementRequest,{type:'relative'}>['edge']>('right'),[relativeGap,setRelativeGap]=useState('600'),[cross,setCross]=useState<'keep'|'center'>('center');
 const reference=references.find(o=>o.key===referenceKey);
 const [radialCenterMode,setRadialCenterMode]=useState<'room'|'reference'|'custom'>('room'),[radialReferenceKey,setRadialReferenceKey]=useState(()=>references[0]?.key??''),[radialX,setRadialX]=useState('0'),[radialZ,setRadialZ]=useState('0'),[radialCount,setRadialCount]=useState('3'),[radialAngle,setRadialAngle]=useState('360'),[radialRotate,setRadialRotate]=useState(true);
 const radialReference=references.find(option=>option.key===radialReferenceKey);
 const radialCenter=useMemo(()=>{if(radialCenterMode==='room')return{x:0,z:0};if(radialCenterMode==='custom')return{x:radialX.trim()?Number(radialX):NaN,z:radialZ.trim()?Number(radialZ):NaN};const referenced=base.nodes.filter(node=>radialReference?.ids.includes(node.id));if(!referenced.length)return{x:NaN,z:NaN};const center=groupBounds(referenced).center;return{x:center.x,z:center.z};},[base,radialCenterMode,radialReference,radialX,radialZ]);
 const [tab,setTab]=useState(nodes.length?'array':'conflicts'),[count,setCount]=useState('1'),[gap,setGap]=useState('300'),[margin,setMargin]=useState('100'),[edge,setEdge]=useState<Extract<PlacementRequest,{type:'align'}>['edge']>('left'),[before,setBefore]=useState(false);
 const [direction,setDirection]=useState(()=>{const choices=['x:1','x:-1','z:1','z:-1'].filter(v=>!host||v[0]===(['back','front'].includes(host)?'x':'z'));return choices.sort((a,b)=>{const [aa,ad]=a.split(':'),[ba,bd]=b.split(':');return arrayCapacity(base,nodes,ba as 'x'|'z',Number(bd) as 1|-1,300)-arrayCapacity(base,nodes,aa as 'x'|'z',Number(ad) as 1|-1,300)})[0]});
 const [axisText,signText]=direction.split(':'),axis=axisText as 'x'|'z',sign=Number(signText) as 1|-1;
 const candidate=useMemo(()=>{if(!ids.length||tab==='conflicts')return {plan:null,error:''};try{
  let input:PlacementRequest;
  if(tab==='array')input={type:'array',axis,direction:sign,count:count.trim()?Number(count):NaN,gap:gap.trim()?Number(gap):NaN};
  else if(tab==='relative')input={type:'relative',referenceIds:reference?.ids??[],edge:relativeEdge,gap:relativeGap.trim()?Number(relativeGap):NaN,cross};
  else if(tab==='radial')input={type:'radial',center:radialCenter,count:radialCount.trim()?Number(radialCount):NaN,angle:radialAngle.trim()?Number(radialAngle):NaN,rotate:radialRotate};
  else input={type:'align',edge,margin:edge==='center'?0:margin.trim()?Number(margin):NaN};
  return {plan:planPlacement(base,ids,input,editGroup),error:''};
 }catch(e){return {plan:null,error:e instanceof Error&&e.name!=='ZodError'?e.message:'배치 크기와 요소 개수 제한을 확인하세요.'}}},[base,ids,editGroup,tab,axis,sign,count,gap,edge,margin,reference,relativeEdge,relativeGap,cross,radialCenter,radialCount,radialAngle,radialRotate]);
 const stale=JSON.stringify(scene)!==JSON.stringify(base),plan=candidate.plan,bounds=nodes.length&&!host?groupBounds(nodes):null,group=sceneGroups(base).find(g=>g.nodes.length===nodes.length&&g.nodes.every(n=>ids.includes(n.id))),conflicts=useMemo(()=>collisions(base),[base]);
 const capacity=gap.trim()?arrayCapacity(base,nodes,axis,sign,Number(gap)):0,selectedName=group?group.name:nodes.length===1?nodes[0].name:`선택한 가구 ${nodes.length}개`;
 const radius=bounds&&[radialCenter.x,radialCenter.z].every(Number.isFinite)?Math.hypot(bounds.center.x-radialCenter.x,bounds.center.z-radialCenter.z):null;
 return <Dialog open onOpenChange={o=>!o&&onClose()}><DialogContent className="placement-workbench"><DialogHeader><DialogTitle>가구 간격·반복 배치·정렬</DialogTitle><DialogDescription>선택한 구성의 크기와 간격을 유지한 채 배치하고, 3D에서 확인해 적용하세요.</DialogDescription></DialogHeader>
  <Tabs value={tab} onValueChange={v=>{setTab(v);setBefore(false)}}><TabsList className="placement-tabs"><TabsTrigger value="array" disabled={!nodes.length}><Copy size={15}/>반복 배치</TabsTrigger><TabsTrigger value="radial" disabled={!nodes.length||nodes.some(n=>n.host||n.hidden)}><RotateCcw size={15}/>원형 배치</TabsTrigger><TabsTrigger value="align" disabled={!nodes.length||nodes.some(n=>n.host)}><Move size={15}/>벽·중앙 정렬</TabsTrigger><TabsTrigger value="relative" disabled={!nodes.length||nodes.some(n=>n.host)}><MoveHorizontal size={15}/>가구 기준 간격</TabsTrigger><TabsTrigger value="conflicts"><ScanLine size={15}/>현재 겹침 {conflicts.length}</TabsTrigger></TabsList></Tabs>
  {stale&&<p className="form-error" role="alert">장면이 변경되었습니다. 창을 닫고 다시 열어 최신 배치를 확인하세요.</p>}
  {tab==='conflicts'?<div className="placement-conflicts"><p className="fineprint">회전과 설치 높이를 반영한 가구 외곽 기준입니다. 실제 메시 간섭이나 통행·시공 기준을 판정하지 않습니다. 사진 추정부품 간 겹침에는 상판·다리 같은 접합부도 포함될 수 있으므로 3D에서 확인하세요.</p>{!nodes.length&&<p className="placement-empty">배열하려면 창을 닫고 가구나 그룹을 선택하세요.</p>}<div className="collision-list">{conflicts.length?conflicts.slice(0,80).map(c=><button key={`${c.a}-${c.b}`} disabled={stale} onClick={()=>{onSelect({id:c.a});onClose()}}><span>{c.names[0]}</span><span>↔</span><span>{c.names[1]}{samePhotoAssembly(base.nodes.find(n=>n.id===c.a)!,base.nodes.find(n=>n.id===c.b)!)&&<small> · 사진 추정부품 간 겹침</small>}</span></button>):<p><Check size={16}/>외곽 기준으로 겹친 가구가 없습니다.</p>}</div>{conflicts.length>80&&<p className="fineprint">전체 {conflicts.length}곳 중 80곳을 표시합니다.</p>}</div>:<div className="placement-layout">
   <section className="placement-settings"><div className="placement-selection"><Layers size={18}/><div><b>{selectedName}</b><span>{nodes.length}개 요소{bounds?` · ${Math.round(bounds.width).toLocaleString()} × ${Math.round(bounds.depth).toLocaleString()} mm`:''}</span></div></div>
    {tab==='array'?<><label className="field-label">원본 외 추가 반복 횟수<input className="text-input" type="number" min={1} max={12} step={1} value={count} onChange={e=>{setCount(e.target.value);setBefore(false)}}/></label><label className="field-label">구성 바깥 경계 사이 간격 · mm<input className="text-input" type="number" min={0} max={5000} step={50} value={gap} onChange={e=>{setGap(e.target.value);setBefore(false)}}/></label><label className="field-label">배치 방향<Select value={direction} onValueChange={v=>{setDirection(v);setBefore(false)}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{[['x:1','오른쪽 · X +'],['x:-1','왼쪽 · X −'],['z:1','입구쪽 · Z +'],['z:-1','안쪽 · Z −']].map(([value,label])=><SelectItem key={value} value={value} disabled={!!host&&value[0]!==(['back','front'].includes(host)?'x':'z')}>{label}</SelectItem>)}</SelectContent></Select></label><p className="placement-capacity">이 방향 공간 기준 최대 <b>{capacity}회</b><small>다른 가구와의 겹침은 별도로 확인합니다.</small></p><p className="fineprint">각 사본의 그룹은 원본과 독립됩니다. 그룹 안에서 일부만 복제하면 개별 가구로 추가됩니다.</p></>:tab==='radial'?<>
     <label className="field-label">원형의 중심 기준<select className="text-input" value={radialCenterMode} onChange={event=>{setRadialCenterMode(event.target.value as typeof radialCenterMode);setBefore(false)}}><option value="room">공간 중앙</option><option value="reference" disabled={!references.length}>다른 가구·그룹의 중심</option><option value="custom">좌표 직접 입력</option></select></label>
     {radialCenterMode==='reference'&&<label className="field-label">중심으로 사용할 가구·그룹<select className="text-input relative-reference-select" value={radialReferenceKey} onChange={event=>{setRadialReferenceKey(event.target.value);setBefore(false)}} disabled={!references.length}>{!references.length&&<option value="">선택할 기준이 없습니다</option>}{references.map(option=><option key={option.key} value={option.key}>{option.name}{option.group?` · 그룹 ${option.ids.length}개`:''}</option>)}</select></label>}
     {radialCenterMode==='custom'?<div className="radial-center-fields"><label className="field-label">중심 X · mm<input className="text-input" type="number" min={-base.room.width/2+60} max={base.room.width/2-60} step={50} value={radialX} onChange={event=>{setRadialX(event.target.value);setBefore(false)}}/></label><label className="field-label">중심 Z · mm<input className="text-input" type="number" min={-base.room.depth/2+60} max={base.room.depth/2-60} step={50} value={radialZ} onChange={event=>{setRadialZ(event.target.value);setBefore(false)}}/></label></div>:<p className="radial-center-readout">중심 좌표 <b>X {Number.isFinite(radialCenter.x)?Math.round(radialCenter.x).toLocaleString():'—'} · Z {Number.isFinite(radialCenter.z)?Math.round(radialCenter.z).toLocaleString():'—'} mm</b></p>}
     <p className="placement-capacity radial-radius">원본 구성 기준 반지름 <b>{radius===null?'—':Math.round(radius).toLocaleString()} mm</b><small>반지름은 50mm를 넘어야 합니다. 중심 위치를 바꿔 조절하세요.</small></p>
     <label className="field-label">원본 외 추가 개수<input className="text-input" type="number" min={1} max={12} step={1} value={radialCount} onChange={event=>{setRadialCount(event.target.value);setBefore(false)}}/></label>
     <label className="field-label">펼칠 각도 · °<input className="text-input" type="number" min={15} max={360} step={1} value={radialAngle} onChange={event=>{setRadialAngle(event.target.value);setBefore(false)}}/></label>
     <div className="relative-gap-presets radial-angle-presets" aria-label="원형 배치 각도 빠른 입력">{[90,180,270,360].map(value=><button key={value} type="button" className={Number(radialAngle)===value&&radialAngle.trim()?'active':''} aria-pressed={Number(radialAngle)===value&&!!radialAngle.trim()} onClick={()=>{setRadialAngle(String(value));setBefore(false)}}>{value}°</button>)}</div>
     <label className="radial-rotate"><input type="checkbox" checked={radialRotate} onChange={event=>{setRadialRotate(event.target.checked);setBefore(false)}}/><span>배치 방향을 따라 함께 회전</span></label>
     <p className="fineprint">평면에서 반시계 방향으로 사본을 놓습니다. 360°는 원본을 포함해 균등 배치하고, 부분 원형은 마지막 사본이 입력한 각도에 놓입니다.</p><p className="fineprint">점선은 원본 구성의 외곽 중심을 기준으로 그린 경로입니다. 크기·높이·구성 내부 간격은 유지됩니다. 중심 좌표의 X+는 오른쪽, Z+는 입구 방향입니다.</p>
    </>:tab==='relative'?<>
     <label className="field-label">움직이지 않을 기준<select className="text-input relative-reference-select" value={referenceKey} onChange={e=>{setReferenceKey(e.target.value);setBefore(false)}} disabled={!references.length}>{!references.length&&<option value="">선택할 기준이 없습니다</option>}{references.map(o=><option key={o.key} value={o.key}>{o.name}{o.group?` · 그룹 ${o.ids.length}개`:''}</option>)}</select></label>
     {!references.length&&<p className="relative-empty">이동할 가구 외에 표시된 가구나 그룹이 필요합니다. 창을 닫고 이동할 구성만 선택한 뒤 다시 여세요.</p>}
     <label className="field-label">기준의 어느 쪽에 배치할까요?<Select value={relativeEdge} onValueChange={v=>{setRelativeEdge(v as typeof relativeEdge);setBefore(false)}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{Object.entries(relativeEdges).map(([value,label])=><SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></label>
     <label className="field-label">두 외곽 사이 간격 · mm<input className="text-input" type="number" min={0} max={5000} step={50} value={relativeGap} onChange={e=>{setRelativeGap(e.target.value);setBefore(false)}}/></label>
     <div className="relative-gap-presets" aria-label="간격 빠른 입력">{[0,300,600,900,1200].map(value=><button key={value} type="button" className={Number(relativeGap)===value&&relativeGap.trim()?'active':''} aria-pressed={Number(relativeGap)===value&&!!relativeGap.trim()} onClick={()=>{setRelativeGap(String(value));setBefore(false)}}>{value.toLocaleString()}</button>)}</div>
     <fieldset className="relative-cross"><legend>{relativeEdge==='left'||relativeEdge==='right'?'앞뒤 위치':'좌우 위치'}</legend><label><input type="radio" name="relative-cross" checked={cross==='keep'} onChange={()=>{setCross('keep');setBefore(false)}}/>현재 위치 유지</label><label><input type="radio" name="relative-cross" checked={cross==='center'} onChange={()=>{setCross('center');setBefore(false)}}/>기준과 중심 맞춤</label></fieldset>
     <p className="fineprint">파란색 기준은 그대로 두고 선택한 구성을 옮깁니다. 잠긴 가구도 기준으로 쓸 수 있으며, 그룹은 전체 외곽을 사용합니다.</p><p className="fineprint">공간의 X·Z 방향에서 회전된 규격 외곽 간격을 맞춥니다. 실제 메시 사이 최단거리나 통행 가능 폭을 뜻하지 않습니다. 크기·회전·높이와 구성 내부 간격은 유지됩니다.</p>
    </>:<><label className="field-label">정렬할 위치<Select value={edge} onValueChange={v=>{setEdge(v as typeof edge);setBefore(false)}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{Object.entries(placementEdges).map(([value,label])=><SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></label><label className="field-label">벽 안쪽 면에서 띄우기 · mm<input className="text-input" type="number" min={0} max={2000} step={50} value={margin} disabled={edge==='center'} onChange={e=>{setMargin(e.target.value);setBefore(false)}}/></label><p className="fineprint">{edge==='center'?'선택 영역의 중심을 공간 중앙에 맞춥니다.':'선택 영역의 바깥 경계를 벽에서 입력한 거리만큼 띄웁니다.'} 가구 크기·회전·높이와 내부 간격은 유지됩니다.</p></>}
    {candidate.error&&<p className="form-error" role="alert">{candidate.error}</p>}{plan?.unchanged&&<p className="placement-capacity">이미 해당 위치에 있습니다.</p>}
   </section>
   <section className="placement-preview"><div className="placement-preview-heading"><b>평면 미리보기</b><button className="outline-button" disabled={!plan||plan.unchanged} onClick={()=>setBefore(v=>!v)}>{before?<Eye size={14}/>:<ArrowLeft size={14}/>} {before?'변경 후 보기':'변경 전 보기'}</button></div><PlacementMap base={base} plan={plan} before={before} sourceIds={ids} referenceIds={tab==='relative'?reference?.ids:tab==='radial'&&radialCenterMode==='reference'?radialReference?.ids:[]} radial={tab==='radial'?{center:radialCenter,angle:radialAngle.trim()?Number(radialAngle):NaN}:undefined}/><div className="placement-legend"><span className="existing">기존 가구</span><span className="source">선택 구성</span><span className="result">배치 결과</span>{(tab==='relative'||(tab==='radial'&&radialCenterMode==='reference'))&&<span className="reference">기준 외곽</span>}{tab==='radial'&&<span className="radial-pivot">원형 중심·반지름</span>}<span className="overlap">새 겹침</span></div><p className="fineprint">가구 외곽과 개구부 위치를 표시합니다. 개구부는 높이와 무관한 기호이며, 실제 형태·소재는 3D에서 확인하세요.</p>{plan&&<div className={`placement-result ${plan.overlaps.length?'has-overlaps':''}`} aria-live="polite"><b>{plan.summary}</b>{(plan.request.type==='array'||plan.request.type==='radial')&&<span>전체 요소 {base.nodes.length} → {plan.scene.nodes.length}개</span>}{plan.request.type==='radial'&&plan.step!==undefined&&<span>배치 각도 간격 {Number(plan.step.toFixed(3))}°</span>}<span>새로 생기는 외곽 겹침 {plan.overlaps.length}곳</span>{plan.overlaps.length>0&&<p>{plan.overlaps.slice(0,3).map(c=>`${c.names[0]} ↔ ${c.names[1]}`).join(' / ')}{plan.overlaps.length>3?' 외':''}</p>}</div>}</section>
  </div>}
  <div className="placement-footer"><button className="outline-button" onClick={onClose}>닫기</button>{tab!=='conflicts'&&<button className="primary-button" disabled={!plan||plan.unchanged||stale} onClick={()=>{if(plan&&!stale)onPreview(plan)}}><Eye size={16}/>3D에서 확인</button>}</div>
 </DialogContent></Dialog>;
}
