'use client';
import {useMemo,useState} from 'react';
import {Check,Copy,Move,ScanLine,Eye,ArrowLeft,Layers} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {selectionIds,groupBounds,sceneGroups} from '@/lib/selection';
import {collisions,type SceneData,type Selection,type SceneNode} from '@/lib/scene-model';
import {openingSpan} from '@/lib/floor-plan';
import {arrayCapacity,planPlacement,placementEdges,type PlacementPlan,type PlacementRequest} from '@/lib/placement';

function PlacementMap({base,plan,before,sourceIds}:{base:SceneData;plan:PlacementPlan|null;before:boolean;sourceIds:string[]}){
 const room=base.room,scene=before||!plan?base:plan.scene,pad=Math.max(room.width,room.depth)*.085,font=pad*.28;
 const selected=new Set(sourceIds),result=new Set(before?[]:plan?.resultIds??[]),newConflicts=new Set(before?[]:plan?.overlaps.flatMap(c=>[c.a,c.b])??[]);
 function shape(n:SceneNode,ghost=false){
  const color=ghost?'#8267ae':newConflicts.has(n.id)?'#c37035':result.has(n.id)?'#248575':selected.has(n.id)?'#8267ae':'#a4abb3';
  if(n.host){const p=openingSpan(n,room);return <rect key={n.id} x={(p.horizontal?p.along:p.cross)-(p.horizontal?p.width:120)/2} y={(p.horizontal?p.cross:p.along)-(p.horizontal?120:p.width)/2} width={p.horizontal?p.width:120} height={p.horizontal?120:p.width} fill={color} opacity={.8}><title>{n.name}</title></rect>}
  return <g key={ghost?`ghost-${n.id}`:n.id} transform={`translate(${n.x} ${n.z}) rotate(${-n.rotation})`} fill={ghost?'none':color} fillOpacity={result.has(n.id)?.55:.28} stroke={color} strokeWidth={Math.max(room.width,room.depth)/300} strokeDasharray={ghost?'55 40':undefined}><title>{n.name}{ghost?' · 변경 전 위치':''}</title>{['round-table','plant','cylinder','pendant'].includes(n.kind)?<ellipse rx={n.width/2} ry={n.depth/2}/>:<rect x={-n.width/2} y={-n.depth/2} width={n.width} height={n.depth}/>}</g>;
 }
 return <svg className="placement-map" viewBox={`${-room.width/2-pad} ${-room.depth/2-pad} ${room.width+pad*2} ${room.depth+pad*2}`} role="img" aria-label={before?'변경 전 가구 배치 평면':'배열·정렬 미리보기 평면'}><rect x={-room.width/2} y={-room.depth/2} width={room.width} height={room.depth} fill="#fbfafc" stroke="#d2ced7" strokeWidth={120}/><text x={0} y={-room.depth/2-pad*.4} textAnchor="middle" fontSize={font} fill="#81798b">{room.width.toLocaleString()} mm</text>{!before&&plan?.request.type==='align'&&base.nodes.filter(n=>selected.has(n.id)&&!n.hidden).map(n=>shape(n,true))}{scene.nodes.filter(n=>!n.hidden).map(n=>shape(n))}<text x={0} y={room.depth/2+pad*.65} textAnchor="middle" fontSize={font} fill="#81798b">입구 방향 · +Z</text></svg>;
}
export default function PlacementDialog({onClose,scene,selection,editingGroupId,onPreview,onSelect}:{onClose:()=>void;scene:SceneData;selection:Selection;editingGroupId:string|null;onPreview:(plan:PlacementPlan)=>void;onSelect:(s:Selection)=>void}){
 const [base]=useState(()=>structuredClone(scene)),[ids]=useState(()=>selectionIds(selection).filter(id=>base.nodes.some(n=>n.id===id))),[editGroup]=useState(editingGroupId);
 const nodes=useMemo(()=>base.nodes.filter(n=>ids.includes(n.id)),[base,ids]),host=nodes.length===1?nodes[0].host:undefined;
 const [tab,setTab]=useState(nodes.length?'array':'conflicts'),[count,setCount]=useState('1'),[gap,setGap]=useState('300'),[margin,setMargin]=useState('100'),[edge,setEdge]=useState<Extract<PlacementRequest,{type:'align'}>['edge']>('left'),[before,setBefore]=useState(false);
 const [direction,setDirection]=useState(()=>{const choices=['x:1','x:-1','z:1','z:-1'].filter(v=>!host||v[0]===(['back','front'].includes(host)?'x':'z'));return choices.sort((a,b)=>{const [aa,ad]=a.split(':'),[ba,bd]=b.split(':');return arrayCapacity(base,nodes,ba as 'x'|'z',Number(bd) as 1|-1,300)-arrayCapacity(base,nodes,aa as 'x'|'z',Number(ad) as 1|-1,300)})[0]});
 const [axisText,signText]=direction.split(':'),axis=axisText as 'x'|'z',sign=Number(signText) as 1|-1;
 const candidate=useMemo(()=>{if(!ids.length||tab==='conflicts')return {plan:null,error:''};try{
  const input:PlacementRequest=tab==='array'?{type:'array',axis,direction:sign,count:count.trim()?Number(count):NaN,gap:gap.trim()?Number(gap):NaN}:{type:'align',edge,margin:edge==='center'?0:margin.trim()?Number(margin):NaN};
  return {plan:planPlacement(base,ids,input,editGroup),error:''};
 }catch(e){return {plan:null,error:e instanceof Error&&e.name!=='ZodError'?e.message:'배치 크기와 요소 개수 제한을 확인하세요.'}}},[base,ids,editGroup,tab,axis,sign,count,gap,edge,margin]);
 const stale=JSON.stringify(scene)!==JSON.stringify(base),plan=candidate.plan,bounds=nodes.length&&!host?groupBounds(nodes):null,group=sceneGroups(base).find(g=>g.nodes.length===nodes.length&&g.nodes.every(n=>ids.includes(n.id))),conflicts=useMemo(()=>collisions(base),[base]);
 const capacity=gap.trim()?arrayCapacity(base,nodes,axis,sign,Number(gap)):0,selectedName=group?group.name:nodes.length===1?nodes[0].name:`선택한 가구 ${nodes.length}개`;
 return <Dialog open onOpenChange={o=>!o&&onClose()}><DialogContent className="placement-workbench"><DialogHeader><DialogTitle>반복 배치와 정렬</DialogTitle><DialogDescription>선택한 구성의 크기와 간격을 유지한 채 배치하고, 3D에서 확인해 적용하세요.</DialogDescription></DialogHeader>
  <Tabs value={tab} onValueChange={v=>{setTab(v);setBefore(false)}}><TabsList className="placement-tabs"><TabsTrigger value="array" disabled={!nodes.length}><Copy size={15}/>반복 배치</TabsTrigger><TabsTrigger value="align" disabled={!nodes.length||nodes.some(n=>n.host)}><Move size={15}/>벽·중앙 정렬</TabsTrigger><TabsTrigger value="conflicts"><ScanLine size={15}/>현재 겹침 {conflicts.length}</TabsTrigger></TabsList></Tabs>
  {stale&&<p className="form-error" role="alert">장면이 변경되었습니다. 창을 닫고 다시 열어 최신 배치를 확인하세요.</p>}
  {tab==='conflicts'?<div className="placement-conflicts"><p className="fineprint">회전과 설치 높이를 반영한 가구 외곽 기준입니다. 실제 메시 간섭이나 통행·시공 기준을 판정하지 않습니다.</p>{!nodes.length&&<p className="placement-empty">배열하려면 창을 닫고 가구나 그룹을 선택하세요.</p>}<div className="collision-list">{conflicts.length?conflicts.slice(0,80).map(c=><button key={`${c.a}-${c.b}`} disabled={stale} onClick={()=>{onSelect({id:c.a});onClose()}}><span>{c.names[0]}</span><span>↔</span><span>{c.names[1]}</span></button>):<p><Check size={16}/>외곽 기준으로 겹친 가구가 없습니다.</p>}</div>{conflicts.length>80&&<p className="fineprint">전체 {conflicts.length}곳 중 80곳을 표시합니다.</p>}</div>:<div className="placement-layout">
   <section className="placement-settings"><div className="placement-selection"><Layers size={18}/><div><b>{selectedName}</b><span>{nodes.length}개 요소{bounds?` · ${Math.round(bounds.width).toLocaleString()} × ${Math.round(bounds.depth).toLocaleString()} mm`:''}</span></div></div>
    {tab==='array'?<><label className="field-label">원본 외 추가 반복 횟수<input className="text-input" type="number" min={1} max={12} step={1} value={count} onChange={e=>{setCount(e.target.value);setBefore(false)}}/></label><label className="field-label">구성 바깥 경계 사이 간격 · mm<input className="text-input" type="number" min={0} max={5000} step={50} value={gap} onChange={e=>{setGap(e.target.value);setBefore(false)}}/></label><label className="field-label">배치 방향<Select value={direction} onValueChange={v=>{setDirection(v);setBefore(false)}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{[['x:1','오른쪽 · X +'],['x:-1','왼쪽 · X −'],['z:1','입구쪽 · Z +'],['z:-1','안쪽 · Z −']].map(([value,label])=><SelectItem key={value} value={value} disabled={!!host&&value[0]!==(['back','front'].includes(host)?'x':'z')}>{label}</SelectItem>)}</SelectContent></Select></label><p className="placement-capacity">이 방향 공간 기준 최대 <b>{capacity}회</b><small>다른 가구와의 겹침은 별도로 확인합니다.</small></p><p className="fineprint">각 사본의 그룹은 원본과 독립됩니다. 그룹 안에서 일부만 복제하면 개별 가구로 추가됩니다.</p></>:<><label className="field-label">정렬할 위치<Select value={edge} onValueChange={v=>{setEdge(v as typeof edge);setBefore(false)}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{Object.entries(placementEdges).map(([value,label])=><SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></label><label className="field-label">벽 안쪽 면에서 띄우기 · mm<input className="text-input" type="number" min={0} max={2000} step={50} value={margin} disabled={edge==='center'} onChange={e=>{setMargin(e.target.value);setBefore(false)}}/></label><p className="fineprint">{edge==='center'?'선택 영역의 중심을 공간 중앙에 맞춥니다.':'선택 영역의 바깥 경계를 벽에서 입력한 거리만큼 띄웁니다.'} 가구 크기·회전·높이와 내부 간격은 유지됩니다.</p></>}
    {candidate.error&&<p className="form-error" role="alert">{candidate.error}</p>}{plan?.unchanged&&<p className="placement-capacity">이미 해당 위치에 있습니다.</p>}
   </section>
   <section className="placement-preview"><div className="placement-preview-heading"><b>평면 미리보기</b><button className="outline-button" disabled={!plan||plan.unchanged} onClick={()=>setBefore(v=>!v)}>{before?<Eye size={14}/>:<ArrowLeft size={14}/>} {before?'변경 후 보기':'변경 전 보기'}</button></div><PlacementMap base={base} plan={plan} before={before} sourceIds={ids}/><div className="placement-legend"><span className="existing">기존 가구</span><span className="source">선택 구성</span><span className="result">배치 결과</span><span className="overlap">새 겹침</span></div><p className="fineprint">가구 외곽의 평면 투영입니다. 실제 소재와 모델은 3D 미리보기에서 확인하세요.</p>{plan&&<div className={`placement-result ${plan.overlaps.length?'has-overlaps':''}`} aria-live="polite"><b>{plan.summary}</b>{plan.request.type==='array'&&<span>전체 요소 {base.nodes.length} → {plan.scene.nodes.length}개</span>}<span>새로 생기는 외곽 겹침 {plan.overlaps.length}곳</span>{plan.overlaps.length>0&&<p>{plan.overlaps.slice(0,3).map(c=>`${c.names[0]} ↔ ${c.names[1]}`).join(' / ')}{plan.overlaps.length>3?' 외':''}</p>}</div>}</section>
  </div>}
  <div className="placement-footer"><button className="outline-button" onClick={onClose}>닫기</button>{tab!=='conflicts'&&<button className="primary-button" disabled={!plan||plan.unchanged||stale} onClick={()=>{if(plan&&!stale)onPreview(plan)}}><Eye size={16}/>3D에서 확인</button>}</div>
 </DialogContent></Dialog>;
}
