'use client';
import {useEffect,useMemo,useState,useRef} from 'react';
import {Check,ExternalLink,Search,LoaderCircle,PackageOpen,ChevronLeft,ChevronRight} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {materialProducts,materialProduct,searchMaterialProducts,type MaterialProduct,type ProductCatalogScope} from '@/lib/material-products';
import {samhwaBooks,samhwaManifest} from '@/lib/samhwa-colors';
import {materialShortlistCsv} from '@/lib/material-shortlist';
import ProductComparisonDialog from './product-comparison-dialog';
import './product-materials.css';
const PAGE_SIZE=60;
const brands=[...new Set(materialProducts.map(p=>p.brand))],categories=[...new Set(materialProducts.map(p=>p.appearance))],productTypes=[...new Set(materialProducts.filter(p=>p.kind!=='color').map(p=>p.category))],productCount=materialProducts.filter(p=>p.kind!=='color').length;
export default function ProductMaterialDialog({shortlist,onShortlistChange,currentId,target,onClose,onApply}:{shortlist:string[];onShortlistChange:(ids:string[])=>boolean;currentId?:string|null;target:string;onClose:()=>void;onApply:(p:MaterialProduct)=>Promise<boolean>}){
 const [brand,setBrand]=useState(materialProduct(currentId)?.brand??'전체'),[category,setCategory]=useState('전체'),[book,setBook]=useState('전체'),[query,setQuery]=useState(''),[selected,setSelected]=useState(currentId??materialProducts[0]?.id),[loaded,setLoaded]=useState<string|null>(null),[imageError,setImageError]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[page,setPage]=useState(()=>{const current=materialProduct(currentId);return current?Math.floor(Math.max(0,materialProducts.filter(p=>p.brand===current.brand).findIndex(p=>p.id===current.id))/PAGE_SIZE):0});
 const [scope,setScope]=useState<ProductCatalogScope>(materialProduct(currentId)?.kind==='color'?'colors':'products'),[productType,setProductType]=useState('전체');
 const [comparisonIds,setComparisonIds]=useState<string[]>([]),[comparing,setComparing]=useState(false);
 const comparisonProducts=comparisonIds.flatMap(id=>{const p=materialProduct(id);return p?[p]:[]});
 const [shortlistOnly,setShortlistOnly]=useState(false);
 const grid=useRef<HTMLDivElement>(null),flight=useRef(false);
 const filtered=useMemo(()=>searchMaterialProducts({brand,category,book,query,scope,productType}).filter(p=>!shortlistOnly||shortlist.includes(p.id)),[brand,category,book,query,scope,productType,shortlistOnly,shortlist]);
 const pageCount=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE)),safePage=Math.min(page,pageCount-1),visible=filtered.slice(safePage*PAGE_SIZE,(safePage+1)*PAGE_SIZE);
 const item=visible.find(p=>p.id===selected)??visible[0],isColor=item?.kind==='color',ready=!!item&&(isColor?!!item.previewColor:loaded===item.id);
 useEffect(()=>{setImageError(false);setError('');},[item?.id]);
 useEffect(()=>{if(grid.current)grid.current.scrollTop=0;},[safePage,brand,category,book,query,scope,productType]);
 function reset(){setShortlistOnly(false);setScope('all');setProductType('전체');setQuery('');setBrand('전체');setCategory('전체');setBook('전체');setPage(0)}
 async function apply(){if(!item||!ready||flight.current)return;flight.current=true;setBusy(true);setError('');try{if(await onApply(item))onClose();}catch(e){setError(e instanceof Error?e.message:'소재를 적용하지 못했습니다.');}finally{flight.current=false;setBusy(false);}}
 function viewCompared(p:MaterialProduct){setShortlistOnly(false);setScope(p.kind==='color'?'colors':'products');setBrand(p.brand);setCategory('전체');setBook('전체');setProductType('전체');setQuery('');setSelected(p.id);setPage(Math.floor(materialProducts.filter(v=>v.brand===p.brand&&v.kind===p.kind).findIndex(v=>v.id===p.id)/PAGE_SIZE));setComparing(false)}
 function changeShortlist(ids:string[]){try{if(!onShortlistChange(ids))setError('후보 목록을 변경하지 못했습니다.');else setError('');}catch(e){setError(e instanceof Error&&e.name!=='ZodError'?e.message:'프로젝트 후보는 중복 없이 최대 40개까지 담을 수 있습니다.')}}
 function downloadShortlist(){try{const url=URL.createObjectURL(new Blob([materialShortlistCsv(shortlist)],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='material-shortlist.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){setError(e instanceof Error?e.message:'목록을 내려받지 못했습니다.')}}
 return <><Dialog open={!comparing} onOpenChange={o=>!o&&!busy&&!comparing&&onClose()}><DialogContent className="product-material-dialog" showCloseButton={!busy}>
  <DialogHeader><DialogTitle>실제 마감재 라이브러리</DialogTitle><DialogDescription>제조사 제품·색상 코드로 찾고, 선택한 면에 적용하세요.</DialogDescription></DialogHeader>
  <div className="product-library-layout"><section className={`product-browser${shortlistOnly?' shortlist-browser':''}`}>
   <div className="product-scope" role="group" aria-label="소재 라이브러리 구분">{([['products',`실제 제품 ${productCount.toLocaleString()}개`],['colors',`페인트 색상 ${samhwaManifest.totalRecords.toLocaleString()}개`],['all','전체']] as const).map(([value,label])=><button key={value} aria-pressed={scope===value} disabled={busy} onClick={()=>{setShortlistOnly(false);setScope(value);setBrand('전체');setProductType('전체');setCategory('전체');setBook('전체');setQuery('');setPage(0)}}>{label}</button>)}</div>
   <div className="product-shortlist-toolbar"><button aria-pressed={shortlistOnly} disabled={busy} onClick={()=>{reset();setShortlistOnly(!shortlistOnly);setPage(0)}}>프로젝트 후보 {shortlist.length} / 40개</button><button disabled={busy||!shortlist.length} onClick={downloadShortlist}>후보 목록 CSV</button></div>
   {shortlistOnly&&<p className="product-source-summary">프로젝트 저장 시 함께 보관됩니다. 적용된 소재 목록과는 별개입니다.</p>}
   {scope==='colors'&&<p className="product-source-summary">삼화페인트 · 950 / 600 / 1200 / 기타 컬러북</p>}
   <div className="product-search"><Search size={18}/><input autoFocus aria-label="브랜드 제품 코드 검색" placeholder="제품 코드, 소재명, 시트지·바닥재·석재 검색" value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}} disabled={busy}/></div>
   <div className="product-filter"><label>브랜드<select aria-label="마감재 브랜드" value={brand} onChange={e=>{setBrand(e.target.value);setBook('전체');setPage(0);if(e.target.value==='삼화페인트'){setScope('colors');setProductType('전체');setCategory('전체')}else if(e.target.value!=='전체'&&scope==='colors'){setScope('products');setProductType('전체');setCategory('전체')}}} disabled={busy}>{['전체',...brands].map(b=><option key={b}>{b}</option>)}</select></label>{scope!=='colors'&&<label>제품군<select aria-label="마감재 제품군" value={productType} onChange={e=>{setProductType(e.target.value);setPage(0)}} disabled={busy}>{['전체',...productTypes].map(t=><option key={t}>{t}</option>)}</select></label>}<label>무늬·소재<select aria-label="마감재 무늬와 소재" value={category} onChange={e=>{setCategory(e.target.value);setPage(0)}} disabled={busy}>{['전체',...categories].map(c=><option key={c}>{c}</option>)}</select></label></div>
   {scope!=='products'&&(!shortlistOnly||shortlist.some(id=>materialProduct(id)?.kind==='color'))&&(brand==='삼화페인트'||brand==='전체')&&<label className="samhwa-book-filter">삼화 컬러북<select aria-label="삼화페인트 컬러북" value={book} disabled={busy} onChange={e=>{setBook(e.target.value);setPage(0)}}><option value="전체">전체 컬러북</option>{Object.entries(samhwaBooks).map(([key,label])=><option key={key} value={key}>{label} · {samhwaManifest.bookCounts[key as keyof typeof samhwaManifest.bookCounts].toLocaleString()}개</option>)}</select></label>}
   <p className="product-results" role="status">검색 {filtered.length.toLocaleString()}개 <span>{filtered.length?`${safePage*PAGE_SIZE+1}–${Math.min((safePage+1)*PAGE_SIZE,filtered.length)} 표시`:'0개 표시'} · {new Set(filtered.map(p=>p.brand)).size}개 브랜드</span></p>
   <div className="product-grid" ref={grid}>{visible.map(p=><button key={p.id} className={`product-card${item?.id===p.id?' selected':''}`} aria-pressed={item?.id===p.id} aria-label={`${p.brand} ${p.code} ${p.name} ${p.collection}`} onClick={()=>setSelected(p.id)} disabled={busy}>
    <div className={p.kind==='color'&&!p.previewColor?'color-unavailable':''} style={p.kind==='color'&&p.previewColor?{background:p.previewColor}:undefined}>{p.image&&<img src={p.image} alt={`${p.brand} ${p.code} 공식 제품 스와치`} loading="lazy"/>}{p.kind==='color'&&!p.previewColor&&<em>색상값 미제공</em>}{currentId===p.id&&<span><Check size={13}/>적용 중</span>}</div>
    <small>{p.kind==='color'?p.collection:`${p.brand} · ${p.category}`}</small><b>{p.code}</b><p>{p.name}</p>
   </button>)}</div>
   {!!filtered.length&&<nav className="product-pagination" aria-label="소재 검색 페이지"><button aria-label="이전 소재 페이지" disabled={busy||safePage===0} onClick={()=>setPage(safePage-1)}><ChevronLeft size={15}/>이전</button><label><select aria-label="소재 페이지 선택" disabled={busy} value={safePage} onChange={e=>setPage(Number(e.target.value))}>{Array.from({length:pageCount},(_,i)=><option key={i} value={i}>{i+1} / {pageCount} 페이지</option>)}</select></label><button aria-label="다음 소재 페이지" disabled={busy||safePage===pageCount-1} onClick={()=>setPage(safePage+1)}>다음<ChevronRight size={15}/></button></nav>}
   <div className="product-comparison-bar"><span aria-live="polite">비교 {comparisonIds.length} / 3개</span><button disabled={busy||comparisonIds.length<2} onClick={()=>setComparing(true)}>나란히 비교</button>{comparisonIds.length>0&&<button disabled={busy} onClick={()=>setComparisonIds([])}>비우기</button>}</div>
   {!filtered.length&&<div className="product-empty"><PackageOpen/><b>검색 결과가 없습니다</b><p>{shortlistOnly?'제품 상세에서 프로젝트 후보에 담아 주세요.':'다른 코드나 컬러북을 선택해 주세요.'}</p><button className="text-button" onClick={reset}>전체 제품 보기</button></div>}
   {error&&!item&&<p className="form-error" role="alert">{error}</p>}
  </section><aside className="product-detail">{item&&<>
   <div className={`product-hero${isColor&&!item.previewColor?' color-unavailable':''}`} style={isColor&&item.previewColor?{background:item.previewColor}:undefined}>{item.image&&<img key={item.id} src={item.image} alt={`${item.brand} ${item.code} 상세 스와치`} onLoad={()=>setLoaded(item.id)} onError={()=>{setImageError(true);setLoaded(null)}}/>}{imageError&&<p role="alert">제품 이미지를 불러오지 못했습니다.</p>}{isColor&&!item.previewColor&&<p>공식 색상값 확인 필요</p>}</div>
   <div className="product-detail-copy"><small>{item.brand} / {item.collection}</small><h3>{item.code}</h3><p>{item.name}</p>
    <div className="product-apply"><small>적용할 범위 · {target}</small><button className="primary-button full" disabled={busy||!ready} onClick={()=>void apply()}>{busy?<LoaderCircle className="spin" size={16}/>:<Check size={16}/>} {busy?'소재 적용 중…':isColor?'이 페인트 색상 적용':'이 제품 소재 적용'}</button></div>
    <button className="shortlist-add" aria-pressed={shortlist.includes(item.id)} disabled={busy||(!shortlist.includes(item.id)&&shortlist.length>=40)} onClick={()=>changeShortlist(shortlist.includes(item.id)?shortlist.filter(id=>id!==item.id):[...shortlist,item.id])}>{shortlist.includes(item.id)?'프로젝트 후보에서 빼기':shortlist.length>=40?'후보는 최대 40개까지':'프로젝트 후보에 담기'}</button>
    <button className="comparison-add" aria-pressed={comparisonIds.includes(item.id)} disabled={busy||(!comparisonIds.includes(item.id)&&comparisonIds.length>=3)} onClick={()=>setComparisonIds(ids=>ids.includes(item.id)?ids.filter(id=>id!==item.id):ids.length<3?[...ids,item.id]:ids)}>{comparisonIds.includes(item.id)?"비교에서 빼기":comparisonIds.length>=3?"비교는 최대 3개까지":"비교에 담기"}</button>
    <dl><div><dt>제품군</dt><dd>{item.category}</dd></div>{isColor?<><div><dt>HEX</dt><dd>{item.previewColor?.toUpperCase()??'미제공'}</dd></div>{item.previewColor&&<div><dt>RGB</dt><dd>{[1,3,5].map(i=>parseInt(item.previewColor!.slice(i,i+2),16)).join(', ')}</dd></div>}{item.pageCode&&<div><dt>컬러북 페이지</dt><dd>{item.pageCode}</dd></div>}</>:<div><dt>무늬</dt><dd>{item.appearance}</dd></div>}<div><dt>확인일</dt><dd>{item.checkedAt}</dd></div></dl>
    {item.codeHasVariants&&<p className="product-source-note">같은 코드가 다른 컬러북에도 있습니다. 이 컬러북에 게시된 화면 색상값을 적용합니다.</p>}
    {isColor&&!item.previewColor&&<p className="product-source-note" role="alert">공식 원본 값이 {item.sourceValue}로 표기되어 적용할 수 없습니다. 임의의 대체색을 사용하지 않습니다.</p>}
    <p className="product-spec">{item.specification}</p>{!isColor&&!item.imageWidthMm&&<p className="fineprint">스와치의 실물 축척은 미확인입니다. 초기 반복 폭은 900mm이며 적용 후 속성에서 조정할 수 있습니다.</p>}
    <a href={item.sourceUrl} target="_blank" rel="noreferrer">제조사 공식 {isColor?'컬러검색':'제품 정보'}<ExternalLink size={13}/></a>
    <p className="fineprint">{isColor?'화면용 색상입니다. 3D 조명·모니터·도료 종류·광택·바탕면에 따라 실물과 달라질 수 있으므로 최종 색상은 실물 색표와 도장 샘플로 확인하세요.':'공식 제품 스와치입니다. 화면 색상과 광택은 시각화 참고값이며, 판매 규격·시공 용도는 제조사 샘플과 제품 정보로 확인하세요.'}</p>{error&&<p className="form-error" role="alert">{error}</p>}
   </div></>}</aside></div>
 </DialogContent></Dialog>{comparing&&<ProductComparisonDialog products={comparisonProducts} onClose={()=>setComparing(false)} onRemove={id=>setComparisonIds(ids=>ids.filter(v=>v!==id))} onSelect={viewCompared}/>}</>;
}
