'use client';
import {useEffect,useState} from 'react';
import {Camera,Download,RotateCcw,Scissors,X} from 'lucide-react';
import {sectionAxes,sectionAtOffset,sectionDescription,sectionOffset,sectionRange,type SectionView,type SectionRoom} from '@/lib/section-view';
export default function SectionPanel({room,value,onChange,onClose,onSaveCamera,onPng,exporting}:{room:SectionRoom;value:SectionView;onChange:(s:SectionView|null)=>void;onClose:()=>void;onSaveCamera:()=>void;onPng:()=>void;exporting:boolean}){
    const offset=sectionOffset(room,value),[min,max]=sectionRange(room,value.axis),[draft,setDraft]=useState(String(Math.round(offset))),[error,setError]=useState('');
    useEffect(()=>{setDraft(String(Math.round(offset)));setError('');},[offset,value.axis]);
    const commit=()=>{try{if(!draft.trim())throw new Error('단면 위치를 입력하세요.');onChange(sectionAtOffset(room,value,Number(draft)));setError('');}catch(e){setError((e as Error).message);setDraft(String(Math.round(offset)));}};
    const sides=value.axis==='x'?['왼쪽 유지','오른쪽 유지']:value.axis==='y'?['아래쪽 유지','위쪽 유지']:['안쪽 유지','입구쪽 유지'];
    return <section className="section-panel" aria-label="단면 보기 설정"><header><b><Scissors size={16}/>단면 보기</b><button aria-label="단면 설정 접기" onClick={onClose}><X size={16}/></button></header><p>보고 싶은 위치에서 공간을 잘라 확인하세요.</p><div className="section-axis" role="group" aria-label="단면 축">{(['x','y','z'] as const).map(axis=><button key={axis} aria-pressed={value.axis===axis} className={value.axis===axis?'selected':''} onClick={()=>onChange({...value,axis,position:.5})}>{sectionAxes[axis]}<small>{axis.toUpperCase()}</small></button>)}</div><label className="section-offset-label">{value.axis==='y'?'바닥에서 높이':'공간 중심에서 위치'}<span><input aria-label="단면 위치 mm" type="number" min={min} max={max} step={10} value={draft} onChange={e=>setDraft(e.target.value)} onBlur={commit} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}}/><small>mm</small></span></label><input className="section-range" aria-label="단면 위치 조절" type="range" min={0} max={1000} step={1} value={value.position*1000} onChange={e=>onChange({...value,position:Number(e.target.value)/1000})}/><div className="section-range-labels"><span>{min.toLocaleString()}mm</span><button onClick={()=>onChange({...value,position:.5})}>중앙</button><span>{max.toLocaleString()}mm</span></div>{value.axis==='y'&&<div className="section-height-presets">{[900,1200,1500,1800].filter(h=>h<=room.height).map(height=><button key={height} onClick={()=>onChange(sectionAtOffset(room,value,height))}>{height.toLocaleString()}mm</button>)}</div>}<div className="section-sides" role="group" aria-label="남길 방향">{(['negative','positive'] as const).map((keep,i)=><button key={keep} className={value.keep===keep?'selected':''} aria-pressed={value.keep===keep} onClick={()=>onChange({...value,keep})}>{sides[i]}</button>)}</div><label className="section-guide-toggle"><input type="checkbox" checked={value.guide} onChange={e=>onChange({...value,guide:e.target.checked})}/>단면 위치선 표시</label><div className="section-summary" role="status">{sectionDescription(room,value)}</div><div className="section-export-actions"><button className="outline-button" onClick={onSaveCamera}><Camera size={14}/>시점 저장</button><button className="primary-button" onClick={onPng} disabled={exporting}><Download size={14}/>{exporting?'준비 중…':'단면 PNG'}</button></div><button className="text-button full" onClick={()=>onChange(null)}><RotateCcw size={13}/>단면 종료 · 전체 형상 보기</button><p className="section-limit">원본 형상은 유지됩니다. 잘린 경계를 채우지는 않습니다. 이동·측정·그리기 도구를 선택하면 단면 보기가 종료됩니다.</p>{error&&<p className="section-error" role="alert">{error}</p>}</section>;
}
