import {finishLabel} from './material-products';
import {validateScene,materials,kindNames,type SceneData,type SceneNode} from './scene-model';
import {selectedNodes} from './selection';
import {layerName} from './layers';
import {escapeMarkup} from './floor-plan';

export type BudgetDesign=Pick<SceneData,'nodes'|'layers'|'budget'>;
export function stableValue(value:unknown):string{if(Array.isArray(value))return `[${value.map(stableValue).join(',')}]`;if(value&&typeof value==='object')return `{${Object.entries(value).filter(([,v])=>v!==undefined).sort(([a],[b])=>a<b?-1:a>b?1:0).map(([k,v])=>`${JSON.stringify(k)}:${stableValue(v)}`).join(',')}}`;return JSON.stringify(value)??'null';}
function specification(n:SceneNode){
 const spec={kind:n.kind,assetId:n.assetId,width:n.width,height:n.height,depth:n.depth,material:n.material,color:n.color,faces:n.faces,finish:n.finish,faceFinishes:n.faceFinishes,uniformMaterial:n.uniformMaterial};
 if(!n.openings?.length)return spec;
 const sorted=[...n.openings].sort((a,b)=>a.x-b.x||a.bottom-b.bottom||a.width-b.width||a.height-b.height||a.kind.localeCompare(b.kind));
 const key=(face:string)=>{for(const [i,o]of sorted.entries())if(face.startsWith(`op-${o.id}-`))return face.replace(`op-${o.id}-`,`op-${i}-`);return face;};
 return {...spec,openings:sorted.map(({id,name,door,...physical})=>({...physical,...(door?{door:{hinge:door.hinge,side:door.side}}:{})})),faces:Object.fromEntries(Object.entries(n.faces).map(([k,v])=>[key(k),v])),faceFinishes:n.faceFinishes?Object.fromEntries(Object.entries(n.faceFinishes).map(([k,v])=>[key(k),v])):undefined};
}
/** Stable fingerprint is a review hint, not a price or authorization source. */
export function priceBasis(n:SceneNode){let hash=14695981039346656037n;for(const byte of new TextEncoder().encode(stableValue(specification(n)))){hash^=BigInt(byte);hash=BigInt.asUintN(64,hash*1099511628211n);}return hash.toString(16).padStart(16,'0');}
export function priceNeedsReview(n:SceneNode){return n.estimate?.unitPrice!==undefined&&n.estimate.basis!==priceBasis(n);}
export function budgetMaterial(n:SceneNode){const products=[...new Set([n.finish,...Object.values(n.faceFinishes??{})].flatMap(f=>f?.catalogId?[finishLabel(f,'제품 소재')]:[]))];if(products.length)return products.join(' / ');if(n.finish?.textureId||Object.values(n.faceFinishes??{}).some(f=>f.textureId))return '이미지 소재';if(n.kind==='model'&&!n.uniformMaterial)return '모델 원본';if(Object.keys(n.faces).length||Object.keys(n.faceFinishes??{}).length)return '복수 소재';return materials.find(m=>m.id===n.material)?.name??n.material;}
export function budgetMaterialDetails(n:SceneNode){const material=(id:string)=>materials.find(m=>m.id===id)?.name??id;const finish=(f:SceneNode['finish'])=>f?Object.entries(f).filter(([,v])=>v!==undefined&&v!==null).sort(([a],[b])=>a.localeCompare(b)).map(([key,value])=>`${({textureId:'이미지',color:'색상',roughness:'거칠기',metalness:'금속성',scale:'소재 크기(mm)',rotation:'소재 회전(도)'} as Record<string,string>)[key]??key}: ${value}`).join(' · '):'';const parts=[`${material(n.material)} · ${n.finish?.color??n.color??materials.find(m=>m.id===n.material)?.color}`,finish(n.finish)];const label=(key:string)=>{const [part,face]=key.split(':'),o=n.openings?.find(o=>part.startsWith(`op-${o.id}-`));if(!o)return key;const role=part.slice(`op-${o.id}-`.length),name=({frameL:'왼쪽 프레임',frameR:'오른쪽 프레임',frameTop:'상부 프레임',frameBottom:'하부 프레임',panel:'문짝·유리',handle:'손잡이'} as Record<string,string>)[role]??role;return `${o.name} ${name} · ${['오른쪽면','왼쪽면','윗면','아랫면','앞면','뒷면'][Number(face)]??face}`;};for(const [part,id]of Object.entries(n.faces).sort(([a],[b])=>a.localeCompare(b)))parts.push(`${label(part)}: ${material(id)}`);for(const [part,f]of Object.entries(n.faceFinishes??{}).sort(([a],[b])=>a.localeCompare(b)))parts.push(`${label(part)}: ${finish(f)}`);if(n.openings?.length)parts.push(...n.openings.map(o=>`${({passage:'통로',door:'문',window:'유리창'})[o.kind]} ${o.width}×${o.height}mm · 중심 ${o.x} / 하부 ${o.bottom}mm${o.door?` · ${o.door.hinge==='left'?'좌':'우'}경첩 / ${o.door.side==='positive'?'앞':'뒤'}면 설치`:''}`));return parts.filter(Boolean).join(' / ');}
export type BudgetRow={key:string;nodes:SceneNode[];name:string;kind:string;layer:string;material:string;unitPrice:number|undefined;excluded:boolean;review:boolean;note:string;amount:number|undefined};
export function budgetRows(scene:BudgetDesign):BudgetRow[]{
 const groups=new Map<string,BudgetRow>();
 for(const n of scene.nodes){const unitPrice=n.estimate?.unitPrice,excluded=!!n.estimate?.excluded,review=priceNeedsReview(n),note=n.estimate?.note??'',key=stableValue({name:n.name,spec:specification(n),layer:n.layerId,unitPrice,excluded,review,note});let row=groups.get(key);if(!row){row={key,nodes:[],name:n.name,kind:kindNames[n.kind],layer:layerName(scene,n),material:budgetMaterial(n),unitPrice,excluded,review,note,amount:excluded?0:unitPrice===undefined?undefined:0};groups.set(key,row)}row.nodes.push(n);if(!excluded&&unitPrice!==undefined)row.amount=(row.amount??0)+unitPrice;}
 return [...groups.values()];
}
export function budgetSummary(scene:BudgetDesign){const included=scene.nodes.filter(n=>!n.estimate?.excluded),priced=included.filter(n=>n.estimate?.unitPrice!==undefined),itemSubtotal=priced.reduce((sum,n)=>sum+n.estimate!.unitPrice!,0),extrasSubtotal=(scene.budget?.extras??[]).reduce((sum,e)=>sum+e.amount,0),total=itemSubtotal+extrasSubtotal,target=scene.budget?.target;return{items:scene.nodes.length,included:included.length,excluded:scene.nodes.length-included.length,priced:priced.length,unpriced:included.length-priced.length,review:priced.filter(priceNeedsReview).length,itemSubtotal,extrasSubtotal,total,target,remaining:target===undefined?undefined:target-total};}
export function compareBudgets(current:BudgetDesign,baseline:BudgetDesign){const a=budgetSummary(current),b=budgetSummary(baseline);return {current:a,baseline:b,difference:a.total-b.total,provisional:a.unpriced+b.unpriced+a.review+b.review>0};}
export type EstimateEdit={unitPrice?:number|null;note?:string;excluded?:boolean;confirm?:boolean};
export function editEstimates(scene:SceneData,ids:string[],edit:EstimateEdit):SceneData{
 // Prices apply to these exact units, never automatically to their group companions.
 const members=selectedNodes(scene,ids),set=new Set(members.map(n=>n.id));
 return validateScene({...scene,nodes:scene.nodes.map(n=>{if(!set.has(n.id))return n;const estimate={...n.estimate};if(edit.unitPrice!==undefined){if(edit.unitPrice===null){delete estimate.unitPrice;delete estimate.basis}else{estimate.unitPrice=edit.unitPrice;estimate.basis=priceBasis(n)}}if(edit.confirm&&estimate.unitPrice!==undefined)estimate.basis=priceBasis(n);if(edit.note!==undefined)estimate.note=edit.note.trim();if(edit.excluded!==undefined)estimate.excluded=edit.excluded;return {...n,estimate}})});
}
export function setBudgetTarget(scene:SceneData,target:number|null){const budget={extras:[],...scene.budget};if(target===null)delete budget.target;else budget.target=target;return validateScene({...scene,budget});}
export function saveBudgetExtra(scene:SceneData,entry:{id:string;name:string;amount:number}){const extras=scene.budget?.extras??[],exists=extras.some(e=>e.id===entry.id);if(!exists&&extras.length>=12)throw new Error('별도 비용은 12개까지 입력할 수 있습니다.');return validateScene({...scene,budget:{...scene.budget,extras:exists?extras.map(e=>e.id===entry.id?entry:e):[...extras,entry]}});}
export function deleteBudgetExtra(scene:SceneData,id:string){if(!scene.budget?.extras.some(e=>e.id===id))throw new Error('별도 비용 항목을 찾을 수 없습니다.');return validateScene({...scene,budget:{...scene.budget,extras:scene.budget.extras.filter(e=>e.id!==id)}});}
export const won=(value:number)=>`${value.toLocaleString('ko-KR')}원`;
export function parseBudgetAmount(value:string,max=1000000000):number|null{const text=value.trim();if(!text)return null;if(!/^(?:\d+|\d{1,3}(?:,\d{3})+)$/.test(text))throw new Error('금액은 0 이상의 정수로 입력하세요.');const n=Number(text.replace(/,/g,''));if(!Number.isSafeInteger(n)||n>max)throw new Error(`금액은 ${max.toLocaleString('ko-KR')}원 이하로 입력하세요.`);return n;}
function rowStatus(row:BudgetRow){return row.excluded?'예산 제외':row.unitPrice===undefined?'단가 미입력':row.review?'규격·소재 단가 재검토':'단가 입력';}
function exportRows(scene:SceneData):Array<Array<string|number>>{return budgetRows(scene).map(r=>['가구·설비',r.name,r.kind,r.layer,r.nodes[0].width,r.nodes[0].depth,r.nodes[0].height,r.nodes.length,r.unitPrice??'',r.amount??'',rowStatus(r),r.note,r.material,budgetMaterialDetails(r.nodes[0])]);}
const headers=['구분','항목명','종류','레이어','가로(mm)','깊이(mm)','높이(mm)','수량','단가(원)','금액(원)','상태','메모','소재','마감 상세'];
export function budgetCsv(scene:SceneData){const s=budgetSummary(scene),rows:Array<Array<string|number>>=[['프로젝트',scene.name],['집계 범위','전체 요소 · 숨긴 요소 포함 · 검색/레이어 필터 미적용'],['금액 기준','사용자 입력 원화 · 세금 자동 계산 없음'],headers,...exportRows(scene),...(scene.budget?.extras??[]).map(e=>['별도 비용',e.name,'','','','', '',1,e.amount,e.amount,'입력','']),['가구·설비 입력액','','','','','','','','',s.itemSubtotal],['별도 비용 입력액','','','','','','','','',s.extrasSubtotal],['입력액 합계','','','','','','','','',s.total],['단가 미입력 수',s.unpriced],['단가 재검토 수',s.review],['예산 제외 수',s.excluded]];if(s.target!==undefined)rows.push(['목표 예산','','','','','','','','',s.target],['목표 대비 잔여 입력액','','','','','','','','',s.remaining!]);const cell=(v:string|number)=>`"${(typeof v==='string'&&/^[\s]*[=+\-@]/.test(v)?"'"+v:String(v)).replace(/"/g,'""')}"`;return '\ufeff'+rows.map(r=>Array.from({length:headers.length},(_,i)=>cell(r[i]??'')).join(',')).join('\r\n');}
export function budgetPrintHtml(scene:SceneData){const s=budgetSummary(scene),rows=budgetRows(scene);return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><title>${escapeMarkup(scene.name)} 수량·예산</title><style>@page{size:A4 landscape;margin:12mm}*{box-sizing:border-box}body{font:10pt Arial,'Noto Sans KR',sans-serif;color:#383145;margin:0}h1{font-size:20pt;margin:6mm 0}h2{font-size:13pt;margin:8mm 0 3mm}p{font-size:9pt;line-height:1.7;overflow-wrap:anywhere}.summary{padding:5mm;background:#f2eef8;margin:5mm 0}.summary strong{font-size:18pt}table{border-collapse:collapse;width:100%;table-layout:fixed;font-size:8pt}th,td{text-align:left;border-bottom:1px solid #ddd5e8;padding:2mm 1mm;overflow-wrap:anywhere}th{background:#f4f0f9}thead{display:table-header-group}tr{break-inside:avoid}th:first-child{width:17%}th:nth-child(2){width:13%}th:nth-child(3){width:5%}th:nth-child(4),th:nth-child(5){width:10%}th:nth-child(6){width:28%}th:last-child{width:17%}.warning{color:#986b39}.footer{margin-top:6mm}</style></head><body><h1>${escapeMarkup(scene.name)} · 수량·예산</h1><p>전체 요소 · 숨긴 요소 포함 · 검색/레이어 필터 미적용<br/>사용자 입력 원화 기준 · 세금 자동 계산 없음 · 벽·바닥·간판·어닝 및 설치비 등은 별도 비용으로 직접 입력</p><div class="summary"><strong>입력액 합계 ${won(s.total)}</strong><p>가구·설비 ${won(s.itemSubtotal)} + 별도 비용 ${won(s.extrasSubtotal)}<br/>포함 ${s.included}개 / 제외 ${s.excluded}개 · 단가 미입력 ${s.unpriced}개 · 단가 재검토 ${s.review}개${s.target!==undefined?`<br/>목표 예산 ${won(s.target)} · 현재 입력액 대비 잔여 ${won(s.remaining!)}`:''}</p></div>${s.unpriced||s.review?'<p class="warning">미입력 또는 재검토 항목이 있습니다. 아래 합계는 입력된 단가만 더한 금액입니다.</p>':''}<h2>가구·설비 수량표</h2><table><thead><tr>${['항목·레이어','규격(mm)','수량','단가(원)','입력액(원)','소재·마감','상태·메모'].map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${[`${r.name} / ${r.layer}`,`${r.nodes[0].width} × ${r.nodes[0].depth} × ${r.nodes[0].height}`,r.nodes.length,r.unitPrice??'미입력',r.amount??'미입력',`${r.material} / ${budgetMaterialDetails(r.nodes[0])}`,`${rowStatus(r)} / ${r.note}`].map(c=>`<td>${escapeMarkup(c)}</td>`).join('')}</tr>`).join('')}</tbody></table><h2>별도 비용</h2><table><thead><tr><th>항목</th><th>입력액</th></tr></thead><tbody>${(scene.budget?.extras??[]).map(e=>`<tr><td>${escapeMarkup(e.name)}</td><td>${won(e.amount)}</td></tr>`).join('')||'<tr><td colspan="2">입력한 별도 비용 없음</td></tr>'}</tbody></table><p class="footer">이름·규격·소재·레이어·단가 상태가 같은 요소를 묶었습니다. 그룹은 개별 요소 수량으로, 가져온 GLB는 하나의 요소로 계산합니다. 시공 견적을 자동 산출하는 기능이 아닙니다.</p></body></html>`;}
