import {facadeProjection,facadeRows} from './facade';
import {materials,kindNames,surfaceNames,type SceneData,type SceneNode} from './scene-model';
export type PlanDesign=Pick<SceneData,'room'|'nodes'|'facade'>;
export type PlanOptions={scale?:number;labels?:boolean;dimensions?:boolean;upper?:boolean;date?:string};
export const escapeMarkup=(s:unknown)=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function planNodes(scene:PlanDesign,upper=true){return scene.nodes.filter(n=>!n.hidden&&(upper||n.y<1200))}
export function planCorners(n:SceneNode){const r=n.rotation*Math.PI/180,c=Math.cos(r),s=Math.sin(r);return[[-1,-1],[1,-1],[1,1],[-1,1]].map(([u,v])=>{const x=u*n.width/2,z=v*n.depth/2;return{x:n.x+c*x+s*z,z:n.z-s*x+c*z}})}
export function openingSpan(n:SceneNode,room:SceneData['room']){if(!n.host)throw new Error('벽 연결이 필요합니다.');const horizontal=n.host==='back'||n.host==='front';return{horizontal,along:horizontal?n.x:n.z,cross:n.host==='back'?-room.depth/2:n.host==='front'?room.depth/2:n.host==='left'?-room.width/2:room.width/2,width:n.width}}
export function planScale(scene:PlanDesign,requested?:number){const fit=(scale:number)=>scene.room.width/scale<=238&&(scene.room.depth+facadeProjection(scene))/scale<=188;if(requested){if(![25,50,75,100,150,200].includes(requested)||!fit(requested))throw new Error('선택한 축척에서는 A3 용지를 벗어납니다. 더 작은 축척을 선택하세요.');return requested}return[25,50,75,100,150,200].find(fit)??200}
const f=(n:number)=>Number(n.toFixed(3));
export function floorPlanSvg(scene:PlanDesign,name:string,options:PlanOptions={}){
 const scale=planScale(scene,options.scale),nodes=planNodes(scene,options.upper!==false),room=scene.room,w=room.width/scale,d=room.depth/scale,ox=153,oy=151-facadeProjection(scene)/scale/2,x0=ox-w/2,y0=oy-d/2,wall=120/scale,X=(x:number)=>f(ox+x/scale),Y=(z:number)=>f(oy+z/scale),date=options.date??new Date().toISOString().slice(0,10);
 const text=(x:number,y:number,label:unknown,size=3.3,attrs='')=>`<text x="${f(x)}" y="${f(y)}" font-size="${size}" ${attrs}>${escapeMarkup(label)}</text>`;
 const line=(x1:number,y1:number,x2:number,y2:number,attrs='')=>`<line x1="${f(x1)}" y1="${f(y1)}" x2="${f(x2)}" y2="${f(y2)}" ${attrs}/>`;
 const dim=(x1:number,y1:number,x2:number,y2:number,label:string,vertical=false)=>`<g fill="#46516a" stroke="#8290a3" stroke-width=".2">${line(x1,y1,x2,y2)}${vertical?line(x1-1.2,y1,x1+1.2,y1)+line(x2-1.2,y2,x2+1.2,y2):line(x1,y1-1.2,x1,y1+1.2)+line(x2,y2-1.2,x2,y2+1.2)}</g>${text((x1+x2)/2+(vertical?-2:0),(y1+y2)/2-2,label,3.2,`text-anchor="middle" ${vertical?`transform="rotate(-90 ${f((x1+x2)/2-2)} ${f((y1+y2)/2-2)})"`:''}`)}`;
 const surfaceColor=(id:keyof SceneData['room']['surfaces'])=>{const v=room.surfaces[id];return v.finish?.color??v.color??materials.find(m=>m.id===v.material)!.color};
 const labels:string[]=[];let body=`<rect x="${f(x0)}" y="${f(y0)}" width="${f(w)}" height="${f(d)}" fill="${escapeMarkup(surfaceColor('floor'))}" fill-opacity=".28" stroke="#303847" stroke-width="${f(wall)}"/>`;
 body+=`<g stroke-width="${f(Math.max(.45,wall*.35))}">${line(x0,y0+wall*.35,x0+w,y0+wall*.35,`stroke="${escapeMarkup(surfaceColor('back'))}"`)}${line(x0,y0+d-wall*.35,x0+w,y0+d-wall*.35,`stroke="${escapeMarkup(surfaceColor('front'))}"`)}${line(x0+wall*.35,y0,x0+wall*.35,y0+d,`stroke="${escapeMarkup(surfaceColor('left'))}"`)}${line(x0+w-wall*.35,y0,x0+w-wall*.35,y0+d,`stroke="${escapeMarkup(surfaceColor('right'))}"`)}</g>`;
 for(const [index,n]of nodes.entries()){
 const material=materials.find(m=>m.id===n.material)!,color=n.finish?.color??n.color??material.color;
 if(n.host){const p=openingSpan(n,room),cx=p.horizontal?X(p.along):X(p.cross),cy=p.horizontal?Y(p.cross):Y(p.along),len=p.width/scale;body+=`<rect x="${f(cx-(p.horizontal?len:wall*1.5)/2)}" y="${f(cy-(p.horizontal?wall*1.5:len)/2)}" width="${f(p.horizontal?len:wall*1.5)}" height="${f(p.horizontal?wall*1.5:len)}" fill="white"/>`;body+=`<g stroke="${n.kind==='window'?'#3c83a3':'#8390a0'}" stroke-width=".4" ${n.kind==='door'?'stroke-dasharray="1.1 .8"':''}>${p.horizontal?line(cx-len/2,cy,cx+len/2,cy):line(cx,cy-len/2,cx,cy+len/2)}</g>`;if(options.dimensions!==false)body+=text(cx+(p.horizontal?0:3),cy+(p.horizontal?-4:0),`${n.kind==='door'?'D':'W'} ${Math.round(n.width)}`,2.8,p.horizontal?'text-anchor="middle"':'');labels.push(text(cx,cy+1, index+1,2.7,'text-anchor="middle" font-weight="600"'))}
 else{const cx=X(n.x),cy=Y(n.z),nw=n.width/scale,nd=n.depth/scale,dashed=n.y>=1200;body+=`<g transform="translate(${cx} ${cy}) rotate(${f(-n.rotation)})" fill="${escapeMarkup(color)}" fill-opacity="${dashed?.18:.42}" stroke="#5d6777" stroke-width=".25" ${dashed?'stroke-dasharray="1 .7"':''}>${['round-table','cylinder','plant','pendant'].includes(n.kind)?`<ellipse rx="${f(nw/2)}" ry="${f(nd/2)}"/>`:`<rect x="${f(-nw/2)}" y="${f(-nd/2)}" width="${f(nw)}" height="${f(nd)}"/>`}</g>`;labels.push(`<circle cx="${cx}" cy="${cy}" r="2.35" fill="white" stroke="#6a617f" stroke-width=".25"/>`+text(cx,cy+.95,index+1,2.7,'text-anchor="middle" font-weight="600"'))}}
 if(options.upper!==false&&scene.facade){const {sign,awning}=scene.facade;if(awning.enabled){const left=X(awning.x-awning.width/2),top=Y(room.depth/2+100),aw=awning.width/scale,ad=awning.projection/scale;body+=`<rect x="${left}" y="${top}" width="${f(aw)}" height="${f(ad)}" fill="${escapeMarkup(awning.color)}" fill-opacity=".15" stroke="#795a83" stroke-width=".3" stroke-dasharray="1.2 .8"/>`;if(options.dimensions!==false)body+=text(left+aw/2,top+ad/2+1,`어닝 돌출 ${Math.round(awning.projection)}`,2.7,'text-anchor="middle"');}if(sign.enabled)body+=`<rect x="${X(sign.x-sign.width/2)}" y="${Y(room.depth/2+60)}" width="${f(sign.width/scale)}" height="${f(sign.depth/scale)}" fill="${escapeMarkup(sign.color)}" stroke="#5c6270" stroke-width=".2"/>`;}
 if(options.labels!==false)body+=labels.join('');
 if(options.dimensions!==false)body+=dim(x0,y0-10,x0+w,y0-10,`${Math.round(room.width).toLocaleString('en-US')} mm`)+dim(x0-11,y0,x0-11,y0+d,`${Math.round(room.depth).toLocaleString('en-US')} mm`,true);
 const legend=nodes.slice(0,23).map((n,i)=>`${text(302,59+i*7.2,`${i+1}`,3.1,'font-weight="700"')}${text(310,59+i*7.2,n.name.length>20?n.name.slice(0,19)+'…':n.name,3.1)}${text(310,62+i*7.2,`${Math.round(n.width)} × ${Math.round(n.depth)} × ${Math.round(n.height)}${n.estimated?' · 추정':''}`,2.55,'fill="#7b8290"')}`).join('');
 const barMm=1000,bar=barMm/scale;
 return `<svg xmlns="http://www.w3.org/2000/svg" width="420mm" height="297mm" viewBox="0 0 420 297" role="img" aria-label="${escapeMarkup(name)} 치수 평면도"><style>text{font-family:Arial,'Noto Sans KR',sans-serif;fill:#263247}line{fill:none}</style><rect width="420" height="297" fill="white"/>${text(16,17,'SPATIAL / FLOOR PLAN',3.2,'letter-spacing=".7" fill="#7654c0"')}${text(16,29,name.length>36?name.slice(0,35)+'…':name,6.2,'font-weight="700"')}${text(16,37,'공간 검토용 개념 평면 · 시공 도면 아님',3.5,'fill="#7a667f"')}${text(403,20,date,3.1,'text-anchor="end"')}${text(403,29,`A3 · 1:${scale}`,5,'text-anchor="end" font-weight="700"')}<line x1="16" y1="43" x2="404" y2="43" stroke="#d5d9e0" stroke-width=".3"/>${body}${text(ox,y0+d+facadeProjection(scene)/scale+8,'입구 방향 (+Z)',3.1,'text-anchor="middle" fill="#727b8c"')}${text(300,51,'요소 번호 · 가로 × 깊이 × 높이 (mm)',3.3,'font-weight="600"')}${legend}${nodes.length>23?text(300,231,`전체 ${nodes.length}개 · 전체 목록은 인쇄/CSV에 포함`,2.8):''}${text(16,263,`폭·깊이: 벽 중심선 기준 · 벽 두께 120mm · 천장 ${Math.round(room.height)}mm`,3.1)}${text(16,270,`${options.upper!==false?'상부·외관 투영 포함 · 어닝과 1,200mm 이상 설치는 점선':'설치 높이 1,200mm 미만 요소 표시 · 간판·어닝 제외'} · 문 개폐 방향 미지정`,3.1)}${text(16,277,`치수 출처: ${room.source==='measured'?'사용자가 실측으로 입력':room.source==='entered'?'사용자 입력':'예시 치수'} · 숨긴 요소 ${scene.nodes.filter(n=>n.hidden).length}개 제외 · 외부 모델은 외곽 표시`,2.9)}<g stroke="#33445e" stroke-width=".5">${line(304,255,304+bar,255)}${line(304,253,304,257)}${line(304+bar,253,304+bar,257)}</g>${text(304+bar/2,251,'1,000mm',3,'text-anchor="middle"')}${text(300,267,'100% 실제 크기로 인쇄할 때 축척 유효',2.8)}${text(300,275,`${(room.width*room.depth/1000000).toFixed(1)}m² / 약 ${(room.width*room.depth/3305800).toFixed(1)}평 (기준선 면적)`,2.8)}<line x1="16" y1="283" x2="404" y2="283" stroke="#d5d9e0" stroke-width=".3"/>${text(16,289,'소재 색상·가구 외곽은 시각화 참고용입니다. 실제 제품·시공 치수는 현장에서 확인하세요.',2.8)}</svg>`;
}
export function planRows(scene:PlanDesign,upper=true){return planNodes(scene,upper).map((n,i)=>[String(i+1),n.name,kindNames[n.kind],String(Math.round(n.width)),String(Math.round(n.depth)),String(Math.round(n.height)),String(Math.round(n.y)),n.kind==='model'&&!n.uniformMaterial?'모델 원본':Object.keys(n.faces).length?'복수 소재':materials.find(m=>m.id===n.material)!.name,n.estimated?'추정':'입력',n.host??''])}
export function surfaceRows(scene:PlanDesign){return Object.entries(scene.room.surfaces).map(([id,s])=>{const m=materials.find(m=>m.id===s.material)!;return[surfaceNames[id],m.name,s.finish?.color??s.color??m.color,String(s.finish?.roughness??m.roughness),String(s.finish?.metalness??m.metalness)]})}
export function floorPlanCsv(scene:PlanDesign,upper=true){const cell=(s:string)=>`"${(/^[\s]*[=+\-@]/.test(s)?"'"+s:s).replace(/"/g,'""')}"`;return '\ufeff'+[['번호','명칭','종류','가로(mm)','깊이(mm)','높이(mm)','바닥에서 높이(mm)','소재','치수 구분','연결 벽'],...planRows(scene,upper)].map(row=>row.map(cell).join(',')).join('\r\n')}
export function floorPlanPrintHtml(scene:PlanDesign,name:string,options:PlanOptions={}){const rows=planRows(scene,options.upper!==false),pages=[];let page:string[][]=[],weight=0;for(const row of rows){const cost=1+Math.max(...row.map((value,i)=>Math.ceil(value.length/(i===1?18:8))));if(weight+cost>46&&page.length){pages.push(page);page=[];weight=0}page.push(row);weight+=cost}if(page.length)pages.push(page);return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><title>${escapeMarkup(name)} 평면도</title><style>@page{size:A3 landscape;margin:0}*{box-sizing:border-box}body{margin:0;font-family:Arial,'Noto Sans KR',sans-serif;color:#263247}.page{width:420mm;height:297mm;break-after:page;overflow:hidden}.page:last-child{break-after:auto}.schedule{padding:16mm}h1{font-size:20pt}h2{font-size:16pt;margin-top:12mm}p{font-size:10pt}table{width:100%;border-collapse:collapse;font-size:10pt;table-layout:fixed}th,td{border-bottom:1px solid #d7dce3;padding:2mm 1mm;overflow-wrap:anywhere;text-align:left}th{background:#f0edf8}td:nth-child(2),th:nth-child(2){width:21%}td:first-child,th:first-child{width:5%}svg{display:block;width:420mm;height:297mm}</style></head><body><section class="page">${floorPlanSvg(scene,name,options)}</section>${pages.map((page,i)=>`<section class="page schedule"><h1>${escapeMarkup(name)} · 가구·개구부 목록 ${i+1}/${pages.length}</h1><p>단위 mm · 외부 모델은 외곽 치수 · 추정 표시 항목은 현장 확인 · 선택한 표시 범위 기준</p><table><thead><tr>${['번호','명칭','종류','가로','깊이','높이','설치 높이','소재','구분','연결 벽'].map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${page.map(row=>`<tr>${row.map(c=>`<td>${escapeMarkup(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></section>`).join('')}<section class="page schedule"><h1>${escapeMarkup(name)} · 벽·바닥 소재</h1><p>시각화 재질 기준 · 색상·광택은 실제 제품 샘플과 다를 수 있습니다. 광택 항목은 거칠기 0(매끄러움)~1(거침)입니다.</p><table><thead><tr>${['표면','소재','색상','거칠기','금속성'].map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${surfaceRows(scene).map(row=>`<tr>${row.map(c=>`<td>${escapeMarkup(c)}</td>`).join('')}</tr>`).join('')}</tbody></table>${facadeRows(scene).length?`<h2>외관 요소 · mm</h2><table><thead><tr>${['요소','문구·형식','크기','높이','색상'].map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${facadeRows(scene).map(row=>`<tr>${row.map(c=>`<td>${escapeMarkup(c)}</td>`).join('')}</tr>`).join('')}</tbody></table>`:''}</section></body></html>`}
