import expandedProducts from './data/material-products-expanded.json';
import {samhwaColors} from './samhwa-colors';
import type {MaterialFinish,MaterialId,SceneData} from './scene-model';
export type MaterialProduct={id:string;brand:string;collection:string;code:string;name:string;category:string;appearance:string;base:MaterialId;image:string;sourceUrl:string;sourceImageUrl:string;imageWidthMm:number|null;previewColor?:string;specification:string;checkedAt:string;kind?:'color';colorBook?:string;pageCode?:string;keywords?:string;sourceValue?:string;codeHasVariants?:boolean};
/** Product codes and swatches are verified against the linked manufacturer pages. */
export const materialProducts:MaterialProduct[]=[
{previewColor:'#b4946f',id:'egger-h1180-st37',brand:'EGGER',collection:'Decorative Collection',code:'H1180 ST37',name:'Natural Halifax Oak',category:'장식용 보드·라미네이트',appearance:'우드',base:'oak',image:'/material-products/egger-h1180-st37.jpg',sourceUrl:'https://www.egger.com/en/furniture-interior-design/decors/H1180_37?country=GB',sourceImageUrl:'https://cdn.egger.com/img/pim/8854365503518/8854523150366/original.png',imageWidthMm:null,specification:'데코·표면 조합 코드. 판매 보드 규격 및 스와치 실물 축척은 별도 확인.',checkedAt:'2026-09-10'},
{previewColor:'#c2a486',id:'egger-h1145-st10',brand:'EGGER',collection:'Decorative Collection',code:'H1145 ST10',name:'Natural Bardolino Oak',category:'장식용 보드·라미네이트',appearance:'우드',base:'oak',image:'/material-products/egger-h1145-st10.jpg',sourceUrl:'https://www.egger.com/en/furniture-interior-design/decors/H1145_10?country=GB',sourceImageUrl:'https://cdn.egger.com/img/pim/8854363537438/8854522462238/original.png',imageWidthMm:null,specification:'데코·표면 조합 코드. 판매 보드 규격 및 스와치 실물 축척은 별도 확인.',checkedAt:'2026-09-10'},
{"previewColor": "#ebe9e3", "id": "egger-h3195-st19", "brand": "EGGER", "collection": "Decorative Collection", "code": "H3195 ST19", "name": "White Fineline", "category": "장식용 보드·라미네이트", "appearance": "우드", "base": "oak", "image": "/material-products/egger-h3195-st19.jpg", "sourceUrl": "https://www.egger.com/en/furniture-interior-design/decors/H3195_19?country=GB", "sourceImageUrl": "https://cdn.egger.com/img/pim/8854406889502/8854540124190/original.png", "imageWidthMm": null, "specification": "데코·표면 조합 코드. 두께·심재와 이미지 실물 축척은 별도 확인.", "checkedAt": "2026-09-10"},
{"previewColor": "#827b76", "id": "egger-f433-st10", "brand": "EGGER", "collection": "Decorative Collection", "code": "F433 ST10", "name": "Anthracite Linen", "category": "장식용 보드·라미네이트", "appearance": "패브릭 무늬", "base": "linen", "image": "/material-products/egger-f433-st10.jpg", "sourceUrl": "https://www.egger.com/en/furniture-interior-design/decors/F433_10?country=GB", "sourceImageUrl": "https://cdn.egger.com/img/pim/8854336208926/8854514958366/original.png", "imageWidthMm": null, "specification": "데코·표면 조합 코드. 두께·심재와 이미지 실물 축척은 별도 확인.", "checkedAt": "2026-09-10"},
{"previewColor": "#a69989", "id": "egger-u727-st9", "brand": "EGGER", "collection": "Decorative Collection", "code": "U727 ST9", "name": "Stone Grey", "category": "장식용 보드·라미네이트", "appearance": "단색", "base": "plaster", "image": "/material-products/egger-u727-st9.jpg", "sourceUrl": "https://www.egger.com/en/furniture-interior-design/decors/U727_9?country=GB", "sourceImageUrl": "https://cdn.egger.com/img/pim/8854455648286/8854455681054/original.png", "imageWidthMm": null, "specification": "데코·표면 조합 코드. 두께·심재와 이미지 실물 축척은 별도 확인.", "checkedAt": "2026-09-10"},
{"previewColor": "#d3cec8", "id": "egger-u708-st9", "brand": "EGGER", "collection": "Decorative Collection", "code": "U708 ST9", "name": "Light Grey", "category": "장식용 보드·라미네이트", "appearance": "단색", "base": "plaster", "image": "/material-products/egger-u708-st9.jpg", "sourceUrl": "https://www.egger.com/en/furniture-interior-design/decors/U708_9?country=GB", "sourceImageUrl": "https://cdn.egger.com/img/pim/8854452502558/8854557032478/original.png", "imageWidthMm": null, "specification": "데코·표면 조합 코드. 두께·심재와 이미지 실물 축척은 별도 확인.", "checkedAt": "2026-09-10"},
{"previewColor": "#1c3629", "id": "egger-u699-st9", "brand": "EGGER", "collection": "Decorative Collection", "code": "U699 ST9", "name": "Fir Green", "category": "장식용 보드·라미네이트", "appearance": "단색", "base": "sage", "image": "/material-products/egger-u699-st9.jpg", "sourceUrl": "https://www.egger.com/en/furniture-interior-design/decors/U699_9?country=GB", "sourceImageUrl": "https://cdn.egger.com/img/pim/8854556213278/8854556246046/original.png", "imageWidthMm": null, "specification": "데코·표면 조합 코드. 두께·심재와 이미지 실물 축척은 별도 확인.", "checkedAt": "2026-09-10"},
{"previewColor": "#909e9e", "id": "egger-u636-st9", "brand": "EGGER", "collection": "Decorative Collection", "code": "U636 ST9", "name": "Fjord Green", "category": "장식용 보드·라미네이트", "appearance": "단색", "base": "sage", "image": "/material-products/egger-u636-st9.jpg", "sourceUrl": "https://www.egger.com/en/furniture-interior-design/decors/U636_9?country=GB", "sourceImageUrl": "https://cdn.egger.com/img/pim/8854446997534/8854554050590/original.png", "imageWidthMm": null, "specification": "데코·표면 조합 코드. 두께·심재와 이미지 실물 축척은 별도 확인.", "checkedAt": "2026-09-10"},
{"previewColor": "#040406", "id": "egger-u999-pm", "brand": "EGGER", "collection": "PerfectSense", "code": "U999 PM", "name": "Black", "category": "장식용 보드·라미네이트", "appearance": "단색", "base": "charcoal", "image": "/material-products/egger-u999-pm.jpg", "sourceUrl": "https://www.egger.com/en/furniture-interior-design/decors/U999_PM?country=GB", "sourceImageUrl": "https://cdn.egger.com/img/pim/8854475767838/8854475800606/original.png", "imageWidthMm": null, "specification": "데코·표면 조합 코드. 두께·심재와 이미지 실물 축척은 별도 확인.", "checkedAt": "2026-09-10"},
{"previewColor": "#fbf6e3", "id": "egger-w990-st7", "brand": "EGGER", "collection": "Decorative Collection", "code": "W990 ST7", "name": "Crystal White", "category": "장식용 보드·라미네이트", "appearance": "단색", "base": "plaster", "image": "/material-products/egger-w990-st7.jpg", "sourceUrl": "https://www.egger.com/en/furniture-interior-design/decors/W990_7?country=GB", "sourceImageUrl": "https://cdn.egger.com/img/pim/8854566699038/8854566731806/original.png", "imageWidthMm": null, "specification": "데코·표면 조합 코드. 두께·심재와 이미지 실물 축척은 별도 확인.", "checkedAt": "2026-09-10"},
{"previewColor": "#a08361", "id": "lx-benif-pw132", "brand": "LX Z:IN", "collection": "BENIF 클래식 우드", "code": "PW132", "name": "데니쉬 티크", "category": "인테리어 필름", "appearance": "우드", "base": "oak", "image": "/material-products/lx-benif-pw132.jpg", "sourceUrl": "https://www.lxzin.com/zin/product/13572", "sourceImageUrl": "https://octapi.lxzin.com/upload/product/202108/20210825/A315E9C2-32CC-F861-A1DD-4DF00FB647B5_thumb_l.jpg", "imageWidthMm": null, "specification": "이형지 제외 두께 0.2mm · 폭 1,220mm. 이미지의 실물 축척은 별도 확인.", "checkedAt": "2026-09-10"},
{"previewColor": "#cbc6bf", "id": "lx-benif-bm013", "brand": "LX Z:IN", "collection": "BENIF 빅 스톤", "code": "BM013", "name": "빅 그라나이트 베이지", "category": "인테리어 필름", "appearance": "스톤 무늬", "base": "concrete", "image": "/material-products/lx-benif-bm013.jpg", "sourceUrl": "https://www.lxzin.com/zin/product/100800", "sourceImageUrl": "https://octapi.lxzin.com/zinPrd/expandFileSeq/202305/24/798647dc-1aba-47a5-ab23-2a16a69520b3.jpg", "imageWidthMm": null, "specification": "이형지 제외 두께 0.2mm · 폭 1,220mm. 이미지의 실물 축척은 별도 확인.", "checkedAt": "2026-09-10"},
{"previewColor": "#fcfbf7", "id": "lx-benif-rs130", "brand": "LX Z:IN", "collection": "BENIF 솔리드", "code": "RS130", "name": "포실화이트", "category": "인테리어 필름", "appearance": "단색", "base": "plaster", "image": "/material-products/lx-benif-rs130.jpg", "sourceUrl": "https://www.lxzin.com/zin/product/10867", "sourceImageUrl": "https://octapi.lxzin.com/upload/product/202108/20210825/CCF14F81-8711-BE86-16B6-6CFD4807B521_thumb_l.jpg", "imageWidthMm": null, "specification": "이형지 제외 두께 0.2mm · 폭 1,220mm. 이미지의 실물 축척은 별도 확인.", "checkedAt": "2026-09-10"},
{"previewColor": "#a68f72", "id": "bodaq-spw38", "brand": "BODAQ 보닥", "collection": "현대L&C 오리진 우드", "code": "SPW38", "name": "시에나티크 / Siena Teak", "category": "인테리어 필름", "appearance": "우드", "base": "oak", "image": "/material-products/bodaq-spw38.jpg", "sourceUrl": "https://www.hyundailnc.com/product/contents?mng_cd=8A14B629", "sourceImageUrl": "https://www.hyundailnc.com/uploads/interior_film/20260316012626878.jpg", "imageWidthMm": null, "specification": "0.42mm(T) × 1,220mm(W) × 50,000mm(L). 공식 페이지에서 제품 코드 검색 후 상세 확인.", "checkedAt": "2026-09-10"},
{"previewColor": "#7b6140", "id": "bodaq-ogw01", "brand": "BODAQ 보닥", "collection": "현대L&C 옵티컬 그레인 우드", "code": "OGW01", "name": "노블오크 / Noble Oak", "category": "인테리어 필름", "appearance": "우드", "base": "oak", "image": "/material-products/bodaq-ogw01.jpg", "sourceUrl": "https://www.hyundailnc.com/product/contents?mng_cd=8A14B629", "sourceImageUrl": "https://www.hyundailnc.com/uploads/interior_film/2026031612501747.jpg", "imageWidthMm": null, "specification": "0.42mm(T) × 1,220mm(W) × 50,000mm(L). 공식 페이지에서 제품 코드 검색 후 상세 확인.", "checkedAt": "2026-09-10"},
{"previewColor": "#53442e", "id": "bodaq-lw122", "brand": "BODAQ 보닥", "collection": "현대L&C 롱 우드", "code": "LW122", "name": "아르덴오크 / Arden Oak", "category": "인테리어 필름", "appearance": "우드", "base": "oak", "image": "/material-products/bodaq-lw122.jpg", "sourceUrl": "https://www.hyundailnc.com/product/contents?mng_cd=8A14B629", "sourceImageUrl": "https://www.hyundailnc.com/uploads/interior_film/20260316011942985.jpg", "imageWidthMm": null, "specification": "0.42mm(T) × 1,220mm(W) × 50,000mm(L). 공식 페이지에서 제품 코드 검색 후 상세 확인.", "checkedAt": "2026-09-10"},
{"previewColor": "#e2e1df", "id": "hanex-cs501", "brand": "HANEX 하넥스", "collection": "현대L&C 베나토", "code": "CS-501", "name": "칼라카타 글로리", "category": "인조대리석", "appearance": "스톤 무늬", "base": "concrete", "image": "/material-products/hanex-cs501.jpg", "sourceUrl": "https://www.hyundailnc.com/product/contents?mng_cd=01320B6C", "sourceImageUrl": "https://www.hyundailnc.com/uploads/interior_stone/20250319104901578.jpg", "imageWidthMm": null, "specification": "판매 규격은 공식 제품 정보에서 확인하세요. 공식 페이지에서 제품 코드로 검색.", "checkedAt": "2026-09-10"},
{"previewColor": "#fcfcfb", "id": "hanstone-cc603", "brand": "칸스톤", "collection": "현대L&C 흐름무늬", "code": "CC603", "name": "스타투아리오 골드", "category": "강화천연석", "appearance": "스톤 무늬", "base": "concrete", "image": "/material-products/hanstone-cc603.jpg", "sourceUrl": "https://www.hyundailnc.com/product/contents?mng_cd=47453481", "sourceImageUrl": "https://www.hyundailnc.com/uploads/interior_stone/20250320015019382.jpg", "imageWidthMm": null, "specification": "13T·20T / 3,300(W) × 1,640(L)mm. 표시 이미지가 판재 전체 축척을 보장하지는 않습니다.", "checkedAt": "2026-09-10"}
,...(expandedProducts as MaterialProduct[]),...samhwaColors];
const productsById=new Map(materialProducts.map(p=>[p.id,p]));
export function materialProduct(id?:string|null){return id?productsById.get(id):undefined;}
export function productFinish(product:MaterialProduct):MaterialFinish{if(product.kind==='color'&&!product.previewColor)throw new Error('공식 색상값이 없어 적용할 수 없습니다.');return {catalogId:product.id,textureId:null,scale:product.imageWidthMm??900,rotation:0,...(product.previewColor?{color:product.previewColor}:{})};}
export function finishTextureKey(f:MaterialFinish){return f.catalogId?(materialProduct(f.catalogId)?.kind==='color'?null:`catalog:${f.catalogId}`):f.textureId??null;}
export function finishImageUrl(f:MaterialFinish){return f.catalogId?(materialProduct(f.catalogId)?.image||undefined):f.textureId?`/api/assets?id=${f.textureId}`:undefined;}
export function finishLabel(f:MaterialFinish,fallback:string){const p=materialProduct(f.catalogId);return p?`${p.brand} · ${p.code}${p.kind==='color'?` (${p.collection})`:''}`:fallback;}
export function catalogTextureKeys(s:Pick<SceneData,'room'|'nodes'>){return [...new Set([...Object.values(s.room.surfaces).map(v=>v.finish),...s.nodes.flatMap(n=>[n.finish,...Object.values(n.faceFinishes??{})])].flatMap(f=>f?.catalogId&&finishTextureKey(f)?[finishTextureKey(f)!]:[]))];}

export const normalizeProductQuery=(s:string)=>s.normalize('NFKC').toLowerCase().replace(/[\s-]+/g,'');
const searchIndex=new Map(materialProducts.map(p=>[p.id,normalizeProductQuery(`${p.brand} ${p.collection} ${p.code} ${p.name} ${p.category} ${p.appearance} ${p.pageCode??''} ${p.keywords??''} ${p.previewColor??''}`)]));
export type ProductCatalogScope='all'|'products'|'colors';
export function searchMaterialProducts({brand='전체',category='전체',book='전체',query='',productType='전체',scope='all'}:{brand?:string;category?:string;book?:string;query?:string;productType?:string;scope?:ProductCatalogScope}){const q=normalizeProductQuery(query);return materialProducts.filter(p=>(scope==='all'||(scope==='colors'?p.kind==='color':p.kind!=='color'))&&(productType==='전체'||p.category===productType)&&(brand==='전체'||p.brand===brand)&&(category==='전체'||p.appearance===category)&&(book==='전체'||p.colorBook===book)&&searchIndex.get(p.id)!.includes(q));}
